import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-Chk998Rz.js";
import { t as getChatChannelMeta } from "../../chat-meta-DNnFqIhM.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DYzVFvFQ.js";
import { n as AcpRuntimeError } from "../../errors-BuJyHrJJ.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-cLEq6pXD.js";
import { r as makeProxyFetch } from "../../proxy-fetch-Crv8HXiR.js";
import { r as resolvePollMaxSelections } from "../../polls-BJ2XUT77.js";
import { t as clearAccountEntryFields } from "../../config-helpers-ulMlBFbn.js";
import { n as formatPairingApproveHint } from "../../helpers-jZ7BUHHD.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-Cjwk9UvV.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-ChWcsymB.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-B6ZzZs6-.js";
import "../../channel-core-DjQm_N76.js";
import { t as resolveTelegramToken } from "../../token-KdkjvHPL.js";
import "../../acp-runtime-C6yHD44S.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-C5_Dm1pD.js";
import "../../channel-plugin-common-bzRh1vyD.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-EU2hrlO2.js";
import "../../channel-status-B1B6b1FE.js";
import "../../channel-actions-DZWZrRK6.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch--hLpVgVn.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-G6WQbFDu.js";
import { n as setTelegramRuntime } from "../../runtime-ChfuqVH7.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-CXcCJWLj.js";
import "../../config-api-eIgeT2gd.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-DYK3OgeW.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-B3gN6tDw.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-KG0jp7xQ.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-XVA0DQ3L.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
