import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Dh6XMgGH.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-CGkX0wi-.js";
import { n as ChannelPlugin } from "../../types.public-BdkEyxaN.js";
import { r as buildChannelConfigSchema } from "../../config-schema-Dx48Ud8L.js";
import { d as getChatChannelMeta } from "../../core-C4QB1ael.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-AZcwFUZz.js";
import { c as collectStatusIssuesFromLastError, r as buildComputedAccountStatusSnapshot } from "../../status-helpers-C142h3pA.js";
import { i as IMessageConfigSchema } from "../../bundled-channel-config-schema-DpDVXTcV.js";
import { g as formatTrimmedAllowFromEntries } from "../../channel-config-helpers-BizLzK4R.js";
import { t as chunkTextForOutbound } from "../../text-chunking-B2vtBPHV.js";
import { a as looksLikeIMessageTargetId, o as normalizeIMessageMessagingTarget, r as probeIMessage, t as IMessageProbe } from "../../probe-CO-DgwTd.js";
import { d as resolveIMessageGroupRequireMention, f as resolveIMessageGroupToolPolicy } from "../../targets-ZOG9xiiA.js";
import { a as monitorIMessageProvider, c as resolveIMessageConfigDefaultTo, i as sendMessageIMessage, n as setIMessageRuntime, o as MonitorIMessageOpts, r as imessageMessageActions, s as resolveIMessageConfigAllowFrom, t as IMessageAccountConfig } from "../../runtime-api-BCLLi3fd.js";
export { type ChannelPlugin, DEFAULT_ACCOUNT_ID, IMessageAccountConfig, IMessageConfigSchema, type IMessageProbe, type MonitorIMessageOpts, PAIRING_APPROVED_MESSAGE, buildChannelConfigSchema, buildComputedAccountStatusSnapshot, chunkTextForOutbound, collectStatusIssuesFromLastError, formatTrimmedAllowFromEntries, getChatChannelMeta, imessageMessageActions, looksLikeIMessageTargetId, monitorIMessageProvider, normalizeIMessageMessagingTarget, probeIMessage, resolveChannelMediaMaxBytes, resolveIMessageConfigAllowFrom, resolveIMessageConfigDefaultTo, resolveIMessageGroupRequireMention, resolveIMessageGroupToolPolicy, sendMessageIMessage, setIMessageRuntime };