import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { t as getChatChannelMeta } from "../../chat-meta-42nqDCp5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-gd9RYI9s.js";
import { n as AcpRuntimeError } from "../../errors-zyHRqIKC.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-DZFnGYgt.js";
import { r as resolvePollMaxSelections } from "../../polls-BXQX1ijK.js";
import { t as clearAccountEntryFields } from "../../config-helpers-VqWhr_tS.js";
import { n as formatPairingApproveHint } from "../../helpers-BJ8ZIvo-.js";
import { r as makeProxyFetch } from "../../proxy-fetch-v9WlvIjL.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-CpMieeGc.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-C8b3OvGy.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-DJLx-uwW.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-CsvqyD6p.js";
import "../../channel-core-DLQQNdcP.js";
import { t as resolveTelegramToken } from "../../token-CRYAOZqX.js";
import "../../acp-runtime-D-8rMzbp.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-B6vSZJO3.js";
import "../../channel-plugin-common-BpK0y8gj.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-CL121ZpD.js";
import "../../channel-status-C1bs_3mh.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-CaAok3C8.js";
import "../../channel-actions-Db6K5Nyn.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-0l-pejil.js";
import { n as setTelegramRuntime } from "../../runtime-CLGIBnEQ.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-CCj0-yFV.js";
import "../../config-api-LpokjiV9.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-Cw9kqG0a.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-DGPxVWOJ.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-DnHnYe7r.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-CLNQxIk8.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
