import { n as SILENT_REPLY_TOKEN, t as HEARTBEAT_TOKEN } from "../../tokens-DQI2KUQE.js";
import { n as HEARTBEAT_PROMPT, u as stripHeartbeatToken } from "../../heartbeat-B48xSXg1.js";
import { c as optimizeImageToPng } from "../../image-ops-Cfq3PTvh.js";
import { r as getDefaultLocalRoots, t as LocalMediaAccessError } from "../../local-media-access-CSeP3ocj.js";
import { n as loadWebMediaRaw, r as optimizeImageToJpeg, t as loadWebMedia } from "../../web-media-CWnCnAZI.js";
import "../../reply-runtime-CgdKC_bo.js";
import { n as resolveWebCredsBackupPath, r as resolveWebCredsPath, t as hasWebCredsSync } from "./creds-files-DrQobVxz.js";
import { n as whatsAppActionRuntime, t as handleWhatsAppAction } from "./action-runtime-DmEoulOp.js";
import { n as getStatusCode, t as formatError } from "./session-errors-BQATnxTz.js";
import { i as sendTypingWhatsApp, n as sendPollWhatsApp, r as sendReactionWhatsApp, t as sendMessageWhatsApp } from "./send-ADFt8xJk.js";
import { n as waitForWebLogin, t as startWebLoginWithQr } from "./login-qr-runtime-rvFnlZfc.js";
import { t as createWhatsAppLoginTool } from "./agent-tools-login-CuVKb6kg.js";
import { n as setWhatsAppRuntime } from "./runtime-B-eW5aUd.js";
import { C as waitForCredsSaveQueueWithTimeout, S as waitForCredsSaveQueue, _ as readWebSelfIdentityForDecision, a as getWebAuthAgeMs, b as webAuthExists, c as pickWebChannel, d as readWebAuthExistsForDecision, f as readWebAuthSnapshot, g as readWebSelfIdentity, h as readWebSelfId, i as formatWhatsAppWebAuthStatusState, l as readCredsJsonRaw, m as readWebAuthState, n as WHATSAPP_AUTH_UNSTABLE_CODE, o as logWebSelfId, p as readWebAuthSnapshotBestEffort, r as WhatsAppAuthUnstableError, s as logoutWeb, t as WA_WEB_AUTH_DIR, u as readWebAuthExistsBestEffort, v as resolveDefaultWebAuthDir, w as writeCredsJsonAtomically, y as restoreCredsFromBackupIfNeeded } from "./auth-store-C2C0dMot.js";
import { t as DEFAULT_WEB_MEDIA_BYTES } from "./constants-QJesIq-5.js";
import { n as resolveWebAccountId, t as getActiveWebListener } from "./active-listener-BewD6nlI.js";
import { c as waitForWaConnection, o as createWaSocket, s as newConnectionId } from "./connection-controller-BMAbA3n_.js";
import { a as extractMediaPlaceholder, i as extractLocationData, n as monitorWebInbox, o as extractText, r as extractContactContext, s as resetWebInboundDedupe, t as monitorWebChannel } from "./monitor-B0GjKFln.js";
import { t as loginWeb } from "./login-DRgqxAYp.js";
export { DEFAULT_WEB_MEDIA_BYTES, HEARTBEAT_PROMPT, HEARTBEAT_TOKEN, LocalMediaAccessError, SILENT_REPLY_TOKEN, WA_WEB_AUTH_DIR, WHATSAPP_AUTH_UNSTABLE_CODE, WhatsAppAuthUnstableError, createWaSocket, createWhatsAppLoginTool, extractContactContext, extractLocationData, extractMediaPlaceholder, extractText, formatError, formatWhatsAppWebAuthStatusState, getActiveWebListener, getDefaultLocalRoots, getStatusCode, getWebAuthAgeMs, handleWhatsAppAction, hasWebCredsSync, loadWebMedia, loadWebMediaRaw, logWebSelfId, loginWeb, logoutWeb, monitorWebChannel, monitorWebInbox, newConnectionId, optimizeImageToJpeg, optimizeImageToPng, pickWebChannel, readCredsJsonRaw, readWebAuthExistsBestEffort, readWebAuthExistsForDecision, readWebAuthSnapshot, readWebAuthSnapshotBestEffort, readWebAuthState, readWebSelfId, readWebSelfIdentity, readWebSelfIdentityForDecision, resetWebInboundDedupe, resolveDefaultWebAuthDir, resolveWebAccountId, resolveWebCredsBackupPath, resolveWebCredsPath, restoreCredsFromBackupIfNeeded, sendMessageWhatsApp, sendPollWhatsApp, sendReactionWhatsApp, sendTypingWhatsApp, setWhatsAppRuntime, startWebLoginWithQr, stripHeartbeatToken, waitForCredsSaveQueue, waitForCredsSaveQueueWithTimeout, waitForWaConnection, waitForWebLogin, webAuthExists, whatsAppActionRuntime, writeCredsJsonAtomically };
