import { i as OpenClawConfig } from "../../types.openclaw-C58U02FA.js";
import { t as FallbackAttempt } from "../../model-fallback.types-vzLpXIuM.js";
import { s as AuthProfileStore } from "../../types-BUF85Z6a.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-Cyjs8MS3.js";
import { a as ImageGenerationProviderPlugin } from "../../types-UTp4ves_.js";
import { n as createSubsystemLogger } from "../../subsystem-BDulbhZL.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BP9-Poca.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-BqsKzYqn.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-Bcg3pk79.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-BwdKq3YJ.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-LmyboZJS.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-B7104Xv4.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-DJ1xD1u_.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };