import { i as OpenClawConfig } from "../../types.openclaw-C58U02FA.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-D5JMGY_J.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-hSeaGqMJ.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-1Yw8kMCr.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-DSOWLZWU.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-zIW2Gjsy.js";
import { t as ChannelMessageActionName } from "../../types.public-JfHpZqwR.js";
import { n as PluginRuntime } from "../../types-taiLI91p.js";
import { d as readRemoteMediaBuffer } from "../../fetch-BHsZrjA_.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-DPoY_Hhn.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-Bl9MA3k5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BU12utEU.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-DG95ojWq.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-YvwQXk43.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-C1eIb4OD.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-CXHV0tFO.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-BZa-QZCy.js";
import { n as resolveWebhookPath } from "../../webhook-path-C0u-awmU.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CmF-3zPi.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-CZFt473y.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-4CvvPZhG.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-_CC3fSwg.js";
import { r as createChannelPairingController } from "../../channel-pairing-V1gTvRfa.js";
import { t as chunkTextForOutbound } from "../../text-chunking-C44sdYxM.js";
import { m as missingTargetError } from "../../channel-feedback-DYP6kVAt.js";
import { t as extractToolSend } from "../../tool-send-DDDKtZPy.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-C2oHEvLE.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-BTTwzloO.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };