/* @vitest-environment jsdom */

import { render } from "lit";
import { describe, expect, it } from "vitest";
import { i18n } from "../../i18n/index.ts";
import type { AppViewState } from "../app-view-state.ts";
import { renderLoginGate } from "./login-gate.ts";

function createState(overrides: Partial<AppViewState> = {}): AppViewState {
  const settings = {
    gatewayUrl: "ws://127.0.0.1:18789",
    token: "",
    sessionKey: "main",
    lastActiveSessionKey: "main",
    theme: "claw",
    themeMode: "system",
    chatFocusMode: false,
    chatShowThinking: true,
    chatShowToolCalls: true,
    splitRatio: 0.6,
    navCollapsed: false,
    navWidth: 220,
    navGroupsCollapsed: {},
    borderRadius: 50,
    locale: "en",
  } as AppViewState["settings"];

  return {
    settings,
    password: "",
    loginShowGatewayToken: false,
    loginShowGatewayPassword: false,
    tab: "overview",
    onboarding: false,
    basePath: "",
    connected: false,
    theme: "claw",
    themeMode: "system",
    themeResolved: "dark",
    themeOrder: ["claw", "knot", "dash"],
    hello: null,
    lastError: null,
    lastErrorCode: null,
    eventLog: [],
    assistantName: "OpenClaw",
    assistantAvatar: null,
    assistantAgentId: null,
    localMediaPreviewRoots: [],
    embedSandboxMode: "allow-same-origin",
    allowExternalEmbedUrls: false,
    sessionKey: "main",
    chatLoading: false,
    chatSending: false,
    chatMessage: "",
    chatAttachments: [],
    chatMessages: [],
    chatToolMessages: [],
    chatStreamSegments: [],
    chatStream: null,
    chatStreamStartedAt: null,
    chatRunId: null,
    chatSideResult: null,
    chatSideResultTerminalRuns: new Set(),
    compactionStatus: null,
    fallbackStatus: null,
    chatAvatarUrl: null,
    chatThinkingLevel: null,
    chatModelOverrides: {},
    chatModelsLoading: false,
    chatModelCatalog: [],
    chatQueue: [],
    realtimeTalkActive: false,
    realtimeTalkStatus: "idle",
    realtimeTalkDetail: null,
    realtimeTalkTranscript: null,
    chatManualRefreshInFlight: false,
    nodesLoading: false,
    nodes: [],
    chatNewMessagesBelow: false,
    navDrawerOpen: false,
    sidebarOpen: false,
    sidebarContent: null,
    sidebarError: null,
    splitRatio: 0.6,
    scrollToBottom: () => undefined,
    devicesLoading: false,
    devicesError: null,
    devicesList: null,
    execApprovalsLoading: false,
    execApprovalsSaving: false,
    execApprovalsDirty: false,
    execApprovalsSnapshot: null,
    execApprovalsForm: null,
    execApprovalsSelectedAgent: null,
    execApprovalsTarget: "gateway",
    execApprovalsTargetNodeId: null,
    execApprovalQueue: [],
    execApprovalBusy: false,
    execApprovalError: null,
    pendingGatewayUrl: null,
    configLoading: false,
    configRaw: "",
    configRawOriginal: "",
    configValid: null,
    configIssues: [],
    configSaving: false,
    configApplying: false,
    updateRunning: false,
    applySessionKey: "main",
    configSnapshot: null,
    configSchema: null,
    configSchemaVersion: null,
    configSchemaLoading: false,
    configUiHints: {},
    configForm: null,
    configFormOriginal: null,
    dreamingStatusLoading: false,
    dreamingStatusError: null,
    dreamingStatus: null,
    dreamingModeSaving: false,
    dreamDiaryLoading: false,
    dreamDiaryActionLoading: false,
    dreamDiaryActionMessage: null,
    dreamDiaryActionArchivePath: null,
    dreamDiaryError: null,
    dreamDiaryPath: null,
    dreamDiaryContent: null,
    wikiImportInsightsLoading: false,
    wikiImportInsightsError: null,
    wikiImportInsights: null,
    wikiMemoryPalaceLoading: false,
    wikiMemoryPalaceError: null,
    wikiMemoryPalace: null,
    configFormMode: "form",
    configSettingsMode: "quick",
    configSearchQuery: "",
    configActiveSection: null,
    configActiveSubsection: null,
    communicationsFormMode: "form",
    communicationsSearchQuery: "",
    communicationsActiveSection: null,
    communicationsActiveSubsection: null,
    appearanceFormMode: "form",
    appearanceSearchQuery: "",
    appearanceActiveSection: null,
    appearanceActiveSubsection: null,
    automationFormMode: "form",
    automationSearchQuery: "",
    automationActiveSection: null,
    automationActiveSubsection: null,
    infrastructureFormMode: "form",
    infrastructureSearchQuery: "",
    infrastructureActiveSection: null,
    infrastructureActiveSubsection: null,
    aiAgentsFormMode: "form",
    aiAgentsSearchQuery: "",
    aiAgentsActiveSection: null,
    aiAgentsActiveSubsection: null,
    channelsLoading: false,
    channelsSnapshot: null,
    channelsError: null,
    channelsLastSuccess: null,
    whatsappLoginMessage: null,
    whatsappLoginQrDataUrl: null,
    whatsappLoginConnected: null,
    whatsappBusy: false,
    nostrProfileFormState: null,
    nostrProfileAccountId: null,
    configFormDirty: false,
    presenceLoading: false,
    presenceEntries: [],
    presenceError: null,
    presenceStatus: null,
    agentsLoading: false,
    agentsList: null,
    agentsError: null,
    agentsSelectedId: null,
    toolsCatalogLoading: false,
    toolsCatalogError: null,
    toolsCatalogResult: null,
    toolsEffectiveLoading: false,
    toolsEffectiveLoadingKey: null,
    toolsEffectiveResultKey: null,
    toolsEffectiveError: null,
    toolsEffectiveResult: null,
    agentsPanel: "overview",
    agentFilesLoading: false,
    agentFilesError: null,
    agentFilesList: null,
    agentFileContents: {},
    agentFileDrafts: {},
    agentFileActive: null,
    agentFileSaving: false,
    agentIdentityLoading: false,
    agentIdentityError: null,
    agentIdentityById: {},
    applySettings: () => undefined,
    connect: () => undefined,
    ...overrides,
  } as AppViewState;
}

describe("renderLoginGate", () => {
  it("renders richer operator guidance cards", async () => {
    await i18n.setLocale("en");
    const container = document.createElement("div");
    render(renderLoginGate(createState()), container);
    await Promise.resolve();

    expect(container.textContent).toContain("Operator access");
    expect(container.textContent).toContain("Before you start");
    expect(container.textContent).toContain("What happens after connect");
    expect(container.textContent).toContain("A gateway token is usually required");
  });

  it("renders an auth-specific hint for unauthorized failures", async () => {
    await i18n.setLocale("en");
    const container = document.createElement("div");
    render(
      renderLoginGate(
        createState({
          lastError: "disconnected (4008): unauthorized",
          lastErrorCode: "AUTH_TOKEN_MISSING",
        }),
      ),
      container,
    );
    await Promise.resolve();

    expect(container.textContent).toContain("Gateway token missing or rejected");
    expect(container.textContent).toContain(
      "the token is missing, expired, or from a different gateway instance",
    );
  });
});
