"""Brand Consistency Guard — prevents voice / offer drift across brands.

Every content artifact generated by OpenClaw must pass BrandGuard.validate()
before generation or publish. This prevents:
- CUTMV tone leaking into Full Digital
- Wrong CTA or KPI
- Mismatched funnel steps
- "Generic" outputs that break system integrity

Violations are logged to the brand_guard_violations table and audit_log.
"""
from __future__ import annotations

import sqlite3
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from packages.agencyu.marketing.content.spec import ALLOWED_BRANDS, ContentSpec
from packages.common.logging import get_logger

log = get_logger("agencyu.marketing.content.brand_guard")

_BRAND_VOICE_PATH = Path(__file__).resolve().parents[4] / "config" / "brand_voice.yaml"
_OFFERS_PATH = Path(__file__).resolve().parents[4] / "config" / "offers.yaml"


class BrandConsistencyError(Exception):
    """Raised when a content spec violates brand consistency rules."""

    def __init__(self, message: str, violation_type: str = "unknown"):
        super().__init__(message)
        self.violation_type = violation_type


def load_brand_voice_config(path: Path | None = None) -> dict[str, Any]:
    """Load brand_voice.yaml config."""
    p = path or _BRAND_VOICE_PATH
    if not p.exists():
        log.warning("brand_voice_yaml_not_found", extra={"path": str(p)})
        return {"brands": {}}
    with open(p) as f:
        return yaml.safe_load(f) or {"brands": {}}


def load_offers_config(path: Path | None = None) -> dict[str, Any]:
    """Load offers.yaml config."""
    p = path or _OFFERS_PATH
    if not p.exists():
        return {"offers": []}
    with open(p) as f:
        return yaml.safe_load(f) or {"offers": []}


def validate_spec(
    spec: ContentSpec,
    *,
    brand_voice_cfg: dict[str, Any] | None = None,
    offers_cfg: dict[str, Any] | None = None,
) -> bool:
    """Validate a ContentSpec against brand consistency rules.

    Raises BrandConsistencyError on any violation.
    Returns True if valid.
    """
    bv = brand_voice_cfg or load_brand_voice_config()
    oc = offers_cfg or load_offers_config()

    # 1. Brand must be valid
    if spec.brand not in ALLOWED_BRANDS:
        raise BrandConsistencyError(
            f"Invalid brand={spec.brand}; allowed={ALLOWED_BRANDS}",
            violation_type="invalid_brand",
        )

    brands = bv.get("brands", {})
    if spec.brand not in brands:
        raise BrandConsistencyError(
            f"Brand={spec.brand} not found in brand_voice.yaml",
            violation_type="invalid_brand",
        )

    brand_cfg = brands[spec.brand]

    # 2. Voice profile must be allowed for this brand
    allowed_voices = set(brand_cfg.get("allowed_voice_profiles", []))
    if spec.voice_profile_id not in allowed_voices:
        raise BrandConsistencyError(
            f"voice_profile_id={spec.voice_profile_id} not allowed for "
            f"brand={spec.brand}; allowed={allowed_voices}",
            violation_type="invalid_voice",
        )

    # 3. Offer must belong to brand (if offer exists in config)
    offer = _find_offer(spec.offer_id, oc)
    if offer:
        offer_brand = offer.get("brand", "")
        if offer_brand and offer_brand != spec.brand:
            raise BrandConsistencyError(
                f"offer_id={spec.offer_id} belongs to brand={offer_brand} "
                f"but spec.brand={spec.brand}",
                violation_type="offer_mismatch",
            )

    return True


def validate_and_log(
    spec: ContentSpec,
    conn: sqlite3.Connection | None = None,
    *,
    brand_voice_cfg: dict[str, Any] | None = None,
    offers_cfg: dict[str, Any] | None = None,
    correlation_id: str | None = None,
) -> bool:
    """Validate spec and log any violations to DB.

    Returns True if valid, False if violation (and logs it).
    Does NOT raise — caller decides whether to block or warn.
    """
    try:
        validate_spec(spec, brand_voice_cfg=brand_voice_cfg, offers_cfg=offers_cfg)
        return True
    except BrandConsistencyError as e:
        log.warning("brand_guard_violation", extra={
            "brand": spec.brand,
            "content_type": spec.content_type,
            "offer_id": spec.offer_id,
            "voice_profile_id": spec.voice_profile_id,
            "violation_type": e.violation_type,
            "detail": str(e),
            "correlation_id": correlation_id,
        })

        if conn is not None:
            try:
                conn.execute(
                    """INSERT INTO brand_guard_violations
                       (brand, content_type, offer_id, angle_id, voice_profile_id,
                        violation_type, detail, correlation_id, created_at)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        spec.brand,
                        spec.content_type,
                        spec.offer_id,
                        spec.angle_id,
                        spec.voice_profile_id,
                        e.violation_type,
                        str(e),
                        correlation_id,
                        datetime.now(UTC).isoformat(),
                    ),
                )
                conn.commit()
            except Exception:
                log.debug("brand_guard_violation_log_failed", exc_info=True)

        return False


def _find_offer(offer_id: str, offers_cfg: dict[str, Any]) -> dict[str, Any] | None:
    """Find an offer by ID in the offers config."""
    for o in offers_cfg.get("offers", []):
        if o.get("id") == offer_id:
            return o
    return None
