import { p as isBlockedHostnameOrIp } from "../../ssrf-DGW1EW2J.js";
import { o as SessionEntry } from "../../types-B4QGOCxC.js";
import { v as OpenClawPluginApi } from "../../types-ItMBrbf4.js";
import { _ as sleep } from "../../utils-DqKz1rhL.js";
import { r as GatewayRequestHandlerOptions } from "../../types-C6EZ6C2P.js";
import { t as definePluginEntry } from "../../plugin-entry-C8MR8DG4.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BLITeikV.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-CplxSqix.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-CrJz09PV.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };