import { i as OpenClawConfig } from "../../types.openclaw-BlE9q7jU.js";
import { t as FallbackAttempt } from "../../model-fallback.types-Cu6znUAp.js";
import { s as AuthProfileStore } from "../../types-CLTB9t7S.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-GE_-_n1i.js";
import { t as ImageGenerationProviderPlugin } from "../../types-DKA4S1yN.js";
import { n as createSubsystemLogger } from "../../subsystem-C8Y0zMwJ.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-Bt_BMmaf.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-CKvpOPXS.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-akiVKtBK.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-BA1HqnNn.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-DSRmVxH4.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-BGwMG8DX.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-DW48pXxw.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };