import { i as resolveOpenProviderRuntimeGroupPolicy } from "../../runtime-group-policy-9uFjq66r.js";
import { a as mergeDiscordAccountConfig, f as resolveDiscordMaxLinesPerMessage, i as listEnabledDiscordAccounts, l as resolveDiscordAccountConfig, o as resolveDefaultDiscordAccountId, r as listDiscordAccountIds, s as resolveDiscordAccount, t as createDiscordActionGate } from "../../accounts-hlGm-UpK.js";
import { t as inspectDiscordAccount } from "../../account-inspect-CY8pYhSV.js";
import { n as resolveDiscordChannelId, t as parseDiscordTarget } from "../../target-parsing-CGq_C3qw.js";
import { n as fetchDiscord, r as requestDiscord, t as DiscordApiError } from "../../api-DFvN2Gp8.js";
import { i as normalizeDiscordOutboundTarget, n as looksLikeDiscordTargetId, r as normalizeDiscordMessagingTarget } from "../../normalize-BhglkFhx.js";
import { n as resolveDiscordTarget, r as parseDiscordSendTarget } from "../../target-resolver-CeiGP6Ft.js";
import { a as buildDiscordComponentMessageFlags, c as resolveDiscordComponentAttachmentName, d as buildDiscordComponentCustomId, f as buildDiscordModalCustomId, g as parseDiscordModalCustomIdForInteraction, h as parseDiscordModalCustomId, i as buildDiscordComponentMessage, l as DISCORD_COMPONENT_CUSTOM_ID_KEY, m as parseDiscordComponentCustomIdForInteraction, n as DiscordFormModal, o as DISCORD_COMPONENT_ATTACHMENT_PREFIX, p as parseDiscordComponentCustomId, r as createDiscordFormModal, s as readDiscordComponentSpec, t as formatDiscordComponentEventText, u as DISCORD_MODAL_CUSTOM_ID_KEY } from "../../components-BKRgZqKV.js";
import { t as buildDiscordInteractiveComponents } from "../../shared-interactive-hK2KE-PQ.js";
import "../../targets-BCvTXz7D.js";
import { a as shouldSuppressLocalDiscordExecApprovalPrompt, i as isDiscordExecApprovalClientEnabled, n as getDiscordExecApprovalApprovers, r as isDiscordExecApprovalApprover } from "../../approval-shared-6WEwicxa.js";
import { i as resolveDiscordGroupToolPolicy, n as collectDiscordStatusIssues, r as resolveDiscordGroupRequireMention, t as discordPlugin } from "../../channel-WoaSrO5k.js";
import { t as normalizeExplicitDiscordSessionKey } from "../../session-key-normalization-BNmeqD8U.js";
import { t as discordSetupPlugin } from "../../channel.setup-D3J1o4K6.js";
import { n as handleDiscordSubagentEnded, r as handleDiscordSubagentSpawning, t as handleDiscordSubagentDeliveryTarget } from "../../subagent-hooks-fuuqnF1c.js";
import { t as tryHandleDiscordMessageActionGuildAdmin } from "../../handle-action.guild-admin-Dcp8gkky.js";
import { n as listDiscordDirectoryPeersFromConfig, t as listDiscordDirectoryGroupsFromConfig } from "../../directory-config-D_-fyQ4t.js";
import { t as fetchPluralKitMessageInfo } from "../../pluralkit-Hw2lZSHj.js";
import { a as resolveDiscordPrivilegedIntentsFromFlags, i as probeDiscord, n as fetchDiscordApplicationSummary, r as parseApplicationIdFromToken, t as fetchDiscordApplicationId } from "../../probe-BXjx4wVU.js";
import { t as collectDiscordSecurityAuditFindings } from "../../security-audit-BkyVgpkF.js";
import { a as mergeAbortSignals, i as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, n as DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, r as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, t as DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS } from "../../timeouts-Cbtr1o6S.js";
//#region extensions/discord/api.ts
const handleDiscordMessageAction = async (...args) => (await import("../../channel-actions.runtime-BXT-IFFz.js")).handleDiscordMessageAction(...args);
//#endregion
export { DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS, DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, DISCORD_COMPONENT_ATTACHMENT_PREFIX, DISCORD_COMPONENT_CUSTOM_ID_KEY, DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, DISCORD_MODAL_CUSTOM_ID_KEY, DiscordApiError, DiscordFormModal, buildDiscordComponentCustomId, buildDiscordComponentMessage, buildDiscordComponentMessageFlags, buildDiscordInteractiveComponents, buildDiscordModalCustomId, collectDiscordSecurityAuditFindings, collectDiscordStatusIssues, createDiscordActionGate, createDiscordFormModal, discordPlugin, discordSetupPlugin, fetchDiscord, fetchDiscordApplicationId, fetchDiscordApplicationSummary, fetchPluralKitMessageInfo, formatDiscordComponentEventText, getDiscordExecApprovalApprovers, handleDiscordMessageAction, handleDiscordSubagentDeliveryTarget, handleDiscordSubagentEnded, handleDiscordSubagentSpawning, inspectDiscordAccount, isDiscordExecApprovalApprover, isDiscordExecApprovalClientEnabled, listDiscordAccountIds, listDiscordDirectoryGroupsFromConfig, listDiscordDirectoryPeersFromConfig, listEnabledDiscordAccounts, looksLikeDiscordTargetId, mergeAbortSignals, mergeDiscordAccountConfig, normalizeDiscordMessagingTarget, normalizeDiscordOutboundTarget, normalizeExplicitDiscordSessionKey, parseApplicationIdFromToken, parseDiscordComponentCustomId, parseDiscordComponentCustomIdForInteraction as parseDiscordComponentCustomIdForCarbon, parseDiscordComponentCustomIdForInteraction, parseDiscordModalCustomId, parseDiscordModalCustomIdForInteraction as parseDiscordModalCustomIdForCarbon, parseDiscordModalCustomIdForInteraction, parseDiscordSendTarget, parseDiscordTarget, probeDiscord, readDiscordComponentSpec, requestDiscord, resolveDefaultDiscordAccountId, resolveDiscordAccount, resolveDiscordAccountConfig, resolveDiscordChannelId, resolveDiscordComponentAttachmentName, resolveDiscordGroupRequireMention, resolveDiscordGroupToolPolicy, resolveDiscordMaxLinesPerMessage, resolveDiscordPrivilegedIntentsFromFlags, resolveOpenProviderRuntimeGroupPolicy as resolveDiscordRuntimeGroupPolicy, resolveDiscordTarget, shouldSuppressLocalDiscordExecApprovalPrompt, tryHandleDiscordMessageActionGuildAdmin };
