import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { t as getChatChannelMeta } from "../../chat-meta-42nqDCp5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-gd9RYI9s.js";
import { n as AcpRuntimeError } from "../../errors-zyHRqIKC.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-B0XXBiTk.js";
import { r as resolvePollMaxSelections } from "../../polls-CEgX13A5.js";
import { t as clearAccountEntryFields } from "../../config-helpers-2u-Tk5Gc.js";
import { n as formatPairingApproveHint } from "../../helpers-BlOFYFV6.js";
import { r as makeProxyFetch } from "../../proxy-fetch-heFvP-e2.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-CFxwu5OO.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-B2hwkAxP.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-DKSCebYh.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DpL4qtml.js";
import "../../channel-core-Dc8oCRP3.js";
import { t as resolveTelegramToken } from "../../token-V-P0MXv-.js";
import "../../acp-runtime-RrlyZRqc.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-Jq5bmS3N.js";
import "../../channel-plugin-common-BAK9lS-p.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-DC20QesH.js";
import "../../channel-status-DsH1v7Er.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-DI3MKmEu.js";
import "../../channel-actions-BoEvPE91.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-DI2NNSzb.js";
import { n as setTelegramRuntime } from "../../runtime-DMDis9SK.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-B53qJjaR.js";
import "../../config-api-mO6ejddM.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-Dg09-LK0.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-CFqDQhIS.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-42NNWvdj.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-BaHU4Niq.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
