import { i as OpenClawConfig } from "../../types.openclaw-CoVv5VQR.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-Df4-Bt6H.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-B0aZxYiS.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Ds9BBXA3.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-CQScvK0N.js";
import { t as ChannelMessageActionName } from "../../types.public-BMrZTIWg.js";
import { n as PluginRuntime } from "../../types-DVhGJHIy.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-qfLnkrwU.js";
import { o as fetchRemoteMedia } from "../../fetch-y1R1eLI6.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BPInIQpI.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DyWSTJ5E.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-45eN-jyu.js";
import { c as resolveDmGroupAccessWithLists } from "../../dm-policy-shared-LVfLuhge.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-C9QwyK0J.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-Bmqcn98O.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-STYjuANm.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-CmSPTWXD.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-FhJBmufJ.js";
import { n as resolveWebhookPath } from "../../webhook-path-ilUGnvtv.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CVVv_KUh.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-BVNvbSOL.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-sP8ru_2h.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-B88OPMOG.js";
import { d as resolveSenderScopedGroupPolicy, s as evaluateGroupRouteAccessForPolicy } from "../../group-access-DK5RmZHa.js";
import { r as createChannelPairingController } from "../../channel-pairing-B8mQlhPz.js";
import { t as chunkTextForOutbound } from "../../text-chunking-BkFkH-DO.js";
import { d as missingTargetError } from "../../channel-feedback-BVxOhBbY.js";
import { t as extractToolSend } from "../../tool-send-BdGmsCjy.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-DiWrzF-q.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-CxnNK6Z-.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, evaluateGroupRouteAccessForPolicy, extractToolSend, fetchRemoteMedia, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveDmGroupAccessWithLists, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveSenderScopedGroupPolicy, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };