import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { t as getChatChannelMeta } from "../../chat-meta-42nqDCp5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DfoOcZXb.js";
import { n as AcpRuntimeError } from "../../errors-BQ_d75hG.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-BRnn7Owx.js";
import { r as resolvePollMaxSelections } from "../../polls-CTmt9f_N.js";
import { t as clearAccountEntryFields } from "../../config-helpers-V1PIzdIZ.js";
import { n as formatPairingApproveHint } from "../../helpers-B1IM5IVe.js";
import { r as makeProxyFetch } from "../../proxy-fetch-BypAsJtJ.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-URMrPZj2.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-u3OO_569.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-C4krLIUQ.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-6o9dmHZ0.js";
import "../../channel-core-DrLpYp9h.js";
import { t as resolveTelegramToken } from "../../token-CdaM1YbV.js";
import "../../acp-runtime-CG4HK0vg.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-BLG_q0yv.js";
import "../../channel-plugin-common-B9Z-DZj_.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-Csewe3pX.js";
import "../../channel-status-BrGRj_08.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-BcAkK-Ic.js";
import "../../channel-actions-D-k0Jbqk.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-Dqxq9ig2.js";
import { n as setTelegramRuntime } from "../../runtime-D2Vjc3Qa.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-Ht2aXTQw.js";
import "../../config-api-Bm0qvFON.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-CkHgczi4.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-BZZUyuso.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-CsVl5xvD.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-B5jgbTTS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
