import { p as isBlockedHostnameOrIp } from "../../ssrf-CMKWbO56.js";
import { o as SessionEntry } from "../../types-DkFheG7a.js";
import { C as OpenClawPluginApi } from "../../types-B1YsHkjI.js";
import { _ as sleep } from "../../utils-D4sGGnmQ.js";
import { r as GatewayRequestHandlerOptions } from "../../types-CIUzzx_d.js";
import { t as definePluginEntry } from "../../plugin-entry-CIF8g-3_.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BzbwrEoM.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-C3-9isUL.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-92fUqxk_.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };