import { p as isBlockedHostnameOrIp } from "../../ssrf-DpkM3iBz.js";
import { o as SessionEntry } from "../../types-C-MWEBlF.js";
import { y as OpenClawPluginApi } from "../../types-CWJThuOe2.js";
import { _ as sleep } from "../../utils-BIopLFWh.js";
import { r as GatewayRequestHandlerOptions } from "../../types-Hf3aPs3a.js";
import { t as definePluginEntry } from "../../plugin-entry-DD_6L5AZ.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-Dj1fWwLa.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-DHvVW0Ue.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-Cdo_4RMw.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };