import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-CBTMFdxJ.js";
import { t as getChatChannelMeta } from "../../chat-meta-C-z5IbYD.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BzjbZqXE.js";
import { n as AcpRuntimeError } from "../../errors-DAXhP6WZ.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-BA98Cs8a.js";
import { r as makeProxyFetch } from "../../proxy-fetch-BGacK047.js";
import { r as resolvePollMaxSelections } from "../../polls-8FE60qiC.js";
import { t as clearAccountEntryFields } from "../../config-helpers-Dd-Yltzo.js";
import { n as formatPairingApproveHint } from "../../helpers-BH5_-HwZ.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-BOt3I9VS.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-B7dmLA7w.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-JAQG2I5N.js";
import "../../channel-core-BV8Aa--P.js";
import { t as resolveTelegramToken } from "../../token-BctU4DWY.js";
import "../../acp-runtime-C_iB31ep.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DmHuSBT7.js";
import "../../channel-plugin-common-j8mpLYIY.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-Csn-585_.js";
import "../../channel-status-O4BFybJX.js";
import "../../channel-actions-D67Km9Lw.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-DswEB_5G.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-CdxmHBe1.js";
import { n as setTelegramRuntime } from "../../runtime-Ddx0xFXj.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-yz2blRcw.js";
import "../../config-api-DLF8uGoF.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-BI9AX4Pc.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-BVsDa2XH.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-DvMIsaj7.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-ClNAyx2q.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
