import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-Bj7l9NI7.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-Dp8HfAry.js";
import { t as getChatChannelMeta } from "../../chat-meta-YaI828S4.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BmvPUIYK.js";
import { n as AcpRuntimeError } from "../../errors-CCOu3UYh.js";
import { f as readNumberParam, g as readStringParam, h as readStringOrNumberParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../../common-Cf8ajZVR.js";
import { r as makeProxyFetch } from "../../proxy-fetch-BZGgC83i.js";
import { r as resolvePollMaxSelections } from "../../polls-CXU6j-rl.js";
import { t as clearAccountEntryFields } from "../../config-helpers-CI7vhbyR.js";
import { n as formatPairingApproveHint } from "../../helpers-PfWBHn-b.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields--WUdg_b7.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-C9YMRwT0.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DyrF9ISN.js";
import "../../channel-core-CUMQ1-YM.js";
import { t as resolveTelegramToken } from "../../token-DfAGU6j4.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-C0n2CCnm.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-BpxzCz5l.js";
import "../../acp-runtime-BbPtv2Om.js";
import "../../channel-plugin-common-6lb5RnKU.js";
import "../../channel-status-CGjVWC2r.js";
import "../../channel-actions-eIOtDEsn.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-C5L6375S.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-DOjKhpO5.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-BPe55136.js";
import { n as setTelegramRuntime } from "../../runtime-D063dicg.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-CY0Ja1es.js";
import "../../config-api-DlV9jdA_.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-xfCyqdkd.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-DdxiztQV.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-BSbDMjyx.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
