import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-Chk998Rz.js";
import { t as getChatChannelMeta } from "../../chat-meta-DNnFqIhM.js";
import { r as buildChannelConfigSchema } from "../../config-schema-B1ZkUpkb.js";
import { n as AcpRuntimeError } from "../../errors-Qjv3JjUa.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-BOb9qduE.js";
import { r as makeProxyFetch } from "../../proxy-fetch-BRLDCCl6.js";
import { r as resolvePollMaxSelections } from "../../polls-DD5sSXK4.js";
import { t as clearAccountEntryFields } from "../../config-helpers-UmJikSPI.js";
import { n as formatPairingApproveHint } from "../../helpers-C42hXXcT.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-CR4_JSwo.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-CoSWJZ3o.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-CsmHDskg.js";
import "../../channel-core-4zhtAoLo.js";
import { t as resolveTelegramToken } from "../../token-CdbwgpLa.js";
import "../../acp-runtime-CmmrH4U4.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-rhC4efse.js";
import "../../channel-plugin-common-DXuwXu6b.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-D6qvq3Fy.js";
import "../../channel-status-DqKjqAvf.js";
import "../../channel-actions-Cmk6tqyd.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-hJaObwyJ.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-BvpPXwCo.js";
import { n as setTelegramRuntime } from "../../runtime-BzsOZ0zW.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-CXcCJWLj.js";
import "../../config-api-PTK2K1fW.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-Dy2kBXhP.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-BhcXgAyf.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-Duz8NgL-.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-XVA0DQ3L.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
