# fly.toml app configuration file generated for openclaw-p28yiw on 2026-08-18T02:09:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openclaw-p28yiw'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  NODE_OPTIONS = '--max-old-space-size=1536'
  OPENCLAW_PREFER_PNPM = '1'
  OPENCLAW_STATE_DIR = '/data'

[processes]
  app = ''

[[mounts]]
  source = 'openclaw_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
grace_period = "2m"
interval = "15s"
method = "GET"
timeout = "5s"
path = "/startupz"

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2048mb'
