import { i as OpenClawConfig } from "../../types.openclaw-Bpxi7OSY.js";
import { t as FallbackAttempt } from "../../model-fallback.types-Cc6tKGi5.js";
import { s as AuthProfileStore } from "../../types-G2uE8rLd.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-fBinwhZe.js";
import { a as ImageGenerationProviderPlugin } from "../../types-Cdl1yOYR.js";
import { n as createSubsystemLogger } from "../../subsystem-DH9VREij.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-B67oI-FD.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-BnBedje2.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-B-jJ_9uG.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-B4-mBP1-.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-BMA01QAn.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-CORYA7Nm.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-PQadddsv.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };