import { i as OpenClawConfig } from "../../types.openclaw-CoVv5VQR.js";
import { t as FallbackAttempt } from "../../model-fallback.types-CdKSKAjU.js";
import { a as AuthProfileStore } from "../../types-B9g5YyO3.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-BZZ3yyr0.js";
import { t as ImageGenerationProviderPlugin } from "../../types-BYigPDoy.js";
import { n as createSubsystemLogger } from "../../subsystem-DzIJaqs3.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BCwxpBfa.js";
import { j as normalizeGooglePreviewModelId } from "../../provider-model-shared-DvjlGN2h.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-DZIBYbYi.js";
import { i as parseGeminiAuth, n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-BGGbtvEu.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-BL2xehLJ.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-dJPPSu7F.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-C97fNKqM.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseGeminiAuth, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };