import type { App } from "@slack/bolt";
import type { OpenClawConfig, SlackReactionNotificationMode } from "openclaw/plugin-sdk/config-contracts";
import type { SessionScope } from "openclaw/plugin-sdk/config-contracts";
import type { DmPolicy, GroupPolicy } from "openclaw/plugin-sdk/config-contracts";
import type { HistoryEntry } from "openclaw/plugin-sdk/reply-history";
import { getChildLogger } from "openclaw/plugin-sdk/runtime-env";
import type { RuntimeEnv } from "openclaw/plugin-sdk/runtime-env";
import type { SlackMessageEvent } from "../types.js";
import type { SlackChannelConfigEntries } from "./channel-config.js";
export { normalizeSlackChannelType, resolveSlackChatType } from "./channel-type.js";
export type SlackAssistantSuggestedPrompt = {
    title: string;
    message: string;
};
export type SlackAssistantThreadContext = {
    assistantChannelId: string;
    threadTs: string;
    userId?: string;
    channelId?: string;
    teamId?: string;
    enterpriseId?: string | null;
    updatedAt: number;
};
export declare const SLACK_ASSISTANT_THREAD_CONTEXT_METADATA_EVENT = "assistant_thread_context";
export declare function buildSlackAssistantThreadMetadata(context: Omit<SlackAssistantThreadContext, "updatedAt">): {
    event_type: string;
    event_payload: Record<string, string>;
};
export declare function parseSlackAssistantThreadMetadata(value: unknown): {
    channelId: string | undefined;
    teamId: string | undefined;
    enterpriseId: string | undefined;
} | undefined;
export type SlackMonitorContext = {
    cfg: OpenClawConfig;
    accountId: string;
    botToken: string;
    app: App;
    runtime: RuntimeEnv;
    botUserId: string;
    botId?: string;
    teamId: string;
    apiAppId: string;
    historyLimit: number;
    dmHistoryLimit: number;
    channelHistories: Map<string, HistoryEntry[]>;
    sessionScope: SessionScope;
    mainKey: string;
    dmEnabled: boolean;
    dmPolicy: DmPolicy;
    allowFrom: string[];
    allowNameMatching: boolean;
    groupDmEnabled: boolean;
    groupDmChannels: string[];
    defaultRequireMention: boolean;
    channelsConfig?: SlackChannelConfigEntries;
    channelsConfigKeys: string[];
    groupPolicy: GroupPolicy;
    useAccessGroups: boolean;
    reactionMode: SlackReactionNotificationMode;
    reactionAllowlist: Array<string | number>;
    replyToMode: "off" | "first" | "all" | "batched";
    threadHistoryScope: "thread" | "channel";
    threadInheritParent: boolean;
    threadRequireExplicitMention: boolean;
    slashCommand: Required<import("openclaw/plugin-sdk/config-contracts").SlackSlashCommandConfig>;
    textLimit: number;
    ackReactionScope: string;
    typingReaction: string;
    mediaMaxBytes: number;
    removeAckAfterReply: boolean;
    logger: ReturnType<typeof getChildLogger>;
    markMessageSeen: (channelId: string | undefined, ts?: string) => boolean;
    releaseSeenMessage: (channelId: string | undefined, ts?: string) => void;
    shouldDropMismatchedSlackEvent: (body: unknown) => boolean;
    resolveSlackSystemEventSessionKey: (params: {
        channelId?: string | null;
        channelType?: string | null;
        senderId?: string | null;
        threadTs?: string | null;
    }) => string;
    isChannelAllowed: (params: {
        channelId?: string;
        channelName?: string;
        channelType?: SlackMessageEvent["channel_type"];
    }) => boolean;
    resolveChannelName: (channelId: string) => Promise<{
        name?: string;
        type?: SlackMessageEvent["channel_type"];
        topic?: string;
        purpose?: string;
    }>;
    resolveUserName: (userId: string) => Promise<{
        name?: string;
    }>;
    setSlackThreadStatus: (params: {
        channelId: string;
        threadTs?: string;
        status: string;
    }) => Promise<void>;
    getSlackAssistantThreadContext: (channelId: string | undefined, threadTs: string | undefined) => SlackAssistantThreadContext | undefined;
    saveSlackAssistantThreadContext: (context: Omit<SlackAssistantThreadContext, "updatedAt">) => void;
    setSlackAssistantSuggestedPrompts: (params: {
        channelId: string;
        threadTs: string;
        title?: string;
        prompts: SlackAssistantSuggestedPrompt[];
    }) => Promise<boolean>;
};
export declare function createSlackMonitorContext(params: {
    cfg: OpenClawConfig;
    accountId: string;
    botToken: string;
    app: App;
    runtime: RuntimeEnv;
    botUserId: string;
    botId?: string;
    teamId: string;
    apiAppId: string;
    historyLimit: number;
    dmHistoryLimit?: number;
    sessionScope: SessionScope;
    mainKey: string;
    dmEnabled: boolean;
    dmPolicy: DmPolicy;
    allowFrom: Array<string | number> | undefined;
    allowNameMatching: boolean;
    groupDmEnabled: boolean;
    groupDmChannels: Array<string | number> | undefined;
    defaultRequireMention?: boolean;
    channelsConfig?: SlackMonitorContext["channelsConfig"];
    groupPolicy: SlackMonitorContext["groupPolicy"];
    useAccessGroups: boolean;
    reactionMode: SlackReactionNotificationMode;
    reactionAllowlist: Array<string | number>;
    replyToMode: SlackMonitorContext["replyToMode"];
    threadHistoryScope: SlackMonitorContext["threadHistoryScope"];
    threadInheritParent: SlackMonitorContext["threadInheritParent"];
    threadRequireExplicitMention: SlackMonitorContext["threadRequireExplicitMention"];
    slashCommand: SlackMonitorContext["slashCommand"];
    textLimit: number;
    ackReactionScope: string;
    typingReaction: string;
    mediaMaxBytes: number;
    removeAckAfterReply: boolean;
}): SlackMonitorContext;
