// Bearer-token credential store for the orchestrator's HTTP route.
// Recon A-B3 — token lives at `~/.openclaw/credentials/orchestrator-bearer.json`
// (mode 0o600), generated by `openclaw orchestrator init`, rotated by
// `openclaw orchestrator rotate-token`. The MC `.env.local` is a
// best-effort mirror; the credentials file is the source of truth.

import { randomBytes } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";

export interface OrchestratorCredentials {
  version: 1;
  token: string;
  createdAt: string;
}

export type CredentialsErrorCode = "missing" | "world_readable" | "schema_drift" | "io_error";

export class CredentialsError extends Error {
  constructor(
    message: string,
    public readonly code: CredentialsErrorCode,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "CredentialsError";
  }
}

export interface CredentialsOptions {
  /** Override path. Default `~/.openclaw/credentials/orchestrator-bearer.json`. */
  path?: string;
  /** Override clock for tests. */
  now?: () => number;
}

export function defaultCredentialsPath(): string {
  return resolve(homedir(), ".openclaw", "credentials", "orchestrator-bearer.json");
}

/** 32 random bytes encoded as hex (64 chars). */
export function generateToken(): string {
  return randomBytes(32).toString("hex");
}

function ensureSecureMode(path: string): void {
  let st;
  try {
    st = statSync(path);
  } catch {
    return;
  }
  // Bits 0o077 = group + others. If any are set, file is too permissive.
  if ((st.mode & 0o077) !== 0) {
    throw new CredentialsError(
      `credentials file ${path} is world/group-readable (mode ${(st.mode & 0o777).toString(8)}); expected 0o600`,
      "world_readable",
      { mode: st.mode & 0o777 },
    );
  }
}

/**
 * Read the credentials file. Throws `CredentialsError` with code:
 *   - "missing" — file doesn't exist
 *   - "world_readable" — file exists but mode is too loose
 *   - "schema_drift" — file exists but JSON is wrong shape
 *   - "io_error" — anything else
 */
export function readCredentials(options: CredentialsOptions = {}): OrchestratorCredentials {
  const path = options.path ?? defaultCredentialsPath();
  if (!existsSync(path)) {
    throw new CredentialsError(
      `orchestrator credentials missing at ${path}; run \`openclaw orchestrator init\``,
      "missing",
    );
  }
  ensureSecureMode(path);
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    throw new CredentialsError(`failed to read credentials at ${path}`, "io_error", {
      cause: (err as Error).message,
    });
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new CredentialsError(`credentials at ${path} are not valid JSON`, "schema_drift");
  }
  if (
    !parsed ||
    typeof parsed !== "object" ||
    (parsed as { version?: unknown }).version !== 1 ||
    typeof (parsed as { token?: unknown }).token !== "string" ||
    typeof (parsed as { createdAt?: unknown }).createdAt !== "string"
  ) {
    throw new CredentialsError(`credentials at ${path} have unexpected shape`, "schema_drift", {
      received: parsed,
    });
  }
  return parsed as OrchestratorCredentials;
}

export interface WriteCredentialsInput extends CredentialsOptions {
  /** Token to write. If omitted, a fresh one is generated. */
  token?: string;
}

/**
 * Atomically write the credentials file with mode 0o600. Returns the
 * persisted record. Used by `openclaw orchestrator init` and
 * `rotate-token`.
 */
export function writeCredentials(input: WriteCredentialsInput = {}): OrchestratorCredentials {
  const path = input.path ?? defaultCredentialsPath();
  const now = input.now ?? Date.now;
  const credentials: OrchestratorCredentials = {
    version: 1,
    token: input.token ?? generateToken(),
    createdAt: new Date(now()).toISOString(),
  };
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(credentials, null, 2)}\n`, {
    mode: 0o600,
  });
  // chmod again after rename in case umask widened the temp file.
  renameSync(tmp, path);
  chmodSync(path, 0o600);
  return credentials;
}

/** Try to read; return null if the file is missing. Throws other CredentialsError codes. */
export function tryReadCredentials(
  options: CredentialsOptions = {},
): OrchestratorCredentials | null {
  try {
    return readCredentials(options);
  } catch (err) {
    if (err instanceof CredentialsError && err.code === "missing") {
      return null;
    }
    throw err;
  }
}
