import { i as OpenClawConfig } from "../../types.openclaw-DNoZmPZ8.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DT4PhXy8.js";
import { s as AuthProfileStore } from "../../types-xTqETsod.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-B2qevvx1.js";
import { Un as VideoGenerationProviderPlugin } from "../../types-CT4HF0Ri.js";
import { n as createSubsystemLogger } from "../../subsystem-B2aVKzlE.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-Cpl_XAY2.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-Cc48-PrL.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-2bHxWacm.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CTiTP5QU.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-BM6yc40m.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-NBvExXj-.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };