import { g as DEFAULT_ACCOUNT_ID, v as normalizeAccountId } from "./session-key-BwICpQs5.js";
import { It as resolveAllowlistProviderRuntimeGroupPolicy, Lt as resolveDefaultGroupPolicy, Pt as init_runtime_group_policy, W as getChatChannelMeta } from "./runtime-CDMAx_h4.js";
import { Jl as resolveTelegramGroupToolPolicy, gd as resolveConfiguredFromCredentialStatuses, hd as projectCredentialSnapshotFields, ql as resolveTelegramGroupRequireMention } from "./setup-wizard-helpers-BPw-E_P4.js";
import "./provider-env-vars-CWXfFyDU.js";
import "./logger-D1gzveLR.js";
import "./tmp-openclaw-dir-DgWJsVV_.js";
import "./subsystem-0lZt3jI5.js";
import "./utils-DknlDzAi.js";
import "./fetch-CysqlwhH.js";
import "./retry-CyJj_oar.js";
import { t as emptyPluginConfigSchema } from "./config-schema-X8cahxVt.js";
import "./paths-BDsrA18Z.js";
import { f as TelegramConfigSchema, q as buildTokenChannelStatusSummary } from "./signal-FT4PyBH3.js";
import { a as formatPairingApproveHint, n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields, u as buildChannelConfigSchema } from "./config-helpers-BQX8LEv1.js";
import "./fetch-CKhAJuFk.js";
import "./exec-DEBhRlDf.js";
import "./agent-scope-CgozsAuQ.js";
import { r as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "./setup-helpers-vyA9zMMX.js";
import { g as listTelegramDirectoryPeersFromConfig, h as listTelegramDirectoryGroupsFromConfig } from "./reply-prefix-Dcd4HlHm.js";
import "./logger-CXkOEiRn.js";
import "./fetch-guard-DryYzke6.js";
import "./resolve-route-CPxNiUBg.js";
import "./pairing-token-ukgXF6GK.js";
import "./query-expansion-t4qzEE5Z.js";
import "./redact-DkskT6Xp.js";
import { t as PAIRING_APPROVED_MESSAGE } from "./channel-plugin-common-Cs4waNSc.js";
import "./secret-file-CCHXecQt.js";
//#region src/plugin-sdk/telegram.ts
init_runtime_group_policy();
//#endregion
export { DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, applyAccountNameToChannelSection, buildChannelConfigSchema, buildTokenChannelStatusSummary, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, listTelegramDirectoryGroupsFromConfig, listTelegramDirectoryPeersFromConfig, migrateBaseNameToDefaultAccount, normalizeAccountId, projectCredentialSnapshotFields, resolveAllowlistProviderRuntimeGroupPolicy, resolveConfiguredFromCredentialStatuses, resolveDefaultGroupPolicy, resolveTelegramGroupRequireMention, resolveTelegramGroupToolPolicy, setAccountEnabledInConfigSection };
