/* AUTO-GENERATED — DO NOT EDIT MANUALLY.
 * Generated by: tools/generate-compositions.ts
 * Specs: 55 files from data/datasets/cutmv/motion/specs/
 *
 * DEFERRED PARSING: Each spec JSON is statically imported (Webpack-safe)
 * but parseMotionSpec + adaptRichSpec run only at render time via useMemo.
 * This keeps Studio boot fast with 55 specs.
 */
import React from "react";
import { Composition } from "remotion";
import { CutmvPremiumAdEngine } from "./compositions/CutmvPremiumAdEngine";
import { parseMotionSpec } from "./engine/parser/parseMotionSpec";
import { adaptRichSpec } from "./engine/parser/adaptRichSpec";
import type { MotionSpec } from "./engine/parser/MotionSpecTypes";

// ── Static JSON imports (Webpack resolves these at build time) ──
import raw_v001 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v001.json";
import raw_v002 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v002.json";
import raw_v003 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v003.json";
import raw_v004 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v004.json";
import raw_v005 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v005.json";
import raw_v006 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v006.json";
import raw_v007 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v007.json";
import raw_v008 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v008.json";
import raw_v009 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v009.json";
import raw_v010 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v010.json";
import raw_v011 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v011.json";
import raw_v012 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v012.json";
import raw_v013 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v013.json";
import raw_v014 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v014.json";
import raw_v015 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v015.json";
import raw_v016 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v016.json";
import raw_v017 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v017.json";
import raw_v018 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v018.json";
import raw_v019 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v019.json";
import raw_v020 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v020.json";
import raw_v021 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v021.json";
import raw_v022 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v022.json";
import raw_v023 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v023.json";
import raw_v024 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v024.json";
import raw_v025 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v025.json";
import raw_v026 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v026.json";
import raw_v027 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v027.json";
import raw_v028 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v028.json";
import raw_v029 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v029.json";
import raw_v030 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v030.json";
import raw_v031 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v031.json";
import raw_v032 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v032.json";
import raw_v033 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v033.json";
import raw_v034 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v034.json";
import raw_v035 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v035.json";
import raw_v036 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v036.json";
import raw_v037 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v037.json";
import raw_v038 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v038.json";
import raw_v039 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v039.json";
import raw_v040 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v040.json";
import raw_v041 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v041.json";
import raw_v043 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v043.json";
import raw_v044 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v044.json";
import raw_v045 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v045.json";
import raw_v046 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v046.json";
import raw_v047 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v047.json";
import raw_v048 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v048.json";
import raw_v049 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v049.json";
import raw_v050 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v050.json";
import raw_v051 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v051.json";
import raw_v052 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v052.json";
import raw_v053 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v053.json";
import raw_v054 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v054.json";
import raw_v055 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v055.json";
import raw_v056 from "../../../data/datasets/cutmv/motion/specs/cutmv_premium_v056.json";

/**
 * DeferredEngine — Wraps CutmvPremiumAdEngine with deferred spec parsing.
 * The raw JSON is passed as a prop; parsing + validation happens in useMemo
 * only when this specific composition is rendered (selected in Studio).
 */
const DeferredEngine: React.FC<{ rawSpec: Record<string, unknown> }> = ({ rawSpec }) => {
  const spec = React.useMemo<MotionSpec>(() => {
    return parseMotionSpec(adaptRichSpec(rawSpec) as Record<string, unknown>);
  }, [rawSpec]);

  return <CutmvPremiumAdEngine spec={spec} />;
};

export const GeneratedCompositions: React.FC = () => (
  <>
    <Composition
      key="cutmv-premium-v001"
      id="cutmv-premium-v001"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v001 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v002"
      id="cutmv-premium-v002"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v002 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v003"
      id="cutmv-premium-v003"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v003 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v004"
      id="cutmv-premium-v004"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v004 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v005"
      id="cutmv-premium-v005"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v005 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v006"
      id="cutmv-premium-v006"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v006 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v007"
      id="cutmv-premium-v007"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v007 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v008"
      id="cutmv-premium-v008"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v008 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v009"
      id="cutmv-premium-v009"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v009 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v010"
      id="cutmv-premium-v010"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v010 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v011"
      id="cutmv-premium-v011"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v011 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v012"
      id="cutmv-premium-v012"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v012 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v013"
      id="cutmv-premium-v013"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v013 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v014"
      id="cutmv-premium-v014"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v014 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v015"
      id="cutmv-premium-v015"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v015 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v016"
      id="cutmv-premium-v016"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v016 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v017"
      id="cutmv-premium-v017"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v017 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v018"
      id="cutmv-premium-v018"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v018 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v019"
      id="cutmv-premium-v019"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v019 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v020"
      id="cutmv-premium-v020"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v020 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v021"
      id="cutmv-premium-v021"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v021 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v022"
      id="cutmv-premium-v022"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v022 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v023"
      id="cutmv-premium-v023"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v023 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v024"
      id="cutmv-premium-v024"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v024 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v025"
      id="cutmv-premium-v025"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v025 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v026"
      id="cutmv-premium-v026"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v026 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v027"
      id="cutmv-premium-v027"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v027 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v028"
      id="cutmv-premium-v028"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v028 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v029"
      id="cutmv-premium-v029"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v029 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v030"
      id="cutmv-premium-v030"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v030 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v031"
      id="cutmv-premium-v031"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v031 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v032"
      id="cutmv-premium-v032"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v032 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v033"
      id="cutmv-premium-v033"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v033 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v034"
      id="cutmv-premium-v034"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v034 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v035"
      id="cutmv-premium-v035"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v035 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v036"
      id="cutmv-premium-v036"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v036 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v037"
      id="cutmv-premium-v037"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v037 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v038"
      id="cutmv-premium-v038"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v038 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v039"
      id="cutmv-premium-v039"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v039 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v040"
      id="cutmv-premium-v040"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v040 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v041"
      id="cutmv-premium-v041"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v041 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v043"
      id="cutmv-premium-v043"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v043 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v044"
      id="cutmv-premium-v044"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v044 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v045"
      id="cutmv-premium-v045"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v045 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v046"
      id="cutmv-premium-v046"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v046 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v047"
      id="cutmv-premium-v047"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v047 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v048"
      id="cutmv-premium-v048"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v048 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v049"
      id="cutmv-premium-v049"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v049 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v050"
      id="cutmv-premium-v050"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v050 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v051"
      id="cutmv-premium-v051"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={450}
      defaultProps={{ rawSpec: raw_v051 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v052"
      id="cutmv-premium-v052"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={336}
      defaultProps={{ rawSpec: raw_v052 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v053"
      id="cutmv-premium-v053"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={336}
      defaultProps={{ rawSpec: raw_v053 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v054"
      id="cutmv-premium-v054"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={336}
      defaultProps={{ rawSpec: raw_v054 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v055"
      id="cutmv-premium-v055"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={336}
      defaultProps={{ rawSpec: raw_v055 as Record<string, unknown> }}
    />
    <Composition
      key="cutmv-premium-v056"
      id="cutmv-premium-v056"
      component={DeferredEngine}
      width={1080}
      height={1920}
      fps={30}
      durationInFrames={336}
      defaultProps={{ rawSpec: raw_v056 as Record<string, unknown> }}
    />
  </>
);
