import { i as OpenClawConfig } from "../../types.openclaw-C9E_zZnO.js";
import { t as FallbackAttempt } from "../../model-fallback.types-BtFkqyWI.js";
import { a as AuthProfileStore } from "../../types-DNLAqYp7.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-DbQGG85m.js";
import { t as ImageGenerationProviderPlugin } from "../../types-DaukV8xd.js";
import { n as createSubsystemLogger } from "../../subsystem-ET63bTu_.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-C1N6TNuu.js";
import { j as normalizeGooglePreviewModelId } from "../../provider-model-shared-BH6aCMPh.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-D5y_R4Zh.js";
import { i as parseGeminiAuth, n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-DAvwE5kM.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-C3F6I6J8.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CmLaS7lU.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-DCOwEVD7.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseGeminiAuth, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };