import { i as OpenClawConfig } from "../../types.openclaw-CQzDxdpQ.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DKmgB7PG.js";
import { s as AuthProfileStore } from "../../types-CE047wJv.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-DeDIC012.js";
import { Jn as VideoGenerationProviderPlugin } from "../../types-Bb8qdnX4.js";
import { n as createSubsystemLogger } from "../../subsystem-CkWk-dX6.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-CylXlRyd.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-HN-9qI3r.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CZkSNIrS.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-CRPwXMYp.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-DBv_oiAT.js";
import { t as parseVideoGenerationModelRef } from "../../video-generation-core-Cs2DRuuU.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };