import { i as OpenClawConfig } from "../../types.openclaw-BYfkTL_f.js";
import { ft as GoogleChatAccountConfig, mt as GoogleChatConfig } from "../../types.channels-6kkMAKLf.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-CCrWEB5U.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Ds9BBXA3.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-C_h6wIm7.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DMG-czl3.js";
import { t as ChannelMessageActionName } from "../../types.public-CwqPONY3.js";
import { n as PluginRuntime } from "../../types-PzLD5nJ3.js";
import { d as readRemoteMediaBuffer } from "../../fetch-DrUbl1N9.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-D66j7qXL.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DfNGR-8N.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DrNcI0sQ.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-BUVDVcUB.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-CTAOWeji.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-CXHV0tFO.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-BzeqhU1L.js";
import { n as resolveWebhookPath } from "../../webhook-path-C0u-awmU.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CmF-3zPi.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-CcB8QzAb.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-CtQNPnyN.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-Cg8-FWXn.js";
import { r as createChannelPairingController } from "../../channel-pairing-Dxfyty5G.js";
import { t as chunkTextForOutbound } from "../../text-chunking-C44sdYxM.js";
import { m as missingTargetError } from "../../channel-feedback-DYP6kVAt.js";
import { t as extractToolSend } from "../../tool-send-DDDKtZPy.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-C2oHEvLE.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-CvfshS9T.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };