import { i as formatErrorMessage } from "../errors-s6LAmrhz.js";
import { p as resolveUserPath } from "../utils-CpmNtyoq.js";
import { n as VERSION } from "../version-B2G3zXnp.js";
import { m as resolveSessionAgentIds } from "../agent-scope-TPiFaS6U.js";
import { a as isSubagentSessionKey } from "../session-key-utils-bmH32UOR.js";
import { a as resolveAgentDir, s as resolveDefaultAgentDir } from "../agent-scope-config-Bo5OijmI.js";
import { n as resolveEmbeddedAgentRuntime } from "../runtime-pgtcC-aT.js";
import { n as disposeRegisteredAgentHarnesses } from "../registry-DXbSRFId.js";
import { a as resolveContextEngineOwnerPluginId } from "../registry-CAETmZ4X.js";
import { d as resetAgentEventsForTest, i as emitAgentEvent, l as onAgentEvent } from "../agent-events-vzMG8R0I.js";
import { c as appendSessionTranscriptMessage } from "../transcript-T1_slPRp.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-CyQVdiNm.js";
import { c as resolveSessionWriteLockAcquireTimeoutMs, r as acquireSessionWriteLock } from "../session-write-lock-CusRtRWS.js";
import { u as resolveModelAuthMode } from "../model-auth-Bdn-DOwA.js";
import { m as setActiveEmbeddedRun, n as abortEmbeddedPiRun, p as resolveActiveEmbeddedRunSessionId, r as clearActiveEmbeddedRun } from "../runs-CzQ1z7Ri.js";
import { o as normalizeUsage } from "../usage-qL_fcg_p.js";
import { t as log } from "../logger-D9NrUrWq.js";
import { o as normalizeHeartbeatToolResponse, t as HEARTBEAT_RESPONSE_TOOL_NAME } from "../heartbeat-tool-response-DmUnGM3r.js";
import { t as createOpenClawCodingTools } from "../pi-tools-CwJ_WjRt.js";
import { d as wrapToolWithBeforeToolCallHook, l as isToolWrappedWithBeforeToolCallHook, o as hasBeforeToolCallPolicy, u as runBeforeToolCallHook } from "../pi-tools.before-tool-call-B9AYTMuP.js";
import { t as callGatewayTool } from "../gateway-D_S6enAt.js";
import { D as formatToolAggregate } from "../channel-streaming-DCwRXYZw.js";
import { a as selectDefaultNodeFromList, i as resolveNodeIdFromList, t as listNodes } from "../nodes-utils-BChf9yKh.js";
import { a as finalizeHarnessContextEngineTurn, i as buildHarnessContextEngineRuntimeContextFromUsage, n as bootstrapHarnessContextEngine, o as isActiveHarnessContextEngine, r as buildHarnessContextEngineRuntimeContext, s as runHarnessContextEngineMaintenance, t as assembleHarnessContextEngine } from "../context-engine-lifecycle-DbYgKaLh.js";
import { i as runAgentHarnessLlmOutputHook, n as runAgentHarnessBeforeAgentFinalizeHook, r as runAgentHarnessLlmInputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-BRAvdVMI.js";
import { a as resolveBootstrapContextForRun } from "../bootstrap-files-DZkhv5dO.js";
import { S as supportsModelTools, a as logAgentRuntimeToolDiagnostics, b as isMessagingTool, c as normalizeProviderToolSchemas, f as extractToolResultMediaArtifact, l as runAgentCleanupStep, m as filterToolResultMediaUrls, n as createAgentToolResultMiddlewareRunner, o as normalizeAgentRuntimeTools, t as buildEmbeddedAttemptToolRunContext, x as isMessagingToolSendAction } from "../attempt.tool-run-context-B2uPEvXQ.js";
import { _ as resolveOpenClawAgentDir } from "../provider-auth-BdVaafmp.js";
import { o as resolveSandboxContext } from "../sandbox-BoIX-oUx.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-Bq6YDEqR.js";
import { t as classifyEmbeddedPiRunResultForModelFallback } from "../result-fallback-classifier-D2gwktl6.js";
import { r as buildAgentRuntimePlan } from "../build-BdZ9fc0E.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-BkcGSvO8.js";
import { a as loadCodexBundleMcpThreadConfig, c as resolveAgentHarnessBeforePromptBuildResult, i as inferToolMetaFromArgs, l as runAgentHarnessAfterCompactionHook, n as classifyAgentHarnessTerminalOutcome, o as queueAgentHarnessMessage, r as formatToolProgressOutput, s as createCodexAppServerToolResultExtensionRunner, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS, u as runAgentHarnessBeforeCompactionHook } from "../agent-harness-runtime-gPupe-FM.js";
import { a as registerNativeHookRelay, c as runAgentHarnessBeforeMessageWriteHook, n as buildNativeHookRelayCommand, s as runAgentHarnessAfterToolCallHook, t as __testing } from "../native-hook-relay-Cy3i1cqz.js";
export { HEARTBEAT_RESPONSE_TOOL_NAME, VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, appendSessionTranscriptMessage, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildAgentRuntimePlan, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, classifyAgentHarnessTerminalOutcome, classifyEmbeddedPiRunResultForModelFallback, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, hasBeforeToolCallPolicy, inferToolMetaFromArgs, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, listNodes, loadCodexBundleMcpThreadConfig, logAgentRuntimeToolDiagnostics, __testing as nativeHookRelayTesting, normalizeAgentRuntimeTools, normalizeHeartbeatToolResponse, normalizeProviderToolSchemas, normalizeUsage, onAgentEvent, queueAgentHarnessMessage, registerNativeHookRelay, resetAgentEventsForTest, resolveActiveEmbeddedRunSessionId, resolveAgentDir, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveBootstrapContextForRun, resolveContextEngineOwnerPluginId, resolveDefaultAgentDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveNodeIdFromList, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveSessionWriteLockAcquireTimeoutMs, resolveUserPath, runAgentCleanupStep, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeAgentFinalizeHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runBeforeToolCallHook, runHarnessContextEngineMaintenance, selectDefaultNodeFromList, setActiveEmbeddedRun, supportsModelTools, wrapToolWithBeforeToolCallHook };
