import { i as OpenClawConfig } from "../../types.openclaw-DBDmmaVM.js";
import { S as MarkdownTableMode, _ as GroupPolicy } from "../../types.base-CzXKYjot.js";
import { o as GroupToolPolicyConfig } from "../../types.tools-9EnNA1hP.js";
import { $ as MSTeamsConfig, Q as MSTeamsChannelConfig, et as MSTeamsReplyStyle, nt as MSTeamsTeamConfig } from "../../types.channels-B8PNxvXK.js";
import { o as SsrFPolicy } from "../../ssrf-D_7xmVo8.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Iwx-m7pc.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-Clghd6aI.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-F3y1zEoe.js";
import { n as RuntimeEnv } from "../../runtime-B4p2dmOC.js";
import { n as ChannelOutboundAdapter } from "../../outbound.types-B5xApU2S.js";
import { m as ChannelGroupContext, t as BaseProbeResult, u as ChannelDirectoryEntry } from "../../types.core-DA-emjB6.js";
import { O as buildMediaPayload, r as ReplyPayload } from "../../reply-payload-CNTUnQyV.js";
import { n as ChannelPlugin, t as ChannelMessageActionName } from "../../types.public-Cx-Og-oG.js";
import { n as PluginRuntime } from "../../types-BkonLdRT.js";
import { l as extractOriginalFilename } from "../../store-Doz8HtAk.js";
import { a as resolveToolsBySender } from "../../group-policy-Drw2jNJF.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DDZdT6ub.js";
import { c as resolveAllowlistMatchSimple, t as AllowlistMatch } from "../../allowlist-match-C3AzpgcD.js";
import { s as normalizeStringEntries } from "../../string-normalization-e7NmZteE.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-HvFp7SHM.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-DRSvuIYX.js";
import { a as normalizeChannelSlug, i as buildChannelKeyCandidates, l as resolveNestedAllowlistDecision, s as resolveChannelEntryMatchWithFallback } from "../../channel-config-B6eJ6Isv.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-DeCAMmmi.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-CE8kF-5-.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-krgJT8On.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-CTxy4utA.js";
import { o as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-CBUPz3wD.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-Dwtl_6Y4.js";
import { a as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-Dheubz8r.js";
import { f as mergeAllowlist, m as summarizeMapping } from "../../allow-from-C0lJ05sX.js";
import { i as logTypingFailure } from "../../logging-BJYi2w-F.js";
import { u as withFileLock } from "../../file-lock-DdQUZeRU.js";
import { r as createChannelPairingController } from "../../channel-pairing-BWpp3F-L.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CwtMbR6o.js";
import { t as setMSTeamsRuntime } from "../../runtime-api-CAmCg0-m.js";
export { AllowlistMatch, BaseProbeResult, ChannelDirectoryEntry, ChannelGroupContext, ChannelMessageActionName, ChannelOutboundAdapter, ChannelPlugin, DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, GroupPolicy, GroupToolPolicyConfig, MSTeamsChannelConfig, MSTeamsConfig, MSTeamsReplyStyle, MSTeamsTeamConfig, MarkdownTableMode, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, ReplyPayload, RuntimeEnv, SsrFPolicy, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };