import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-05Z3mmpO.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-B8jvaNbU.js";
import { t as getChatChannelMeta } from "../../chat-meta-xat6MzuT.js";
import { r as buildChannelConfigSchema } from "../../config-schema-CLM6ogpT.js";
import { n as AcpRuntimeError } from "../../errors-Bl372wkS.js";
import { f as readNumberParam, g as readStringParam, h as readStringOrNumberParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../../common-DZqX8QYm.js";
import { r as makeProxyFetch } from "../../proxy-fetch-T-Azqd23.js";
import { r as resolvePollMaxSelections } from "../../polls-BrJ3RoTA.js";
import { t as clearAccountEntryFields } from "../../config-helpers-MniV1jJS.js";
import { n as formatPairingApproveHint } from "../../helpers-BUOSsuwP.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-jZExApHj.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-BdQs1TAL.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DW8jXNGU.js";
import "../../channel-core-BASvgwzh.js";
import { t as resolveTelegramToken } from "../../token-9qOqN7XI.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DDuxp0PB.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-CaAM_77P.js";
import "../../acp-runtime-DgsMFaDJ.js";
import "../../channel-plugin-common-B9kXSyUl.js";
import "../../channel-status-Bs_3DYkc.js";
import "../../channel-actions-Dvpzx5Sm.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-Y3JbzCpQ.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-B1cSsHo5.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-DILz8pjK.js";
import { n as setTelegramRuntime } from "../../runtime-CLMqSuO6.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-DRdChIYE.js";
import "../../config-api-D-TyyYc_.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-Dy_-GJIQ.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-By_5xPvR.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-B5n5-UyS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
