import { i as OpenClawConfig } from "../../types.openclaw-CQzDxdpQ.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DKmgB7PG.js";
import { s as AuthProfileStore } from "../../types-CE047wJv.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-Csr8Vf5n.js";
import { a as ImageGenerationProviderPlugin } from "../../types-Bb8qdnX4.js";
import { n as createSubsystemLogger } from "../../subsystem-CkWk-dX6.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-CylXlRyd.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-a4mPK9Lm.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-HN-9qI3r.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CZkSNIrS.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-CRPwXMYp.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-BmIhsD30.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-D97HdDDr.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };