import type { ComponentType } from "react";
import {
	SiGmail,
	SiSlack,
	SiDiscord,
	SiGithub,
	SiNotion,
	SiGooglecalendar,
	SiLinear,
	SiAirtable,
	SiHubspot,
	SiSalesforce,
	SiJira,
	SiAsana,
	SiGoogledrive,
	SiTrello,
	SiZendesk,
	SiShopify,
	SiStripe,
	SiTwilio,
	SiDropbox,
	SiZoom,
	SiGooglesheets,
	SiFigma,
	SiIntercom,
} from "react-icons/si";
import {
	Globe,
	Zap,
	Search,
	Workflow,
	Users,
	BarChart3,
	Clock,
	Phone,
	FileText,
	Database,
	BrainCircuit,
	Rocket,
	Target,
	TrendingUp,
} from "lucide-react";

export type PromptCategory =
	| "crm-sales"
	| "email-comms"
	| "dev-tools"
	| "productivity"
	| "search-research"
	| "automation";

export type PromptSuggestion = {
	id: string;
	label: string;
	subtitle: string;
	prompt: string;
	category: PromptCategory;
} & (
	| { iconType: "brand"; icon: ComponentType<{ className?: string; style?: React.CSSProperties }>; brandColor: string }
	| { iconType: "generic"; icon: ComponentType<{ className?: string }>; brandColor?: undefined }
);

export const PROMPT_SUGGESTIONS: PromptSuggestion[] = [
	// ── CRM & Sales ──
	{
		id: "hubspot-sync-contacts",
		label: "Sync HubSpot Contacts",
		subtitle: "Import & deduplicate CRM contacts",
		icon: SiHubspot,
		iconType: "brand",
		brandColor: "#FF7A59",
		category: "crm-sales",
		prompt: "Connect to my HubSpot CRM and pull all contacts updated this week. Deduplicate them by email and list any with missing phone numbers or job titles so I can clean up the data.",
	},
	{
		id: "salesforce-pipeline",
		label: "Salesforce Pipeline",
		subtitle: "Analyze deal stages & revenue",
		icon: SiSalesforce,
		iconType: "brand",
		brandColor: "#00A1E0",
		category: "crm-sales",
		prompt: "Connect to Salesforce and pull my current sales pipeline. Break down deals by stage, show total expected revenue per stage, and flag any deals that have been stuck in the same stage for more than 14 days.",
	},
	{
		id: "apollo-enrich-lead",
		label: "Enrich Lead via Apollo",
		subtitle: "Find LinkedIn, company data & funding",
		icon: Rocket,
		iconType: "generic",
		category: "crm-sales",
		prompt: "I just added a new lead — use Apollo enrichment to find their LinkedIn profile, current company, job title, company size, funding stage, and any recent news. Update the contact record with everything you find.",
	},
	{
		id: "hubspot-deal-update",
		label: "Update HubSpot Deals",
		subtitle: "Bulk update deal properties",
		icon: SiHubspot,
		iconType: "brand",
		brandColor: "#FF7A59",
		category: "crm-sales",
		prompt: "Find all HubSpot deals in 'Negotiation' stage that haven't been touched in 7+ days. Move them to 'Needs Follow-up' and add a note saying 'Auto-flagged: no activity for 7 days'.",
	},
	{
		id: "salesforce-lead-score",
		label: "Score Salesforce Leads",
		subtitle: "Rank leads by engagement signals",
		icon: SiSalesforce,
		iconType: "brand",
		brandColor: "#00A1E0",
		category: "crm-sales",
		prompt: "Pull all Salesforce leads from this month. Score them based on email opens, meeting attendance, and form submissions. Give me a ranked list of the top 20 hottest leads with their scores and recommended next actions.",
	},
	{
		id: "apollo-company-research",
		label: "Research Company",
		subtitle: "Apollo + web research on a prospect",
		icon: Target,
		iconType: "generic",
		category: "crm-sales",
		prompt: "Research this prospect's company using Apollo enrichment and Exa web search. I need: company size, revenue, tech stack, recent news, key decision-makers, and any mutual connections. Compile everything into a one-page briefing.",
	},
	{
		id: "intercom-tickets",
		label: "Intercom Ticket Summary",
		subtitle: "Summarize open support tickets",
		icon: SiIntercom,
		iconType: "brand",
		brandColor: "#6AFDEF",
		category: "crm-sales",
		prompt: "Pull all open Intercom conversations from this week. Categorize them by issue type (bug, feature request, billing, onboarding) and summarize the top 5 most urgent ones with recommended responses.",
	},
	{
		id: "zendesk-trends",
		label: "Zendesk Support Trends",
		subtitle: "Analyze ticket patterns",
		icon: SiZendesk,
		iconType: "brand",
		brandColor: "#03363D",
		category: "crm-sales",
		prompt: "Analyze my Zendesk tickets from the past 30 days. What are the most common issues? Show a breakdown by category, average resolution time, and flag any recurring problems that might need a product fix.",
	},
	{
		id: "crm-weekly-report",
		label: "CRM Weekly Report",
		subtitle: "Pipeline + activity summary",
		icon: TrendingUp,
		iconType: "generic",
		category: "crm-sales",
		prompt: "Generate a weekly CRM report: new leads added, deals moved forward, deals closed (won/lost), total pipeline value, and team activity metrics. Format it as a clean summary I can share with leadership.",
	},

	// ── Email & Comms ──
	{
		id: "gmail-follow-up",
		label: "Gmail Follow-ups",
		subtitle: "Draft replies to unanswered threads",
		icon: SiGmail,
		iconType: "brand",
		brandColor: "#EA4335",
		category: "email-comms",
		prompt: "Check my Gmail for threads where I was the last sender and haven't gotten a reply in 3+ days. Draft a friendly follow-up for each one, keeping the original context. Show me all drafts before sending.",
	},
	{
		id: "slack-standup",
		label: "Slack Standup Summary",
		subtitle: "Digest #standup channel updates",
		icon: SiSlack,
		iconType: "brand",
		brandColor: "#4A154B",
		category: "email-comms",
		prompt: "Read today's messages in #standup on Slack. Summarize what each team member is working on, any blockers they mentioned, and highlight anything that needs my attention or a response.",
	},
	{
		id: "discord-moderation",
		label: "Discord Community Digest",
		subtitle: "Summarize server activity",
		icon: SiDiscord,
		iconType: "brand",
		brandColor: "#5865F2",
		category: "email-comms",
		prompt: "Pull the last 24 hours of messages from my Discord server's #general and #support channels. Summarize the key discussions, flag any unanswered questions, and list new member introductions.",
	},
	{
		id: "gmail-newsletter-cleanup",
		label: "Clean Up Gmail",
		subtitle: "Unsubscribe from noisy newsletters",
		icon: SiGmail,
		iconType: "brand",
		brandColor: "#EA4335",
		category: "email-comms",
		prompt: "Scan my Gmail inbox for newsletter and promotional emails I haven't opened in the last 30 days. List them with their sender and frequency, then help me draft unsubscribe actions for the ones I don't need.",
	},
	{
		id: "slack-channel-summary",
		label: "Slack Channel Recap",
		subtitle: "Catch up on missed conversations",
		icon: SiSlack,
		iconType: "brand",
		brandColor: "#4A154B",
		category: "email-comms",
		prompt: "I've been away for 2 days. Summarize the important messages and decisions from my top Slack channels (#engineering, #sales, #general). Highlight anything that needs my input and any @mentions I missed.",
	},
	{
		id: "phone-call-summary",
		label: "Call Summary",
		subtitle: "Recap client phone calls",
		icon: Phone,
		iconType: "generic",
		category: "email-comms",
		prompt: "I just finished a client call. Help me write a structured summary: key discussion points, decisions made, action items for each party, and next meeting date. Format it so I can paste it directly into the CRM notes.",
	},
	{
		id: "twilio-sms-campaign",
		label: "SMS Campaign via Twilio",
		subtitle: "Draft & schedule text messages",
		icon: SiTwilio,
		iconType: "brand",
		brandColor: "#F22F46",
		category: "email-comms",
		prompt: "I need to send a promotional SMS to my customer list via Twilio. Draft a short, compelling message (under 160 chars) about our new feature launch, with a link to the landing page. Set it up to send tomorrow at 10am.",
	},

	// ── Dev Tools ──
	{
		id: "github-pr-review",
		label: "Review GitHub PRs",
		subtitle: "Summarize open pull requests",
		icon: SiGithub,
		iconType: "brand",
		brandColor: "#181717",
		category: "dev-tools",
		prompt: "List all open pull requests on my GitHub repo. For each one, summarize the changes, check if CI passed, note how long it's been open, and flag any that have merge conflicts or are missing reviews.",
	},
	{
		id: "linear-sprint-status",
		label: "Linear Sprint Status",
		subtitle: "Track current sprint progress",
		icon: SiLinear,
		iconType: "brand",
		brandColor: "#5E6AD2",
		category: "dev-tools",
		prompt: "Pull the current sprint from Linear. Show me: total issues, completed vs in-progress vs blocked, who's overloaded, and which issues are at risk of not being completed by sprint end. Suggest priorities.",
	},
	{
		id: "jira-backlog-groom",
		label: "Groom Jira Backlog",
		subtitle: "Prioritize & clean up stale tickets",
		icon: SiJira,
		iconType: "brand",
		brandColor: "#0052CC",
		category: "dev-tools",
		prompt: "Review my Jira backlog. Find tickets older than 90 days with no activity, duplicates, and vague tickets missing acceptance criteria. Suggest which to close, merge, or update with better descriptions.",
	},
	{
		id: "github-issue-triage",
		label: "Triage GitHub Issues",
		subtitle: "Categorize & label new issues",
		icon: SiGithub,
		iconType: "brand",
		brandColor: "#181717",
		category: "dev-tools",
		prompt: "Go through unlabeled GitHub issues in my repo from this week. Read each one, categorize it (bug, feature, question, docs), suggest appropriate labels and priority, and draft a short acknowledgment comment for each.",
	},
	{
		id: "linear-create-issues",
		label: "Create Linear Issues",
		subtitle: "Turn meeting notes into tasks",
		icon: SiLinear,
		iconType: "brand",
		brandColor: "#5E6AD2",
		category: "dev-tools",
		prompt: "I have meeting notes in my workspace with action items. Parse them and create Linear issues for each action item. Set appropriate priorities, assign to team members mentioned, and add them to the current sprint.",
	},
	{
		id: "github-release-notes",
		label: "GitHub Release Notes",
		subtitle: "Auto-generate changelog from PRs",
		icon: SiGithub,
		iconType: "brand",
		brandColor: "#181717",
		category: "dev-tools",
		prompt: "Generate release notes for my GitHub repo based on all merged PRs since the last release tag. Categorize changes into Features, Bug Fixes, and Improvements. Format as a clean Markdown changelog ready to publish.",
	},

	// ── Productivity ──
	{
		id: "notion-meeting-notes",
		label: "Notion Meeting Notes",
		subtitle: "Create structured meeting page",
		icon: SiNotion,
		iconType: "brand",
		brandColor: "#000000",
		category: "productivity",
		prompt: "Create a new page in my Notion workspace for today's team meeting. Include sections for Attendees, Agenda, Discussion Notes, Action Items, and Decisions. Pre-fill the agenda from my calendar event details.",
	},
	{
		id: "gcal-schedule-optimizer",
		label: "Optimize My Calendar",
		subtitle: "Find focus time & reduce conflicts",
		icon: SiGooglecalendar,
		iconType: "brand",
		brandColor: "#4285F4",
		category: "productivity",
		prompt: "Analyze my Google Calendar for this week. Identify back-to-back meetings without breaks, suggest which meetings could be shorter or async, and find 2-hour blocks I can protect as focus time for deep work.",
	},
	{
		id: "asana-project-plan",
		label: "Asana Project Plan",
		subtitle: "Break down a project into tasks",
		icon: SiAsana,
		iconType: "brand",
		brandColor: "#F06A6A",
		category: "productivity",
		prompt: "I'm starting a new product launch. Create an Asana project with milestones for: market research, design, development, testing, marketing prep, and launch day. Add subtasks under each milestone with estimated durations.",
	},
	{
		id: "airtable-tracker",
		label: "Airtable Content Tracker",
		subtitle: "Build a content pipeline base",
		icon: SiAirtable,
		iconType: "brand",
		brandColor: "#18BFFF",
		category: "productivity",
		prompt: "Create an Airtable base for tracking our content marketing pipeline. I need columns for: Title, Type (blog/video/social), Status (idea/draft/review/published), Author, Due Date, Target Audience, and Performance Metrics.",
	},
	{
		id: "notion-weekly-planning",
		label: "Notion Weekly Plan",
		subtitle: "Structure your week ahead",
		icon: SiNotion,
		iconType: "brand",
		brandColor: "#000000",
		category: "productivity",
		prompt: "Create a weekly planning page in Notion for next week. Pull my upcoming calendar events, pending tasks from my project boards, and any deadlines. Organize them by day with priority levels and estimated time needed.",
	},
	{
		id: "google-sheets-dashboard",
		label: "Sheets KPI Dashboard",
		subtitle: "Build a metrics tracking sheet",
		icon: SiGooglesheets,
		iconType: "brand",
		brandColor: "#34A853",
		category: "productivity",
		prompt: "Create a Google Sheets dashboard to track our key business metrics: MRR, churn rate, new signups, active users, NPS score, and support ticket volume. Include formulas for month-over-month changes and visual sparklines.",
	},
	{
		id: "trello-kanban",
		label: "Trello Board Setup",
		subtitle: "Design a workflow board",
		icon: SiTrello,
		iconType: "brand",
		brandColor: "#0052CC",
		category: "productivity",
		prompt: "Set up a Trello board for our hiring pipeline. Create lists for: Applications Received, Phone Screen, Technical Interview, Culture Fit, Offer Sent, and Hired. Add card templates with checklists for each stage.",
	},
	{
		id: "gcal-meeting-prep",
		label: "Calendar Meeting Prep",
		subtitle: "Brief me before each meeting",
		icon: SiGooglecalendar,
		iconType: "brand",
		brandColor: "#4285F4",
		category: "productivity",
		prompt: "Check my Google Calendar for tomorrow's meetings. For each one, pull the attendee list, find relevant context (recent emails, CRM notes, past meeting notes), and create a quick briefing with talking points I should prepare.",
	},
	{
		id: "figma-handoff",
		label: "Figma Design Handoff",
		subtitle: "Extract specs from designs",
		icon: SiFigma,
		iconType: "brand",
		brandColor: "#F24E1E",
		category: "productivity",
		prompt: "I have a new Figma design ready for development. Extract all the key specs: colors, typography, spacing, component hierarchy, and interaction notes. Format them as a developer handoff document with clear implementation guidance.",
	},
	{
		id: "zoom-meeting-summary",
		label: "Zoom Call Summary",
		subtitle: "Summarize recorded calls",
		icon: SiZoom,
		iconType: "brand",
		brandColor: "#0B5CFF",
		category: "productivity",
		prompt: "I have a Zoom recording transcript from my latest client call. Summarize the key discussion points, extract action items with assigned owners, and highlight any concerns or risks the client raised that we need to address.",
	},
	{
		id: "dropbox-organize",
		label: "Organize Dropbox",
		subtitle: "Clean up shared folders",
		icon: SiDropbox,
		iconType: "brand",
		brandColor: "#0061FF",
		category: "productivity",
		prompt: "Scan my Dropbox workspace for duplicate files, outdated documents, and files with no clear folder. Suggest a cleaner folder structure and help me reorganize by project and document type.",
	},
	{
		id: "gdrive-doc-summary",
		label: "Summarize Google Docs",
		subtitle: "Digest long documents",
		icon: SiGoogledrive,
		iconType: "brand",
		brandColor: "#4285F4",
		category: "productivity",
		prompt: "I have several long Google Docs from last quarter's planning sessions. Read through them and create a single executive summary covering: key decisions made, goals set, assigned responsibilities, and current status of each initiative.",
	},

	// ── Search & Research ──
	{
		id: "exa-competitor-research",
		label: "Research Competitors",
		subtitle: "Deep web search via Exa",
		icon: Search,
		iconType: "generic",
		category: "search-research",
		prompt: "Use Exa to research my top 5 competitors. For each, find: pricing page, recent blog posts, product updates in the last 3 months, customer reviews, and social media presence. Compile into a comparison matrix.",
	},
	{
		id: "exa-industry-trends",
		label: "Industry Trend Report",
		subtitle: "Search for latest trends & insights",
		icon: Globe,
		iconType: "generic",
		category: "search-research",
		prompt: "Use Exa web search to find the latest trends in my industry from the past month. Look for analyst reports, notable funding rounds, product launches, and thought leadership articles. Create a trends briefing I can share with the team.",
	},
	{
		id: "exa-prospect-intel",
		label: "Prospect Intelligence",
		subtitle: "Research a prospect before outreach",
		icon: Search,
		iconType: "generic",
		category: "search-research",
		prompt: "I'm about to reach out to a prospect. Use Exa to research their company: recent news, tech blog posts, job openings (to infer priorities), and any public talks by their team. Help me craft a personalized outreach message based on what you find.",
	},
	{
		id: "web-market-analysis",
		label: "Market Analysis",
		subtitle: "Research market size & opportunities",
		icon: BarChart3,
		iconType: "generic",
		category: "search-research",
		prompt: "Research the market opportunity for our product category. Find total addressable market size, growth rate, key players and their market share, emerging trends, and any analyst predictions for the next 2-3 years.",
	},
	{
		id: "exa-content-ideas",
		label: "Content Research",
		subtitle: "Find trending topics for content",
		icon: Globe,
		iconType: "generic",
		category: "search-research",
		prompt: "Search the web for the most popular and trending content in my industry from the last 2 weeks. Find top-performing blog posts, viral social threads, and trending discussions. Suggest 10 content ideas based on the gaps you see.",
	},

	// ── Automation & Workflows ──
	{
		id: "auto-lead-nurture",
		label: "Lead Nurture Workflow",
		subtitle: "Auto-follow-up new signups",
		icon: Zap,
		iconType: "generic",
		category: "automation",
		prompt: "Design an automated lead nurture workflow: when a new user signs up, send a welcome email via Gmail, wait 3 days, check if they've logged in — if not, send a helpful onboarding tip. If still inactive after 7 days, alert the sales team on Slack.",
	},
	{
		id: "auto-invoice-tracking",
		label: "Invoice Automation",
		subtitle: "Track & remind overdue payments",
		icon: SiStripe,
		iconType: "brand",
		brandColor: "#635BFF",
		category: "automation",
		prompt: "Set up a workflow that checks Stripe for invoices overdue by more than 5 days. For each one, draft a friendly reminder email, send it via Gmail, and post a summary in the #finance Slack channel. Run this check every morning at 9am.",
	},
	{
		id: "auto-onboarding",
		label: "Client Onboarding Flow",
		subtitle: "Automate new client setup",
		icon: Workflow,
		iconType: "generic",
		category: "automation",
		prompt: "Build an automated client onboarding workflow: create a Notion project page, set up a Slack channel, add a HubSpot deal, schedule a kickoff meeting via Google Calendar, and send a welcome email with next steps. Trigger it when a deal is marked 'Closed Won'.",
	},
	{
		id: "auto-daily-digest",
		label: "Daily Briefing Bot",
		subtitle: "Morning summary across all tools",
		icon: Clock,
		iconType: "generic",
		category: "automation",
		prompt: "Create a daily briefing cron job that runs at 8:30am: pull today's calendar events, unread email count, open support tickets, any blocked tasks from Linear, and yesterday's revenue from Stripe. Compile into a clean summary and post to #daily-digest on Slack.",
	},
	{
		id: "auto-github-slack",
		label: "GitHub → Slack Alerts",
		subtitle: "Notify team of PR & issue activity",
		icon: SiGithub,
		iconType: "brand",
		brandColor: "#181717",
		category: "automation",
		prompt: "Set up a workflow that watches my GitHub repo. When a new PR is opened, post a summary in #engineering on Slack with the author, description, and a review link. When CI fails, alert the PR author directly via DM.",
	},
	{
		id: "auto-deal-alert",
		label: "Deal Stage Alerts",
		subtitle: "Notify sales on CRM changes",
		icon: SiHubspot,
		iconType: "brand",
		brandColor: "#FF7A59",
		category: "automation",
		prompt: "Create an automation that watches HubSpot deal stage changes. When a deal moves to 'Demo Scheduled', send the AE a prep email with the prospect's enrichment data. When it moves to 'Closed Won', post a celebration message in #wins on Slack.",
	},
	{
		id: "auto-shopify-support",
		label: "Shopify Order Alerts",
		subtitle: "Auto-handle order issues",
		icon: SiShopify,
		iconType: "brand",
		brandColor: "#96BF48",
		category: "automation",
		prompt: "Set up a workflow for my Shopify store: when an order is flagged as high-risk, automatically hold it, create a Zendesk ticket for review, and notify the team on Slack. When an order is refunded, update the customer record in HubSpot.",
	},
	{
		id: "auto-content-pipeline",
		label: "Content Pipeline Bot",
		subtitle: "Auto-assign & remind writers",
		icon: SiNotion,
		iconType: "brand",
		brandColor: "#000000",
		category: "automation",
		prompt: "Build a workflow that checks my Notion content calendar every Monday. For any pieces due this week that are still in 'Idea' status, assign them to available writers, send them a Slack message with the brief, and set a reminder for Wednesday if the draft isn't started.",
	},
	{
		id: "auto-expense-report",
		label: "Auto Expense Report",
		subtitle: "Compile weekly expenses",
		icon: Database,
		iconType: "generic",
		category: "automation",
		prompt: "Create a weekly automation that pulls transaction data from Stripe, categorizes expenses (software, marketing, operations), calculates totals, and generates a formatted expense report in Google Sheets. Email the report to the finance team every Friday at 5pm.",
	},
	{
		id: "auto-meeting-followup",
		label: "Auto Meeting Follow-up",
		subtitle: "Send notes after every meeting",
		icon: SiGooglecalendar,
		iconType: "brand",
		brandColor: "#4285F4",
		category: "automation",
		prompt: "After each meeting on my Google Calendar, automatically compile the notes (from Notion or the calendar description), extract action items, and send a follow-up email to all attendees via Gmail with the summary and their assigned tasks.",
	},
];
