import { p as isBlockedHostnameOrIp } from "../../ssrf-DAZxh7gy.js";
import { o as SessionEntry } from "../../types-DW5Lfc9v.js";
import { v as OpenClawPluginApi } from "../../types-DzNNj7u7.js";
import { _ as sleep } from "../../utils-CgYhRCJm.js";
import { r as GatewayRequestHandlerOptions } from "../../types-DUA2OA0o.js";
import { t as definePluginEntry } from "../../plugin-entry-_BiBdoIZ.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BruMQXri.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-tWbeBJz2.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-Emqsxia9.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };