import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-DUpVOe8L.js";
import { r as buildChannelConfigSchema } from "../../config-schema-C2n-k4o1.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-BGDCDnty.js";
import { t as getChatChannelMeta } from "../../chat-meta-O3JfTDA4.js";
import { n as AcpRuntimeError } from "../../errors-CYoRsEKQ.js";
import { f as readNumberParam, g as readStringParam, h as readStringOrNumberParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../../common-CBt8chmE.js";
import { r as makeProxyFetch } from "../../proxy-fetch-CKDKKbdo.js";
import { r as resolvePollMaxSelections } from "../../polls-DhrLANY3.js";
import { t as clearAccountEntryFields } from "../../config-helpers-DyBVgEMG.js";
import { n as formatPairingApproveHint } from "../../helpers-DrODJMht.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-sjgMIMZQ.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-L0ta1VTW.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DdpC30u1.js";
import "../../channel-core-sEYzZvNP.js";
import { t as resolveTelegramToken } from "../../token-CAbvYXLW.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-B7fZ2qTh.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-BvzPNo7p.js";
import "../../acp-runtime-BH1tTrgX.js";
import "../../channel-plugin-common-uZG0N3PT.js";
import "../../channel-status-be0NZxcV.js";
import "../../channel-actions-Lt3Lc2lg.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-Caopnqrq.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-DvEYx6zp.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-BOOp8CQl.js";
import { n as setTelegramRuntime } from "../../runtime-SpzBwgIi.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-KWS4sPHJ.js";
import "../../config-api-CpQcqa8a.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-Cec0q6_t.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-BQDIbbIj.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-CSHzDfbR.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
