export const browserCoreExamples = [
  "dna browser status",
  "dna browser start",
  "dna browser stop",
  "dna browser tabs",
  "dna browser open https://example.com",
  "dna browser focus abcd1234",
  "dna browser close abcd1234",
  "dna browser screenshot",
  "dna browser screenshot --full-page",
  "dna browser screenshot --ref 12",
  "dna browser snapshot",
  "dna browser snapshot --format aria --limit 200",
  "dna browser snapshot --efficient",
  "dna browser snapshot --labels",
];

export const browserActionExamples = [
  "dna browser navigate https://example.com",
  "dna browser resize 1280 720",
  "dna browser click 12 --double",
  'dna browser type 23 "hello" --submit',
  "dna browser press Enter",
  "dna browser hover 44",
  "dna browser drag 10 11",
  "dna browser select 9 OptionA OptionB",
  "dna browser upload /tmp/file.pdf",
  'dna browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dna browser dialog --accept",
  'dna browser wait --text "Done"',
  "dna browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dna browser console --level error",
  "dna browser pdf",
];
