export const browserCoreExamples = [
  "evox browser status",
  "evox browser start",
  "evox browser stop",
  "evox browser tabs",
  "evox browser open https://example.com",
  "evox browser focus abcd1234",
  "evox browser close abcd1234",
  "evox browser screenshot",
  "evox browser screenshot --full-page",
  "evox browser screenshot --ref 12",
  "evox browser snapshot",
  "evox browser snapshot --format aria --limit 200",
  "evox browser snapshot --efficient",
  "evox browser snapshot --labels",
];

export const browserActionExamples = [
  "evox browser navigate https://example.com",
  "evox browser resize 1280 720",
  "evox browser click 12 --double",
  'evox browser type 23 "hello" --submit',
  "evox browser press Enter",
  "evox browser hover 44",
  "evox browser drag 10 11",
  "evox browser select 9 OptionA OptionB",
  "evox browser upload /tmp/evox/uploads/file.pdf",
  'evox browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "evox browser dialog --accept",
  'evox browser wait --text "Done"',
  "evox browser evaluate --fn '(el) => el.textContent' --ref 7",
  "evox browser console --level error",
  "evox browser pdf",
];
