export const browserCoreExamples = [
  "smart-agent-neo browser status",
  "smart-agent-neo browser start",
  "smart-agent-neo browser stop",
  "smart-agent-neo browser tabs",
  "smart-agent-neo browser open https://example.com",
  "smart-agent-neo browser focus abcd1234",
  "smart-agent-neo browser close abcd1234",
  "smart-agent-neo browser screenshot",
  "smart-agent-neo browser screenshot --full-page",
  "smart-agent-neo browser screenshot --ref 12",
  "smart-agent-neo browser snapshot",
  "smart-agent-neo browser snapshot --format aria --limit 200",
  "smart-agent-neo browser snapshot --efficient",
  "smart-agent-neo browser snapshot --labels",
];

export const browserActionExamples = [
  "smart-agent-neo browser navigate https://example.com",
  "smart-agent-neo browser resize 1280 720",
  "smart-agent-neo browser click 12 --double",
  'smart-agent-neo browser type 23 "hello" --submit',
  "smart-agent-neo browser press Enter",
  "smart-agent-neo browser hover 44",
  "smart-agent-neo browser drag 10 11",
  "smart-agent-neo browser select 9 OptionA OptionB",
  "smart-agent-neo browser upload /tmp/smart-agent-neo/uploads/file.pdf",
  'smart-agent-neo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "smart-agent-neo browser dialog --accept",
  'smart-agent-neo browser wait --text "Done"',
  "smart-agent-neo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "smart-agent-neo browser console --level error",
  "smart-agent-neo browser pdf",
];
