import { i as formatErrorMessage } from "../errors-D3K0qXmL.js";
import { p as resolveUserPath } from "../utils-BlCbsks0.js";
import { n as VERSION } from "../version-CQfgAE7_.js";
import { v as resolveSessionAgentIds } from "../agent-scope-Bl5pjInQ.js";
import { a as isSubagentSessionKey } from "../session-key-utils-Ce_xWkNq.js";
import { a as resolveAgentDir, s as resolveDefaultAgentDir } from "../agent-scope-config-Dm11aCiH.js";
import { n as resolveEmbeddedAgentRuntime } from "../runtime-fVbSwiLb.js";
import { n as disposeRegisteredAgentHarnesses } from "../registry-C5gpGLvV.js";
import { a as resolveContextEngineOwnerPluginId } from "../registry-B-mVXdYO.js";
import { d as resetAgentEventsForTest, i as emitAgentEvent, l as onAgentEvent } from "../agent-events-BuYtWSh4.js";
import { l as appendSessionTranscriptMessage } from "../transcript-ChT1fc4-.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-ClYG_P1o.js";
import { d as resolveSessionWriteLockOptions, i as acquireSessionWriteLock, l as resolveSessionWriteLockAcquireTimeoutMs } from "../session-write-lock-BfzCD55Q.js";
import { u as resolveModelAuthMode } from "../model-auth-Cxwuuej8.js";
import { m as setActiveEmbeddedRun, n as abortEmbeddedPiRun, p as resolveActiveEmbeddedRunSessionId, r as clearActiveEmbeddedRun } from "../runs-B_letAfx.js";
import { o as normalizeUsage } from "../usage-HiJpzhay.js";
import { o as normalizeHeartbeatToolResponse, t as HEARTBEAT_RESPONSE_TOOL_NAME } from "../heartbeat-tool-response-DyfNPUEq.js";
import { p as buildAgentHookContextChannelFields } from "../attempt.prompt-helpers-Cff-SOWb.js";
import { a as resolveBootstrapContextForRun } from "../bootstrap-files-BkmXzi3V.js";
import { a as hasBeforeToolCallPolicy, c as isToolWrappedWithBeforeToolCallHook, f as wrapToolWithBeforeToolCallHook, l as runBeforeToolCallHook, u as setBeforeToolCallDiagnosticsEnabled } from "../pi-tools.before-tool-call-28rCfk3u.js";
import { t as callGatewayTool } from "../gateway-CLvOhD7F.js";
import { t as createOpenClawCodingTools } from "../pi-tools-ChPdl_Ng.js";
import { C as isMessagingTool, T as supportsModelTools, a as logAgentRuntimeToolDiagnostics, c as normalizeProviderToolSchemas, g as filterToolResultMediaUrls, l as runAgentCleanupStep, m as extractToolResultMediaArtifact, n as createAgentToolResultMiddlewareRunner, o as normalizeAgentRuntimeTools, t as buildEmbeddedAttemptToolRunContext, w as isMessagingToolSendAction } from "../attempt.tool-run-context-CaLJRlhH.js";
import { N as formatToolAggregate } from "../channel-streaming-COJvnRXu.js";
import { t as log } from "../logger-EZ6OokuK.js";
import { a as selectDefaultNodeFromList, i as resolveNodeIdFromList, t as listNodes } from "../nodes-utils-DsNDoiiL.js";
import { c as hasSandboxBindReadonlyHostShadows, l as resolveWritableSandboxBindHostRoots, o as resolveSandboxContext, s as hasSandboxBindContainerPathAliases } from "../sandbox-Cc4FV_Dy.js";
import { r as resolveCompactionTimeoutMs, t as compactContextEngineWithSafetyTimeout } from "../compaction-safety-timeout-DZX3bbpS.js";
import { a as finalizeHarnessContextEngineTurn, i as buildHarnessContextEngineRuntimeContextFromUsage, n as bootstrapHarnessContextEngine, o as isActiveHarnessContextEngine, r as buildHarnessContextEngineRuntimeContext, s as runHarnessContextEngineMaintenance, t as assembleHarnessContextEngine } from "../context-engine-lifecycle-CQvKCDF3.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-Bf_OCDyj.js";
import { t as classifyEmbeddedPiRunResultForModelFallback } from "../result-fallback-classifier-DVVlFbrg.js";
import { r as buildAgentRuntimePlan } from "../build-BMR1Ep0R.js";
import { i as runAgentHarnessLlmOutputHook, n as runAgentHarnessBeforeAgentFinalizeHook, r as runAgentHarnessLlmInputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-w2DzZFhd.js";
import { t as resolveOpenClawAgentDir } from "../agent-dir-compat-9wvd193r.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-BqRczx-P.js";
import { a as loadCodexBundleMcpThreadConfig, c as resolveAgentHarnessBeforePromptBuildResult, i as inferToolMetaFromArgs, l as runAgentHarnessAfterCompactionHook, n as classifyAgentHarnessTerminalOutcome, o as queueAgentHarnessMessage, r as formatToolProgressOutput, s as createCodexAppServerToolResultExtensionRunner, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS, u as runAgentHarnessBeforeCompactionHook } from "../agent-harness-runtime-B7VrZtL6.js";
import { a as registerNativeHookRelay, c as runAgentHarnessAfterToolCallHook, l as runAgentHarnessBeforeMessageWriteHook, n as hasNativeHookRelayInvocation, r as invokeNativeHookRelay, s as testing, t as buildNativeHookRelayCommand } from "../native-hook-relay-bz_H4P9v.js";
export { HEARTBEAT_RESPONSE_TOOL_NAME, VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, appendSessionTranscriptMessage, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildAgentHookContextChannelFields, buildAgentRuntimePlan, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, classifyAgentHarnessTerminalOutcome, classifyEmbeddedPiRunResultForModelFallback, clearActiveEmbeddedRun, compactContextEngineWithSafetyTimeout, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, hasBeforeToolCallPolicy, hasNativeHookRelayInvocation, hasSandboxBindContainerPathAliases, hasSandboxBindReadonlyHostShadows, inferToolMetaFromArgs, invokeNativeHookRelay, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, listNodes, loadCodexBundleMcpThreadConfig, logAgentRuntimeToolDiagnostics, testing as nativeHookRelayTesting, normalizeAgentRuntimeTools, normalizeHeartbeatToolResponse, normalizeProviderToolSchemas, normalizeUsage, onAgentEvent, queueAgentHarnessMessage, registerNativeHookRelay, resetAgentEventsForTest, resolveActiveEmbeddedRunSessionId, resolveAgentDir, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveBootstrapContextForRun, resolveCompactionTimeoutMs, resolveContextEngineOwnerPluginId, resolveDefaultAgentDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveNodeIdFromList, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveSessionWriteLockAcquireTimeoutMs, resolveSessionWriteLockOptions, resolveUserPath, resolveWritableSandboxBindHostRoots, runAgentCleanupStep, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeAgentFinalizeHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runBeforeToolCallHook, runHarnessContextEngineMaintenance, selectDefaultNodeFromList, setActiveEmbeddedRun, setBeforeToolCallDiagnosticsEnabled, supportsModelTools, wrapToolWithBeforeToolCallHook };
