import { i as OpenClawConfig } from "../../types.openclaw-Bpxi7OSY.js";
import { ft as GoogleChatAccountConfig, mt as GoogleChatConfig } from "../../types.channels-BQaK8GCG.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-BHDf_7WT.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-CocONTDn.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-Dosgf_na.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-1gJzFdXJ.js";
import { t as ChannelMessageActionName } from "../../types.public-oY5Zsold.js";
import { n as PluginRuntime } from "../../types-Dsa-0Faj.js";
import { d as readRemoteMediaBuffer } from "../../fetch-DP2xkuVf.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-DXV9rMJC.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-CjNZ1gpq.js";
import { r as buildChannelConfigSchema } from "../../config-schema-Cu4qnl0J.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BrZJ1X5M.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-DTkELUiI.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-CtQ47EKo.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-DylImiro.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-B-RCeMAw.js";
import { n as resolveWebhookPath } from "../../webhook-path-D2qAZ3ta.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-BCnDfHsA.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-9wuNl8n4.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-RK6NNtBh.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-CTGLJY14.js";
import { r as createChannelPairingController } from "../../channel-pairing-fIlJcWsI.js";
import { t as chunkTextForOutbound } from "../../text-chunking-D_wnKW5L.js";
import { m as missingTargetError } from "../../channel-feedback-BVFlDcU2.js";
import { t as extractToolSend } from "../../tool-send-Dc3ZkPHQ.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-B_8mQ2X2.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-B57I0mNh.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };