import { i as formatErrorMessage } from "../errors-C5Jbj3g5.js";
import { p as resolveUserPath } from "../utils-CpmNtyoq.js";
import { n as VERSION } from "../version-B2G3zXnp.js";
import { a as isSubagentSessionKey } from "../session-key-utils-qD-NZHCY.js";
import { a as resolveAgentDir, s as resolveDefaultAgentDir } from "../agent-scope-config-D57hqxoj.js";
import { m as resolveSessionAgentIds } from "../agent-scope-cOcI3Bf3.js";
import { n as resolveEmbeddedAgentRuntime } from "../runtime-Bfe5_EU9.js";
import { n as disposeRegisteredAgentHarnesses } from "../registry-DnVtS_Qy.js";
import { d as resetAgentEventsForTest, i as emitAgentEvent, l as onAgentEvent } from "../agent-events-B1hkQDEm.js";
import { c as appendSessionTranscriptMessage } from "../transcript-B405c2Is.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-B5Cg8Hyf.js";
import { c as resolveSessionWriteLockAcquireTimeoutMs, r as acquireSessionWriteLock } from "../session-write-lock-DhdXJ_rw.js";
import { u as resolveModelAuthMode } from "../model-auth-ChezQtKQ.js";
import { h as setActiveEmbeddedRun, m as resolveActiveEmbeddedRunSessionId, n as abortEmbeddedPiRun, r as clearActiveEmbeddedRun } from "../runs-ChtHyhIB.js";
import { o as normalizeUsage } from "../usage-DCHsUjMx.js";
import { i as runAgentHarnessLlmOutputHook, n as runAgentHarnessBeforeAgentFinalizeHook, r as runAgentHarnessLlmInputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-a6fQ3c-w.js";
import { a as resolveBootstrapContextForRun } from "../bootstrap-files-Cu_ZhAO8.js";
import { c as isToolWrappedWithBeforeToolCallHook, u as wrapToolWithBeforeToolCallHook } from "../pi-tools.before-tool-call-D8vqoOUW.js";
import { a as normalizeProviderToolSchemas, s as supportsModelTools, t as createAgentToolResultMiddlewareRunner } from "../tool-result-middleware-Ppz6nr2q.js";
import { o as normalizeHeartbeatToolResponse, t as HEARTBEAT_RESPONSE_TOOL_NAME } from "../heartbeat-tool-response-DJE5nTKg.js";
import { S as isMessagingToolSendAction, a as buildHarnessContextEngineRuntimeContextFromUsage, c as runHarnessContextEngineMaintenance, d as runAgentCleanupStep, g as filterToolResultMediaUrls, i as buildHarnessContextEngineRuntimeContext, l as logAgentRuntimeToolDiagnostics, m as extractToolResultMediaArtifact, n as assembleHarnessContextEngine, o as finalizeHarnessContextEngineTurn, r as bootstrapHarnessContextEngine, s as isActiveHarnessContextEngine, t as buildEmbeddedAttemptToolRunContext, u as normalizeAgentRuntimeTools, x as isMessagingTool } from "../attempt.tool-run-context-C_mAMn5k.js";
import { T as formatToolAggregate } from "../channel-streaming-DJqJ584R.js";
import { t as log } from "../logger-Bkp60SNw.js";
import { t as callGatewayTool } from "../gateway-gqb9cO7s.js";
import { t as createOpenClawCodingTools } from "../pi-tools-GJH0N5Mc.js";
import { a as selectDefaultNodeFromList, i as resolveNodeIdFromList, t as listNodes } from "../nodes-utils-D1PIw9nA.js";
import { _ as resolveOpenClawAgentDir } from "../provider-auth-BmQN-1-7.js";
import { o as resolveSandboxContext } from "../sandbox-D9npHsLz.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-DujsUMEw.js";
import { t as classifyEmbeddedPiRunResultForModelFallback } from "../result-fallback-classifier-CX5WrnI-.js";
import { r as buildAgentRuntimePlan } from "../build-8Kfn5UAx.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-DVRcRZhn.js";
import { a as queueAgentHarnessMessage, c as runAgentHarnessAfterCompactionHook, i as inferToolMetaFromArgs, l as runAgentHarnessBeforeCompactionHook, n as classifyAgentHarnessTerminalOutcome, o as createCodexAppServerToolResultExtensionRunner, r as formatToolProgressOutput, s as resolveAgentHarnessBeforePromptBuildResult, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS } from "../agent-harness-runtime-D8Rm3EGi.js";
import { a as registerNativeHookRelay, c as runAgentHarnessBeforeMessageWriteHook, n as buildNativeHookRelayCommand, s as runAgentHarnessAfterToolCallHook, t as __testing } from "../native-hook-relay-a3LqQOW7.js";
export { HEARTBEAT_RESPONSE_TOOL_NAME, VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, appendSessionTranscriptMessage, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildAgentRuntimePlan, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, classifyAgentHarnessTerminalOutcome, classifyEmbeddedPiRunResultForModelFallback, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, inferToolMetaFromArgs, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, listNodes, logAgentRuntimeToolDiagnostics, __testing as nativeHookRelayTesting, normalizeAgentRuntimeTools, normalizeHeartbeatToolResponse, normalizeProviderToolSchemas, normalizeUsage, onAgentEvent, queueAgentHarnessMessage, registerNativeHookRelay, resetAgentEventsForTest, resolveActiveEmbeddedRunSessionId, resolveAgentDir, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveBootstrapContextForRun, resolveDefaultAgentDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveNodeIdFromList, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveSessionWriteLockAcquireTimeoutMs, resolveUserPath, runAgentCleanupStep, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeAgentFinalizeHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runHarnessContextEngineMaintenance, selectDefaultNodeFromList, setActiveEmbeddedRun, supportsModelTools, wrapToolWithBeforeToolCallHook };
