import { i as OpenClawConfig } from "../../types.openclaw-DZQrhn8E.js";
import { S as MarkdownTableMode, _ as GroupPolicy } from "../../types.base-0oN-mnFt.js";
import { o as GroupToolPolicyConfig } from "../../types.tools-DLW0nzGW.js";
import { $ as MSTeamsConfig, Q as MSTeamsChannelConfig, et as MSTeamsReplyStyle, nt as MSTeamsTeamConfig } from "../../types.channels-tnOjW6oA.js";
import { o as SsrFPolicy } from "../../ssrf-HuuPklwv.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Ds9BBXA3.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-D04dttxa.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-CNfePAuU.js";
import { n as RuntimeEnv } from "../../runtime-BGFXd35m.js";
import { n as ChannelOutboundAdapter } from "../../outbound.types-DKGVr4LC.js";
import { m as ChannelGroupContext, t as BaseProbeResult, u as ChannelDirectoryEntry } from "../../types.core-DiLRQ15F.js";
import { O as buildMediaPayload, r as ReplyPayload } from "../../reply-payload-BXM1DJCi.js";
import { n as ChannelPlugin, t as ChannelMessageActionName } from "../../types.public-BGobpRnR.js";
import { n as PluginRuntime } from "../../types-DIe2gsAQ.js";
import { l as extractOriginalFilename } from "../../store-a9HWwy4M.js";
import { a as resolveToolsBySender } from "../../group-policy-MUM3_zAq.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-STPhpcZ3.js";
import { c as resolveAllowlistMatchSimple, t as AllowlistMatch } from "../../allowlist-match-BZA8Pr5o.js";
import { s as normalizeStringEntries } from "../../string-normalization-x_uTWirA.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-CwDNdfN9.js";
import { a as normalizeChannelSlug, i as buildChannelKeyCandidates, l as resolveNestedAllowlistDecision, s as resolveChannelEntryMatchWithFallback } from "../../channel-config--pRU_O9q.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-w96f2wiG.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-BBa-yuRa.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DBDCj8AZ.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-sKHu-JZm.js";
import { o as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-CwWcRzhh.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-DjkcXuzT.js";
import { a as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-VOeh0kul.js";
import { f as mergeAllowlist, m as summarizeMapping } from "../../allow-from-SDNGw7qS.js";
import { i as logTypingFailure } from "../../logging-Chsd2s4a.js";
import { u as withFileLock } from "../../file-lock-gRVKl98y.js";
import { r as createChannelPairingController } from "../../channel-pairing-BIzOnDWB.js";
import { t as chunkTextForOutbound } from "../../text-chunking-BLJe1VMb.js";
import { t as setMSTeamsRuntime } from "../../runtime-api-CfWFJk6u.js";
export { AllowlistMatch, BaseProbeResult, ChannelDirectoryEntry, ChannelGroupContext, ChannelMessageActionName, ChannelOutboundAdapter, ChannelPlugin, DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, GroupPolicy, GroupToolPolicyConfig, MSTeamsChannelConfig, MSTeamsConfig, MSTeamsReplyStyle, MSTeamsTeamConfig, MarkdownTableMode, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, ReplyPayload, RuntimeEnv, SsrFPolicy, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };