// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               unknown
// source: openclaw/sandbox/v1/exec.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "openclaw.sandbox.v1";

export interface ExecRequest {
  start?: StartExec | undefined;
  stdinData?: Buffer | undefined;
  closeStdin?: boolean | undefined;
}

export interface StartExec {
  sandboxId: string;
  command: string[];
  workingDir: string;
  env: { [key: string]: string };
  timeoutMs: number;
}

export interface StartExec_EnvEntry {
  key: string;
  value: string;
}

export interface ExecResponse {
  stdoutData?: Buffer | undefined;
  stderrData?: Buffer | undefined;
  exit?: ExecExit | undefined;
}

export interface ExecExit {
  exitCode: number;
  error: string;
}

function createBaseExecRequest(): ExecRequest {
  return { start: undefined, stdinData: undefined, closeStdin: undefined };
}

export const ExecRequest: MessageFns<ExecRequest> = {
  encode(message: ExecRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start !== undefined) {
      StartExec.encode(message.start, writer.uint32(10).fork()).join();
    }
    if (message.stdinData !== undefined) {
      writer.uint32(18).bytes(message.stdinData);
    }
    if (message.closeStdin !== undefined) {
      writer.uint32(24).bool(message.closeStdin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.start = StartExec.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stdinData = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.closeStdin = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecRequest {
    return {
      start: isSet(object.start) ? StartExec.fromJSON(object.start) : undefined,
      stdinData: isSet(object.stdinData)
        ? Buffer.from(bytesFromBase64(object.stdinData))
        : isSet(object.stdin_data)
          ? Buffer.from(bytesFromBase64(object.stdin_data))
          : undefined,
      closeStdin: isSet(object.closeStdin)
        ? globalThis.Boolean(object.closeStdin)
        : isSet(object.close_stdin)
          ? globalThis.Boolean(object.close_stdin)
          : undefined,
    };
  },

  toJSON(message: ExecRequest): unknown {
    const obj: any = {};
    if (message.start !== undefined) {
      obj.start = StartExec.toJSON(message.start);
    }
    if (message.stdinData !== undefined) {
      obj.stdinData = base64FromBytes(message.stdinData);
    }
    if (message.closeStdin !== undefined) {
      obj.closeStdin = message.closeStdin;
    }
    return obj;
  },

  create(base?: DeepPartial<ExecRequest>): ExecRequest {
    return ExecRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExecRequest>): ExecRequest {
    const message = createBaseExecRequest();
    message.start =
      object.start !== undefined && object.start !== null
        ? StartExec.fromPartial(object.start)
        : undefined;
    message.stdinData = object.stdinData ?? undefined;
    message.closeStdin = object.closeStdin ?? undefined;
    return message;
  },
};

function createBaseStartExec(): StartExec {
  return { sandboxId: "", command: [], workingDir: "", env: {}, timeoutMs: 0 };
}

export const StartExec: MessageFns<StartExec> = {
  encode(message: StartExec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    for (const v of message.command) {
      writer.uint32(18).string(v!);
    }
    if (message.workingDir !== "") {
      writer.uint32(26).string(message.workingDir);
    }
    globalThis.Object.entries(message.env).forEach(([key, value]: [string, string]) => {
      StartExec_EnvEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.timeoutMs !== 0) {
      writer.uint32(40).uint32(message.timeoutMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartExec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartExec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.command.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.workingDir = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = StartExec_EnvEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.env[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timeoutMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartExec {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      command: globalThis.Array.isArray(object?.command)
        ? object.command.map((e: any) => globalThis.String(e))
        : [],
      workingDir: isSet(object.workingDir)
        ? globalThis.String(object.workingDir)
        : isSet(object.working_dir)
          ? globalThis.String(object.working_dir)
          : "",
      env: isObject(object.env)
        ? (globalThis.Object.entries(object.env) as [string, any][]).reduce(
            (acc: { [key: string]: string }, [key, value]: [string, any]) => {
              acc[key] = globalThis.String(value);
              return acc;
            },
            {},
          )
        : {},
      timeoutMs: isSet(object.timeoutMs)
        ? globalThis.Number(object.timeoutMs)
        : isSet(object.timeout_ms)
          ? globalThis.Number(object.timeout_ms)
          : 0,
    };
  },

  toJSON(message: StartExec): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.command?.length) {
      obj.command = message.command;
    }
    if (message.workingDir !== "") {
      obj.workingDir = message.workingDir;
    }
    if (message.env) {
      const entries = globalThis.Object.entries(message.env) as [string, string][];
      if (entries.length > 0) {
        obj.env = {};
        entries.forEach(([k, v]) => {
          obj.env[k] = v;
        });
      }
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    return obj;
  },

  create(base?: DeepPartial<StartExec>): StartExec {
    return StartExec.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartExec>): StartExec {
    const message = createBaseStartExec();
    message.sandboxId = object.sandboxId ?? "";
    message.command = object.command?.map((e) => e) || [];
    message.workingDir = object.workingDir ?? "";
    message.env = (globalThis.Object.entries(object.env ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.timeoutMs = object.timeoutMs ?? 0;
    return message;
  },
};

function createBaseStartExec_EnvEntry(): StartExec_EnvEntry {
  return { key: "", value: "" };
}

export const StartExec_EnvEntry: MessageFns<StartExec_EnvEntry> = {
  encode(message: StartExec_EnvEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartExec_EnvEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartExec_EnvEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartExec_EnvEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: StartExec_EnvEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<StartExec_EnvEntry>): StartExec_EnvEntry {
    return StartExec_EnvEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartExec_EnvEntry>): StartExec_EnvEntry {
    const message = createBaseStartExec_EnvEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseExecResponse(): ExecResponse {
  return { stdoutData: undefined, stderrData: undefined, exit: undefined };
}

export const ExecResponse: MessageFns<ExecResponse> = {
  encode(message: ExecResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stdoutData !== undefined) {
      writer.uint32(10).bytes(message.stdoutData);
    }
    if (message.stderrData !== undefined) {
      writer.uint32(18).bytes(message.stderrData);
    }
    if (message.exit !== undefined) {
      ExecExit.encode(message.exit, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stdoutData = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stderrData = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exit = ExecExit.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecResponse {
    return {
      stdoutData: isSet(object.stdoutData)
        ? Buffer.from(bytesFromBase64(object.stdoutData))
        : isSet(object.stdout_data)
          ? Buffer.from(bytesFromBase64(object.stdout_data))
          : undefined,
      stderrData: isSet(object.stderrData)
        ? Buffer.from(bytesFromBase64(object.stderrData))
        : isSet(object.stderr_data)
          ? Buffer.from(bytesFromBase64(object.stderr_data))
          : undefined,
      exit: isSet(object.exit) ? ExecExit.fromJSON(object.exit) : undefined,
    };
  },

  toJSON(message: ExecResponse): unknown {
    const obj: any = {};
    if (message.stdoutData !== undefined) {
      obj.stdoutData = base64FromBytes(message.stdoutData);
    }
    if (message.stderrData !== undefined) {
      obj.stderrData = base64FromBytes(message.stderrData);
    }
    if (message.exit !== undefined) {
      obj.exit = ExecExit.toJSON(message.exit);
    }
    return obj;
  },

  create(base?: DeepPartial<ExecResponse>): ExecResponse {
    return ExecResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExecResponse>): ExecResponse {
    const message = createBaseExecResponse();
    message.stdoutData = object.stdoutData ?? undefined;
    message.stderrData = object.stderrData ?? undefined;
    message.exit =
      object.exit !== undefined && object.exit !== null
        ? ExecExit.fromPartial(object.exit)
        : undefined;
    return message;
  },
};

function createBaseExecExit(): ExecExit {
  return { exitCode: 0, error: "" };
}

export const ExecExit: MessageFns<ExecExit> = {
  encode(message: ExecExit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.exitCode !== 0) {
      writer.uint32(8).int32(message.exitCode);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecExit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecExit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.exitCode = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecExit {
    return {
      exitCode: isSet(object.exitCode)
        ? globalThis.Number(object.exitCode)
        : isSet(object.exit_code)
          ? globalThis.Number(object.exit_code)
          : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: ExecExit): unknown {
    const obj: any = {};
    if (message.exitCode !== 0) {
      obj.exitCode = Math.round(message.exitCode);
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create(base?: DeepPartial<ExecExit>): ExecExit {
    return ExecExit.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExecExit>): ExecExit {
    const message = createBaseExecExit();
    message.exitCode = object.exitCode ?? 0;
    message.error = object.error ?? "";
    return message;
  },
};

/** ExecService provides command execution inside sandboxes with bidirectional streaming. */
export type ExecServiceDefinition = typeof ExecServiceDefinition;
export const ExecServiceDefinition = {
  name: "ExecService",
  fullName: "openclaw.sandbox.v1.ExecService",
  methods: {
    /**
     * Execute a command in a sandbox with bidirectional streaming.
     * Client sends: initial ExecRequest with command, then optional stdin chunks.
     * Server sends: stdout/stderr chunks, then final exit code.
     */
    exec: {
      name: "Exec",
      requestType: ExecRequest as typeof ExecRequest,
      requestStream: true,
      responseType: ExecResponse as typeof ExecResponse,
      responseStream: true,
      options: {},
    },
  },
} as const;

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
