// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               unknown
// source: openclaw/sandbox/v1/sandbox.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../../google/protobuf/timestamp.js";

export const protobufPackage = "openclaw.sandbox.v1";

/** SandboxState represents the lifecycle state of a sandbox. */
export enum SandboxState {
  SANDBOX_STATE_UNSPECIFIED = 0,
  SANDBOX_STATE_CREATING = 1,
  SANDBOX_STATE_RUNNING = 2,
  SANDBOX_STATE_STOPPED = 3,
  SANDBOX_STATE_ERROR = 4,
  UNRECOGNIZED = -1,
}

export function sandboxStateFromJSON(object: any): SandboxState {
  switch (object) {
    case 0:
    case "SANDBOX_STATE_UNSPECIFIED":
      return SandboxState.SANDBOX_STATE_UNSPECIFIED;
    case 1:
    case "SANDBOX_STATE_CREATING":
      return SandboxState.SANDBOX_STATE_CREATING;
    case 2:
    case "SANDBOX_STATE_RUNNING":
      return SandboxState.SANDBOX_STATE_RUNNING;
    case 3:
    case "SANDBOX_STATE_STOPPED":
      return SandboxState.SANDBOX_STATE_STOPPED;
    case 4:
    case "SANDBOX_STATE_ERROR":
      return SandboxState.SANDBOX_STATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SandboxState.UNRECOGNIZED;
  }
}

export function sandboxStateToJSON(object: SandboxState): string {
  switch (object) {
    case SandboxState.SANDBOX_STATE_UNSPECIFIED:
      return "SANDBOX_STATE_UNSPECIFIED";
    case SandboxState.SANDBOX_STATE_CREATING:
      return "SANDBOX_STATE_CREATING";
    case SandboxState.SANDBOX_STATE_RUNNING:
      return "SANDBOX_STATE_RUNNING";
    case SandboxState.SANDBOX_STATE_STOPPED:
      return "SANDBOX_STATE_STOPPED";
    case SandboxState.SANDBOX_STATE_ERROR:
      return "SANDBOX_STATE_ERROR";
    case SandboxState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CreateSandboxRequest {
  sandboxId: string;
  vcpuCount: number;
  memSizeMib: number;
  kernelImagePath: string;
  rootfsPath: string;
}

export interface CreateSandboxResponse {
  sandboxId: string;
  createdAt?: Date | undefined;
  state: SandboxState;
  /** boot_method indicates how the sandbox was created: "cold" or "snapshot". */
  bootMethod: string;
}

export interface DestroySandboxRequest {
  sandboxId: string;
  force: boolean;
}

export interface DestroySandboxResponse {}

export interface SandboxStatusRequest {
  sandboxId: string;
}

export interface SandboxStatusResponse {
  sandboxId: string;
  state: SandboxState;
  createdAt?: Date | undefined;
}

export interface ListSandboxesRequest {}

export interface ListSandboxesResponse {
  sandboxes: SandboxInfo[];
}

export interface SandboxInfo {
  sandboxId: string;
  state: SandboxState;
  createdAt?: Date | undefined;
}

function createBaseCreateSandboxRequest(): CreateSandboxRequest {
  return { sandboxId: "", vcpuCount: 0, memSizeMib: 0, kernelImagePath: "", rootfsPath: "" };
}

export const CreateSandboxRequest: MessageFns<CreateSandboxRequest> = {
  encode(message: CreateSandboxRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.vcpuCount !== 0) {
      writer.uint32(16).uint32(message.vcpuCount);
    }
    if (message.memSizeMib !== 0) {
      writer.uint32(24).uint32(message.memSizeMib);
    }
    if (message.kernelImagePath !== "") {
      writer.uint32(34).string(message.kernelImagePath);
    }
    if (message.rootfsPath !== "") {
      writer.uint32(42).string(message.rootfsPath);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSandboxRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSandboxRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.vcpuCount = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.memSizeMib = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.kernelImagePath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.rootfsPath = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSandboxRequest {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      vcpuCount: isSet(object.vcpuCount)
        ? globalThis.Number(object.vcpuCount)
        : isSet(object.vcpu_count)
          ? globalThis.Number(object.vcpu_count)
          : 0,
      memSizeMib: isSet(object.memSizeMib)
        ? globalThis.Number(object.memSizeMib)
        : isSet(object.mem_size_mib)
          ? globalThis.Number(object.mem_size_mib)
          : 0,
      kernelImagePath: isSet(object.kernelImagePath)
        ? globalThis.String(object.kernelImagePath)
        : isSet(object.kernel_image_path)
          ? globalThis.String(object.kernel_image_path)
          : "",
      rootfsPath: isSet(object.rootfsPath)
        ? globalThis.String(object.rootfsPath)
        : isSet(object.rootfs_path)
          ? globalThis.String(object.rootfs_path)
          : "",
    };
  },

  toJSON(message: CreateSandboxRequest): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.vcpuCount !== 0) {
      obj.vcpuCount = Math.round(message.vcpuCount);
    }
    if (message.memSizeMib !== 0) {
      obj.memSizeMib = Math.round(message.memSizeMib);
    }
    if (message.kernelImagePath !== "") {
      obj.kernelImagePath = message.kernelImagePath;
    }
    if (message.rootfsPath !== "") {
      obj.rootfsPath = message.rootfsPath;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSandboxRequest>): CreateSandboxRequest {
    return CreateSandboxRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSandboxRequest>): CreateSandboxRequest {
    const message = createBaseCreateSandboxRequest();
    message.sandboxId = object.sandboxId ?? "";
    message.vcpuCount = object.vcpuCount ?? 0;
    message.memSizeMib = object.memSizeMib ?? 0;
    message.kernelImagePath = object.kernelImagePath ?? "";
    message.rootfsPath = object.rootfsPath ?? "";
    return message;
  },
};

function createBaseCreateSandboxResponse(): CreateSandboxResponse {
  return { sandboxId: "", createdAt: undefined, state: 0, bootMethod: "" };
}

export const CreateSandboxResponse: MessageFns<CreateSandboxResponse> = {
  encode(message: CreateSandboxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(18).fork()).join();
    }
    if (message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.bootMethod !== "") {
      writer.uint32(34).string(message.bootMethod);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSandboxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSandboxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bootMethod = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSandboxResponse {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
      state: isSet(object.state) ? sandboxStateFromJSON(object.state) : 0,
      bootMethod: isSet(object.bootMethod)
        ? globalThis.String(object.bootMethod)
        : isSet(object.boot_method)
          ? globalThis.String(object.boot_method)
          : "",
    };
  },

  toJSON(message: CreateSandboxResponse): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.state !== 0) {
      obj.state = sandboxStateToJSON(message.state);
    }
    if (message.bootMethod !== "") {
      obj.bootMethod = message.bootMethod;
    }
    return obj;
  },

  create(base?: DeepPartial<CreateSandboxResponse>): CreateSandboxResponse {
    return CreateSandboxResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateSandboxResponse>): CreateSandboxResponse {
    const message = createBaseCreateSandboxResponse();
    message.sandboxId = object.sandboxId ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.state = object.state ?? 0;
    message.bootMethod = object.bootMethod ?? "";
    return message;
  },
};

function createBaseDestroySandboxRequest(): DestroySandboxRequest {
  return { sandboxId: "", force: false };
}

export const DestroySandboxRequest: MessageFns<DestroySandboxRequest> = {
  encode(message: DestroySandboxRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.force !== false) {
      writer.uint32(16).bool(message.force);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DestroySandboxRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDestroySandboxRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.force = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DestroySandboxRequest {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      force: isSet(object.force) ? globalThis.Boolean(object.force) : false,
    };
  },

  toJSON(message: DestroySandboxRequest): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.force !== false) {
      obj.force = message.force;
    }
    return obj;
  },

  create(base?: DeepPartial<DestroySandboxRequest>): DestroySandboxRequest {
    return DestroySandboxRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DestroySandboxRequest>): DestroySandboxRequest {
    const message = createBaseDestroySandboxRequest();
    message.sandboxId = object.sandboxId ?? "";
    message.force = object.force ?? false;
    return message;
  },
};

function createBaseDestroySandboxResponse(): DestroySandboxResponse {
  return {};
}

export const DestroySandboxResponse: MessageFns<DestroySandboxResponse> = {
  encode(_: DestroySandboxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DestroySandboxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDestroySandboxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DestroySandboxResponse {
    return {};
  },

  toJSON(_: DestroySandboxResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<DestroySandboxResponse>): DestroySandboxResponse {
    return DestroySandboxResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<DestroySandboxResponse>): DestroySandboxResponse {
    const message = createBaseDestroySandboxResponse();
    return message;
  },
};

function createBaseSandboxStatusRequest(): SandboxStatusRequest {
  return { sandboxId: "" };
}

export const SandboxStatusRequest: MessageFns<SandboxStatusRequest> = {
  encode(message: SandboxStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SandboxStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSandboxStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SandboxStatusRequest {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
    };
  },

  toJSON(message: SandboxStatusRequest): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    return obj;
  },

  create(base?: DeepPartial<SandboxStatusRequest>): SandboxStatusRequest {
    return SandboxStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SandboxStatusRequest>): SandboxStatusRequest {
    const message = createBaseSandboxStatusRequest();
    message.sandboxId = object.sandboxId ?? "";
    return message;
  },
};

function createBaseSandboxStatusResponse(): SandboxStatusResponse {
  return { sandboxId: "", state: 0, createdAt: undefined };
}

export const SandboxStatusResponse: MessageFns<SandboxStatusResponse> = {
  encode(message: SandboxStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.state !== 0) {
      writer.uint32(16).int32(message.state);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SandboxStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSandboxStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SandboxStatusResponse {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      state: isSet(object.state) ? sandboxStateFromJSON(object.state) : 0,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
    };
  },

  toJSON(message: SandboxStatusResponse): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.state !== 0) {
      obj.state = sandboxStateToJSON(message.state);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<SandboxStatusResponse>): SandboxStatusResponse {
    return SandboxStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SandboxStatusResponse>): SandboxStatusResponse {
    const message = createBaseSandboxStatusResponse();
    message.sandboxId = object.sandboxId ?? "";
    message.state = object.state ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseListSandboxesRequest(): ListSandboxesRequest {
  return {};
}

export const ListSandboxesRequest: MessageFns<ListSandboxesRequest> = {
  encode(_: ListSandboxesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSandboxesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSandboxesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListSandboxesRequest {
    return {};
  },

  toJSON(_: ListSandboxesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<ListSandboxesRequest>): ListSandboxesRequest {
    return ListSandboxesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListSandboxesRequest>): ListSandboxesRequest {
    const message = createBaseListSandboxesRequest();
    return message;
  },
};

function createBaseListSandboxesResponse(): ListSandboxesResponse {
  return { sandboxes: [] };
}

export const ListSandboxesResponse: MessageFns<ListSandboxesResponse> = {
  encode(message: ListSandboxesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sandboxes) {
      SandboxInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListSandboxesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSandboxesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxes.push(SandboxInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSandboxesResponse {
    return {
      sandboxes: globalThis.Array.isArray(object?.sandboxes)
        ? object.sandboxes.map((e: any) => SandboxInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListSandboxesResponse): unknown {
    const obj: any = {};
    if (message.sandboxes?.length) {
      obj.sandboxes = message.sandboxes.map((e) => SandboxInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListSandboxesResponse>): ListSandboxesResponse {
    return ListSandboxesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListSandboxesResponse>): ListSandboxesResponse {
    const message = createBaseListSandboxesResponse();
    message.sandboxes = object.sandboxes?.map((e) => SandboxInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSandboxInfo(): SandboxInfo {
  return { sandboxId: "", state: 0, createdAt: undefined };
}

export const SandboxInfo: MessageFns<SandboxInfo> = {
  encode(message: SandboxInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sandboxId !== "") {
      writer.uint32(10).string(message.sandboxId);
    }
    if (message.state !== 0) {
      writer.uint32(16).int32(message.state);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SandboxInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSandboxInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sandboxId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SandboxInfo {
    return {
      sandboxId: isSet(object.sandboxId)
        ? globalThis.String(object.sandboxId)
        : isSet(object.sandbox_id)
          ? globalThis.String(object.sandbox_id)
          : "",
      state: isSet(object.state) ? sandboxStateFromJSON(object.state) : 0,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
          ? fromJsonTimestamp(object.created_at)
          : undefined,
    };
  },

  toJSON(message: SandboxInfo): unknown {
    const obj: any = {};
    if (message.sandboxId !== "") {
      obj.sandboxId = message.sandboxId;
    }
    if (message.state !== 0) {
      obj.state = sandboxStateToJSON(message.state);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<SandboxInfo>): SandboxInfo {
    return SandboxInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SandboxInfo>): SandboxInfo {
    const message = createBaseSandboxInfo();
    message.sandboxId = object.sandboxId ?? "";
    message.state = object.state ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

/** SandboxService manages Firecracker MicroVM sandbox lifecycle. */
export type SandboxServiceDefinition = typeof SandboxServiceDefinition;
export const SandboxServiceDefinition = {
  name: "SandboxService",
  fullName: "openclaw.sandbox.v1.SandboxService",
  methods: {
    /** Create a new Firecracker MicroVM sandbox. */
    createSandbox: {
      name: "CreateSandbox",
      requestType: CreateSandboxRequest as typeof CreateSandboxRequest,
      requestStream: false,
      responseType: CreateSandboxResponse as typeof CreateSandboxResponse,
      responseStream: false,
      options: {},
    },
    /** Destroy a running sandbox. */
    destroySandbox: {
      name: "DestroySandbox",
      requestType: DestroySandboxRequest as typeof DestroySandboxRequest,
      requestStream: false,
      responseType: DestroySandboxResponse as typeof DestroySandboxResponse,
      responseStream: false,
      options: {},
    },
    /** Get the status of a sandbox. */
    sandboxStatus: {
      name: "SandboxStatus",
      requestType: SandboxStatusRequest as typeof SandboxStatusRequest,
      requestStream: false,
      responseType: SandboxStatusResponse as typeof SandboxStatusResponse,
      responseStream: false,
      options: {},
    },
    /** List all sandboxes managed by this runner. */
    listSandboxes: {
      name: "ListSandboxes",
      requestType: ListSandboxesRequest as typeof ListSandboxesRequest,
      requestStream: false,
      responseType: ListSandboxesResponse as typeof ListSandboxesResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
