mod agent_browser;
mod app_view;
mod attention;
mod attention_state;
mod browser_panel;
mod composer;
mod composer_actions;
mod composer_state;
mod connect_screen;
mod events;
pub(crate) mod gateway_manager;
mod header;
mod palette;
mod panel_dock;
mod session_actions;
mod sidebar;
mod sidebar_agent_picker;
mod sidebar_state;
pub mod theme;
mod transcript;
mod transcript_message;
mod transcript_state;
mod transcript_tools;
mod web_state;
mod webview_surface;

pub use app_view::AppView;

mod session_menu;
mod session_organization;
mod sidebar_activity;
mod sidebar_avatar;
mod sidebar_batch;
mod sidebar_catalog;
mod sidebar_filters;
mod sidebar_menu_surface;
mod sidebar_navigation;
mod sidebar_people;
mod sidebar_person_hover;
mod sidebar_preferences;
mod sidebar_rows;
mod sidebar_sections;
pub(crate) use session_menu::init_session_menu_shortcuts;
