# Security Scan Workflow Template
#
# This workflow runs security scans on your OpenClaw workspace:
# - Trivy: Vulnerability scanning for dependencies and filesystem
# - KICS: Infrastructure as Code security scanning
# - TruffleHog: Secret detection in git history
#
# Based on Catena-X TRG 8 security guidelines (eclipse-tractusx)
#
# Usage: Copy this file to your repo's .github/workflows/ directory

name: Security Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 3 * * 0" # Weekly Sunday 3 AM UTC
  workflow_dispatch: # Manual trigger

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "fs"
          scan-ref: "."
          severity: "CRITICAL,HIGH"
          format: "table"
          exit-code: "0" # Set to '1' to fail on findings
          ignore-unfixed: true

  kics-scan:
    name: KICS IaC Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run KICS scan
        uses: Checkmarx/kics-github-action@v2.1.0
        with:
          path: "."
          fail_on: "critical" # Only fail on critical issues
          output_path: "kics-results"
          output_formats: "json"
          exclude_paths: "node_modules,dist,.git,tmp"

  secret-scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for secret scanning

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.88.0
        with:
          extra_args: --only-verified
