import { i as OpenClawConfig } from "../../types.openclaw-CQzDxdpQ.js";
import { S as MarkdownTableMode, _ as GroupPolicy } from "../../types.base-BSU34aN9.js";
import { o as GroupToolPolicyConfig } from "../../types.tools-CxacbZLS.js";
import { et as MSTeamsChannelConfig, it as MSTeamsTeamConfig, nt as MSTeamsReplyStyle, tt as MSTeamsConfig } from "../../types.channels-BX77gn-L.js";
import { o as SsrFPolicy } from "../../ssrf-CMKWbO56.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-jXSHRHDW.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-6_aqXYT2.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-DDZDGzun.js";
import { n as RuntimeEnv } from "../../runtime-dOUD4nei.js";
import { n as ChannelOutboundAdapter } from "../../outbound.types-_qtghrWY.js";
import { m as ChannelGroupContext, t as BaseProbeResult, u as ChannelDirectoryEntry } from "../../types.core-DrB_kWzl.js";
import { O as buildMediaPayload, r as ReplyPayload } from "../../reply-payload-DUBNZ2s7.js";
import { n as ChannelPlugin, t as ChannelMessageActionName } from "../../types.public-B24V6qkJ.js";
import { n as PluginRuntime } from "../../types-CXGnubLv.js";
import { l as extractOriginalFilename } from "../../store-CYg06GaY.js";
import { a as resolveToolsBySender } from "../../group-policy-DqLt4zZ4.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BUCmnyv5.js";
import { c as resolveAllowlistMatchSimple, t as AllowlistMatch } from "../../allowlist-match-B--SnSk3.js";
import { s as normalizeStringEntries } from "../../string-normalization-DqhxpJGE.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BzbwrEoM.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-DyZvMlRr.js";
import { a as normalizeChannelSlug, i as buildChannelKeyCandidates, l as resolveNestedAllowlistDecision, s as resolveChannelEntryMatchWithFallback } from "../../channel-config-B91NJVig.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy--CM-L-TH.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-92fUqxk_.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-BsOt1j-z.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-V186JBZC.js";
import { o as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-Bn-AvIYR.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-C5l7NW9s.js";
import { a as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-BAbrRCVd.js";
import { f as mergeAllowlist, m as summarizeMapping } from "../../allow-from-C78HEMhn.js";
import { i as logTypingFailure } from "../../logging-CeiKZXZ4.js";
import { u as withFileLock } from "../../file-lock-BJDiRxLW.js";
import { r as createChannelPairingController } from "../../channel-pairing-BzWQ9q4C.js";
import { t as chunkTextForOutbound } from "../../text-chunking-Xn1GuzXu.js";
import { t as setMSTeamsRuntime } from "../../runtime-api-CeYox6pz.js";
export { AllowlistMatch, BaseProbeResult, ChannelDirectoryEntry, ChannelGroupContext, ChannelMessageActionName, ChannelOutboundAdapter, ChannelPlugin, DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, GroupPolicy, GroupToolPolicyConfig, MSTeamsChannelConfig, MSTeamsConfig, MSTeamsReplyStyle, MSTeamsTeamConfig, MarkdownTableMode, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, ReplyPayload, RuntimeEnv, SsrFPolicy, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };