import { n as SILENT_REPLY_TOKEN, t as HEARTBEAT_TOKEN } from "../../tokens-DX16zuOP.js";
import { n as HEARTBEAT_PROMPT, u as stripHeartbeatToken } from "../../heartbeat-Dz5PwkSM.js";
import { c as optimizeImageToPng } from "../../image-ops-CXDu1pv2.js";
import { r as getDefaultLocalRoots, t as LocalMediaAccessError } from "../../local-media-access-D0aFEXYO.js";
import { n as loadWebMediaRaw, r as optimizeImageToJpeg, t as loadWebMedia } from "../../web-media-BDpsgP8o.js";
import "../../reply-runtime-z4EOPSQ1.js";
import { n as resolveWebCredsBackupPath, r as resolveWebCredsPath, t as hasWebCredsSync } from "../../creds-files-J3040_qX.js";
import { n as whatsAppActionRuntime, t as handleWhatsAppAction } from "../../action-runtime-zwWgv-rZ.js";
import { n as getStatusCode, t as formatError } from "../../session-errors-BViYeCCY.js";
import { i as sendTypingWhatsApp, n as sendPollWhatsApp, r as sendReactionWhatsApp, t as sendMessageWhatsApp } from "../../send-NaMGSYNI.js";
import { n as waitForWebLogin, t as startWebLoginWithQr } from "../../login-qr-runtime-fMsKa8zx.js";
import { t as createWhatsAppLoginTool } from "../../agent-tools-login-CYHoy51X.js";
import { n as setWhatsAppRuntime } from "../../runtime-CZw-yZ-F.js";
import { C as waitForCredsSaveQueueWithTimeout, S as waitForCredsSaveQueue, _ as readWebSelfIdentityForDecision, a as getWebAuthAgeMs, b as webAuthExists, c as pickWebChannel, d as readWebAuthExistsForDecision, f as readWebAuthSnapshot, g as readWebSelfIdentity, h as readWebSelfId, i as formatWhatsAppWebAuthStatusState, l as readCredsJsonRaw, m as readWebAuthState, n as WHATSAPP_AUTH_UNSTABLE_CODE, o as logWebSelfId, p as readWebAuthSnapshotBestEffort, r as WhatsAppAuthUnstableError, s as logoutWeb, t as WA_WEB_AUTH_DIR, u as readWebAuthExistsBestEffort, v as resolveDefaultWebAuthDir, w as writeCredsJsonAtomically, y as restoreCredsFromBackupIfNeeded } from "../../auth-store-CAloeBUB.js";
import { t as DEFAULT_WEB_MEDIA_BYTES } from "../../constants-Bt7Oqrw5.js";
import { c as extractContactContext, d as extractMediaPlaceholder, p as extractText, u as extractLocationData } from "../../send-api-BJq3u3vM.js";
import { n as newConnectionId, r as waitForWaConnection, t as createWaSocket } from "../../session-uIpgoXef.js";
import { n as resolveWebAccountId, t as getActiveWebListener } from "../../active-listener-Cwangv2Z.js";
import { n as monitorWebInbox, r as resetWebInboundDedupe, t as monitorWebChannel } from "../../monitor-BkVg5B-H.js";
import { t as loginWeb } from "../../login-DXICp4FR.js";
export { DEFAULT_WEB_MEDIA_BYTES, HEARTBEAT_PROMPT, HEARTBEAT_TOKEN, LocalMediaAccessError, SILENT_REPLY_TOKEN, WA_WEB_AUTH_DIR, WHATSAPP_AUTH_UNSTABLE_CODE, WhatsAppAuthUnstableError, createWaSocket, createWhatsAppLoginTool, extractContactContext, extractLocationData, extractMediaPlaceholder, extractText, formatError, formatWhatsAppWebAuthStatusState, getActiveWebListener, getDefaultLocalRoots, getStatusCode, getWebAuthAgeMs, handleWhatsAppAction, hasWebCredsSync, loadWebMedia, loadWebMediaRaw, logWebSelfId, loginWeb, logoutWeb, monitorWebChannel, monitorWebInbox, newConnectionId, optimizeImageToJpeg, optimizeImageToPng, pickWebChannel, readCredsJsonRaw, readWebAuthExistsBestEffort, readWebAuthExistsForDecision, readWebAuthSnapshot, readWebAuthSnapshotBestEffort, readWebAuthState, readWebSelfId, readWebSelfIdentity, readWebSelfIdentityForDecision, resetWebInboundDedupe, resolveDefaultWebAuthDir, resolveWebAccountId, resolveWebCredsBackupPath, resolveWebCredsPath, restoreCredsFromBackupIfNeeded, sendMessageWhatsApp, sendPollWhatsApp, sendReactionWhatsApp, sendTypingWhatsApp, setWhatsAppRuntime, startWebLoginWithQr, stripHeartbeatToken, waitForCredsSaveQueue, waitForCredsSaveQueueWithTimeout, waitForWaConnection, waitForWebLogin, webAuthExists, whatsAppActionRuntime, writeCredsJsonAtomically };
