import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-fkYplFFW.js";
import { r as buildChannelConfigSchema } from "../../config-schema-Cv6_wz1q.js";
import { c as TelegramConfigSchema } from "../../zod-schema.providers-whatsapp-BGYiCmAE.js";
import { t as getChatChannelMeta } from "../../chat-meta--2Jcz1Mq.js";
import { n as AcpRuntimeError } from "../../errors-a8gYghkh.js";
import { f as readNumberParam, g as readStringParam, h as readStringOrNumberParam, l as jsonResult, m as readStringArrayParam, p as readReactionParams } from "../../common-O8axt5-B.js";
import { r as makeProxyFetch } from "../../proxy-fetch-D5HzGPrj.js";
import { r as resolvePollMaxSelections } from "../../polls-DKhM2pWW.js";
import { t as clearAccountEntryFields } from "../../config-helpers-lZfrUYAN.js";
import { n as formatPairingApproveHint } from "../../helpers-DSAkXmYY.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-Cypu7gLc.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-eqIFFnZN.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-q-T0QfDn.js";
import "../../channel-core-zFYC7MML.js";
import { t as resolveTelegramToken } from "../../token-COU3jTbA.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CQAMfMKv.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-Bt2mvr5s.js";
import "../../acp-runtime-C2f84EtG.js";
import "../../channel-plugin-common-Blb6MBuJ.js";
import "../../channel-status-C5TtpNEM.js";
import "../../channel-actions-CjoBRlW1.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-CHose6kk.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-CwGhasmn.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, o as telegramMessageActions, r as monitorTelegramProvider, t as probeTelegram } from "../../probe-BcDb4Z78.js";
import { n as setTelegramRuntime } from "../../runtime-XK8hN8NW.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-HaYGuHmr.js";
import "../../config-api-COuzVlnm.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-CMy3czES.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-NPqrKXNf.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-DA0dMg68.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
