const THREAD_BINDINGS_VERSION = 1;
const THREAD_BINDINGS_SWEEP_INTERVAL_MS = 12e4;
const DEFAULT_THREAD_BINDING_IDLE_TIMEOUT_MS = 24 * 60 * 60 * 1e3;
const DEFAULT_THREAD_BINDING_MAX_AGE_MS = 0;
const DEFAULT_FAREWELL_TEXT = "Thread unfocused. Messages here will no longer be routed.";
const DISCORD_UNKNOWN_CHANNEL_ERROR_CODE = 10003;
const RECENT_UNBOUND_WEBHOOK_ECHO_WINDOW_MS = 3e4;
export {
  DEFAULT_FAREWELL_TEXT,
  DEFAULT_THREAD_BINDING_IDLE_TIMEOUT_MS,
  DEFAULT_THREAD_BINDING_MAX_AGE_MS,
  DISCORD_UNKNOWN_CHANNEL_ERROR_CODE,
  RECENT_UNBOUND_WEBHOOK_ECHO_WINDOW_MS,
  THREAD_BINDINGS_SWEEP_INTERVAL_MS,
  THREAD_BINDINGS_VERSION
};
