import { i as OpenClawConfig } from "../../types.openclaw-D8bJSZjd.js";
import { t as FallbackAttempt } from "../../model-fallback.types-B1RX5U_i.js";
import { s as AuthProfileStore } from "../../types-B1ltAm8n2.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-utFvlMJ5.js";
import { Wn as VideoGenerationProviderPlugin } from "../../types-DdGVOQ6y.js";
import { n as createSubsystemLogger } from "../../subsystem-CQ9ScpqT.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-CS-1397R.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-68F0_82h.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-DfQCzvDp.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-CZqh45Y5.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-CpJlnnjL.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-CL_hcmSo.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };