import { t as normalizeXaiModelId } from "../../model-id-9qA0DFk-.js";
import { a as resolveXaiModelCompatPatch, i as applyXaiModelCompat, n as XAI_TOOL_SCHEMA_PROFILE, t as HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING } from "../../model-compat-BJL5wcUi.js";
import { a as XAI_DEFAULT_MODEL_ID, c as buildXaiCatalogModels, d as resolveXaiCatalogEntry, i as XAI_DEFAULT_MAX_TOKENS, l as buildXaiModelDefinition, n as XAI_DEFAULT_CONTEXT_WINDOW, o as XAI_DEFAULT_MODEL_REF, r as XAI_DEFAULT_IMAGE_MODEL, s as XAI_IMAGE_MODELS, t as XAI_BASE_URL } from "../../model-definitions-C57rQNZ6.js";
import { t as buildXaiProvider } from "../../provider-catalog-3rtgjFuC.js";
import { n as applyXaiConfig, r as applyXaiProviderConfig } from "../../onboard-D16FR2Mm.js";
import { t as buildXaiImageGenerationProvider } from "../../image-generation-provider-Awd10YDf.js";
import { t as applyXaiRuntimeModelCompat } from "../../runtime-model-compat-BZXEQnqT.js";
import { n as resolveXaiForwardCompatModel, t as isModernXaiModel } from "../../provider-models-DarQx8r0.js";
import { i as shouldContributeXaiCompat, n as resolveXaiBaseUrl, r as resolveXaiTransport, t as isXaiModelHint } from "../../api-CiuLMtrf.js";
export { HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING, XAI_BASE_URL, XAI_DEFAULT_CONTEXT_WINDOW, XAI_DEFAULT_IMAGE_MODEL, XAI_DEFAULT_MAX_TOKENS, XAI_DEFAULT_MODEL_ID, XAI_DEFAULT_MODEL_REF, XAI_IMAGE_MODELS, XAI_TOOL_SCHEMA_PROFILE, applyXaiConfig, applyXaiModelCompat, applyXaiProviderConfig, applyXaiRuntimeModelCompat, buildXaiCatalogModels, buildXaiImageGenerationProvider, buildXaiModelDefinition, buildXaiProvider, isModernXaiModel, isXaiModelHint, normalizeXaiModelId, resolveXaiBaseUrl, resolveXaiCatalogEntry, resolveXaiForwardCompatModel, resolveXaiModelCompatPatch, resolveXaiTransport, shouldContributeXaiCompat };
