import { i as OpenClawConfig } from "../../types.openclaw-BdZr8Ncl.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DVjvbBEH.js";
import { s as AuthProfileStore } from "../../types-DCVMn130.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-oYIf6Wfq.js";
import { t as ImageGenerationProviderPlugin } from "../../types-D40p5jC7.js";
import { n as createSubsystemLogger } from "../../subsystem-B962FG0G.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-Db8mRlwZ.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-COJv1gK3.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-C6R3uvj5.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-LvNMnL6v.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-BRtHYmcM.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-BDnd8qFm.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-DMQTIs47.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };