export const DEFAULT_INLINE_IMAGE_THUMBNAIL_MAX_WIDTH = 480;
export const DEFAULT_INLINE_IMAGE_THUMBNAIL_MAX_HEIGHT = 480;
export const DEFAULT_INLINE_IMAGE_THUMBNAIL_MAX_DIMENSION =
  DEFAULT_INLINE_IMAGE_THUMBNAIL_MAX_WIDTH;
