import { i as OpenClawConfig } from "../../types.openclaw-D8bJSZjd.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-CbXYzgGk.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-CrJv12Zi.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-BP6vIgTy.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DWkvQuBM.js";
import { t as ChannelMessageActionName } from "../../types.public-i4hJTC6b.js";
import { n as PluginRuntime } from "../../types-_VshWtBa.js";
import { d as readRemoteMediaBuffer } from "../../fetch-CvmcaExb.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-Y-5fsO7u.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DC_WzaQp.js";
import { r as buildChannelConfigSchema } from "../../config-schema-D2DpU2CE.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-CwCJqokG.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-geeohgS7.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-DhzMnh67.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-HCcU4MwG.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-BhmuUc8x.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-BYn8UHkD.js";
import { n as resolveWebhookPath } from "../../webhook-path-DwvrAT7o.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-X7ok4ayY.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-Y7Pt-2db.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-DOP55uhX.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BYID9gFg.js";
import { r as createChannelPairingController } from "../../channel-pairing-BvrLN7YX.js";
import { t as chunkTextForOutbound } from "../../text-chunking-fw_p0nFX.js";
import { m as missingTargetError } from "../../channel-feedback-CGfsBJQp.js";
import { t as extractToolSend } from "../../tool-send-CJ4da6yS.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-DkgWRhHE.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-iZvcjjv6.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };