import { i as OpenClawConfig } from "../../types.openclaw-BYfkTL_f.js";
import { t as FallbackAttempt } from "../../model-fallback.types-lteinV-m.js";
import { s as AuthProfileStore } from "../../types-qAWrW0I9.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-CbAlS6TN.js";
import { a as ImageGenerationProviderPlugin } from "../../types-CkHYPqDj.js";
import { n as createSubsystemLogger } from "../../subsystem-d1VSDcdo.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BtMyhUBu.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-Bv3zJ0kc.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-Bl8gVQve.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-CVIbkayt.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CW51CPst.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-Cv-4gge0.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-CEWfM4ms.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };