import { p as isBlockedHostnameOrIp } from "../../ssrf-BDx1bk44.js";
import { o as SessionEntry } from "../../types-5yIklHT9.js";
import { y as OpenClawPluginApi } from "../../types-Dggwf5Fv.js";
import { _ as sleep } from "../../utils-BAEx3b18.js";
import { r as GatewayRequestHandlerOptions } from "../../types-DomnfiGA.js";
import { t as definePluginEntry } from "../../plugin-entry-D8cx8Upy.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-TqGT2xIt.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-B_LzibG7.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-CSvMHs40.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };