import { i as OpenClawConfig } from "../../types.openclaw-GamulG8g.js";
import { t as FallbackAttempt } from "../../model-fallback.types-B2o5-mGE.js";
import { s as AuthProfileStore } from "../../types-CbacZYKs.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-vT3JzOUB.js";
import { Jn as VideoGenerationProviderPlugin } from "../../types-DolEO2Jl.js";
import { n as createSubsystemLogger } from "../../subsystem-Ce5qcC5n.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-AktT41ea.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-DQhtVXzc.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-BEmenFnv.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-BRu3v3P_.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-mtPT-mlX.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-9VUBN_rE.js";
export { type AuthProfileStore, type FallbackAttempt, type GeneratedVideoAsset, type OpenClawConfig, type VideoGenerationIgnoredOverride, type VideoGenerationMode, type VideoGenerationModeCapabilities, type VideoGenerationProvider, type VideoGenerationProviderCapabilities, type VideoGenerationProviderConfiguredContext, type VideoGenerationProviderPlugin, type VideoGenerationRequest, type VideoGenerationResolution, type VideoGenerationResult, type VideoGenerationSourceAsset, type VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };