export const MAX_PENDING_SESSION_SUGGESTIONS_PER_AUTHOR = 20;
export const MAX_PENDING_SESSION_SUGGESTIONS_PER_SESSION = 100;
export const MAX_RETAINED_RESOLVED_SESSION_SUGGESTIONS = 200;
export const SESSION_SUGGESTION_DISPATCH_CLAIM_TTL_MS = 30_000;
