import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { t as getChatChannelMeta } from "../../chat-meta-BosAS4Sd.js";
import { r as buildChannelConfigSchema } from "../../config-schema-Bte5Yg6T.js";
import { n as AcpRuntimeError } from "../../errors-UGV84Ac_.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-DHPeQHu2.js";
import { r as resolvePollMaxSelections } from "../../polls-BL1HNQQE.js";
import { t as clearAccountEntryFields } from "../../config-helpers-DEY-Ez7N.js";
import { n as formatPairingApproveHint } from "../../helpers-D8kE2zJ5.js";
import { r as makeProxyFetch } from "../../proxy-fetch-7eDan3Ih.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-CfhDXO7x.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-DwUF-qE5.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-Dh5ESMrc.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DDEfka3K.js";
import "../../channel-core-DXmAkt9U.js";
import { t as resolveTelegramToken } from "../../token-DrIzUjfN.js";
import "../../acp-runtime-CTjl6Doi.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DAZut6Hh.js";
import "../../channel-plugin-common-CwB6gTgz.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-MWz4ebYh.js";
import "../../channel-status-D8Np2Hnc.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-CwSmAESn.js";
import "../../channel-actions-qudH-xs4.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-BuSGAcEA2.js";
import { n as setTelegramRuntime } from "../../runtime-BXKUMNyD.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-eXY917QS.js";
import "../../config-api-BIrHZAYY.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-ZoAWLZqd.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-CV7r3b5k.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-DN19_ry_.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-DbRpHEhe.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
