import type { ModelDefinitionConfig } from "openclaw/plugin-sdk/provider-model-shared";

export const NEBIUS_BASE_URL = "https://api.tokenfactory.nebius.com/v1";

export const NEBIUS_MODEL_CATALOG: ModelDefinitionConfig[] = [
  // ── MiniMax ──────────────────────────────────────────────────────────────
  {
    id: "minimax/MiniMax-M2.5",
    name: "MiniMax M2.5",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "minimax/MiniMax-M2.1",
    name: "MiniMax M2.1",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.3, output: 1.2, cacheRead: 0, cacheWrite: 0 },
  },

  // ── NVIDIA ───────────────────────────────────────────────────────────────
  {
    id: "nvidia/Nemotron-3-Super-120b-a12b",
    name: "Nemotron Super 120B",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: { input: 0.3, output: 0.9, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
    name: "Nemotron Ultra 253B",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.6, output: 1.8, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "nvidia/Nemotron-Nano-V2-12b",
    name: "Nemotron Nano V2 12B",
    reasoning: false,
    input: ["text"],
    contextWindow: 32768,
    maxTokens: 8192,
    cost: { input: 0.07, output: 0.2, cacheRead: 0, cacheWrite: 0 },
  },

  // ── Qwen ─────────────────────────────────────────────────────────────────
  {
    id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    name: "Qwen3 Coder 480B",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: { input: 0.4, output: 1.8, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3.5-397B-A17B",
    name: "Qwen 3.5 397B MoE",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.6, output: 3.6, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
    name: "Qwen3 235B Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 65536,
    cost: { input: 0.2, output: 0.8, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
    name: "Qwen3 235B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 16384,
    cost: { input: 0.2, output: 0.6, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-32B",
    name: "Qwen3 32B",
    reasoning: false,
    input: ["text"],
    contextWindow: 40960,
    maxTokens: 40960,
    cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Thinking-2507",
    name: "Qwen3 30B Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 40960,
    maxTokens: 40960,
    cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen3 30B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 40960,
    maxTokens: 16384,
    cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    name: "Qwen3 Coder 30B",
    reasoning: false,
    input: ["text"],
    contextWindow: 40960,
    maxTokens: 16384,
    cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "Qwen/Qwen2.5-Coder-7B",
    name: "Qwen2.5 Coder 7B",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 8192,
    cost: { input: 0.03, output: 0.09, cacheRead: 0, cacheWrite: 0 },
  },

  // ── Moonshot AI ──────────────────────────────────────────────────────────
  {
    id: "moonshot-ai/Kimi-K2.5",
    name: "Kimi K2.5",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 262144,
    cost: { input: 0.5, output: 2.5, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "moonshot-ai/Kimi-K2-Instruct",
    name: "Kimi K2 Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.5, output: 2.4, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "moonshot-ai/Kimi-K2-Thinking",
    name: "Kimi K2 Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.6, output: 2.5, cacheRead: 0, cacheWrite: 0 },
  },

  // ── Z.ai (GLM) ───────────────────────────────────────────────────────────
  {
    id: "zai-org/GLM-5",
    name: "GLM-5",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 1.0, output: 3.2, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM-4.7",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.4, output: 2.0, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "zai-org/GLM-4.5",
    name: "GLM-4.5",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.6, output: 2.2, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "zai-org/GLM-4.5-Air",
    name: "GLM-4.5 Air",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.2, output: 1.2, cacheRead: 0, cacheWrite: 0 },
  },

  // ── DeepSeek ─────────────────────────────────────────────────────────────
  {
    id: "deepseek-ai/DeepSeek-V3.2",
    name: "DeepSeek V3.2",
    reasoning: false,
    input: ["text"],
    contextWindow: 163840,
    maxTokens: 163840,
    cost: { input: 0.3, output: 0.45, cacheRead: 0, cacheWrite: 0 },
    compat: { supportsUsageInStreaming: true },
  },
  {
    id: "deepseek-ai/DeepSeek-R1-0528",
    name: "DeepSeek R1",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16000,
    cost: { input: 0.8, output: 2.4, cacheRead: 0, cacheWrite: 0 },
    compat: { supportsUsageInStreaming: true },
  },
  {
    id: "deepseek-ai/DeepSeek-V3-0324",
    name: "DeepSeek V3",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.5, output: 1.5, cacheRead: 0, cacheWrite: 0 },
    compat: { supportsUsageInStreaming: true },
  },

  // ── NousResearch ─────────────────────────────────────────────────────────
  {
    id: "NousResearch/Hermes-4-405B",
    name: "Hermes 4 405B",
    reasoning: true,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 1.0, output: 3.0, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "NousResearch/Hermes-4-70B",
    name: "Hermes 4 70B",
    reasoning: false,
    input: ["text"],
    contextWindow: 128000,
    maxTokens: 16384,
    cost: { input: 0.13, output: 0.4, cacheRead: 0, cacheWrite: 0 },
  },

  // ── OpenAI open-weight ───────────────────────────────────────────────────
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 },
    compat: { supportsUsageInStreaming: true },
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT-OSS 20B",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.05, output: 0.2, cacheRead: 0, cacheWrite: 0 },
    compat: { supportsUsageInStreaming: true },
  },

  // ── Google ───────────────────────────────────────────────────────────────
  {
    id: "google/Gemma-3-27b-it",
    name: "Gemma 3 27B",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "google/Gemma-2-9b-it",
    name: "Gemma 2 9B",
    reasoning: false,
    input: ["text"],
    contextWindow: 8192,
    maxTokens: 8192,
    cost: { input: 0.03, output: 0.09, cacheRead: 0, cacheWrite: 0 },
  },

  // ── Meta ─────────────────────────────────────────────────────────────────
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.13, output: 0.4, cacheRead: 0, cacheWrite: 0 },
  },
  {
    id: "meta-llama/Meta-Llama-3.1-8B-Instruct",
    name: "Llama 3.1 8B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 16384,
    cost: { input: 0.02, output: 0.06, cacheRead: 0, cacheWrite: 0 },
  },
];

export function buildNebiusModelDefinition(
  model: (typeof NEBIUS_MODEL_CATALOG)[number],
): ModelDefinitionConfig {
  return {
    ...model,
    api: "openai-completions",
  };
}
