import { i as resolveOpenProviderRuntimeGroupPolicy } from "../../runtime-group-policy-BUzFlosd.js";
import { a as mergeDiscordAccountConfig, f as resolveDiscordMaxLinesPerMessage, i as listEnabledDiscordAccounts, l as resolveDiscordAccountConfig, o as resolveDefaultDiscordAccountId, r as listDiscordAccountIds, s as resolveDiscordAccount, t as createDiscordActionGate } from "../../accounts-CXV3yr2x.js";
import { t as inspectDiscordAccount } from "../../account-inspect-7TiN26Xq.js";
import { n as resolveDiscordChannelId, t as parseDiscordTarget } from "../../target-parsing-Dmrbc9no.js";
import { n as fetchDiscord, r as requestDiscord, t as DiscordApiError } from "../../api-riMamPKO.js";
import { i as normalizeDiscordOutboundTarget, n as looksLikeDiscordTargetId, r as normalizeDiscordMessagingTarget } from "../../normalize-BLL1XJSk.js";
import { n as resolveDiscordTarget, r as parseDiscordSendTarget } from "../../target-resolver-DJ7nqKxS.js";
import { a as buildDiscordComponentMessageFlags, c as resolveDiscordComponentAttachmentName, d as buildDiscordComponentCustomId, f as buildDiscordModalCustomId, g as parseDiscordModalCustomIdForInteraction, h as parseDiscordModalCustomId, i as buildDiscordComponentMessage, l as DISCORD_COMPONENT_CUSTOM_ID_KEY, m as parseDiscordComponentCustomIdForInteraction, n as DiscordFormModal, o as DISCORD_COMPONENT_ATTACHMENT_PREFIX, p as parseDiscordComponentCustomId, r as createDiscordFormModal, s as readDiscordComponentSpec, t as formatDiscordComponentEventText, u as DISCORD_MODAL_CUSTOM_ID_KEY } from "../../components-BHd4MexF.js";
import { t as buildDiscordInteractiveComponents } from "../../shared-interactive-D80qQRwI.js";
import "../../targets-BiYx0Vg5.js";
import { a as shouldSuppressLocalDiscordExecApprovalPrompt, i as isDiscordExecApprovalClientEnabled, n as getDiscordExecApprovalApprovers, r as isDiscordExecApprovalApprover } from "../../approval-shared-BvnjrFqj.js";
import { i as resolveDiscordGroupToolPolicy, n as collectDiscordStatusIssues, r as resolveDiscordGroupRequireMention, t as discordPlugin } from "../../channel-BCrQXAKV.js";
import { t as normalizeExplicitDiscordSessionKey } from "../../session-key-normalization-CWJaEwfs.js";
import { t as discordSetupPlugin } from "../../channel.setup-DNJOoMmu.js";
import { n as handleDiscordSubagentEnded, r as handleDiscordSubagentSpawning, t as handleDiscordSubagentDeliveryTarget } from "../../subagent-hooks-BVTJS9RT.js";
import { t as tryHandleDiscordMessageActionGuildAdmin } from "../../handle-action.guild-admin-Crqws4yd.js";
import { n as listDiscordDirectoryPeersFromConfig, t as listDiscordDirectoryGroupsFromConfig } from "../../directory-config-DUrovSbU.js";
import { t as fetchPluralKitMessageInfo } from "../../pluralkit-Bp45ogcK.js";
import { a as resolveDiscordPrivilegedIntentsFromFlags, i as probeDiscord, n as fetchDiscordApplicationSummary, r as parseApplicationIdFromToken, t as fetchDiscordApplicationId } from "../../probe-CHkBarpd.js";
import { t as collectDiscordSecurityAuditFindings } from "../../security-audit-XE2EaWm7.js";
import { a as mergeAbortSignals, i as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, n as DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, r as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, t as DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS } from "../../timeouts-BrvfHBCQ.js";
//#region extensions/discord/api.ts
const handleDiscordMessageAction = async (...args) => (await import("../../channel-actions.runtime-DiW0iOTU.js")).handleDiscordMessageAction(...args);
//#endregion
export { DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS, DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, DISCORD_COMPONENT_ATTACHMENT_PREFIX, DISCORD_COMPONENT_CUSTOM_ID_KEY, DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, DISCORD_MODAL_CUSTOM_ID_KEY, DiscordApiError, DiscordFormModal, buildDiscordComponentCustomId, buildDiscordComponentMessage, buildDiscordComponentMessageFlags, buildDiscordInteractiveComponents, buildDiscordModalCustomId, collectDiscordSecurityAuditFindings, collectDiscordStatusIssues, createDiscordActionGate, createDiscordFormModal, discordPlugin, discordSetupPlugin, fetchDiscord, fetchDiscordApplicationId, fetchDiscordApplicationSummary, fetchPluralKitMessageInfo, formatDiscordComponentEventText, getDiscordExecApprovalApprovers, handleDiscordMessageAction, handleDiscordSubagentDeliveryTarget, handleDiscordSubagentEnded, handleDiscordSubagentSpawning, inspectDiscordAccount, isDiscordExecApprovalApprover, isDiscordExecApprovalClientEnabled, listDiscordAccountIds, listDiscordDirectoryGroupsFromConfig, listDiscordDirectoryPeersFromConfig, listEnabledDiscordAccounts, looksLikeDiscordTargetId, mergeAbortSignals, mergeDiscordAccountConfig, normalizeDiscordMessagingTarget, normalizeDiscordOutboundTarget, normalizeExplicitDiscordSessionKey, parseApplicationIdFromToken, parseDiscordComponentCustomId, parseDiscordComponentCustomIdForInteraction as parseDiscordComponentCustomIdForCarbon, parseDiscordComponentCustomIdForInteraction, parseDiscordModalCustomId, parseDiscordModalCustomIdForInteraction as parseDiscordModalCustomIdForCarbon, parseDiscordModalCustomIdForInteraction, parseDiscordSendTarget, parseDiscordTarget, probeDiscord, readDiscordComponentSpec, requestDiscord, resolveDefaultDiscordAccountId, resolveDiscordAccount, resolveDiscordAccountConfig, resolveDiscordChannelId, resolveDiscordComponentAttachmentName, resolveDiscordGroupRequireMention, resolveDiscordGroupToolPolicy, resolveDiscordMaxLinesPerMessage, resolveDiscordPrivilegedIntentsFromFlags, resolveOpenProviderRuntimeGroupPolicy as resolveDiscordRuntimeGroupPolicy, resolveDiscordTarget, shouldSuppressLocalDiscordExecApprovalPrompt, tryHandleDiscordMessageActionGuildAdmin };
