import { t as normalizeXaiModelId } from "../../model-id-B9q9y026.js";
import { a as resolveXaiModelCompatPatch, i as applyXaiModelCompat, n as XAI_TOOL_SCHEMA_PROFILE, t as HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING } from "../../model-compat-CceXS1a8.js";
import { a as XAI_DEFAULT_MODEL_ID, c as buildXaiCatalogModels, d as resolveXaiCatalogEntry, i as XAI_DEFAULT_MAX_TOKENS, l as buildXaiModelDefinition, n as XAI_DEFAULT_CONTEXT_WINDOW, o as XAI_DEFAULT_MODEL_REF, r as XAI_DEFAULT_IMAGE_MODEL, s as XAI_IMAGE_MODELS, t as XAI_BASE_URL } from "../../model-definitions-BgdLqxX8.js";
import { t as buildXaiProvider } from "../../provider-catalog-B5xSo-iF.js";
import { n as applyXaiConfig, r as applyXaiProviderConfig } from "../../onboard-C--Ckib6.js";
import { t as buildXaiImageGenerationProvider } from "../../image-generation-provider-DVffv5xU.js";
import { t as applyXaiRuntimeModelCompat } from "../../runtime-model-compat-C3PrwlNC.js";
import { n as resolveXaiForwardCompatModel, t as isModernXaiModel } from "../../provider-models-DBHCxHBK.js";
import { i as shouldContributeXaiCompat, n as resolveXaiBaseUrl, r as resolveXaiTransport, t as isXaiModelHint } from "../../api-DT70TcSU.js";
export { HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING, XAI_BASE_URL, XAI_DEFAULT_CONTEXT_WINDOW, XAI_DEFAULT_IMAGE_MODEL, XAI_DEFAULT_MAX_TOKENS, XAI_DEFAULT_MODEL_ID, XAI_DEFAULT_MODEL_REF, XAI_IMAGE_MODELS, XAI_TOOL_SCHEMA_PROFILE, applyXaiConfig, applyXaiModelCompat, applyXaiProviderConfig, applyXaiRuntimeModelCompat, buildXaiCatalogModels, buildXaiImageGenerationProvider, buildXaiModelDefinition, buildXaiProvider, isModernXaiModel, isXaiModelHint, normalizeXaiModelId, resolveXaiBaseUrl, resolveXaiCatalogEntry, resolveXaiForwardCompatModel, resolveXaiModelCompatPatch, resolveXaiTransport, shouldContributeXaiCompat };
