// Defines user-facing labels for secret handling and security policy configuration.
export const SECURITY_FIELD_LABELS: Record<string, string> = {
  secrets: "Secrets",
  "secrets.egressProxy": "Secret Egress Proxy",
  "secrets.egressProxy.enabled": "Secret Egress Proxy Enabled",
  "secrets.egressProxy.allowedHosts": "Secret Egress Proxy Allowed Hosts",
  "secrets.egressProxy.bypassHosts": "Secret Egress Proxy Bypass Hosts",
  "security.audit": "Security Audit",
  "security.audit.suppressions": "Audit Suppressions",
  "security.audit.suppressions.*.checkId": "Audit Check ID",
  "security.audit.suppressions.*.titleIncludes": "Finding Title Contains",
  "security.audit.suppressions.*.detailIncludes": "Finding Detail Contains",
  "security.audit.suppressions.*.reason": "Suppression Reason",
  "security.installPolicy": "Install Policy",
  "security.installPolicy.enabled": "Enable Install Policy",
  "security.installPolicy.targets": "Install Policy Targets",
  "security.installPolicy.exec": "Install Policy Command",
  "security.installPolicy.exec.source": "Policy Command Source",
  "security.installPolicy.exec.command": "Policy Executable",
  "security.installPolicy.exec.args": "Policy Command Arguments",
  "security.installPolicy.exec.timeoutMs": "Policy Timeout (ms)",
  "security.installPolicy.exec.noOutputTimeoutMs": "Policy Idle Timeout (ms)",
  "security.installPolicy.exec.maxOutputBytes": "Policy Output Limit (bytes)",
  "security.installPolicy.exec.env": "Policy Environment Variables",
  "security.installPolicy.exec.passEnv": "Inherited Policy Environment Variables",
  "security.installPolicy.exec.trustedDirs": "Policy Trusted Directories",
};
