import { i as formatErrorMessage } from "../errors-QN8rySzW.js";
import { p as resolveUserPath } from "../utils-D5swhEXt.js";
import { n as VERSION } from "../version-DdTF4eka.js";
import { a as isSubagentSessionKey } from "../session-key-utils-8PXPWO4Z.js";
import { m as resolveSessionAgentIds } from "../agent-scope-CcybJBoN.js";
import { S as disposeRegisteredAgentHarnesses } from "../loader-BC-6x6qB.js";
import { d as resetAgentEventsForTest, i as emitAgentEvent, l as onAgentEvent } from "../agent-events-NWmMKpmM.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-C2gz-tl8.js";
import { c as resolveSessionWriteLockAcquireTimeoutMs, r as acquireSessionWriteLock } from "../session-write-lock-vddWzh3p.js";
import { o as appendSessionTranscriptMessage } from "../transcript-Dlrr7XVN.js";
import { t as resolveOpenClawAgentDir } from "../agent-paths-CYt_vl-H.js";
import { u as resolveModelAuthMode } from "../model-auth-4K4rXeIE.js";
import { f as setActiveEmbeddedRun, l as queueEmbeddedPiMessage, n as abortEmbeddedPiRun, r as clearActiveEmbeddedRun } from "../runs-C1DNunYV.js";
import { n as resolveEmbeddedAgentRuntime } from "../runtime-Yp2cJZeu.js";
import { o as normalizeUsage } from "../usage-DgYEKR-Z.js";
import { a as resolveBootstrapContextForRun } from "../bootstrap-files-DkuHtjZt.js";
import { c as wrapToolWithBeforeToolCallHook, o as isToolWrappedWithBeforeToolCallHook } from "../pi-tools.before-tool-call-B3h4zwpd.js";
import { a as normalizeProviderToolSchemas, s as supportsModelTools, t as createAgentToolResultMiddlewareRunner } from "../tool-result-middleware-CbzEiiiD.js";
import { t as log } from "../logger-WjiJP55B.js";
import { o as normalizeHeartbeatToolResponse, t as HEARTBEAT_RESPONSE_TOOL_NAME } from "../heartbeat-tool-response-Doen4xTo.js";
import { S as isMessagingToolSendAction, a as buildHarnessContextEngineRuntimeContextFromUsage, c as runHarnessContextEngineMaintenance, d as runAgentCleanupStep, g as filterToolResultMediaUrls, i as buildHarnessContextEngineRuntimeContext, l as logAgentRuntimeToolDiagnostics, m as extractToolResultMediaArtifact, n as assembleHarnessContextEngine, o as finalizeHarnessContextEngineTurn, r as bootstrapHarnessContextEngine, s as isActiveHarnessContextEngine, t as buildEmbeddedAttemptToolRunContext, u as normalizeAgentRuntimeTools, x as isMessagingTool } from "../attempt.tool-run-context-DWoeab5E.js";
import { t as formatToolAggregate } from "../tool-meta-CKTvmliy.js";
import { t as callGatewayTool } from "../gateway-CBGKPeLg.js";
import { t as createOpenClawCodingTools } from "../pi-tools-Ch84T_iU.js";
import { a as selectDefaultNodeFromList, i as resolveNodeIdFromList, t as listNodes } from "../nodes-utils-DMYZjw6p.js";
import { o as resolveSandboxContext } from "../sandbox-G5EnSfYs.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-Cgwj5qsv.js";
import { r as buildAgentRuntimePlan } from "../build-BTsZ4HxF.js";
import { t as classifyEmbeddedPiRunResultForModelFallback } from "../result-fallback-classifier-DfOGzpJ5.js";
import { i as runAgentHarnessLlmOutputHook, n as runAgentHarnessBeforeAgentFinalizeHook, r as runAgentHarnessLlmInputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-D0-3DKWU.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-BEaN6i1p.js";
import { a as createCodexAppServerToolResultExtensionRunner, c as runAgentHarnessBeforeCompactionHook, i as inferToolMetaFromArgs, n as classifyAgentHarnessTerminalOutcome, o as resolveAgentHarnessBeforePromptBuildResult, r as formatToolProgressOutput, s as runAgentHarnessAfterCompactionHook, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS } from "../agent-harness-runtime-PIBBM_v4.js";
import { a as registerNativeHookRelay, c as runAgentHarnessBeforeMessageWriteHook, n as buildNativeHookRelayCommand, s as runAgentHarnessAfterToolCallHook, t as __testing } from "../native-hook-relay-6YJn9VwN.js";
import "../agent-harness-knLqs5uc.js";
export { HEARTBEAT_RESPONSE_TOOL_NAME, VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, appendSessionTranscriptMessage, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildAgentRuntimePlan, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, classifyAgentHarnessTerminalOutcome, classifyEmbeddedPiRunResultForModelFallback, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, inferToolMetaFromArgs, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, listNodes, logAgentRuntimeToolDiagnostics, __testing as nativeHookRelayTesting, normalizeAgentRuntimeTools, normalizeHeartbeatToolResponse, normalizeProviderToolSchemas, normalizeUsage, onAgentEvent, queueEmbeddedPiMessage as queueAgentHarnessMessage, registerNativeHookRelay, resetAgentEventsForTest, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveBootstrapContextForRun, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveNodeIdFromList, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveSessionWriteLockAcquireTimeoutMs, resolveUserPath, runAgentCleanupStep, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeAgentFinalizeHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runHarnessContextEngineMaintenance, selectDefaultNodeFromList, setActiveEmbeddedRun, supportsModelTools, wrapToolWithBeforeToolCallHook };
