import { i as OpenClawConfig } from "../../types.openclaw-DZQrhn8E.js";
import { t as FallbackAttempt } from "../../model-fallback.types-lteinV-m.js";
import { s as AuthProfileStore } from "../../types-Bp0KTkSV.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-CR8rW2kY.js";
import { a as ImageGenerationProviderPlugin } from "../../types-_HTuWOFH.js";
import { n as createSubsystemLogger } from "../../subsystem-d1VSDcdo.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-DA7xouC9.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-DX35nzAl.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-HFRVPeNg.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-CsJdVQn8.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-_gkiAzrF.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-C3gSBSmY.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-CmsZZlO_.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };