// Curated emoji options for the agent identity emoji picker dropdown.
// Grouped for readability in the native <select>; values are the raw glyphs
// stored as the agent's identity emoji (same field the free-text input sets).
// Generated from Unicode emoji-test.txt (Emoji 18.0): fully-qualified only, no flags, ZWJ sequences, skin tones or keycaps.

export type EmojiCatalogGroup = {
  label: string;
  options: Array<{ emoji: string; label: string }>;
};

export const EMOJI_CATALOG: EmojiCatalogGroup[] = [
  {
    label: "Animals & Nature",
    options: [
      { emoji: "🦞", label: "Lobster" },
      { emoji: "🐵", label: "Monkey Face" },
      { emoji: "🐒", label: "Monkey" },
      { emoji: "🦍", label: "Gorilla" },
      { emoji: "🦧", label: "Orangutan" },
      { emoji: "🐶", label: "Dog Face" },
      { emoji: "🐕", label: "Dog" },
      { emoji: "🦮", label: "Guide Dog" },
      { emoji: "🐩", label: "Poodle" },
      { emoji: "🐺", label: "Wolf" },
      { emoji: "🦊", label: "Fox" },
      { emoji: "🦝", label: "Raccoon" },
      { emoji: "🐱", label: "Cat Face" },
      { emoji: "🐈", label: "Cat" },
      { emoji: "🦁", label: "Lion" },
      { emoji: "🐯", label: "Tiger Face" },
      { emoji: "🐅", label: "Tiger" },
      { emoji: "🐆", label: "Leopard" },
      { emoji: "🐴", label: "Horse Face" },
      { emoji: "🫎", label: "Moose" },
      { emoji: "🫏", label: "Donkey" },
      { emoji: "🐎", label: "Horse" },
      { emoji: "🦄", label: "Unicorn" },
      { emoji: "🦓", label: "Zebra" },
      { emoji: "🦌", label: "Deer" },
      { emoji: "🦬", label: "Bison" },
      { emoji: "🐮", label: "Cow Face" },
      { emoji: "🐂", label: "Ox" },
      { emoji: "🐃", label: "Water Buffalo" },
      { emoji: "🐄", label: "Cow" },
      { emoji: "🐷", label: "Pig Face" },
      { emoji: "🐖", label: "Pig" },
      { emoji: "🐗", label: "Boar" },
      { emoji: "🐽", label: "Pig Nose" },
      { emoji: "🐏", label: "Ram" },
      { emoji: "🐑", label: "Ewe" },
      { emoji: "🐐", label: "Goat" },
      { emoji: "🐪", label: "Camel" },
      { emoji: "🐫", label: "Two-hump Camel" },
      { emoji: "🦙", label: "Llama" },
      { emoji: "🦒", label: "Giraffe" },
      { emoji: "🐘", label: "Elephant" },
      { emoji: "🦣", label: "Mammoth" },
      { emoji: "🦏", label: "Rhinoceros" },
      { emoji: "🦛", label: "Hippopotamus" },
      { emoji: "🐭", label: "Mouse Face" },
      { emoji: "🐁", label: "Mouse" },
      { emoji: "🐀", label: "Rat" },
      { emoji: "🐹", label: "Hamster" },
      { emoji: "🐰", label: "Rabbit Face" },
      { emoji: "🐇", label: "Rabbit" },
      { emoji: "🐿️", label: "Chipmunk" },
      { emoji: "🦫", label: "Beaver" },
      { emoji: "🦔", label: "Hedgehog" },
      { emoji: "🦇", label: "Bat" },
      { emoji: "🐻", label: "Bear" },
      { emoji: "🐨", label: "Koala" },
      { emoji: "🐼", label: "Panda" },
      { emoji: "🦥", label: "Sloth" },
      { emoji: "🦦", label: "Otter" },
      { emoji: "🦨", label: "Skunk" },
      { emoji: "🦘", label: "Kangaroo" },
      { emoji: "🦡", label: "Badger" },
      { emoji: "🐾", label: "Paw Prints" },
      { emoji: "🦃", label: "Turkey" },
      { emoji: "🐔", label: "Chicken" },
      { emoji: "🐓", label: "Rooster" },
      { emoji: "🐣", label: "Hatching Chick" },
      { emoji: "🐤", label: "Baby Chick" },
      { emoji: "🐥", label: "Front-facing Baby Chick" },
      { emoji: "🐦", label: "Bird" },
      { emoji: "🐧", label: "Penguin" },
      { emoji: "🕊️", label: "Dove" },
      { emoji: "🦅", label: "Eagle" },
      { emoji: "🦆", label: "Duck" },
      { emoji: "🦢", label: "Swan" },
      { emoji: "🦉", label: "Owl" },
      { emoji: "🦤", label: "Dodo" },
      { emoji: "🪶", label: "Feather" },
      { emoji: "🦩", label: "Flamingo" },
      { emoji: "🦚", label: "Peacock" },
      { emoji: "🦜", label: "Parrot" },
      { emoji: "🪽", label: "Wing" },
      { emoji: "🪿", label: "Goose" },
      { emoji: "🐸", label: "Frog" },
      { emoji: "🐊", label: "Crocodile" },
      { emoji: "🐢", label: "Turtle" },
      { emoji: "🦎", label: "Lizard" },
      { emoji: "🐍", label: "Snake" },
      { emoji: "🐲", label: "Dragon Face" },
      { emoji: "🐉", label: "Dragon" },
      { emoji: "🦕", label: "Sauropod" },
      { emoji: "🦖", label: "T-rex" },
      { emoji: "🐳", label: "Spouting Whale" },
      { emoji: "🐋", label: "Whale" },
      { emoji: "🐬", label: "Dolphin" },
      { emoji: "🫍", label: "Orca" },
      { emoji: "🦭", label: "Seal" },
      { emoji: "🐟", label: "Fish" },
      { emoji: "🐠", label: "Tropical Fish" },
      { emoji: "🐡", label: "Blowfish" },
      { emoji: "🦈", label: "Shark" },
      { emoji: "🐙", label: "Octopus" },
      { emoji: "🐚", label: "Spiral Shell" },
      { emoji: "🪸", label: "Coral" },
      { emoji: "🪼", label: "Jellyfish" },
      { emoji: "🦀", label: "Crab" },
      { emoji: "🦐", label: "Shrimp" },
      { emoji: "🦑", label: "Squid" },
      { emoji: "🦪", label: "Oyster" },
      { emoji: "🐌", label: "Snail" },
      { emoji: "🦋", label: "Butterfly" },
      { emoji: "🫌", label: "Monarch Butterfly" },
      { emoji: "🐛", label: "Bug" },
      { emoji: "🐜", label: "Ant" },
      { emoji: "🐝", label: "Honeybee" },
      { emoji: "🪲", label: "Beetle" },
      { emoji: "🐞", label: "Lady Beetle" },
      { emoji: "🦗", label: "Cricket" },
      { emoji: "🪳", label: "Cockroach" },
      { emoji: "🕷️", label: "Spider" },
      { emoji: "🕸️", label: "Spider Web" },
      { emoji: "🦂", label: "Scorpion" },
      { emoji: "🦟", label: "Mosquito" },
      { emoji: "🪰", label: "Fly" },
      { emoji: "🪱", label: "Worm" },
      { emoji: "🦠", label: "Microbe" },
      { emoji: "💐", label: "Bouquet" },
      { emoji: "🌸", label: "Cherry Blossom" },
      { emoji: "💮", label: "White Flower" },
      { emoji: "🪷", label: "Lotus" },
      { emoji: "🏵️", label: "Rosette" },
      { emoji: "🌹", label: "Rose" },
      { emoji: "🥀", label: "Wilted Flower" },
      { emoji: "🌺", label: "Hibiscus" },
      { emoji: "🌻", label: "Sunflower" },
      { emoji: "🌼", label: "Blossom" },
      { emoji: "🌷", label: "Tulip" },
      { emoji: "🪻", label: "Hyacinth" },
      { emoji: "🌱", label: "Seedling" },
      { emoji: "🪴", label: "Potted Plant" },
      { emoji: "🌲", label: "Evergreen Tree" },
      { emoji: "🌳", label: "Deciduous Tree" },
      { emoji: "🌴", label: "Palm Tree" },
      { emoji: "🌵", label: "Cactus" },
      { emoji: "🌾", label: "Sheaf of Rice" },
      { emoji: "🌿", label: "Herb" },
      { emoji: "☘️", label: "Shamrock" },
      { emoji: "🍀", label: "Four Leaf Clover" },
      { emoji: "🍁", label: "Maple Leaf" },
      { emoji: "🍂", label: "Fallen Leaf" },
      { emoji: "🍃", label: "Leaf Fluttering in Wind" },
      { emoji: "🪹", label: "Empty Nest" },
      { emoji: "🪺", label: "Nest with Eggs" },
      { emoji: "🍄", label: "Mushroom" },
      { emoji: "🪾", label: "Leafless Tree" },
    ],
  },
  {
    label: "Smileys & Emotion",
    options: [
      { emoji: "😀", label: "Grinning Face" },
      { emoji: "😃", label: "Grinning Face with Big Eyes" },
      { emoji: "😄", label: "Grinning Face with Smiling Eyes" },
      { emoji: "😁", label: "Beaming Face with Smiling Eyes" },
      { emoji: "😆", label: "Grinning Squinting Face" },
      { emoji: "😅", label: "Grinning Face with Sweat" },
      { emoji: "🤣", label: "Rolling on the Floor Laughing" },
      { emoji: "😂", label: "Face with Tears of Joy" },
      { emoji: "🙂", label: "Slightly Smiling Face" },
      { emoji: "🙃", label: "Upside-down Face" },
      { emoji: "🫠", label: "Melting Face" },
      { emoji: "🫫", label: "Cracking Face" },
      { emoji: "😉", label: "Winking Face" },
      { emoji: "😊", label: "Smiling Face with Smiling Eyes" },
      { emoji: "😇", label: "Smiling Face with Halo" },
      { emoji: "🥰", label: "Smiling Face with Hearts" },
      { emoji: "😍", label: "Smiling Face with Heart-eyes" },
      { emoji: "🤩", label: "Star-struck" },
      { emoji: "😘", label: "Face Blowing a Kiss" },
      { emoji: "😗", label: "Kissing Face" },
      { emoji: "☺️", label: "Smiling Face" },
      { emoji: "😚", label: "Kissing Face with Closed Eyes" },
      { emoji: "😙", label: "Kissing Face with Smiling Eyes" },
      { emoji: "🥲", label: "Smiling Face with Tear" },
      { emoji: "😋", label: "Face Savoring Food" },
      { emoji: "😛", label: "Face with Tongue" },
      { emoji: "😜", label: "Winking Face with Tongue" },
      { emoji: "🤪", label: "Zany Face" },
      { emoji: "😝", label: "Squinting Face with Tongue" },
      { emoji: "🤑", label: "Money-mouth Face" },
      { emoji: "🤗", label: "Smiling Face with Open Hands" },
      { emoji: "🤭", label: "Face with Hand Over Mouth" },
      { emoji: "🫢", label: "Face with Open Eyes and Hand Over Mouth" },
      { emoji: "🫣", label: "Face with Peeking Eye" },
      { emoji: "🤫", label: "Shushing Face" },
      { emoji: "🤔", label: "Thinking Face" },
      { emoji: "🫡", label: "Saluting Face" },
      { emoji: "🤐", label: "Zipper-mouth Face" },
      { emoji: "🤨", label: "Face with Raised Eyebrow" },
      { emoji: "😐", label: "Neutral Face" },
      { emoji: "😑", label: "Expressionless Face" },
      { emoji: "😶", label: "Face Without Mouth" },
      { emoji: "🫥", label: "Dotted Line Face" },
      { emoji: "😏", label: "Smirking Face" },
      { emoji: "😒", label: "Unamused Face" },
      { emoji: "🙄", label: "Face with Rolling Eyes" },
      { emoji: "😬", label: "Grimacing Face" },
      { emoji: "🤥", label: "Lying Face" },
      { emoji: "🫨", label: "Shaking Face" },
      { emoji: "😌", label: "Relieved Face" },
      { emoji: "😔", label: "Pensive Face" },
      { emoji: "😪", label: "Sleepy Face" },
      { emoji: "🤤", label: "Drooling Face" },
      { emoji: "😴", label: "Sleeping Face" },
      { emoji: "🫩", label: "Face with Bags Under Eyes" },
      { emoji: "😷", label: "Face with Medical Mask" },
      { emoji: "🤒", label: "Face with Thermometer" },
      { emoji: "🤕", label: "Face with Head-bandage" },
      { emoji: "🤢", label: "Nauseated Face" },
      { emoji: "🤮", label: "Face Vomiting" },
      { emoji: "🤧", label: "Sneezing Face" },
      { emoji: "🥵", label: "Hot Face" },
      { emoji: "🥶", label: "Cold Face" },
      { emoji: "🥴", label: "Woozy Face" },
      { emoji: "😵", label: "Face with Crossed-out Eyes" },
      { emoji: "🤯", label: "Exploding Head" },
      { emoji: "🤠", label: "Cowboy Hat Face" },
      { emoji: "🥳", label: "Partying Face" },
      { emoji: "🥸", label: "Disguised Face" },
      { emoji: "😎", label: "Smiling Face with Sunglasses" },
      { emoji: "🤓", label: "Nerd Face" },
      { emoji: "🧐", label: "Face with Monocle" },
      { emoji: "😕", label: "Confused Face" },
      { emoji: "🫤", label: "Face with Diagonal Mouth" },
      { emoji: "😟", label: "Worried Face" },
      { emoji: "🙁", label: "Slightly Frowning Face" },
      { emoji: "☹️", label: "Frowning Face" },
      { emoji: "😮", label: "Face with Open Mouth" },
      { emoji: "😯", label: "Hushed Face" },
      { emoji: "😲", label: "Astonished Face" },
      { emoji: "😳", label: "Flushed Face" },
      { emoji: "🫪", label: "Distorted Face" },
      { emoji: "🥺", label: "Pleading Face" },
      { emoji: "🥹", label: "Face Holding Back Tears" },
      { emoji: "😦", label: "Frowning Face with Open Mouth" },
      { emoji: "😧", label: "Anguished Face" },
      { emoji: "😨", label: "Fearful Face" },
      { emoji: "😰", label: "Anxious Face with Sweat" },
      { emoji: "😥", label: "Sad But Relieved Face" },
      { emoji: "😢", label: "Crying Face" },
      { emoji: "😭", label: "Loudly Crying Face" },
      { emoji: "😱", label: "Face Screaming in Fear" },
      { emoji: "😖", label: "Confounded Face" },
      { emoji: "😣", label: "Persevering Face" },
      { emoji: "😞", label: "Disappointed Face" },
      { emoji: "😓", label: "Downcast Face with Sweat" },
      { emoji: "😩", label: "Weary Face" },
      { emoji: "😫", label: "Tired Face" },
      { emoji: "🥱", label: "Yawning Face" },
      { emoji: "😤", label: "Face with Steam From Nose" },
      { emoji: "😡", label: "Enraged Face" },
      { emoji: "😠", label: "Angry Face" },
      { emoji: "🤬", label: "Face with Symbols on Mouth" },
      { emoji: "😈", label: "Smiling Face with Horns" },
      { emoji: "👿", label: "Angry Face with Horns" },
      { emoji: "💀", label: "Skull" },
      { emoji: "☠️", label: "Skull and Crossbones" },
      { emoji: "💩", label: "Pile of Poo" },
      { emoji: "🤡", label: "Clown Face" },
      { emoji: "👹", label: "Ogre" },
      { emoji: "👺", label: "Goblin" },
      { emoji: "👻", label: "Ghost" },
      { emoji: "👽", label: "Alien" },
      { emoji: "👾", label: "Alien Monster" },
      { emoji: "🤖", label: "Robot" },
      { emoji: "😺", label: "Grinning Cat" },
      { emoji: "😸", label: "Grinning Cat with Smiling Eyes" },
      { emoji: "😹", label: "Cat with Tears of Joy" },
      { emoji: "😻", label: "Smiling Cat with Heart-eyes" },
      { emoji: "😼", label: "Cat with Wry Smile" },
      { emoji: "😽", label: "Kissing Cat" },
      { emoji: "🙀", label: "Weary Cat" },
      { emoji: "😿", label: "Crying Cat" },
      { emoji: "😾", label: "Pouting Cat" },
      { emoji: "🙈", label: "See-no-evil Monkey" },
      { emoji: "🙉", label: "Hear-no-evil Monkey" },
      { emoji: "🙊", label: "Speak-no-evil Monkey" },
      { emoji: "💌", label: "Love Letter" },
      { emoji: "💘", label: "Heart with Arrow" },
      { emoji: "💝", label: "Heart with Ribbon" },
      { emoji: "💖", label: "Sparkling Heart" },
      { emoji: "💗", label: "Growing Heart" },
      { emoji: "💓", label: "Beating Heart" },
      { emoji: "💞", label: "Revolving Hearts" },
      { emoji: "💕", label: "Two Hearts" },
      { emoji: "💟", label: "Heart Decoration" },
      { emoji: "❣️", label: "Heart Exclamation" },
      { emoji: "💔", label: "Broken Heart" },
      { emoji: "❤️", label: "Red Heart" },
      { emoji: "🩷", label: "Pink Heart" },
      { emoji: "🧡", label: "Orange Heart" },
      { emoji: "💛", label: "Yellow Heart" },
      { emoji: "💚", label: "Green Heart" },
      { emoji: "💙", label: "Blue Heart" },
      { emoji: "🩵", label: "Light Blue Heart" },
      { emoji: "💜", label: "Purple Heart" },
      { emoji: "🤎", label: "Brown Heart" },
      { emoji: "🖤", label: "Black Heart" },
      { emoji: "🩶", label: "Grey Heart" },
      { emoji: "🤍", label: "White Heart" },
      { emoji: "💋", label: "Kiss Mark" },
      { emoji: "💯", label: "Hundred Points" },
      { emoji: "💢", label: "Anger Symbol" },
      { emoji: "🫯", label: "Fight Cloud" },
      { emoji: "💥", label: "Collision" },
      { emoji: "💫", label: "Dizzy" },
      { emoji: "💦", label: "Sweat Droplets" },
      { emoji: "💨", label: "Dashing Away" },
      { emoji: "🕳️", label: "Hole" },
      { emoji: "💬", label: "Speech Balloon" },
      { emoji: "🗨️", label: "Left Speech Bubble" },
      { emoji: "🗯️", label: "Right Anger Bubble" },
      { emoji: "💭", label: "Thought Balloon" },
      { emoji: "💤", label: "Zzz" },
    ],
  },
  {
    label: "People & Body",
    options: [
      { emoji: "👋", label: "Waving Hand" },
      { emoji: "🤚", label: "Raised Back of Hand" },
      { emoji: "🖐️", label: "Hand with Fingers Splayed" },
      { emoji: "✋", label: "Raised Hand" },
      { emoji: "🖖", label: "Vulcan Salute" },
      { emoji: "🫱", label: "Rightwards Hand" },
      { emoji: "🫲", label: "Leftwards Hand" },
      { emoji: "🫳", label: "Palm Down Hand" },
      { emoji: "🫴", label: "Palm Up Hand" },
      { emoji: "🫷", label: "Leftwards Pushing Hand" },
      { emoji: "🫸", label: "Rightwards Pushing Hand" },
      { emoji: "👌", label: "Ok Hand" },
      { emoji: "🤌", label: "Pinched Fingers" },
      { emoji: "🤏", label: "Pinching Hand" },
      { emoji: "✌️", label: "Victory Hand" },
      { emoji: "🤞", label: "Crossed Fingers" },
      { emoji: "🫰", label: "Hand with Index Finger and Thumb Crossed" },
      { emoji: "🤟", label: "Love-you Gesture" },
      { emoji: "🤘", label: "Sign of the Horns" },
      { emoji: "🤙", label: "Call Me Hand" },
      { emoji: "👈", label: "Backhand Index Pointing Left" },
      { emoji: "👉", label: "Backhand Index Pointing Right" },
      { emoji: "👆", label: "Backhand Index Pointing Up" },
      { emoji: "🖕", label: "Middle Finger" },
      { emoji: "👇", label: "Backhand Index Pointing Down" },
      { emoji: "☝️", label: "Index Pointing Up" },
      { emoji: "🫵", label: "Index Pointing at the Viewer" },
      { emoji: "👍", label: "Thumbs Up" },
      { emoji: "👎", label: "Thumbs Down" },
      { emoji: "🫹", label: "Leftwards Thumb Sign" },
      { emoji: "🫺", label: "Rightwards Thumb Sign" },
      { emoji: "✊", label: "Raised Fist" },
      { emoji: "👊", label: "Oncoming Fist" },
      { emoji: "🤛", label: "Left-facing Fist" },
      { emoji: "🤜", label: "Right-facing Fist" },
      { emoji: "👏", label: "Clapping Hands" },
      { emoji: "🙌", label: "Raising Hands" },
      { emoji: "🫶", label: "Heart Hands" },
      { emoji: "👐", label: "Open Hands" },
      { emoji: "🤲", label: "Palms Up Together" },
      { emoji: "🤝", label: "Handshake" },
      { emoji: "🙏", label: "Folded Hands" },
      { emoji: "✍️", label: "Writing Hand" },
      { emoji: "💅", label: "Nail Polish" },
      { emoji: "🤳", label: "Selfie" },
      { emoji: "💪", label: "Flexed Biceps" },
      { emoji: "🦾", label: "Mechanical Arm" },
      { emoji: "🦿", label: "Mechanical Leg" },
      { emoji: "🦵", label: "Leg" },
      { emoji: "🦶", label: "Foot" },
      { emoji: "👂", label: "Ear" },
      { emoji: "🦻", label: "Ear with Hearing Aid" },
      { emoji: "👃", label: "Nose" },
      { emoji: "🧠", label: "Brain" },
      { emoji: "🫀", label: "Anatomical Heart" },
      { emoji: "🫁", label: "Lungs" },
      { emoji: "🦷", label: "Tooth" },
      { emoji: "🦴", label: "Bone" },
      { emoji: "👀", label: "Eyes" },
      { emoji: "👁️", label: "Eye" },
      { emoji: "👅", label: "Tongue" },
      { emoji: "👄", label: "Mouth" },
      { emoji: "🫦", label: "Biting Lip" },
      { emoji: "👶", label: "Baby" },
      { emoji: "🧒", label: "Child" },
      { emoji: "👦", label: "Boy" },
      { emoji: "👧", label: "Girl" },
      { emoji: "🧑", label: "Person" },
      { emoji: "👱", label: "Person: Blond Hair" },
      { emoji: "👨", label: "Man" },
      { emoji: "🧔", label: "Person: Beard" },
      { emoji: "👩", label: "Woman" },
      { emoji: "🧓", label: "Older Person" },
      { emoji: "👴", label: "Old Man" },
      { emoji: "👵", label: "Old Woman" },
      { emoji: "🙍", label: "Person Frowning" },
      { emoji: "🙎", label: "Person Pouting" },
      { emoji: "🙅", label: "Person Gesturing No" },
      { emoji: "🙆", label: "Person Gesturing Ok" },
      { emoji: "💁", label: "Person Tipping Hand" },
      { emoji: "🙋", label: "Person Raising Hand" },
      { emoji: "🧏", label: "Deaf Person" },
      { emoji: "🙇", label: "Person Bowing" },
      { emoji: "🤦", label: "Person Facepalming" },
      { emoji: "🤷", label: "Person Shrugging" },
      { emoji: "👮", label: "Police Officer" },
      { emoji: "🕵️", label: "Detective" },
      { emoji: "💂", label: "Guard" },
      { emoji: "🥷", label: "Ninja" },
      { emoji: "👷", label: "Construction Worker" },
      { emoji: "🫅", label: "Person with Crown" },
      { emoji: "🤴", label: "Prince" },
      { emoji: "👸", label: "Princess" },
      { emoji: "👳", label: "Person Wearing Turban" },
      { emoji: "👲", label: "Person with Skullcap" },
      { emoji: "🧕", label: "Woman with Headscarf" },
      { emoji: "🤵", label: "Person in Tuxedo" },
      { emoji: "👰", label: "Person with Veil" },
      { emoji: "🤰", label: "Pregnant Woman" },
      { emoji: "🫃", label: "Pregnant Man" },
      { emoji: "🫄", label: "Pregnant Person" },
      { emoji: "🤱", label: "Breast-feeding" },
      { emoji: "👼", label: "Baby Angel" },
      { emoji: "🎅", label: "Santa Claus" },
      { emoji: "🤶", label: "Mrs. Claus" },
      { emoji: "🦸", label: "Superhero" },
      { emoji: "🦹", label: "Supervillain" },
      { emoji: "🧙", label: "Mage" },
      { emoji: "🧚", label: "Fairy" },
      { emoji: "🧛", label: "Vampire" },
      { emoji: "🧜", label: "Merperson" },
      { emoji: "🧝", label: "Elf" },
      { emoji: "🧞", label: "Genie" },
      { emoji: "🧟", label: "Zombie" },
      { emoji: "🧌", label: "Troll" },
      { emoji: "🫈", label: "Hairy Creature" },
      { emoji: "💆", label: "Person Getting Massage" },
      { emoji: "💇", label: "Person Getting Haircut" },
      { emoji: "🚶", label: "Person Walking" },
      { emoji: "🧍", label: "Person Standing" },
      { emoji: "🧎", label: "Person Kneeling" },
      { emoji: "🏃", label: "Person Running" },
      { emoji: "💃", label: "Woman Dancing" },
      { emoji: "🕺", label: "Man Dancing" },
      { emoji: "🕴️", label: "Person in Suit Levitating" },
      { emoji: "👯", label: "People with Bunny Ears" },
      { emoji: "🧖", label: "Person in Steamy Room" },
      { emoji: "🧗", label: "Person Climbing" },
      { emoji: "🤺", label: "Person Fencing" },
      { emoji: "🏇", label: "Horse Racing" },
      { emoji: "⛷️", label: "Skier" },
      { emoji: "🏂", label: "Snowboarder" },
      { emoji: "🏌️", label: "Person Golfing" },
      { emoji: "🏄", label: "Person Surfing" },
      { emoji: "🚣", label: "Person Rowing Boat" },
      { emoji: "🏊", label: "Person Swimming" },
      { emoji: "⛹️", label: "Person Bouncing Ball" },
      { emoji: "🏋️", label: "Person Lifting Weights" },
      { emoji: "🚴", label: "Person Biking" },
      { emoji: "🚵", label: "Person Mountain Biking" },
      { emoji: "🤸", label: "Person Cartwheeling" },
      { emoji: "🤼", label: "People Wrestling" },
      { emoji: "🤽", label: "Person Playing Water Polo" },
      { emoji: "🤾", label: "Person Playing Handball" },
      { emoji: "🤹", label: "Person Juggling" },
      { emoji: "🧘", label: "Person in Lotus Position" },
      { emoji: "🛀", label: "Person Taking Bath" },
      { emoji: "🛌", label: "Person in Bed" },
      { emoji: "👭", label: "Women Holding Hands" },
      { emoji: "👫", label: "Woman and Man Holding Hands" },
      { emoji: "👬", label: "Men Holding Hands" },
      { emoji: "💏", label: "Kiss" },
      { emoji: "💑", label: "Couple with Heart" },
      { emoji: "🗣️", label: "Speaking Head" },
      { emoji: "👤", label: "Bust in Silhouette" },
      { emoji: "👥", label: "Busts in Silhouette" },
      { emoji: "🫂", label: "People Hugging" },
      { emoji: "👪", label: "Family" },
      { emoji: "👣", label: "Footprints" },
      { emoji: "🫆", label: "Fingerprint" },
    ],
  },
  {
    label: "Food & Drink",
    options: [
      { emoji: "🍇", label: "Grapes" },
      { emoji: "🍈", label: "Melon" },
      { emoji: "🍉", label: "Watermelon" },
      { emoji: "🍊", label: "Tangerine" },
      { emoji: "🍋", label: "Lemon" },
      { emoji: "🍌", label: "Banana" },
      { emoji: "🍍", label: "Pineapple" },
      { emoji: "🥭", label: "Mango" },
      { emoji: "🍎", label: "Red Apple" },
      { emoji: "🍏", label: "Green Apple" },
      { emoji: "🍐", label: "Pear" },
      { emoji: "🍑", label: "Peach" },
      { emoji: "🍒", label: "Cherries" },
      { emoji: "🍓", label: "Strawberry" },
      { emoji: "🫐", label: "Blueberries" },
      { emoji: "🥝", label: "Kiwi Fruit" },
      { emoji: "🍅", label: "Tomato" },
      { emoji: "🫒", label: "Olive" },
      { emoji: "🥥", label: "Coconut" },
      { emoji: "🥑", label: "Avocado" },
      { emoji: "🍆", label: "Eggplant" },
      { emoji: "🥔", label: "Potato" },
      { emoji: "🥕", label: "Carrot" },
      { emoji: "🌽", label: "Ear of Corn" },
      { emoji: "🌶️", label: "Hot Pepper" },
      { emoji: "🫑", label: "Bell Pepper" },
      { emoji: "🥒", label: "Cucumber" },
      { emoji: "🫝", label: "Pickle" },
      { emoji: "🥬", label: "Leafy Green" },
      { emoji: "🥦", label: "Broccoli" },
      { emoji: "🧄", label: "Garlic" },
      { emoji: "🧅", label: "Onion" },
      { emoji: "🥜", label: "Peanuts" },
      { emoji: "🫘", label: "Beans" },
      { emoji: "🌰", label: "Chestnut" },
      { emoji: "🫚", label: "Ginger Root" },
      { emoji: "🫛", label: "Pea Pod" },
      { emoji: "🫜", label: "Root Vegetable" },
      { emoji: "🍞", label: "Bread" },
      { emoji: "🥐", label: "Croissant" },
      { emoji: "🥖", label: "Baguette Bread" },
      { emoji: "🫓", label: "Flatbread" },
      { emoji: "🥨", label: "Pretzel" },
      { emoji: "🥯", label: "Bagel" },
      { emoji: "🥞", label: "Pancakes" },
      { emoji: "🧇", label: "Waffle" },
      { emoji: "🧀", label: "Cheese Wedge" },
      { emoji: "🍖", label: "Meat on Bone" },
      { emoji: "🍗", label: "Poultry Leg" },
      { emoji: "🥩", label: "Cut of Meat" },
      { emoji: "🥓", label: "Bacon" },
      { emoji: "🍔", label: "Hamburger" },
      { emoji: "🍟", label: "French Fries" },
      { emoji: "🍕", label: "Pizza" },
      { emoji: "🌭", label: "Hot Dog" },
      { emoji: "🥪", label: "Sandwich" },
      { emoji: "🌮", label: "Taco" },
      { emoji: "🌯", label: "Burrito" },
      { emoji: "🫔", label: "Tamale" },
      { emoji: "🥙", label: "Stuffed Flatbread" },
      { emoji: "🧆", label: "Falafel" },
      { emoji: "🥚", label: "Egg" },
      { emoji: "🍳", label: "Cooking" },
      { emoji: "🥘", label: "Shallow Pan of Food" },
      { emoji: "🍲", label: "Pot of Food" },
      { emoji: "🫕", label: "Fondue" },
      { emoji: "🥣", label: "Bowl with Spoon" },
      { emoji: "🥗", label: "Green Salad" },
      { emoji: "🍿", label: "Popcorn" },
      { emoji: "🧈", label: "Butter" },
      { emoji: "🧂", label: "Salt" },
      { emoji: "🥫", label: "Canned Food" },
      { emoji: "🍱", label: "Bento Box" },
      { emoji: "🍘", label: "Rice Cracker" },
      { emoji: "🍙", label: "Rice Ball" },
      { emoji: "🍚", label: "Cooked Rice" },
      { emoji: "🍛", label: "Curry Rice" },
      { emoji: "🍜", label: "Steaming Bowl" },
      { emoji: "🍝", label: "Spaghetti" },
      { emoji: "🍠", label: "Roasted Sweet Potato" },
      { emoji: "🍢", label: "Oden" },
      { emoji: "🍣", label: "Sushi" },
      { emoji: "🍤", label: "Fried Shrimp" },
      { emoji: "🍥", label: "Fish Cake with Swirl" },
      { emoji: "🥮", label: "Moon Cake" },
      { emoji: "🍡", label: "Dango" },
      { emoji: "🥟", label: "Dumpling" },
      { emoji: "🥠", label: "Fortune Cookie" },
      { emoji: "🥡", label: "Takeout Box" },
      { emoji: "🍦", label: "Soft Ice Cream" },
      { emoji: "🍧", label: "Shaved Ice" },
      { emoji: "🍨", label: "Ice Cream" },
      { emoji: "🍩", label: "Doughnut" },
      { emoji: "🍪", label: "Cookie" },
      { emoji: "🎂", label: "Birthday Cake" },
      { emoji: "🍰", label: "Shortcake" },
      { emoji: "🧁", label: "Cupcake" },
      { emoji: "🥧", label: "Pie" },
      { emoji: "🍫", label: "Chocolate Bar" },
      { emoji: "🍬", label: "Candy" },
      { emoji: "🍭", label: "Lollipop" },
      { emoji: "🍮", label: "Custard" },
      { emoji: "🍯", label: "Honey Pot" },
      { emoji: "🍼", label: "Baby Bottle" },
      { emoji: "🥛", label: "Glass of Milk" },
      { emoji: "☕", label: "Hot Beverage" },
      { emoji: "🫖", label: "Teapot" },
      { emoji: "🍵", label: "Teacup Without Handle" },
      { emoji: "🍶", label: "Sake" },
      { emoji: "🍾", label: "Bottle with Popping Cork" },
      { emoji: "🍷", label: "Wine Glass" },
      { emoji: "🍸", label: "Cocktail Glass" },
      { emoji: "🍹", label: "Tropical Drink" },
      { emoji: "🍺", label: "Beer Mug" },
      { emoji: "🍻", label: "Clinking Beer Mugs" },
      { emoji: "🥂", label: "Clinking Glasses" },
      { emoji: "🥃", label: "Tumbler Glass" },
      { emoji: "🫗", label: "Pouring Liquid" },
      { emoji: "🥤", label: "Cup with Straw" },
      { emoji: "🧋", label: "Bubble Tea" },
      { emoji: "🧃", label: "Beverage Box" },
      { emoji: "🧉", label: "Mate" },
      { emoji: "🧊", label: "Ice" },
      { emoji: "🥢", label: "Chopsticks" },
      { emoji: "🍽️", label: "Fork and Knife with Plate" },
      { emoji: "🍴", label: "Fork and Knife" },
      { emoji: "🥄", label: "Spoon" },
      { emoji: "🔪", label: "Kitchen Knife" },
      { emoji: "🫙", label: "Jar" },
      { emoji: "🏺", label: "Amphora" },
    ],
  },
  {
    label: "Travel & Places — Places & Ground Transport",
    options: [
      { emoji: "🌍", label: "Globe Showing Europe-africa" },
      { emoji: "🌎", label: "Globe Showing Americas" },
      { emoji: "🌏", label: "Globe Showing Asia-australia" },
      { emoji: "🌐", label: "Globe with Meridians" },
      { emoji: "🗺️", label: "World Map" },
      { emoji: "🗾", label: "Map of Japan" },
      { emoji: "🧭", label: "Compass" },
      { emoji: "🏔️", label: "Snow-capped Mountain" },
      { emoji: "⛰️", label: "Mountain" },
      { emoji: "🛘", label: "Landslide" },
      { emoji: "🌋", label: "Volcano" },
      { emoji: "🗻", label: "Mount Fuji" },
      { emoji: "🏕️", label: "Camping" },
      { emoji: "🏖️", label: "Beach with Umbrella" },
      { emoji: "🏜️", label: "Desert" },
      { emoji: "🏝️", label: "Desert Island" },
      { emoji: "🏞️", label: "National Park" },
      { emoji: "🏟️", label: "Stadium" },
      { emoji: "🏛️", label: "Classical Building" },
      { emoji: "🏗️", label: "Building Construction" },
      { emoji: "🧱", label: "Brick" },
      { emoji: "🪨", label: "Rock" },
      { emoji: "🪵", label: "Wood" },
      { emoji: "🛖", label: "Hut" },
      { emoji: "🏘️", label: "Houses" },
      { emoji: "🏚️", label: "Derelict House" },
      { emoji: "🏠", label: "House" },
      { emoji: "🏡", label: "House with Garden" },
      { emoji: "🏢", label: "Office Building" },
      { emoji: "🏣", label: "Japanese Post Office" },
      { emoji: "🏤", label: "Post Office" },
      { emoji: "🏥", label: "Hospital" },
      { emoji: "🏦", label: "Bank" },
      { emoji: "🏨", label: "Hotel" },
      { emoji: "🏩", label: "Love Hotel" },
      { emoji: "🏪", label: "Convenience Store" },
      { emoji: "🏫", label: "School" },
      { emoji: "🏬", label: "Department Store" },
      { emoji: "🏭", label: "Factory" },
      { emoji: "🏯", label: "Japanese Castle" },
      { emoji: "🏰", label: "Castle" },
      { emoji: "💒", label: "Wedding" },
      { emoji: "🗼", label: "Tokyo Tower" },
      { emoji: "🗽", label: "Statue of Liberty" },
      { emoji: "⛪", label: "Church" },
      { emoji: "🕌", label: "Mosque" },
      { emoji: "🛕", label: "Hindu Temple" },
      { emoji: "🕍", label: "Synagogue" },
      { emoji: "⛩️", label: "Shinto Shrine" },
      { emoji: "🕋", label: "Kaaba" },
      { emoji: "⛲", label: "Fountain" },
      { emoji: "⛺", label: "Tent" },
      { emoji: "🌁", label: "Foggy" },
      { emoji: "🌃", label: "Night with Stars" },
      { emoji: "🏙️", label: "Cityscape" },
      { emoji: "🌄", label: "Sunrise Over Mountains" },
      { emoji: "🌅", label: "Sunrise" },
      { emoji: "🌆", label: "Cityscape at Dusk" },
      { emoji: "🌇", label: "Sunset" },
      { emoji: "🌉", label: "Bridge at Night" },
      { emoji: "♨️", label: "Hot Springs" },
      { emoji: "🎠", label: "Carousel Horse" },
      { emoji: "🛝", label: "Playground Slide" },
      { emoji: "🎡", label: "Ferris Wheel" },
      { emoji: "🎢", label: "Roller Coaster" },
      { emoji: "💈", label: "Barber Pole" },
      { emoji: "🎪", label: "Circus Tent" },
      { emoji: "🚂", label: "Locomotive" },
      { emoji: "🚃", label: "Railway Car" },
      { emoji: "🚄", label: "High-speed Train" },
      { emoji: "🚅", label: "Bullet Train" },
      { emoji: "🚆", label: "Train" },
      { emoji: "🚇", label: "Metro" },
      { emoji: "🚈", label: "Light Rail" },
      { emoji: "🚉", label: "Station" },
      { emoji: "🚊", label: "Tram" },
      { emoji: "🚝", label: "Monorail" },
      { emoji: "🚞", label: "Mountain Railway" },
      { emoji: "🚋", label: "Tram Car" },
      { emoji: "🚌", label: "Bus" },
      { emoji: "🚍", label: "Oncoming Bus" },
      { emoji: "🚎", label: "Trolleybus" },
      { emoji: "🚐", label: "Minibus" },
      { emoji: "🚑", label: "Ambulance" },
      { emoji: "🚒", label: "Fire Engine" },
      { emoji: "🚓", label: "Police Car" },
      { emoji: "🚔", label: "Oncoming Police Car" },
      { emoji: "🚕", label: "Taxi" },
      { emoji: "🚖", label: "Oncoming Taxi" },
      { emoji: "🚗", label: "Automobile" },
      { emoji: "🚘", label: "Oncoming Automobile" },
      { emoji: "🚙", label: "Sport Utility Vehicle" },
      { emoji: "🛻", label: "Pickup Truck" },
      { emoji: "🚚", label: "Delivery Truck" },
      { emoji: "🚛", label: "Articulated Lorry" },
      { emoji: "🚜", label: "Tractor" },
      { emoji: "🏎️", label: "Racing Car" },
      { emoji: "🏍️", label: "Motorcycle" },
      { emoji: "🛵", label: "Motor Scooter" },
      { emoji: "🦽", label: "Manual Wheelchair" },
      { emoji: "🦼", label: "Motorized Wheelchair" },
      { emoji: "🛺", label: "Auto Rickshaw" },
      { emoji: "🚲", label: "Bicycle" },
      { emoji: "🛴", label: "Kick Scooter" },
      { emoji: "🛹", label: "Skateboard" },
      { emoji: "🛼", label: "Roller Skate" },
      { emoji: "🚏", label: "Bus Stop" },
      { emoji: "🛣️", label: "Motorway" },
      { emoji: "🛤️", label: "Railway Track" },
      { emoji: "🛢️", label: "Oil Drum" },
      { emoji: "⛽", label: "Fuel Pump" },
      { emoji: "🛞", label: "Wheel" },
      { emoji: "🚨", label: "Police Car Light" },
      { emoji: "🚥", label: "Horizontal Traffic Light" },
      { emoji: "🚦", label: "Vertical Traffic Light" },
      { emoji: "🛑", label: "Stop Sign" },
      { emoji: "🚧", label: "Construction" },
    ],
  },
  {
    label: "Travel & Places — Water, Air & Weather",
    options: [
      { emoji: "🛙", label: "Lighthouse" },
      { emoji: "⚓", label: "Anchor" },
      { emoji: "🛟", label: "Ring Buoy" },
      { emoji: "⛵", label: "Sailboat" },
      { emoji: "🛶", label: "Canoe" },
      { emoji: "🚤", label: "Speedboat" },
      { emoji: "🛳️", label: "Passenger Ship" },
      { emoji: "⛴️", label: "Ferry" },
      { emoji: "🛥️", label: "Motor Boat" },
      { emoji: "🚢", label: "Ship" },
      { emoji: "✈️", label: "Airplane" },
      { emoji: "🛩️", label: "Small Airplane" },
      { emoji: "🛫", label: "Airplane Departure" },
      { emoji: "🛬", label: "Airplane Arrival" },
      { emoji: "🪂", label: "Parachute" },
      { emoji: "💺", label: "Seat" },
      { emoji: "🚁", label: "Helicopter" },
      { emoji: "🚟", label: "Suspension Railway" },
      { emoji: "🚠", label: "Mountain Cableway" },
      { emoji: "🚡", label: "Aerial Tramway" },
      { emoji: "🛰️", label: "Satellite" },
      { emoji: "🚀", label: "Rocket" },
      { emoji: "🛸", label: "Flying Saucer" },
      { emoji: "🛎️", label: "Bellhop Bell" },
      { emoji: "🧳", label: "Luggage" },
      { emoji: "⌛", label: "Hourglass Done" },
      { emoji: "⏳", label: "Hourglass Not Done" },
      { emoji: "⌚", label: "Watch" },
      { emoji: "⏰", label: "Alarm Clock" },
      { emoji: "⏱️", label: "Stopwatch" },
      { emoji: "⏲️", label: "Timer Clock" },
      { emoji: "🕰️", label: "Mantelpiece Clock" },
      { emoji: "🕛", label: "Twelve O’clock" },
      { emoji: "🕧", label: "Twelve-thirty" },
      { emoji: "🕐", label: "One O’clock" },
      { emoji: "🕜", label: "One-thirty" },
      { emoji: "🕑", label: "Two O’clock" },
      { emoji: "🕝", label: "Two-thirty" },
      { emoji: "🕒", label: "Three O’clock" },
      { emoji: "🕞", label: "Three-thirty" },
      { emoji: "🕓", label: "Four O’clock" },
      { emoji: "🕟", label: "Four-thirty" },
      { emoji: "🕔", label: "Five O’clock" },
      { emoji: "🕠", label: "Five-thirty" },
      { emoji: "🕕", label: "Six O’clock" },
      { emoji: "🕡", label: "Six-thirty" },
      { emoji: "🕖", label: "Seven O’clock" },
      { emoji: "🕢", label: "Seven-thirty" },
      { emoji: "🕗", label: "Eight O’clock" },
      { emoji: "🕣", label: "Eight-thirty" },
      { emoji: "🕘", label: "Nine O’clock" },
      { emoji: "🕤", label: "Nine-thirty" },
      { emoji: "🕙", label: "Ten O’clock" },
      { emoji: "🕥", label: "Ten-thirty" },
      { emoji: "🕚", label: "Eleven O’clock" },
      { emoji: "🕦", label: "Eleven-thirty" },
      { emoji: "🌑", label: "New Moon" },
      { emoji: "🌒", label: "Waxing Crescent Moon" },
      { emoji: "🌓", label: "First Quarter Moon" },
      { emoji: "🌔", label: "Waxing Gibbous Moon" },
      { emoji: "🌕", label: "Full Moon" },
      { emoji: "🌖", label: "Waning Gibbous Moon" },
      { emoji: "🌗", label: "Last Quarter Moon" },
      { emoji: "🌘", label: "Waning Crescent Moon" },
      { emoji: "🌙", label: "Crescent Moon" },
      { emoji: "🌚", label: "New Moon Face" },
      { emoji: "🌛", label: "First Quarter Moon Face" },
      { emoji: "🌜", label: "Last Quarter Moon Face" },
      { emoji: "🌡️", label: "Thermometer" },
      { emoji: "☀️", label: "Sun" },
      { emoji: "🌝", label: "Full Moon Face" },
      { emoji: "🌞", label: "Sun with Face" },
      { emoji: "🪐", label: "Ringed Planet" },
      { emoji: "⭐", label: "Star" },
      { emoji: "🌟", label: "Glowing Star" },
      { emoji: "🌠", label: "Shooting Star" },
      { emoji: "🌌", label: "Milky Way" },
      { emoji: "☁️", label: "Cloud" },
      { emoji: "⛅", label: "Sun Behind Cloud" },
      { emoji: "⛈️", label: "Cloud with Lightning and Rain" },
      { emoji: "🌤️", label: "Sun Behind Small Cloud" },
      { emoji: "🌥️", label: "Sun Behind Large Cloud" },
      { emoji: "🌦️", label: "Sun Behind Rain Cloud" },
      { emoji: "🌧️", label: "Cloud with Rain" },
      { emoji: "🌨️", label: "Cloud with Snow" },
      { emoji: "🌩️", label: "Cloud with Lightning" },
      { emoji: "🌪️", label: "Tornado" },
      { emoji: "🌫️", label: "Fog" },
      { emoji: "🌬️", label: "Wind Face" },
      { emoji: "🌀", label: "Cyclone" },
      { emoji: "🌈", label: "Rainbow" },
      { emoji: "🌂", label: "Closed Umbrella" },
      { emoji: "☂️", label: "Umbrella" },
      { emoji: "☔", label: "Umbrella with Rain Drops" },
      { emoji: "⛱️", label: "Umbrella on Ground" },
      { emoji: "⚡", label: "High Voltage" },
      { emoji: "❄️", label: "Snowflake" },
      { emoji: "☃️", label: "Snowman" },
      { emoji: "⛄", label: "Snowman Without Snow" },
      { emoji: "☄️", label: "Comet" },
      { emoji: "🪋", label: "Meteor" },
      { emoji: "🔥", label: "Fire" },
      { emoji: "💧", label: "Droplet" },
      { emoji: "🌊", label: "Water Wave" },
    ],
  },
  {
    label: "Activities",
    options: [
      { emoji: "🎃", label: "Jack-o-lantern" },
      { emoji: "🎄", label: "Christmas Tree" },
      { emoji: "🎆", label: "Fireworks" },
      { emoji: "🎇", label: "Sparkler" },
      { emoji: "🧨", label: "Firecracker" },
      { emoji: "✨", label: "Sparkles" },
      { emoji: "🎈", label: "Balloon" },
      { emoji: "🎉", label: "Party Popper" },
      { emoji: "🎊", label: "Confetti Ball" },
      { emoji: "🎋", label: "Tanabata Tree" },
      { emoji: "🎍", label: "Pine Decoration" },
      { emoji: "🎎", label: "Japanese Dolls" },
      { emoji: "🎏", label: "Carp Streamer" },
      { emoji: "🎐", label: "Wind Chime" },
      { emoji: "🎑", label: "Moon Viewing Ceremony" },
      { emoji: "🧧", label: "Red Envelope" },
      { emoji: "🎀", label: "Ribbon" },
      { emoji: "🎁", label: "Wrapped Gift" },
      { emoji: "🎗️", label: "Reminder Ribbon" },
      { emoji: "🎟️", label: "Admission Tickets" },
      { emoji: "🎫", label: "Ticket" },
      { emoji: "🎖️", label: "Military Medal" },
      { emoji: "🏆", label: "Trophy" },
      { emoji: "🏅", label: "Sports Medal" },
      { emoji: "🥇", label: "1st Place Medal" },
      { emoji: "🥈", label: "2nd Place Medal" },
      { emoji: "🥉", label: "3rd Place Medal" },
      { emoji: "⚽", label: "Soccer Ball" },
      { emoji: "⚾", label: "Baseball" },
      { emoji: "🥎", label: "Softball" },
      { emoji: "🏀", label: "Basketball" },
      { emoji: "🏐", label: "Volleyball" },
      { emoji: "🏈", label: "American Football" },
      { emoji: "🏉", label: "Rugby Football" },
      { emoji: "🎾", label: "Tennis" },
      { emoji: "🥏", label: "Flying Disc" },
      { emoji: "🎳", label: "Bowling" },
      { emoji: "🏏", label: "Cricket Game" },
      { emoji: "🏑", label: "Field Hockey" },
      { emoji: "🏒", label: "Ice Hockey" },
      { emoji: "🥍", label: "Lacrosse" },
      { emoji: "🏓", label: "Ping Pong" },
      { emoji: "🏸", label: "Badminton" },
      { emoji: "🥊", label: "Boxing Glove" },
      { emoji: "🥋", label: "Martial Arts Uniform" },
      { emoji: "🥅", label: "Goal Net" },
      { emoji: "⛳", label: "Flag in Hole" },
      { emoji: "⛸️", label: "Ice Skate" },
      { emoji: "🎣", label: "Fishing Pole" },
      { emoji: "🤿", label: "Diving Mask" },
      { emoji: "🎽", label: "Running Shirt" },
      { emoji: "🎿", label: "Skis" },
      { emoji: "🛷", label: "Sled" },
      { emoji: "🥌", label: "Curling Stone" },
      { emoji: "🎯", label: "Bullseye" },
      { emoji: "🪀", label: "Yo-yo" },
      { emoji: "🪁", label: "Kite" },
      { emoji: "🔫", label: "Water Pistol" },
      { emoji: "🎱", label: "Pool 8 Ball" },
      { emoji: "🔮", label: "Crystal Ball" },
      { emoji: "🪄", label: "Magic Wand" },
      { emoji: "🎮", label: "Video Game" },
      { emoji: "🕹️", label: "Joystick" },
      { emoji: "🎰", label: "Slot Machine" },
      { emoji: "🎲", label: "Game Die" },
      { emoji: "🧩", label: "Puzzle Piece" },
      { emoji: "🧸", label: "Teddy Bear" },
      { emoji: "🪅", label: "Piñata" },
      { emoji: "🪩", label: "Mirror Ball" },
      { emoji: "🪆", label: "Nesting Dolls" },
      { emoji: "♠️", label: "Spade Suit" },
      { emoji: "♥️", label: "Heart Suit" },
      { emoji: "♦️", label: "Diamond Suit" },
      { emoji: "♣️", label: "Club Suit" },
      { emoji: "♟️", label: "Chess Pawn" },
      { emoji: "🃏", label: "Joker" },
      { emoji: "🀄", label: "Mahjong Red Dragon" },
      { emoji: "🎴", label: "Flower Playing Cards" },
      { emoji: "🎭", label: "Performing Arts" },
      { emoji: "🖼️", label: "Framed Picture" },
      { emoji: "🎨", label: "Artist Palette" },
      { emoji: "🧵", label: "Thread" },
      { emoji: "🪡", label: "Sewing Needle" },
      { emoji: "🧶", label: "Yarn" },
      { emoji: "🪢", label: "Knot" },
    ],
  },
  {
    label: "Objects — Clothing, Music & Money",
    options: [
      { emoji: "👓", label: "Glasses" },
      { emoji: "🕶️", label: "Sunglasses" },
      { emoji: "🥽", label: "Goggles" },
      { emoji: "🥼", label: "Lab Coat" },
      { emoji: "🦺", label: "Safety Vest" },
      { emoji: "👔", label: "Necktie" },
      { emoji: "👕", label: "T-shirt" },
      { emoji: "👖", label: "Jeans" },
      { emoji: "🧣", label: "Scarf" },
      { emoji: "🧤", label: "Gloves" },
      { emoji: "🧥", label: "Coat" },
      { emoji: "🧦", label: "Socks" },
      { emoji: "👗", label: "Dress" },
      { emoji: "👘", label: "Kimono" },
      { emoji: "🥻", label: "Sari" },
      { emoji: "🩱", label: "One-piece Swimsuit" },
      { emoji: "🩲", label: "Briefs" },
      { emoji: "🩳", label: "Shorts" },
      { emoji: "👙", label: "Bikini" },
      { emoji: "👚", label: "Woman’s Clothes" },
      { emoji: "🪭", label: "Folding Hand Fan" },
      { emoji: "👛", label: "Purse" },
      { emoji: "👜", label: "Handbag" },
      { emoji: "👝", label: "Clutch Bag" },
      { emoji: "🛍️", label: "Shopping Bags" },
      { emoji: "🎒", label: "Backpack" },
      { emoji: "🩴", label: "Thong Sandal" },
      { emoji: "👞", label: "Man’s Shoe" },
      { emoji: "👟", label: "Running Shoe" },
      { emoji: "🥾", label: "Hiking Boot" },
      { emoji: "🥿", label: "Flat Shoe" },
      { emoji: "👠", label: "High-heeled Shoe" },
      { emoji: "👡", label: "Woman’s Sandal" },
      { emoji: "🩰", label: "Ballet Shoes" },
      { emoji: "👢", label: "Woman’s Boot" },
      { emoji: "🪮", label: "Hair Pick" },
      { emoji: "👑", label: "Crown" },
      { emoji: "👒", label: "Woman’s Hat" },
      { emoji: "🎩", label: "Top Hat" },
      { emoji: "🎓", label: "Graduation Cap" },
      { emoji: "🧢", label: "Billed Cap" },
      { emoji: "🪖", label: "Military Helmet" },
      { emoji: "⛑️", label: "Rescue Worker’s Helmet" },
      { emoji: "📿", label: "Prayer Beads" },
      { emoji: "💄", label: "Lipstick" },
      { emoji: "💍", label: "Ring" },
      { emoji: "💎", label: "Gem Stone" },
      { emoji: "🔇", label: "Muted Speaker" },
      { emoji: "🔈", label: "Speaker Low Volume" },
      { emoji: "🔉", label: "Speaker Medium Volume" },
      { emoji: "🔊", label: "Speaker High Volume" },
      { emoji: "📢", label: "Loudspeaker" },
      { emoji: "📣", label: "Megaphone" },
      { emoji: "📯", label: "Postal Horn" },
      { emoji: "🔔", label: "Bell" },
      { emoji: "🔕", label: "Bell with Slash" },
      { emoji: "🎼", label: "Musical Score" },
      { emoji: "🎵", label: "Musical Note" },
      { emoji: "🎶", label: "Musical Notes" },
      { emoji: "🎙️", label: "Studio Microphone" },
      { emoji: "🎚️", label: "Level Slider" },
      { emoji: "🎛️", label: "Control Knobs" },
      { emoji: "🎤", label: "Microphone" },
      { emoji: "🎧", label: "Headphone" },
      { emoji: "📻", label: "Radio" },
      { emoji: "🎷", label: "Saxophone" },
      { emoji: "🎺", label: "Trumpet" },
      { emoji: "🪊", label: "Trombone" },
      { emoji: "🪗", label: "Accordion" },
      { emoji: "🎸", label: "Guitar" },
      { emoji: "🎹", label: "Musical Keyboard" },
      { emoji: "🎻", label: "Violin" },
      { emoji: "🪕", label: "Banjo" },
      { emoji: "🥁", label: "Drum" },
      { emoji: "🪘", label: "Long Drum" },
      { emoji: "🪇", label: "Maracas" },
      { emoji: "🪈", label: "Flute" },
      { emoji: "🪉", label: "Harp" },
      { emoji: "📱", label: "Mobile Phone" },
      { emoji: "📲", label: "Mobile Phone with Arrow" },
      { emoji: "☎️", label: "Telephone" },
      { emoji: "📞", label: "Telephone Receiver" },
      { emoji: "📟", label: "Pager" },
      { emoji: "📠", label: "Fax Machine" },
      { emoji: "🔋", label: "Battery" },
      { emoji: "🪫", label: "Low Battery" },
      { emoji: "🔌", label: "Electric Plug" },
      { emoji: "💻", label: "Laptop" },
      { emoji: "🖥️", label: "Desktop Computer" },
      { emoji: "🖨️", label: "Printer" },
      { emoji: "⌨️", label: "Keyboard" },
      { emoji: "🖱️", label: "Computer Mouse" },
      { emoji: "🖲️", label: "Trackball" },
      { emoji: "💽", label: "Computer Disk" },
      { emoji: "💾", label: "Floppy Disk" },
      { emoji: "💿", label: "Optical Disk" },
      { emoji: "📀", label: "Dvd" },
      { emoji: "🧮", label: "Abacus" },
      { emoji: "🎥", label: "Movie Camera" },
      { emoji: "🎞️", label: "Film Frames" },
      { emoji: "📽️", label: "Film Projector" },
      { emoji: "🎬", label: "Clapper Board" },
      { emoji: "📺", label: "Television" },
      { emoji: "📷", label: "Camera" },
      { emoji: "📸", label: "Camera with Flash" },
      { emoji: "📹", label: "Video Camera" },
      { emoji: "📼", label: "Videocassette" },
      { emoji: "🔍", label: "Magnifying Glass Tilted Left" },
      { emoji: "🔎", label: "Magnifying Glass Tilted Right" },
      { emoji: "🕯️", label: "Candle" },
      { emoji: "💡", label: "Light Bulb" },
      { emoji: "🔦", label: "Flashlight" },
      { emoji: "🏮", label: "Red Paper Lantern" },
      { emoji: "🪔", label: "Diya Lamp" },
      { emoji: "📔", label: "Notebook with Decorative Cover" },
      { emoji: "📕", label: "Closed Book" },
      { emoji: "📖", label: "Open Book" },
      { emoji: "📗", label: "Green Book" },
      { emoji: "📘", label: "Blue Book" },
      { emoji: "📙", label: "Orange Book" },
      { emoji: "📚", label: "Books" },
      { emoji: "📓", label: "Notebook" },
      { emoji: "📒", label: "Ledger" },
      { emoji: "📃", label: "Page with Curl" },
      { emoji: "📜", label: "Scroll" },
      { emoji: "📄", label: "Page Facing Up" },
      { emoji: "📰", label: "Newspaper" },
      { emoji: "🗞️", label: "Rolled-up Newspaper" },
      { emoji: "📑", label: "Bookmark Tabs" },
      { emoji: "🔖", label: "Bookmark" },
      { emoji: "🏷️", label: "Label" },
      { emoji: "🪙", label: "Coin" },
      { emoji: "💰", label: "Money Bag" },
      { emoji: "🪎", label: "Treasure Chest" },
      { emoji: "💴", label: "Yen Banknote" },
      { emoji: "💵", label: "Dollar Banknote" },
      { emoji: "💶", label: "Euro Banknote" },
      { emoji: "💷", label: "Pound Banknote" },
      { emoji: "💸", label: "Money with Wings" },
      { emoji: "💳", label: "Credit Card" },
      { emoji: "🧾", label: "Receipt" },
      { emoji: "💹", label: "Chart Increasing with Yen" },
    ],
  },
  {
    label: "Objects — Office, Tools & Household",
    options: [
      { emoji: "✉️", label: "Envelope" },
      { emoji: "📧", label: "E-mail" },
      { emoji: "📨", label: "Incoming Envelope" },
      { emoji: "📩", label: "Envelope with Arrow" },
      { emoji: "📤", label: "Outbox Tray" },
      { emoji: "📥", label: "Inbox Tray" },
      { emoji: "📦", label: "Package" },
      { emoji: "📫", label: "Closed Mailbox with Raised Flag" },
      { emoji: "📪", label: "Closed Mailbox with Lowered Flag" },
      { emoji: "📬", label: "Open Mailbox with Raised Flag" },
      { emoji: "📭", label: "Open Mailbox with Lowered Flag" },
      { emoji: "📮", label: "Postbox" },
      { emoji: "🗳️", label: "Ballot Box with Ballot" },
      { emoji: "✏️", label: "Pencil" },
      { emoji: "✒️", label: "Black Nib" },
      { emoji: "🖋️", label: "Fountain Pen" },
      { emoji: "🖊️", label: "Pen" },
      { emoji: "🖌️", label: "Paintbrush" },
      { emoji: "🖍️", label: "Crayon" },
      { emoji: "📝", label: "Memo" },
      { emoji: "🪌", label: "Eraser" },
      { emoji: "💼", label: "Briefcase" },
      { emoji: "📁", label: "File Folder" },
      { emoji: "📂", label: "Open File Folder" },
      { emoji: "🗂️", label: "Card Index Dividers" },
      { emoji: "📅", label: "Calendar" },
      { emoji: "📆", label: "Tear-off Calendar" },
      { emoji: "🗒️", label: "Spiral Notepad" },
      { emoji: "🗓️", label: "Spiral Calendar" },
      { emoji: "📇", label: "Card Index" },
      { emoji: "📈", label: "Chart Increasing" },
      { emoji: "📉", label: "Chart Decreasing" },
      { emoji: "📊", label: "Bar Chart" },
      { emoji: "📋", label: "Clipboard" },
      { emoji: "📌", label: "Pushpin" },
      { emoji: "📍", label: "Round Pushpin" },
      { emoji: "📎", label: "Paperclip" },
      { emoji: "🖇️", label: "Linked Paperclips" },
      { emoji: "📏", label: "Straight Ruler" },
      { emoji: "📐", label: "Triangular Ruler" },
      { emoji: "✂️", label: "Scissors" },
      { emoji: "🗃️", label: "Card File Box" },
      { emoji: "🗄️", label: "File Cabinet" },
      { emoji: "🗑️", label: "Wastebasket" },
      { emoji: "🔒", label: "Locked" },
      { emoji: "🔓", label: "Unlocked" },
      { emoji: "🔏", label: "Locked with Pen" },
      { emoji: "🔐", label: "Locked with Key" },
      { emoji: "🔑", label: "Key" },
      { emoji: "🗝️", label: "Old Key" },
      { emoji: "🪍", label: "Net with Handle" },
      { emoji: "🔨", label: "Hammer" },
      { emoji: "🪓", label: "Axe" },
      { emoji: "⛏️", label: "Pick" },
      { emoji: "⚒️", label: "Hammer and Pick" },
      { emoji: "🛠️", label: "Hammer and Wrench" },
      { emoji: "🗡️", label: "Dagger" },
      { emoji: "⚔️", label: "Crossed Swords" },
      { emoji: "💣", label: "Bomb" },
      { emoji: "🪃", label: "Boomerang" },
      { emoji: "🏹", label: "Bow and Arrow" },
      { emoji: "🛡️", label: "Shield" },
      { emoji: "🪚", label: "Carpentry Saw" },
      { emoji: "🔧", label: "Wrench" },
      { emoji: "🪛", label: "Screwdriver" },
      { emoji: "🔩", label: "Nut and Bolt" },
      { emoji: "⚙️", label: "Gear" },
      { emoji: "🗜️", label: "Clamp" },
      { emoji: "⚖️", label: "Balance Scale" },
      { emoji: "🦯", label: "White Cane" },
      { emoji: "🔗", label: "Link" },
      { emoji: "⛓️", label: "Chains" },
      { emoji: "🪝", label: "Hook" },
      { emoji: "🧰", label: "Toolbox" },
      { emoji: "🧲", label: "Magnet" },
      { emoji: "🪜", label: "Ladder" },
      { emoji: "🪏", label: "Shovel" },
      { emoji: "⚗️", label: "Alembic" },
      { emoji: "🧪", label: "Test Tube" },
      { emoji: "🧫", label: "Petri Dish" },
      { emoji: "🧬", label: "Dna" },
      { emoji: "🔬", label: "Microscope" },
      { emoji: "🔭", label: "Telescope" },
      { emoji: "📡", label: "Satellite Antenna" },
      { emoji: "💉", label: "Syringe" },
      { emoji: "🩸", label: "Drop of Blood" },
      { emoji: "💊", label: "Pill" },
      { emoji: "🩹", label: "Adhesive Bandage" },
      { emoji: "🩼", label: "Crutch" },
      { emoji: "🩺", label: "Stethoscope" },
      { emoji: "🩻", label: "X-ray" },
      { emoji: "🚪", label: "Door" },
      { emoji: "🛗", label: "Elevator" },
      { emoji: "🪞", label: "Mirror" },
      { emoji: "🪟", label: "Window" },
      { emoji: "🛏️", label: "Bed" },
      { emoji: "🛋️", label: "Couch and Lamp" },
      { emoji: "🪑", label: "Chair" },
      { emoji: "🚽", label: "Toilet" },
      { emoji: "🪠", label: "Plunger" },
      { emoji: "🚿", label: "Shower" },
      { emoji: "🛁", label: "Bathtub" },
      { emoji: "🪤", label: "Mouse Trap" },
      { emoji: "🪒", label: "Razor" },
      { emoji: "🧴", label: "Lotion Bottle" },
      { emoji: "🧷", label: "Safety Pin" },
      { emoji: "🧹", label: "Broom" },
      { emoji: "🧺", label: "Basket" },
      { emoji: "🧻", label: "Roll of Paper" },
      { emoji: "🪣", label: "Bucket" },
      { emoji: "🧼", label: "Soap" },
      { emoji: "🫧", label: "Bubbles" },
      { emoji: "🪥", label: "Toothbrush" },
      { emoji: "🧽", label: "Sponge" },
      { emoji: "🧯", label: "Fire Extinguisher" },
      { emoji: "🛒", label: "Shopping Cart" },
      { emoji: "🚬", label: "Cigarette" },
      { emoji: "⚰️", label: "Coffin" },
      { emoji: "🪦", label: "Headstone" },
      { emoji: "⚱️", label: "Funeral Urn" },
      { emoji: "🧿", label: "Nazar Amulet" },
      { emoji: "🪬", label: "Hamsa" },
      { emoji: "🗿", label: "Moai" },
      { emoji: "🪧", label: "Placard" },
      { emoji: "🪪", label: "Identification Card" },
    ],
  },
  {
    label: "Symbols — Signs, Arrows & Math",
    options: [
      { emoji: "🏧", label: "Atm Sign" },
      { emoji: "🚮", label: "Litter in Bin Sign" },
      { emoji: "🚰", label: "Potable Water" },
      { emoji: "♿", label: "Wheelchair Symbol" },
      { emoji: "🚹", label: "Men’s Room" },
      { emoji: "🚺", label: "Women’s Room" },
      { emoji: "🚻", label: "Restroom" },
      { emoji: "🚼", label: "Baby Symbol" },
      { emoji: "🚾", label: "Water Closet" },
      { emoji: "🛂", label: "Passport Control" },
      { emoji: "🛃", label: "Customs" },
      { emoji: "🛄", label: "Baggage Claim" },
      { emoji: "🛅", label: "Left Luggage" },
      { emoji: "⚠️", label: "Warning" },
      { emoji: "🚸", label: "Children Crossing" },
      { emoji: "⛔", label: "No Entry" },
      { emoji: "🚫", label: "Prohibited" },
      { emoji: "🚳", label: "No Bicycles" },
      { emoji: "🚭", label: "No Smoking" },
      { emoji: "🚯", label: "No Littering" },
      { emoji: "🚱", label: "Non-potable Water" },
      { emoji: "🚷", label: "No Pedestrians" },
      { emoji: "📵", label: "No Mobile Phones" },
      { emoji: "🔞", label: "No One Under Eighteen" },
      { emoji: "☢️", label: "Radioactive" },
      { emoji: "☣️", label: "Biohazard" },
      { emoji: "⬆️", label: "Up Arrow" },
      { emoji: "↗️", label: "Up-right Arrow" },
      { emoji: "➡️", label: "Right Arrow" },
      { emoji: "↘️", label: "Down-right Arrow" },
      { emoji: "⬇️", label: "Down Arrow" },
      { emoji: "↙️", label: "Down-left Arrow" },
      { emoji: "⬅️", label: "Left Arrow" },
      { emoji: "↖️", label: "Up-left Arrow" },
      { emoji: "↕️", label: "Up-down Arrow" },
      { emoji: "↔️", label: "Left-right Arrow" },
      { emoji: "↩️", label: "Right Arrow Curving Left" },
      { emoji: "↪️", label: "Left Arrow Curving Right" },
      { emoji: "⤴️", label: "Right Arrow Curving Up" },
      { emoji: "⤵️", label: "Right Arrow Curving Down" },
      { emoji: "🔃", label: "Clockwise Vertical Arrows" },
      { emoji: "🔄", label: "Counterclockwise Arrows Button" },
      { emoji: "🔙", label: "Back Arrow" },
      { emoji: "🔚", label: "End Arrow" },
      { emoji: "🔛", label: "On! Arrow" },
      { emoji: "🔜", label: "Soon Arrow" },
      { emoji: "🔝", label: "Top Arrow" },
      { emoji: "🛐", label: "Place of Worship" },
      { emoji: "⚛️", label: "Atom Symbol" },
      { emoji: "🕉️", label: "Om" },
      { emoji: "✡️", label: "Star of David" },
      { emoji: "☸️", label: "Wheel of Dharma" },
      { emoji: "☯️", label: "Yin Yang" },
      { emoji: "✝️", label: "Latin Cross" },
      { emoji: "☦️", label: "Orthodox Cross" },
      { emoji: "☪️", label: "Star and Crescent" },
      { emoji: "☮️", label: "Peace Symbol" },
      { emoji: "🕎", label: "Menorah" },
      { emoji: "🔯", label: "Dotted Six-pointed Star" },
      { emoji: "🪯", label: "Khanda" },
      { emoji: "♈", label: "Aries" },
      { emoji: "♉", label: "Taurus" },
      { emoji: "♊", label: "Gemini" },
      { emoji: "♋", label: "Cancer" },
      { emoji: "♌", label: "Leo" },
      { emoji: "♍", label: "Virgo" },
      { emoji: "♎", label: "Libra" },
      { emoji: "♏", label: "Scorpio" },
      { emoji: "♐", label: "Sagittarius" },
      { emoji: "♑", label: "Capricorn" },
      { emoji: "♒", label: "Aquarius" },
      { emoji: "♓", label: "Pisces" },
      { emoji: "⛎", label: "Ophiuchus" },
      { emoji: "🔀", label: "Shuffle Tracks Button" },
      { emoji: "🔁", label: "Repeat Button" },
      { emoji: "🔂", label: "Repeat Single Button" },
      { emoji: "▶️", label: "Play Button" },
      { emoji: "⏩", label: "Fast-forward Button" },
      { emoji: "⏭️", label: "Next Track Button" },
      { emoji: "⏯️", label: "Play or Pause Button" },
      { emoji: "◀️", label: "Reverse Button" },
      { emoji: "⏪", label: "Fast Reverse Button" },
      { emoji: "⏮️", label: "Last Track Button" },
      { emoji: "🔼", label: "Upwards Button" },
      { emoji: "⏫", label: "Fast Up Button" },
      { emoji: "🔽", label: "Downwards Button" },
      { emoji: "⏬", label: "Fast Down Button" },
      { emoji: "⏸️", label: "Pause Button" },
      { emoji: "⏹️", label: "Stop Button" },
      { emoji: "⏺️", label: "Record Button" },
      { emoji: "⏏️", label: "Eject Button" },
      { emoji: "🎦", label: "Cinema" },
      { emoji: "🔅", label: "Dim Button" },
      { emoji: "🔆", label: "Bright Button" },
      { emoji: "📶", label: "Antenna Bars" },
      { emoji: "🛜", label: "Wireless" },
      { emoji: "📳", label: "Vibration Mode" },
      { emoji: "📴", label: "Mobile Phone Off" },
      { emoji: "♀️", label: "Female Sign" },
      { emoji: "♂️", label: "Male Sign" },
      { emoji: "⚧️", label: "Transgender Symbol" },
      { emoji: "✖️", label: "Multiply" },
      { emoji: "➕", label: "Plus" },
      { emoji: "➖", label: "Minus" },
      { emoji: "➗", label: "Divide" },
      { emoji: "🟰", label: "Heavy Equals Sign" },
      { emoji: "♾️", label: "Infinity" },
    ],
  },
  {
    label: "Symbols — Punctuation & Shapes",
    options: [
      { emoji: "‼️", label: "Double Exclamation Mark" },
      { emoji: "⁉️", label: "Exclamation Question Mark" },
      { emoji: "❓", label: "Red Question Mark" },
      { emoji: "❔", label: "White Question Mark" },
      { emoji: "❕", label: "White Exclamation Mark" },
      { emoji: "❗", label: "Red Exclamation Mark" },
      { emoji: "〰️", label: "Wavy Dash" },
      { emoji: "💱", label: "Currency Exchange" },
      { emoji: "💲", label: "Heavy Dollar Sign" },
      { emoji: "⚕️", label: "Medical Symbol" },
      { emoji: "♻️", label: "Recycling Symbol" },
      { emoji: "⚜️", label: "Fleur-de-lis" },
      { emoji: "🔱", label: "Trident Emblem" },
      { emoji: "📛", label: "Name Badge" },
      { emoji: "🔰", label: "Japanese Symbol for Beginner" },
      { emoji: "⭕", label: "Hollow Red Circle" },
      { emoji: "✅", label: "Check Mark Button" },
      { emoji: "☑️", label: "Check Box with Check" },
      { emoji: "✔️", label: "Check Mark" },
      { emoji: "❌", label: "Cross Mark" },
      { emoji: "❎", label: "Cross Mark Button" },
      { emoji: "➰", label: "Curly Loop" },
      { emoji: "➿", label: "Double Curly Loop" },
      { emoji: "〽️", label: "Part Alternation Mark" },
      { emoji: "✳️", label: "Eight-spoked Asterisk" },
      { emoji: "✴️", label: "Eight-pointed Star" },
      { emoji: "❇️", label: "Sparkle" },
      { emoji: "©️", label: "Copyright" },
      { emoji: "®️", label: "Registered" },
      { emoji: "™️", label: "Trade Mark" },
      { emoji: "🫟", label: "Splatter" },
      { emoji: "🔟", label: "Keycap: 10" },
      { emoji: "🔠", label: "Input Latin Uppercase" },
      { emoji: "🔡", label: "Input Latin Lowercase" },
      { emoji: "🔢", label: "Input Numbers" },
      { emoji: "🔣", label: "Input Symbols" },
      { emoji: "🔤", label: "Input Latin Letters" },
      { emoji: "🅰️", label: "A Button (blood Type)" },
      { emoji: "🆎", label: "Ab Button (blood Type)" },
      { emoji: "🅱️", label: "B Button (blood Type)" },
      { emoji: "🆑", label: "Cl Button" },
      { emoji: "🆒", label: "Cool Button" },
      { emoji: "🆓", label: "Free Button" },
      { emoji: "ℹ️", label: "Information" },
      { emoji: "🆔", label: "Id Button" },
      { emoji: "Ⓜ️", label: "Circled M" },
      { emoji: "🆕", label: "New Button" },
      { emoji: "🆖", label: "Ng Button" },
      { emoji: "🅾️", label: "O Button (blood Type)" },
      { emoji: "🆗", label: "Ok Button" },
      { emoji: "🅿️", label: "P Button" },
      { emoji: "🆘", label: "Sos Button" },
      { emoji: "🆙", label: "Up! Button" },
      { emoji: "🆚", label: "Vs Button" },
      { emoji: "🈁", label: "Japanese “here” Button" },
      { emoji: "🈂️", label: "Japanese “service Charge” Button" },
      { emoji: "🈷️", label: "Japanese “monthly Amount” Button" },
      { emoji: "🈶", label: "Japanese “not Free of Charge” Button" },
      { emoji: "🈯", label: "Japanese “reserved” Button" },
      { emoji: "🉐", label: "Japanese “bargain” Button" },
      { emoji: "🈹", label: "Japanese “discount” Button" },
      { emoji: "🈚", label: "Japanese “free of Charge” Button" },
      { emoji: "🈲", label: "Japanese “prohibited” Button" },
      { emoji: "🉑", label: "Japanese “acceptable” Button" },
      { emoji: "🈸", label: "Japanese “application” Button" },
      { emoji: "🈴", label: "Japanese “passing Grade” Button" },
      { emoji: "🈳", label: "Japanese “vacancy” Button" },
      { emoji: "㊗️", label: "Japanese “congratulations” Button" },
      { emoji: "㊙️", label: "Japanese “secret” Button" },
      { emoji: "🈺", label: "Japanese “open for Business” Button" },
      { emoji: "🈵", label: "Japanese “no Vacancy” Button" },
      { emoji: "🔴", label: "Red Circle" },
      { emoji: "🟠", label: "Orange Circle" },
      { emoji: "🟡", label: "Yellow Circle" },
      { emoji: "🟢", label: "Green Circle" },
      { emoji: "🔵", label: "Blue Circle" },
      { emoji: "🟣", label: "Purple Circle" },
      { emoji: "🟤", label: "Brown Circle" },
      { emoji: "⚫", label: "Black Circle" },
      { emoji: "⚪", label: "White Circle" },
      { emoji: "🟥", label: "Red Square" },
      { emoji: "🟧", label: "Orange Square" },
      { emoji: "🟨", label: "Yellow Square" },
      { emoji: "🟩", label: "Green Square" },
      { emoji: "🟦", label: "Blue Square" },
      { emoji: "🟪", label: "Purple Square" },
      { emoji: "🟫", label: "Brown Square" },
      { emoji: "⬛", label: "Black Large Square" },
      { emoji: "⬜", label: "White Large Square" },
      { emoji: "◼️", label: "Black Medium Square" },
      { emoji: "◻️", label: "White Medium Square" },
      { emoji: "◾", label: "Black Medium-small Square" },
      { emoji: "◽", label: "White Medium-small Square" },
      { emoji: "▪️", label: "Black Small Square" },
      { emoji: "▫️", label: "White Small Square" },
      { emoji: "🔶", label: "Large Orange Diamond" },
      { emoji: "🔷", label: "Large Blue Diamond" },
      { emoji: "🔸", label: "Small Orange Diamond" },
      { emoji: "🔹", label: "Small Blue Diamond" },
      { emoji: "🔺", label: "Red Triangle Pointed Up" },
      { emoji: "🔻", label: "Red Triangle Pointed Down" },
      { emoji: "💠", label: "Diamond with a Dot" },
      { emoji: "🔘", label: "Radio Button" },
      { emoji: "🔳", label: "White Square Button" },
      { emoji: "🔲", label: "Black Square Button" },
    ],
  },
];
