import { o as coerceSecretRef } from "../../types.secrets-m6J7qPGz.js";
import { n as ensureAuthProfileStore } from "../../store-B6VhslyM.js";
import { n as listProfilesForProvider } from "../../profile-list-CXReKi2I.js";
import { f as resolveCopilotApiToken, o as DEFAULT_COPILOT_API_BASE_URL } from "../../provider-auth-BTiyooTa.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-DFz2vK68.js";
import { i as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-D4QQx-ls.js";
import "../../token-CNLxgouO.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-MzxA-PQX.js";
import { t as fetchCopilotUsage } from "../../usage-DiFPw20X.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
