import { i as OpenClawConfig } from "../../types.openclaw-DBDmmaVM.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-B8PNxvXK.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-DiB-YMdz.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Iwx-m7pc.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-Clghd6aI.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DA-emjB6.js";
import { t as ChannelMessageActionName } from "../../types.public-Cx-Og-oG.js";
import { n as PluginRuntime } from "../../types-BkonLdRT.js";
import { d as readRemoteMediaBuffer } from "../../fetch-kvWXMXkD.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-Dc9uVKJp.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DDZdT6ub.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BsLYUSD_.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-HvFp7SHM.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-DRSvuIYX.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-DeCAMmmi.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-fgMBlfpS.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-CgGH0e2-.js";
import { n as resolveWebhookPath } from "../../webhook-path-P9jz85Yx.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-krgJT8On.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-KMjFyoSF.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-CBUPz3wD.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-Dwtl_6Y4.js";
import { r as createChannelPairingController } from "../../channel-pairing-BWpp3F-L.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CwtMbR6o.js";
import { m as missingTargetError } from "../../channel-feedback-SpSar9m-.js";
import { t as extractToolSend } from "../../tool-send-BjN-UOmo.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-C68yI5Le.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-B597dvIT.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };