import { i as OpenClawConfig } from "../../types.openclaw-BdSNxnBz.js";
import { t as FallbackAttempt } from "../../model-fallback.types-D-yOuaC4.js";
import { s as AuthProfileStore } from "../../types-6eKuwe7u.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-BS7J5paV.js";
import { t as ImageGenerationProviderPlugin } from "../../types-ItMBrbf4.js";
import { n as createSubsystemLogger } from "../../subsystem-CVkBUUYw.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-DQCUfNup.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-B6F9hBfq.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-6Ty263Tj.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core--WikbKMa.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-DYum6be2.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-C-XfClZC.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-CULlqOxg.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };