import type { TemplateResult } from "lit";
import { githubMark } from "./github-mark.ts";
import { iconData, type IconName } from "./icon-data.ts";
import { renderIconData } from "./icon-lit.ts";
import { toolIcons } from "./icons-tools.ts";

export type { IconName } from "./icon-data.ts";

export const icons = {
  github: githubMark,
  repeat: renderIconData(iconData.repeat),
  layers: renderIconData(iconData.layers),
  messageCircle: renderIconData(iconData.messageCircle),
  messageSquare: renderIconData(iconData.messageSquare),
  messageSquarePlus: renderIconData(iconData.messageSquarePlus),
  messageCircleOff: renderIconData(iconData.messageCircleOff),
  layoutGrid: renderIconData(iconData.layoutGrid),
  barChart: renderIconData(iconData.barChart),
  layoutDashboard: renderIconData(iconData.layoutDashboard),
  coins: renderIconData(iconData.coins),
  activity: renderIconData(iconData.activity),
  clock: renderIconData(iconData.clock),
  circleX: renderIconData(iconData.circleX),
  arrowLeftRight: renderIconData(iconData.arrowLeftRight),
  arrowUpRight: renderIconData(iconData.arrowUpRight),
  link: renderIconData(iconData.link),
  radio: renderIconData(iconData.radio),
  fileText: renderIconData(iconData.fileText),
  file: renderIconData(iconData.file),
  fileDiff: renderIconData(iconData.fileDiff),
  diff: renderIconData(iconData.diff),
  braces: renderIconData(iconData.braces),
  mail: renderIconData(iconData.mail),
  outbox: renderIconData(iconData.outbox),
  inbox: renderIconData(iconData.inbox),
  star: renderIconData(iconData.star),
  wandSparkles: renderIconData(iconData.wandSparkles),
  chrome: renderIconData(iconData.chrome),
  panelsTopLeft: renderIconData(iconData.panelsTopLeft),
  box: renderIconData(iconData.box),
  music: renderIconData(iconData.music),
  asterisk: renderIconData(iconData.asterisk),
  zap: renderIconData(iconData.zap),
  monitor: renderIconData(iconData.monitor),
  monitorSmartphone: renderIconData(iconData.monitorSmartphone),
  server: renderIconData(iconData.server),
  sun: renderIconData(iconData.sun),
  moon: renderIconData(iconData.moon),
  settings: renderIconData(iconData.settings),
  bug: renderIconData(iconData.bug),
  scrollText: renderIconData(iconData.scrollText),
  folder: renderIconData(iconData.folder),
  kanban: renderIconData(iconData.kanban),
  bot: renderIconData(iconData.bot),
  userPlus: renderIconData(iconData.userPlus),
  users: renderIconData(iconData.users),
  shieldQuestion: renderIconData(iconData.shieldQuestion),
  shield: renderIconData(iconData.shield),
  shieldEllipsis: renderIconData(iconData.shieldEllipsis),
  shieldLock: renderIconData(iconData.shieldLock),
  shieldCog: renderIconData(iconData.shieldCog),
  shieldAlert: renderIconData(iconData.shieldAlert),
  menu: renderIconData(iconData.menu),
  x: renderIconData(iconData.x),
  check: renderIconData(iconData.check),
  info: renderIconData(iconData.info),
  square: renderIconData(iconData.square),
  play: renderIconData(iconData.play),
  pause: renderIconData(iconData.pause),
  target: renderIconData(iconData.target),
  switchCamera: renderIconData(iconData.switchCamera),
  archive: renderIconData(iconData.archive),
  archiveRestore: renderIconData(iconData.archiveRestore),
  alertTriangle: renderIconData(iconData.alertTriangle),
  globeOff: renderIconData(iconData.globeOff),
  hand: renderIconData(iconData.hand),
  key: renderIconData(iconData.key),
  flag: renderIconData(iconData.flag),
  lock: renderIconData(iconData.lock),
  pencil: renderIconData(iconData.pencil),
  pipette: renderIconData(iconData.pipette),
  pencilSparkles: renderIconData(iconData.pencilSparkles),
  layoutComfortable: renderIconData(iconData.layoutComfortable),
  layoutCompact: renderIconData(iconData.layoutCompact),
  list: renderIconData(iconData.list),
  listFilter: renderIconData(iconData.listFilter),
  gripVertical: renderIconData(iconData.gripVertical),
  arrowDown: renderIconData(iconData.arrowDown),
  arrowUp: renderIconData(iconData.arrowUp),
  audioLines: renderIconData(iconData.audioLines),
  chevronUp: renderIconData(iconData.chevronUp),
  chevronsUpDown: renderIconData(iconData.chevronsUpDown),
  arrowRight: renderIconData(iconData.arrowRight),
  arrowLeft: renderIconData(iconData.arrowLeft),
  cornerDownLeft: renderIconData(iconData.cornerDownLeft),
  cornerUpLeft: renderIconData(iconData.cornerUpLeft),
  cornerDownRight: renderIconData(iconData.cornerDownRight),
  copy: renderIconData(iconData.copy),
  search: renderIconData(iconData.search),
  wrapText: renderIconData(iconData.wrapText),
  brain: renderIconData(iconData.brain),
  book: renderIconData(iconData.book),
  loader: renderIconData(iconData.loader),
  calendarClock: renderIconData(iconData.calendarClock),
  listChecks: renderIconData(iconData.listChecks),
  moreHorizontal: renderIconData(iconData.moreHorizontal),
  ...toolIcons,
} as const;

export function icon(name: IconName): TemplateResult {
  return icons[name];
}
