// Only generated KaTeX output receives this allowlist; authored HTML stays escaped.
const markdownMathTags = [
  "math",
  "annotation",
  "menclose",
  "merror",
  "mfrac",
  "mi",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mroot",
  "mrow",
  "ms",
  "mspace",
  "msqrt",
  "mstyle",
  "msub",
  "msup",
  "msubsup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "semantics",
  "svg",
  "path",
  "line",
  "use",
];
const markdownMathAttrs = [
  "aria-hidden",
  "aria-level",
  "xmlns",
  // KaTeX MathML carries semantic variants and barless binomial fractions.
  "mathvariant",
  "linethickness",
  "fence",
  "viewBox",
  "width",
  "height",
  "x",
  "y",
  "d",
  "fill",
  "stroke",
  "stroke-width",
  "focusable",
  "preserveAspectRatio",
  "style",
];

export const markdownMathSanitizer = {
  tags: markdownMathTags,
  attrs: markdownMathAttrs,
};
