import { p as isBlockedHostnameOrIp } from "../../ssrf-HuuPklwv.js";
import { o as SessionEntry } from "../../types-CWcVAdid.js";
import { C as OpenClawPluginApi } from "../../types-_HTuWOFH.js";
import { _ as sleep } from "../../utils-CW0tmUjp.js";
import { r as GatewayRequestHandlerOptions } from "../../types-Cb8yfRzl.js";
import { t as definePluginEntry } from "../../plugin-entry-DX0V8NBJ.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-k1fsMnaH.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-BBa-yuRa.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };