name: SmartAgentNeo
options:
  bundleIdPrefix: ai.smart-agent-neo
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  SmartAgentNeoKit:
    path: ../shared/SmartAgentNeoKit
  Swabble:
    path: ../../Swabble

schemes:
  SmartAgentNeo:
    shared: true
    build:
      targets:
        SmartAgentNeo: all
    test:
      targets:
        - SmartAgentNeoTests

targets:
  SmartAgentNeo:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: SmartAgentNeoKit
      - package: SmartAgentNeoKit
        product: SmartAgentNeoChatUI
      - package: SmartAgentNeoKit
        product: SmartAgentNeoProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: ai.smartagentneo.ios
        PROVISIONING_PROFILE_SPECIFIER: "ai.smartagentneo.ios Development"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: SmartAgentNeo
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "2026.2.16"
        CFBundleVersion: "20260216"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: SmartAgentNeo discovers and connects to your SmartAgentNeo gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _smart-agent-neo-gw._tcp
        NSCameraUsageDescription: SmartAgentNeo can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: SmartAgentNeo uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: SmartAgentNeo can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: SmartAgentNeo needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: SmartAgentNeo uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  SmartAgentNeoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: SmartAgentNeo
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.smartagentneo.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SmartAgentNeo.app/SmartAgentNeo"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: SmartAgentNeoTests
        CFBundleShortVersionString: "2026.2.16"
        CFBundleVersion: "20260216"
