import { i as formatErrorMessage } from "../errors-ixwfrboQ.js";
import { p as resolveUserPath } from "../utils-CpmNtyoq.js";
import { n as VERSION } from "../version-DmRkhYua.js";
import { v as resolveSessionAgentIds } from "../agent-scope-wct0i6B_.js";
import { a as isSubagentSessionKey } from "../session-key-utils-CJRKuBJA.js";
import { a as resolveAgentDir, s as resolveDefaultAgentDir } from "../agent-scope-config-BuKrT2wm.js";
import { n as resolveEmbeddedAgentRuntime } from "../runtime-BRQxtJYr.js";
import { n as disposeRegisteredAgentHarnesses } from "../registry-Ds-bZfDD.js";
import { a as resolveContextEngineOwnerPluginId } from "../registry-Q0MBSM-3.js";
import { d as resetAgentEventsForTest, i as emitAgentEvent, l as onAgentEvent } from "../agent-events-DkpIHRmj.js";
import { c as appendSessionTranscriptMessage } from "../transcript-DCXkPRXp.js";
import { t as emitSessionTranscriptUpdate } from "../transcript-events-Bk5onV1S.js";
import { d as resolveSessionWriteLockOptions, i as acquireSessionWriteLock, l as resolveSessionWriteLockAcquireTimeoutMs } from "../session-write-lock-BXScA6gP.js";
import { u as resolveModelAuthMode } from "../model-auth-CKoZpOSv.js";
import { m as setActiveEmbeddedRun, n as abortEmbeddedPiRun, p as resolveActiveEmbeddedRunSessionId, r as clearActiveEmbeddedRun } from "../runs-F2-LpDOb.js";
import { o as normalizeUsage } from "../usage-tvgl9mFS.js";
import { p as buildAgentHookContextChannelFields } from "../attempt.prompt-helpers-BMiLITPy.js";
import { a as resolveBootstrapContextForRun } from "../bootstrap-files-CtDBdSmK.js";
import { a as hasBeforeToolCallPolicy, c as isToolWrappedWithBeforeToolCallHook, f as wrapToolWithBeforeToolCallHook, l as runBeforeToolCallHook, u as setBeforeToolCallDiagnosticsEnabled } from "../pi-tools.before-tool-call-Kf_EY49N.js";
import { t as callGatewayTool } from "../gateway-BBQ1yjrG.js";
import { t as createOpenClawCodingTools } from "../pi-tools-CpVvjNDo.js";
import { S as supportsModelTools, a as logAgentRuntimeToolDiagnostics, b as isMessagingTool, c as normalizeProviderToolSchemas, f as extractToolResultMediaArtifact, l as runAgentCleanupStep, m as filterToolResultMediaUrls, n as createAgentToolResultMiddlewareRunner, o as normalizeAgentRuntimeTools, t as buildEmbeddedAttemptToolRunContext, x as isMessagingToolSendAction } from "../attempt.tool-run-context-BQAUaZ1k.js";
import { o as normalizeHeartbeatToolResponse, t as HEARTBEAT_RESPONSE_TOOL_NAME } from "../heartbeat-tool-response-BgIvZCLr.js";
import { N as formatToolAggregate } from "../channel-streaming-7kVLi4-h.js";
import { t as log } from "../logger-BOPLULTq.js";
import { a as selectDefaultNodeFromList, i as resolveNodeIdFromList, t as listNodes } from "../nodes-utils-C-IBHB9X.js";
import { c as hasSandboxBindReadonlyHostShadows, l as resolveWritableSandboxBindHostRoots, o as resolveSandboxContext, s as hasSandboxBindContainerPathAliases } from "../sandbox-D8f42a_o.js";
import { a as finalizeHarnessContextEngineTurn, i as buildHarnessContextEngineRuntimeContextFromUsage, n as bootstrapHarnessContextEngine, o as isActiveHarnessContextEngine, r as buildHarnessContextEngineRuntimeContext, s as runHarnessContextEngineMaintenance, t as assembleHarnessContextEngine } from "../context-engine-lifecycle-BLsqyVuM.js";
import { r as resolveAttemptSpawnWorkspaceDir } from "../attempt.thread-helpers-BGwyQn0d.js";
import { t as classifyEmbeddedPiRunResultForModelFallback } from "../result-fallback-classifier-BYT_4z8T.js";
import { r as buildAgentRuntimePlan } from "../build-5MDGHiXs.js";
import { i as runAgentHarnessLlmOutputHook, n as runAgentHarnessBeforeAgentFinalizeHook, r as runAgentHarnessLlmInputHook, t as runAgentHarnessAgentEndHook } from "../lifecycle-hook-helpers-Da8MMMak.js";
import { t as resolveOpenClawAgentDir } from "../agent-dir-compat-JiepgBbc.js";
import { t as formatApprovalDisplayPath } from "../approval-display-paths-7aHD6bTl.js";
import { a as loadCodexBundleMcpThreadConfig, c as resolveAgentHarnessBeforePromptBuildResult, i as inferToolMetaFromArgs, l as runAgentHarnessAfterCompactionHook, n as classifyAgentHarnessTerminalOutcome, o as queueAgentHarnessMessage, r as formatToolProgressOutput, s as createCodexAppServerToolResultExtensionRunner, t as TOOL_PROGRESS_OUTPUT_MAX_CHARS, u as runAgentHarnessBeforeCompactionHook } from "../agent-harness-runtime-0FdirvlW.js";
import { a as registerNativeHookRelay, c as runAgentHarnessAfterToolCallHook, l as runAgentHarnessBeforeMessageWriteHook, n as hasNativeHookRelayInvocation, r as invokeNativeHookRelay, s as testing, t as buildNativeHookRelayCommand } from "../native-hook-relay-xHV-r-4n.js";
export { HEARTBEAT_RESPONSE_TOOL_NAME, VERSION as OPENCLAW_VERSION, TOOL_PROGRESS_OUTPUT_MAX_CHARS, abortEmbeddedPiRun as abortAgentHarnessRun, acquireSessionWriteLock, appendSessionTranscriptMessage, assembleHarnessContextEngine, bootstrapHarnessContextEngine, buildAgentHookContextChannelFields, buildAgentRuntimePlan, buildEmbeddedAttemptToolRunContext, buildHarnessContextEngineRuntimeContext, buildHarnessContextEngineRuntimeContextFromUsage, buildNativeHookRelayCommand, callGatewayTool, classifyAgentHarnessTerminalOutcome, classifyEmbeddedPiRunResultForModelFallback, clearActiveEmbeddedRun, createAgentToolResultMiddlewareRunner, createCodexAppServerToolResultExtensionRunner, createOpenClawCodingTools, disposeRegisteredAgentHarnesses, log as embeddedAgentLog, emitAgentEvent, emitSessionTranscriptUpdate, extractToolResultMediaArtifact, filterToolResultMediaUrls, finalizeHarnessContextEngineTurn, formatApprovalDisplayPath, formatErrorMessage, formatToolAggregate, formatToolProgressOutput, hasBeforeToolCallPolicy, hasNativeHookRelayInvocation, hasSandboxBindContainerPathAliases, hasSandboxBindReadonlyHostShadows, inferToolMetaFromArgs, invokeNativeHookRelay, isActiveHarnessContextEngine, isMessagingTool, isMessagingToolSendAction, isSubagentSessionKey, isToolWrappedWithBeforeToolCallHook, listNodes, loadCodexBundleMcpThreadConfig, logAgentRuntimeToolDiagnostics, testing as nativeHookRelayTesting, normalizeAgentRuntimeTools, normalizeHeartbeatToolResponse, normalizeProviderToolSchemas, normalizeUsage, onAgentEvent, queueAgentHarnessMessage, registerNativeHookRelay, resetAgentEventsForTest, resolveActiveEmbeddedRunSessionId, resolveAgentDir, resolveAgentHarnessBeforePromptBuildResult, resolveAttemptSpawnWorkspaceDir, resolveBootstrapContextForRun, resolveContextEngineOwnerPluginId, resolveDefaultAgentDir, resolveEmbeddedAgentRuntime, resolveModelAuthMode, resolveNodeIdFromList, resolveOpenClawAgentDir, resolveSandboxContext, resolveSessionAgentIds, resolveSessionWriteLockAcquireTimeoutMs, resolveSessionWriteLockOptions, resolveUserPath, resolveWritableSandboxBindHostRoots, runAgentCleanupStep, runAgentHarnessAfterCompactionHook, runAgentHarnessAfterToolCallHook, runAgentHarnessAgentEndHook, runAgentHarnessBeforeAgentFinalizeHook, runAgentHarnessBeforeCompactionHook, runAgentHarnessBeforeMessageWriteHook, runAgentHarnessLlmInputHook, runAgentHarnessLlmOutputHook, runBeforeToolCallHook, runHarnessContextEngineMaintenance, selectDefaultNodeFromList, setActiveEmbeddedRun, setBeforeToolCallDiagnosticsEnabled, supportsModelTools, wrapToolWithBeforeToolCallHook };
