import { p as isBlockedHostnameOrIp } from "../../ssrf-CMKWbO56.js";
import { o as SessionEntry } from "../../types-DkFheG7a.js";
import { C as OpenClawPluginApi } from "../../types-Bb8qdnX4.js";
import { _ as sleep } from "../../utils-D4sGGnmQ.js";
import { r as GatewayRequestHandlerOptions } from "../../types-D0jreYRC.js";
import { t as definePluginEntry } from "../../plugin-entry-qX4ndZRP.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BzbwrEoM.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-Dui9Huid.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-CJwccV5s.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };