import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-B32J-iNN.js";
import { t as getChatChannelMeta } from "../../chat-meta-Btw-4ZkB.js";
import { r as buildChannelConfigSchema } from "../../config-schema-CmARlg6A.js";
import { n as AcpRuntimeError } from "../../errors-BZ1JYsDB.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-Co446nPw.js";
import { r as resolvePollMaxSelections } from "../../polls-C-v11_tu.js";
import { t as clearAccountEntryFields } from "../../config-helpers-a_k3n5UT.js";
import { n as formatPairingApproveHint } from "../../helpers-CswdXPdi.js";
import { r as makeProxyFetch } from "../../proxy-fetch-CTbWb258.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-Dmp_cuMa.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-Ck6n8xcq.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-CasAXVT2.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DBTUnI0T.js";
import "../../channel-core-DkTG-ENq.js";
import { t as resolveTelegramToken } from "../../token-DtBUs3HB.js";
import "../../acp-runtime-BpBbLKI4.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-C9w9gv4K.js";
import "../../channel-plugin-common-B3iIlJYf.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-CkYd4QGd.js";
import "../../channel-status-Bsp7cc4O.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-DLot5wXA.js";
import "../../channel-actions-BBYevPTQ.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-6OJfU9VW2.js";
import { n as setTelegramRuntime } from "../../runtime-CgUUiBzP.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-B6kdtLDb.js";
import "../../config-api-Bv9hJODP.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-DIp--jsG.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-B8RUJeZA.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-BQ1uDKbt.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-Ds4ydsWS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
