/**
 * Revenue Engine
 *
 * Tracks real money generated BY the agents running the business.
 * This is the P&L engine — revenue in, expenses out, net income tracked.
 *
 * Revenue comes from:
 * - Sales agents closing deals and collecting payments
 * - Support agents upselling or retaining customers
 * - Content agents driving ad revenue or affiliate commissions
 * - Service agents delivering billable work
 *
 * The Master Agent uses this to report on business performance,
 * set goals, and optimize agent deployment for maximum revenue.
 */

import crypto from "node:crypto";
import type { OrgId } from "../tenants/types.js";
import type {
	Client,
	Deal,
	Invoice,
	InvoiceLineItem,
	RevenueEvent,
	RevenueGoal,
	RevenueSource,
	RevenueSummary,
} from "./types.js";

// ── In-Memory Stores ─────────────────────────────────────────────────────────

const revenueLog: RevenueEvent[] = [];
const clientStore = new Map<string, Client>();
const invoiceStore = new Map<string, Invoice>();
const dealStore = new Map<string, Deal>();
const goalStore = new Map<string, RevenueGoal>();

// ── Record Revenue ───────────────────────────────────────────────────────────

/**
 * Record a revenue event — real money earned by an agent.
 *
 * Called when:
 * - A Stripe payment succeeds for a client invoice
 * - An agent reports a closed deal
 * - A subscription payment comes in
 * - An affiliate commission is tracked
 */
export function recordRevenue(params: {
	orgId: OrgId;
	agentId: string;
	source: RevenueSource;
	amountCents: number;
	currency?: string;
	payer: string;
	description: string;
	externalRef?: string;
	entityId?: string;
	metadata?: Record<string, string>;
}): RevenueEvent {
	const event: RevenueEvent = {
		id: `rev_${crypto.randomBytes(12).toString("hex")}`,
		orgId: params.orgId,
		entityId: params.entityId,
		agentId: params.agentId,
		source: params.source,
		amountCents: params.amountCents,
		currency: params.currency ?? "usd",
		payer: params.payer,
		description: params.description,
		externalRef: params.externalRef,
		metadata: params.metadata ?? {},
		timestamp: new Date(),
	};
	revenueLog.push(event);

	// Update client lifetime value if we have a client record
	updateClientRevenue(params.orgId, params.payer, params.amountCents);

	// Check goal progress
	checkGoalProgress(params.orgId);

	return event;
}

// ── Revenue Queries ──────────────────────────────────────────────────────────

export function getRevenueSummary(orgId: OrgId, periodDays: number = 30): RevenueSummary {
	const periodStart = new Date(Date.now() - periodDays * 86_400_000);
	const periodEnd = new Date();

	const periodEvents = revenueLog.filter(
		(e) => e.orgId === orgId && e.timestamp >= periodStart,
	);

	const bySource: Record<string, number> = {};
	const byAgent: Record<string, number> = {};
	let totalRevenueCents = 0;

	for (const e of periodEvents) {
		totalRevenueCents += e.amountCents;
		bySource[e.source] = (bySource[e.source] ?? 0) + e.amountCents;
		byAgent[e.agentId] = (byAgent[e.agentId] ?? 0) + e.amountCents;
	}

	// Expenses = platform credits consumed (agent run costs)
	// In production, pull from usage-meter
	const totalExpensesCents = 0; // Will be calculated from usage data

	return {
		orgId,
		periodStart,
		periodEnd,
		totalRevenueCents,
		totalExpensesCents,
		netIncomeCents: totalRevenueCents - totalExpensesCents,
		bySource,
		byAgent,
		transactionCount: periodEvents.length,
	};
}

export function getDailyRevenue(
	orgId: OrgId,
	days: number = 30,
): { date: string; revenueCents: number; transactions: number }[] {
	const result: { date: string; revenueCents: number; transactions: number }[] = [];
	const now = new Date();

	for (let i = days - 1; i >= 0; i--) {
		const day = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i);
		const dayEnd = new Date(day.getTime() + 86_400_000);
		const dayStr = day.toISOString().slice(0, 10);

		const dayEvents = revenueLog.filter(
			(e) => e.orgId === orgId && e.timestamp >= day && e.timestamp < dayEnd,
		);

		result.push({
			date: dayStr,
			revenueCents: dayEvents.reduce((sum, e) => sum + e.amountCents, 0),
			transactions: dayEvents.length,
		});
	}

	return result;
}

export function getAgentRevenue(agentId: string): {
	totalCents: number;
	last30DaysCents: number;
	transactionCount: number;
} {
	const agentEvents = revenueLog.filter((e) => e.agentId === agentId);
	const thirtyDaysAgo = new Date(Date.now() - 30 * 86_400_000);

	return {
		totalCents: agentEvents.reduce((sum, e) => sum + e.amountCents, 0),
		last30DaysCents: agentEvents
			.filter((e) => e.timestamp >= thirtyDaysAgo)
			.reduce((sum, e) => sum + e.amountCents, 0),
		transactionCount: agentEvents.length,
	};
}

// ── Client Management ────────────────────────────────────────────────────────

export function createClient(params: {
	orgId: OrgId;
	name: string;
	email: string;
	company?: string;
	source: string;
	acquiredByAgentId?: string;
	tags?: string[];
}): Client {
	const client: Client = {
		id: `client_${crypto.randomBytes(12).toString("hex")}`,
		orgId: params.orgId,
		name: params.name,
		email: params.email,
		company: params.company,
		source: params.source,
		acquiredByAgentId: params.acquiredByAgentId,
		lifetimeValueCents: 0,
		status: "lead",
		tags: params.tags ?? [],
		metadata: {},
		createdAt: new Date(),
		lastInteractionAt: new Date(),
	};
	clientStore.set(client.id, client);
	return client;
}

export function listClients(orgId: OrgId): Client[] {
	return [...clientStore.values()].filter((c) => c.orgId === orgId);
}

export function getClient(clientId: string): Client | undefined {
	return clientStore.get(clientId);
}

export function updateClientStatus(clientId: string, status: Client["status"]): void {
	const client = clientStore.get(clientId);
	if (client) {
		client.status = status;
		client.lastInteractionAt = new Date();
	}
}

function updateClientRevenue(orgId: OrgId, payerIdentifier: string, amountCents: number): void {
	// Find client by name or email
	for (const client of clientStore.values()) {
		if (
			client.orgId === orgId &&
			(client.name === payerIdentifier || client.email === payerIdentifier)
		) {
			client.lifetimeValueCents += amountCents;
			client.lastInteractionAt = new Date();
			if (client.status === "lead" || client.status === "prospect") {
				client.status = "active";
			}
			break;
		}
	}
}

// ── Deal Pipeline ────────────────────────────────────────────────────────────

export function createDeal(params: {
	orgId: OrgId;
	clientId: string;
	agentId: string;
	name: string;
	valueCents: number;
	expectedCloseDate: Date;
}): Deal {
	const deal: Deal = {
		id: `deal_${crypto.randomBytes(12).toString("hex")}`,
		orgId: params.orgId,
		clientId: params.clientId,
		agentId: params.agentId,
		name: params.name,
		valueCents: params.valueCents,
		stage: "lead",
		probability: 10,
		expectedCloseDate: params.expectedCloseDate,
		notes: "",
		createdAt: new Date(),
		updatedAt: new Date(),
	};
	dealStore.set(deal.id, deal);
	return deal;
}

export function advanceDeal(
	dealId: string,
	stage: Deal["stage"],
	notes?: string,
): Deal | undefined {
	const deal = dealStore.get(dealId);
	if (!deal) return undefined;

	deal.stage = stage;
	deal.updatedAt = new Date();
	if (notes) deal.notes = notes;

	// Update probability based on stage
	const stageProbability: Record<string, number> = {
		lead: 10,
		qualified: 25,
		proposal: 50,
		negotiation: 75,
		closed_won: 100,
		closed_lost: 0,
	};
	deal.probability = stageProbability[stage] ?? 0;

	return deal;
}

export function listDeals(orgId: OrgId): Deal[] {
	return [...dealStore.values()].filter((d) => d.orgId === orgId);
}

export function getPipelineValue(orgId: OrgId): {
	totalValueCents: number;
	weightedValueCents: number;
	dealCount: number;
	byStage: Record<string, { count: number; valueCents: number }>;
} {
	const deals = listDeals(orgId).filter(
		(d) => d.stage !== "closed_won" && d.stage !== "closed_lost",
	);

	const byStage: Record<string, { count: number; valueCents: number }> = {};
	let totalValueCents = 0;
	let weightedValueCents = 0;

	for (const deal of deals) {
		totalValueCents += deal.valueCents;
		weightedValueCents += Math.round(deal.valueCents * (deal.probability / 100));

		if (!byStage[deal.stage]) {
			byStage[deal.stage] = { count: 0, valueCents: 0 };
		}
		byStage[deal.stage].count++;
		byStage[deal.stage].valueCents += deal.valueCents;
	}

	return { totalValueCents, weightedValueCents, dealCount: deals.length, byStage };
}

// ── Invoicing ────────────────────────────────────────────────────────────────

export function createInvoice(params: {
	orgId: OrgId;
	clientId: string;
	agentId: string;
	lineItems: InvoiceLineItem[];
	dueDate: Date;
	taxCents?: number;
}): Invoice {
	const subtotalCents = params.lineItems.reduce((sum, item) => sum + item.totalCents, 0);
	const taxCents = params.taxCents ?? 0;

	const invoice: Invoice = {
		id: `inv_${crypto.randomBytes(12).toString("hex")}`,
		orgId: params.orgId,
		clientId: params.clientId,
		agentId: params.agentId,
		lineItems: params.lineItems,
		subtotalCents,
		taxCents,
		totalCents: subtotalCents + taxCents,
		status: "draft",
		dueDate: params.dueDate,
		createdAt: new Date(),
	};
	invoiceStore.set(invoice.id, invoice);
	return invoice;
}

export function markInvoicePaid(invoiceId: string, stripeChargeId?: string): Invoice | undefined {
	const invoice = invoiceStore.get(invoiceId);
	if (!invoice) return undefined;

	invoice.status = "paid";
	invoice.paidAt = new Date();
	if (stripeChargeId) invoice.stripeInvoiceId = stripeChargeId;

	// Record as revenue
	const client = clientStore.get(invoice.clientId);
	recordRevenue({
		orgId: invoice.orgId,
		agentId: invoice.agentId,
		source: "invoice_paid",
		amountCents: invoice.totalCents,
		payer: client?.name ?? invoice.clientId,
		description: `Invoice ${invoice.id} paid`,
		externalRef: stripeChargeId,
	});

	return invoice;
}

export function listInvoices(orgId: OrgId): Invoice[] {
	return [...invoiceStore.values()].filter((inv) => inv.orgId === orgId);
}

// ── Revenue Goals ────────────────────────────────────────────────────────────

export function setRevenueGoal(params: {
	orgId: OrgId;
	targetAmountCents: number;
	period: RevenueGoal["period"];
}): RevenueGoal {
	const now = new Date();
	const endDate = getGoalEndDate(now, params.period);

	const goal: RevenueGoal = {
		id: `goal_${crypto.randomBytes(8).toString("hex")}`,
		orgId: params.orgId,
		targetAmountCents: params.targetAmountCents,
		currentAmountCents: 0,
		period: params.period,
		startDate: now,
		endDate,
		status: "on_track",
	};
	goalStore.set(goal.id, goal);
	return goal;
}

function getGoalEndDate(start: Date, period: RevenueGoal["period"]): Date {
	const end = new Date(start);
	switch (period) {
		case "daily":
			end.setDate(end.getDate() + 1);
			break;
		case "weekly":
			end.setDate(end.getDate() + 7);
			break;
		case "monthly":
			end.setMonth(end.getMonth() + 1);
			break;
		case "quarterly":
			end.setMonth(end.getMonth() + 3);
			break;
		case "annual":
			end.setFullYear(end.getFullYear() + 1);
			break;
	}
	return end;
}

function checkGoalProgress(orgId: OrgId): void {
	for (const goal of goalStore.values()) {
		if (goal.orgId !== orgId) continue;
		if (goal.endDate < new Date()) continue;

		const periodEvents = revenueLog.filter(
			(e) => e.orgId === orgId && e.timestamp >= goal.startDate && e.timestamp <= goal.endDate,
		);
		goal.currentAmountCents = periodEvents.reduce((sum, e) => sum + e.amountCents, 0);

		const elapsed = Date.now() - goal.startDate.getTime();
		const total = goal.endDate.getTime() - goal.startDate.getTime();
		const progressRatio = elapsed / total;
		const revenueRatio = goal.currentAmountCents / goal.targetAmountCents;

		if (revenueRatio >= 1) {
			goal.status = "achieved";
		} else if (revenueRatio >= progressRatio * 0.9) {
			goal.status = "on_track";
		} else if (revenueRatio >= progressRatio * 0.7) {
			goal.status = "behind";
		} else {
			goal.status = revenueRatio > progressRatio ? "ahead" : "behind";
		}
	}
}

export function getActiveGoals(orgId: OrgId): RevenueGoal[] {
	return [...goalStore.values()].filter(
		(g) => g.orgId === orgId && g.endDate >= new Date(),
	);
}

// ── Business Health Dashboard ────────────────────────────────────────────────

export function getBusinessHealth(orgId: OrgId): {
	revenue30d: number;
	revenue7d: number;
	revenueToday: number;
	activeClients: number;
	totalClients: number;
	openDeals: number;
	pipelineValue: number;
	unpaidInvoices: number;
	unpaidInvoiceValue: number;
	goals: RevenueGoal[];
	topAgent: { agentId: string; revenueCents: number } | null;
} {
	const now = new Date();
	const thirtyDaysAgo = new Date(now.getTime() - 30 * 86_400_000);
	const sevenDaysAgo = new Date(now.getTime() - 7 * 86_400_000);
	const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());

	const orgRevenue = revenueLog.filter((e) => e.orgId === orgId);

	const revenue30d = orgRevenue
		.filter((e) => e.timestamp >= thirtyDaysAgo)
		.reduce((sum, e) => sum + e.amountCents, 0);
	const revenue7d = orgRevenue
		.filter((e) => e.timestamp >= sevenDaysAgo)
		.reduce((sum, e) => sum + e.amountCents, 0);
	const revenueToday = orgRevenue
		.filter((e) => e.timestamp >= todayStart)
		.reduce((sum, e) => sum + e.amountCents, 0);

	const clients = listClients(orgId);
	const deals = listDeals(orgId);
	const openDeals = deals.filter((d) => d.stage !== "closed_won" && d.stage !== "closed_lost");
	const invoices = listInvoices(orgId);
	const unpaidInvoices = invoices.filter((inv) => inv.status !== "paid" && inv.status !== "void");

	// Find top revenue-generating agent
	const agentRevMap: Record<string, number> = {};
	for (const e of orgRevenue.filter((r) => r.timestamp >= thirtyDaysAgo)) {
		agentRevMap[e.agentId] = (agentRevMap[e.agentId] ?? 0) + e.amountCents;
	}
	const topAgentEntry = Object.entries(agentRevMap).sort((a, b) => b[1] - a[1])[0];

	return {
		revenue30d,
		revenue7d,
		revenueToday,
		activeClients: clients.filter((c) => c.status === "active").length,
		totalClients: clients.length,
		openDeals: openDeals.length,
		pipelineValue: openDeals.reduce((sum, d) => sum + d.valueCents, 0),
		unpaidInvoices: unpaidInvoices.length,
		unpaidInvoiceValue: unpaidInvoices.reduce((sum, inv) => sum + inv.totalCents, 0),
		goals: getActiveGoals(orgId),
		topAgent: topAgentEntry
			? { agentId: topAgentEntry[0], revenueCents: topAgentEntry[1] }
			: null,
	};
}
