// SafeOps adapter client generated by safeops.openclaw.skill v2.4.
import crypto from "node:crypto";

export class SafeOpsAdapterClient {
  constructor({
    adapterUrl = process.env.SAFEOPS_ADAPTER_URL || "http://127.0.0.1:8787",
    authToken = process.env.SAFEOPS_ADAPTER_TOKEN,
    timeoutMs = 5000,
  } = {}) {
    this.adapterUrl = adapterUrl;
    this.authToken = authToken;
    this.timeoutMs = timeoutMs;
  }

  async preflight(event) {
    if (!this.authToken) return this.deny("SafeOps token missing.");
    const payload = {
      contractVersion: "safeops.preflight.v1",
      nonce: event.nonce || crypto.randomUUID(),
      timestamp: event.timestamp || Date.now(),
      ...event,
    };

    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), this.timeoutMs);
      const response = await fetch(this.adapterUrl + "/v1/preflight", {
        method: "POST",
        headers: { "content-type": "application/json", authorization: "Bearer " + this.authToken },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });
      clearTimeout(timer);
      if (!response.ok) return this.deny("SafeOps adapter HTTP " + response.status);
      const body = await response.json();
      if (!["allow", "confirm", "deny"].includes(body.decision))
        return this.deny("Invalid SafeOps decision.");
      if (body.decision === "allow" && body.safeToExecute !== true)
        return this.deny("Invalid allow response.");
      if ((body.decision === "confirm" || body.decision === "deny") && body.safeToExecute !== false)
        return this.deny("Invalid blocked response.");
      return body;
    } catch (error) {
      return this.deny("SafeOps adapter unavailable: " + error.message);
    }
  }

  deny(reason) {
    return {
      ok: false,
      decision: "deny",
      safeToExecute: false,
      reason,
      findings: [{ id: "safeops.adapter.failure", severity: "high", decision: "deny", reason }],
    };
  }
}
