import { p as isBlockedHostnameOrIp } from "../../ssrf-BaAslmHK.js";
import { o as SessionEntry } from "../../types-D_FjxLJc.js";
import { C as OpenClawPluginApi } from "../../types-UTp4ves_.js";
import { _ as sleep } from "../../utils-ByGTa1-u.js";
import { r as GatewayRequestHandlerOptions } from "../../types-P4cYjGVC.js";
import { t as definePluginEntry } from "../../plugin-entry-Btsit5Jq.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-DG95ojWq.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-Yd94V1PE.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-BE7owwD3.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };