/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AcpParentStreamEvents {
  created_at: number;
  event_json: string;
  run_id: string;
  seq: number;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: Uint8Array;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: Uint8Array;
  embedding_dims: number | null;
  end_line: number;
  hash: string;
  id: string | null;
  model: string;
  path: string;
  session_id: string | null;
  source_key: string;
  source_kind: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  chunk_overlap: number;
  chunk_tokens: number;
  config_hash: string | null;
  fts_tokenizer: string;
  meta_key: string;
  model: string;
  provider: string;
  provider_key: string | null;
  schema_version: number;
  scope_hash: string;
  sources_json: string;
  updated_at: number;
  vector_dims: number | null;
}

export interface MemoryIndexSources {
  hash: string;
  mtime: number;
  path: string | null;
  session_id: string | null;
  size: number;
  source_key: string;
  source_kind: Generated<string>;
}

export interface RunArtifacts {
  blob: Uint8Array | null;
  created_at: number;
  kind: string;
  metadata_json: string;
  path: string;
  run_id: string;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface SessionEntries {
  entry_json: string;
  session_id: string;
  session_key: string;
  updated_at: number;
}

export interface Sessions {
  agent_harness_id: string | null;
  channel: string | null;
  chat_type: string | null;
  created_at: number;
  display_name: string | null;
  ended_at: number | null;
  model: string | null;
  model_provider: string | null;
  parent_session_key: string | null;
  session_id: string;
  session_key: string;
  spawned_by: string | null;
  started_at: number | null;
  status: string | null;
  updated_at: number;
}

export interface ToolArtifacts {
  artifact_id: string;
  blob: Uint8Array | null;
  created_at: number;
  kind: string;
  metadata_json: string;
  run_id: string;
}

export interface TrajectoryRuntimeEvents {
  created_at: number;
  event_id: Generated<number>;
  event_json: string;
  run_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEventIdentities {
  created_at: number;
  event_id: string;
  event_type: string | null;
  has_parent: Generated<number>;
  message_idempotency_key: string | null;
  parent_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEvents {
  created_at: number;
  event_json: string;
  seq: number;
  session_id: string;
}

export interface TranscriptSnapshots {
  created_at: number;
  event_count: number;
  metadata_json: string;
  reason: string;
  session_id: string;
  snapshot_id: string;
}

export interface VfsEntries {
  content_blob: Uint8Array | null;
  kind: string;
  metadata_json: string;
  namespace: string;
  path: string;
  updated_at: number;
}

export interface DB {
  acp_parent_stream_events: AcpParentStreamEvents;
  cache_entries: CacheEntries;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  run_artifacts: RunArtifacts;
  schema_meta: SchemaMeta;
  session_entries: SessionEntries;
  sessions: Sessions;
  tool_artifacts: ToolArtifacts;
  trajectory_runtime_events: TrajectoryRuntimeEvents;
  transcript_event_identities: TranscriptEventIdentities;
  transcript_events: TranscriptEvents;
  transcript_snapshots: TranscriptSnapshots;
  vfs_entries: VfsEntries;
}
