/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface Boxes {
  box_id: string;
  importance: number | null;
  label: string | null;
  last_active_seq: number | null;
  session_key: string;
  state: Generated<string>;
  summary: string | null;
  summary_embedding_ref: string | null;
  suppression_rollup: string | null;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string | null;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string | null;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface Spans {
  box_id: string | null;
  end_seq: number;
  noise_class: string | null;
  session_key: string;
  span_id: string;
  start_seq: number;
  topic: string | null;
}

export interface Turns {
  channel: string | null;
  content: string;
  content_hash: string;
  idempotency_key: string;
  noise_class: string | null;
  role: string;
  run_id: string | null;
  seq: number;
  session_key: string;
  ts: number;
}

export interface DB {
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  boxes: Boxes;
  cache_entries: CacheEntries;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  schema_meta: SchemaMeta;
  spans: Spans;
  turns: Turns;
}
