/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string | null;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string | null;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface SessionTranscriptSearchFts {
  agent_id: string | null;
  message_id: string | null;
  path: string | null;
  role: string | null;
  seq: string | null;
  session_id: string | null;
  session_key: string | null;
  text: string | null;
  timestamp_ms: string | null;
}

export interface SessionTranscriptSearchFtsConfig {
  k: string;
  v: string | null;
}

export interface SessionTranscriptSearchFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  c5: string | null;
  c6: string | null;
  c7: string | null;
  c8: string | null;
  id: Generated<number>;
}

export interface SessionTranscriptSearchFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface SessionTranscriptSearchFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface SessionTranscriptSearchFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface SessionTranscriptSearchSources {
  agent_id: string;
  mtime: number;
  path: string;
  session_id: string;
  session_key: string;
  size: number;
  updated_at: number;
}

export interface DB {
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  cache_entries: CacheEntries;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  schema_meta: SchemaMeta;
  session_transcript_search_fts: SessionTranscriptSearchFts;
  session_transcript_search_fts_config: SessionTranscriptSearchFtsConfig;
  session_transcript_search_fts_content: SessionTranscriptSearchFtsContent;
  session_transcript_search_fts_data: SessionTranscriptSearchFtsData;
  session_transcript_search_fts_docsize: SessionTranscriptSearchFtsDocsize;
  session_transcript_search_fts_idx: SessionTranscriptSearchFtsIdx;
  session_transcript_search_sources: SessionTranscriptSearchSources;
}
