import { i as OpenClawConfig } from "../../types.openclaw-BMMD0Ykw.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-CORfnj4x.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-MKouOaZh.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-B20n5Nn2.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-CgjRAtD6.js";
import { t as ChannelMessageActionName } from "../../types.public-ElAweHV2.js";
import { n as PluginRuntime } from "../../types-1xy7Ddy0.js";
import { d as readRemoteMediaBuffer } from "../../fetch-DvdLuYfK.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-DcpcJNSi.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-FWD3RwUr.js";
import { r as buildChannelConfigSchema } from "../../config-schema-3flc7X46.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-Dj1fWwLa.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-kJp1knXq.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-BcaDMq_4.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-XaE9rZY_.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-6qxpjEeb.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-B8DBiw1C.js";
import { n as resolveWebhookPath } from "../../webhook-path-Ck6dC8z8.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-B37bo0Va.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-CQvduBnk.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-2WNMcGUO.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BA2V2QYV.js";
import { r as createChannelPairingController } from "../../channel-pairing-DzZYd0qz.js";
import { t as chunkTextForOutbound } from "../../text-chunking-snSv-Jpe.js";
import { m as missingTargetError } from "../../channel-feedback-C75XR-jG.js";
import { t as extractToolSend } from "../../tool-send-D934_3WP.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-BBEr7WNT.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-DEgc1ahx.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };