import { p as isBlockedHostnameOrIp } from "../../ssrf-HuuPklwv.js";
import { o as SessionEntry } from "../../types-BQPM9qpo.js";
import { C as OpenClawPluginApi } from "../../types-CkHYPqDj.js";
import { _ as sleep } from "../../utils-CW0tmUjp.js";
import { r as GatewayRequestHandlerOptions } from "../../types-3i6VeDVA.js";
import { t as definePluginEntry } from "../../plugin-entry-BS7KEM0n.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-CiFRtOcK.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-BE7owwD3.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };