import { i as OpenClawConfig } from "../../types.openclaw-BYfkTL_f.js";
import { t as FallbackAttempt } from "../../model-fallback.types-lteinV-m.js";
import { s as AuthProfileStore } from "../../types-qAWrW0I9.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-WMMnQ4uO.js";
import { Jn as VideoGenerationProviderPlugin } from "../../types-Wr1dwNsu.js";
import { n as createSubsystemLogger } from "../../subsystem-d1VSDcdo.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BtMyhUBu.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-Bl8gVQve.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-D14SC8qu.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-ojF0HrxK.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-obWEFrLJ.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-C0IZaDGZ.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };