import { p as isBlockedHostnameOrIp } from "../../ssrf-D_7xmVo8.js";
import { o as SessionEntry } from "../../types-CGFl2KSE.js";
import { C as OpenClawPluginApi } from "../../types-CPAF_tyr.js";
import { _ as sleep } from "../../utils-DnMW-o0a.js";
import { r as GatewayRequestHandlerOptions } from "../../types-CbCkng-Z.js";
import { t as definePluginEntry } from "../../plugin-entry-DJiOR4Sg.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-HvFp7SHM.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-C8ZRegIs.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-CE8kF-5-.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };