#!/usr/bin/env bash
# Generated by docker-setup.sh
# Source this file to get the 'openclaw' command via Docker
#
# Usage:
#   openclaw <command>              # Uses default mode (OPENCLAW_USE_DOCKER)
#   openclaw --docker <command>     # Forces Docker usage
#   openclaw --no-docker <command>  # Forces native CLI usage
#
# Configuration:
#   OPENCLAW_USE_DOCKER=1           # Default to Docker (set in this file or your profile)
#   OPENCLAW_USE_DOCKER=0           # Default to native CLI

export OPENCLAW_DOCKER_PROJECT_DIR="__PROJECT_DIR__"
export OPENCLAW_USE_DOCKER="${OPENCLAW_USE_DOCKER:-__USE_DOCKER_DEFAULT__}"

openclaw() {
  local use_docker="$OPENCLAW_USE_DOCKER"
  local explicit_no_docker=0
  local args=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --docker)
        use_docker=1
        shift
        ;;
      --no-docker)
        use_docker=0
        explicit_no_docker=1
        shift
        ;;
      *)
        args+=("$1")
        shift
        ;;
    esac
  done

  if [[ "$use_docker" == "1" ]]; then
    docker compose -f "$OPENCLAW_DOCKER_PROJECT_DIR/docker-compose.yml" run --rm openclaw-cli "${args[@]}"
  elif type -P openclaw >/dev/null 2>&1; then
    # type -P finds only binaries, not shell functions
    command openclaw "${args[@]}"
  elif [[ "$explicit_no_docker" == "1" ]]; then
    echo "error: --no-docker specified but native openclaw CLI not found in PATH" >&2
    return 1
  else
    # Native not found, fall back to Docker
    docker compose -f "$OPENCLAW_DOCKER_PROJECT_DIR/docker-compose.yml" run --rm openclaw-cli "${args[@]}"
  fi
}
