#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ACTIVI_INSTALL_E2E_IMAGE:-${ACTIVI_INSTALL_E2E_IMAGE:-activi-install-e2e:local}}"
INSTALL_URL="${ACTIVI_INSTALL_URL:-${ACTIVI_INSTALL_URL:-https://activi.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ACTIVI_E2E_MODELS="${ACTIVI_E2E_MODELS:-${ACTIVI_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e ACTIVI_INSTALL_URL="$INSTALL_URL" \
  -e ACTIVI_INSTALL_TAG="${ACTIVI_INSTALL_TAG:-${ACTIVI_INSTALL_TAG:-latest}}" \
  -e ACTIVI_E2E_MODELS="$ACTIVI_E2E_MODELS" \
  -e ACTIVI_INSTALL_E2E_PREVIOUS="${ACTIVI_INSTALL_E2E_PREVIOUS:-${ACTIVI_INSTALL_E2E_PREVIOUS:-}}" \
  -e ACTIVI_INSTALL_E2E_SKIP_PREVIOUS="${ACTIVI_INSTALL_E2E_SKIP_PREVIOUS:-${ACTIVI_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
