export const CLI_WATCHDOG_MIN_TIMEOUT_MS = 1_000;
export const CLI_WATCHDOG_DEFAULT_OVERALL_POLICY = "fixed" as const;
export const CLI_WATCHDOG_DEFAULT_EXTEND_OVERALL_MAX_MULTIPLIER = 6;
export const CLI_WATCHDOG_DEFAULT_EXTEND_OVERALL_MAX_FLOOR_MS = 900_000;
export const CLI_WATCHDOG_DEFAULT_EVIDENCE_TAIL_LINES = 20;
export const CLI_WATCHDOG_DEFAULT_EVIDENCE_MAX_CHARS = 4_000;
export const CLI_CODEX_WATCHDOG_OVERALL_MAX_MS = 3_600_000;

export const CLI_FRESH_WATCHDOG_DEFAULTS = {
  noOutputTimeoutRatio: 0.8,
  minMs: 180_000,
  maxMs: 600_000,
} as const;

export const CLI_RESUME_WATCHDOG_DEFAULTS = {
  noOutputTimeoutRatio: 0.3,
  minMs: 60_000,
  maxMs: 180_000,
} as const;
