// Template bytes earlier releases seeded into workspaces.
import { sha256Hex } from "@openclaw/normalization-core/node-crypto";
import {
  DEFAULT_AGENTS_FILENAME,
  DEFAULT_IDENTITY_FILENAME,
  DEFAULT_SOUL_FILENAME,
} from "./workspace-bootstrap-policy.js";

// Previously shipped generated bytes, so a template edit does not make an
// untouched seeded file look user-customized and end a pending bootstrap.
const RETIRED_GENERATED_TEMPLATE_SHA256: Readonly<Record<string, readonly string[]>> = {
  [DEFAULT_AGENTS_FILENAME]: [
    "1e17784e422c0e47e44c5214d0b37092f7b378bb2d3746976032be3075203c88",
    "490fc2b32865dd310a3af1225a409ac5c942d89ba456167feb0fd95e2807aaff",
  ],
  [DEFAULT_SOUL_FILENAME]: ["4f9042f259b076e429d0f01ce39340030f47ea5b7f5befe306296c36baf1f60f"],
  [DEFAULT_IDENTITY_FILENAME]: ["59b223766c8dd978162044e333a684c72e22af753d1ba3dc3bff4b2d915c54e2"],
};

/** True when `content` is the exact bytes an earlier release seeded for `fileName`. */
export function isRetiredGeneratedTemplate(fileName: string, content: string): boolean {
  return RETIRED_GENERATED_TEMPLATE_SHA256[fileName]?.includes(sha256Hex(content)) === true;
}
