import { i as OpenClawConfig } from "../../types.openclaw-BdSNxnBz.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-BT4PMdXb.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-PkdSYxsi.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-BWIRLVzl.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-BDQOD1ST.js";
import { t as ChannelMessageActionName } from "../../types.public-D-nwYThg.js";
import { n as PluginRuntime } from "../../types-Czv_rpgT.js";
import { o as fetchRemoteMedia } from "../../fetch-p0_5FAeJ.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-Dic5PYOZ.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BxidFswl.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DvPswMZV.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BLITeikV.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-Bwp-c7Qu.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-B4avXJmy.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-Z6wyRouH.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-CuatdQ0f.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-D-asuK_S.js";
import { n as resolveWebhookPath } from "../../webhook-path-COHHjsdz.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-D2cbzMRA.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-D4UCyrhD.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-Du6AY8q-.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-Do8cZHwk.js";
import { r as createChannelPairingController } from "../../channel-pairing-DtYU0Asj.js";
import { t as chunkTextForOutbound } from "../../text-chunking-B-_JQAyH.js";
import { d as missingTargetError } from "../../channel-feedback-BdmDUdAV.js";
import { t as extractToolSend } from "../../tool-send-quP_Uq4z.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-BmNdKKf9.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-Bd_T_5sC.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchRemoteMedia, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };