import {
  EXPLICIT_FINAL_MESSAGE_TOOL_ONLY_DELIVERY_HINT,
  MESSAGE_TOOL_DELIVERY_HINTS,
  MESSAGE_TOOL_ONLY_DELIVERY_HINT,
} from "../../plugin-sdk/message-tool-delivery-hints.js";

export {
  EXPLICIT_FINAL_MESSAGE_TOOL_ONLY_DELIVERY_HINT,
  MESSAGE_TOOL_DELIVERY_HINTS,
  MESSAGE_TOOL_ONLY_DELIVERY_HINT,
};

export const ROOM_EVENT_DELIVERY_HINT = MESSAGE_TOOL_DELIVERY_HINTS[4];
