/**
 * README generated by `openclaw init --mode teammate`.
 */
import {
  TEAMMATE_SLA,
  type TeammateBackend,
  type TeammateProfilePaths,
} from "./profile.js";

export type TeammateReadmeParams = {
  backend: TeammateBackend;
  paths: TeammateProfilePaths;
};

export function renderTeammateReadme(params: TeammateReadmeParams): string {
  return `# OpenClaw teammate computer

${TEAMMATE_SLA}

This install is a **split**: Gateway can stay on a cheap VPS. Exec, browser,
and computer default to the long-lived worker, never the gateway host.

## Worker disk

| Path | Role |
| --- | --- |
| \`${params.paths.homeDir}\` | Durable workspace mounted at \`${params.paths.containerHome}\` |
| \`${params.paths.browserDir}\` | Browser profile (logins, cookies) |

Secrets use SecretRef only. Do not paste tokens into MEMORY.md or chat.

## Backend

Selected backend: \`${params.backend}\`

- \`docker\` (default): shared sandbox container, idle prune + heartbeat wake
- \`openshell\`: NVIDIA OpenShell sandbox plugin
- \`firecracker\`: same volume/secret/network story behind an explicit OCI runtime (Kata/Firecracker). Not the default.

## Check that exec is off the gateway

\`\`\`bash
openclaw sandbox explain --json
openclaw security audit
\`\`\`

\`exec.host\` must be \`sandbox\`. \`gatewayExec\` must be false.

## Upgrade from a Coolify gateway-is-the-computer install

1. Keep the existing Gateway process.
2. Run \`openclaw init --mode teammate\` against a **new** state dir (or pass \`--reset\`) so sandbox.mode=all is not applied silently to the live host-exec install.
3. Copy only the files you want onto the worker disk (\`${params.paths.homeDir}\`).
4. Re-point channels at this Gateway. Do not SSH into the live Coolify container to add \`--mode teammate\`.

## Next

Create named Bots in Control UI (Researcher, Writer, Ops). They share this
computer and keep separate conversation, memory, skills, and approval personality.
`;
}
