import { i as OpenClawConfig } from "../../types.openclaw-BYfkTL_f.js";
import { ft as GoogleChatAccountConfig, mt as GoogleChatConfig } from "../../types.channels-6kkMAKLf.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-CCrWEB5U.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Ds9BBXA3.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-C_h6wIm7.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DMG-czl3.js";
import { t as ChannelMessageActionName } from "../../types.public-BQzzyxCQ.js";
import { n as PluginRuntime } from "../../types-PzLD5nJ3.js";
import { d as readRemoteMediaBuffer } from "../../fetch-DrUbl1N9.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-D66j7qXL.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DfNGR-8N.js";
import { r as buildChannelConfigSchema } from "../../config-schema-DrNcI0sQ.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-BE7fLn0f.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-BxcWsy0h.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-fgMBlfpS.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-CX7oJcuR.js";
import { n as resolveWebhookPath } from "../../webhook-path-P9jz85Yx.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-krgJT8On.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-jC4ZJekM.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-DLhsAKHN.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BJQxjUSA.js";
import { r as createChannelPairingController } from "../../channel-pairing-Lu6dsx7G.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CwtMbR6o.js";
import { m as missingTargetError } from "../../channel-feedback-BsJPsOOh.js";
import { t as extractToolSend } from "../../tool-send-C_tcEsx2.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-CJTuutBM.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-D-1aySyE.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };