// MABOS Dashboard Mock Data
// Replace with real data via: window.MABOS_DATA = { ... }

window.MABOS_MOCK = {
  portfolio: {
    name: "Kingler Bercy Ventures",
    totalRevenue: 487200,
    totalBusinesses: 3,
    activeAgents: 27,
    openDecisions: 7,
    workforceUtilization: 0.78,
  },

  businesses: [
    {
      id: "techflow",
      name: "TechFlow",
      type: "saas",
      status: "active",
      health: 0.87,
      revenue: 284000,
      mrrGrowth: 0.12,
      mrr: 23667,
      agentCount: 9,
      activeGoals: 6,
      kpis: [
        { name: "MRR", value: 23667, target: 25000, unit: "$" },
        { name: "Churn", value: 3.2, target: 2.5, unit: "%", inverse: true },
        { name: "NPS", value: 62, target: 70, unit: "" },
        { name: "DAU", value: 1847, target: 2000, unit: "" },
        { name: "Trial→Paid", value: 18.5, target: 22, unit: "%" },
        { name: "Uptime", value: 99.97, target: 99.95, unit: "%" },
      ],
      agents: [
        { role: "CEO", status: "active", pendingTasks: 2, lastAction: "Strategic review complete" },
        { role: "CFO", status: "active", pendingTasks: 1, lastAction: "Q1 forecast updated" },
        {
          role: "COO",
          status: "active",
          pendingTasks: 3,
          lastAction: "Onboarding pipeline optimized",
        },
        {
          role: "CMO",
          status: "active",
          pendingTasks: 2,
          lastAction: "Content calendar Q2 published",
        },
        { role: "CTO", status: "active", pendingTasks: 4, lastAction: "v2.4 release deployed" },
        { role: "HR", status: "idle", pendingTasks: 0, lastAction: "Contractor reviews complete" },
        { role: "Legal", status: "idle", pendingTasks: 1, lastAction: "Terms of service updated" },
        {
          role: "Strategy",
          status: "active",
          pendingTasks: 1,
          lastAction: "Competitive analysis refresh",
        },
        {
          role: "Knowledge",
          status: "active",
          pendingTasks: 0,
          lastAction: "Case library indexed",
        },
      ],
      goals: [
        { name: "Reach $25K MRR", progress: 0.85, priority: 0.92, deadline: "2026-03-31" },
        { name: "Launch Enterprise Tier", progress: 0.45, priority: 0.88, deadline: "2026-04-15" },
        { name: "Reduce Churn to <3%", progress: 0.6, priority: 0.85, deadline: "2026-03-15" },
        { name: "SOC 2 Compliance", progress: 0.3, priority: 0.78, deadline: "2026-06-01" },
        { name: "API v2 Launch", progress: 0.7, priority: 0.75, deadline: "2026-03-01" },
        { name: "Hire 2 Senior Devs", progress: 0.25, priority: 0.65, deadline: "2026-04-01" },
      ],
      recentActivity: [
        {
          time: "2h ago",
          agent: "CTO",
          action: "Deployed v2.4.1 hotfix — resolved webhook timeout issue",
        },
        {
          time: "4h ago",
          agent: "CMO",
          action: "Published blog post: 'Why Teams Switch to TechFlow'",
        },
        {
          time: "6h ago",
          agent: "CFO",
          action: "Flagged: CAC trending up 15% MoM — recommend review",
        },
        {
          time: "1d ago",
          agent: "CEO",
          action: "Approved partnership proposal with DataSync Corp",
        },
        {
          time: "1d ago",
          agent: "COO",
          action: "Optimized onboarding flow — time-to-value down 22%",
        },
      ],
    },
    {
      id: "urbanmarket",
      name: "UrbanMarket",
      type: "ecommerce",
      status: "active",
      health: 0.72,
      revenue: 156000,
      mrrGrowth: -0.03,
      agentCount: 9,
      activeGoals: 5,
      kpis: [
        { name: "Revenue", value: 156000, target: 200000, unit: "$" },
        { name: "AOV", value: 67.4, target: 75, unit: "$" },
        { name: "Conv Rate", value: 2.8, target: 3.5, unit: "%" },
        { name: "Return Rate", value: 8.2, target: 5, unit: "%", inverse: true },
        { name: "CLV", value: 245, target: 300, unit: "$" },
        { name: "Inventory Turn", value: 6.3, target: 8, unit: "x" },
      ],
      agents: [
        { role: "CEO", status: "active", pendingTasks: 3, lastAction: "Q1 strategy pivot review" },
        {
          role: "CFO",
          status: "active",
          pendingTasks: 2,
          lastAction: "Margin analysis by category",
        },
        {
          role: "COO",
          status: "alert",
          pendingTasks: 5,
          lastAction: "Fulfillment delays — 3PL escalation",
        },
        {
          role: "CMO",
          status: "active",
          pendingTasks: 2,
          lastAction: "Instagram campaign launched",
        },
        {
          role: "CTO",
          status: "idle",
          pendingTasks: 1,
          lastAction: "Shopify theme update deployed",
        },
        { role: "HR", status: "idle", pendingTasks: 0, lastAction: "Seasonal staffing plan done" },
        {
          role: "Legal",
          status: "active",
          pendingTasks: 2,
          lastAction: "Return policy revision pending",
        },
        {
          role: "Strategy",
          status: "active",
          pendingTasks: 1,
          lastAction: "Market expansion analysis: Southeast",
        },
        {
          role: "Knowledge",
          status: "idle",
          pendingTasks: 0,
          lastAction: "Product knowledge base updated",
        },
      ],
      goals: [
        { name: "Hit $200K Revenue", progress: 0.78, priority: 0.9, deadline: "2026-06-30" },
        { name: "Reduce Returns to <5%", progress: 0.4, priority: 0.82, deadline: "2026-04-01" },
        { name: "Launch Southeast Market", progress: 0.2, priority: 0.75, deadline: "2026-05-15" },
        { name: "Improve AOV to $75", progress: 0.55, priority: 0.7, deadline: "2026-03-31" },
        { name: "Automate Fulfillment", progress: 0.35, priority: 0.68, deadline: "2026-04-30" },
      ],
      recentActivity: [
        {
          time: "1h ago",
          agent: "COO",
          action: "3PL partner escalation — 48hr SLA breach on 12 orders",
        },
        {
          time: "3h ago",
          agent: "CMO",
          action: "Instagram Spring Collection campaign — 2.4% CTR first day",
        },
        {
          time: "5h ago",
          agent: "CFO",
          action: "Category margins: Electronics down 4%, Apparel up 2%",
        },
        { time: "1d ago", agent: "CEO", action: "Approved supplier switch for top 5 SKUs" },
        {
          time: "2d ago",
          agent: "Legal",
          action: "Drafted updated return policy — awaiting stakeholder review",
        },
      ],
    },
    {
      id: "strategypeak",
      name: "StrategyPeak",
      type: "consulting",
      status: "active",
      health: 0.91,
      revenue: 47200,
      utilization: 0.82,
      agentCount: 9,
      activeGoals: 4,
      kpis: [
        { name: "Revenue", value: 47200, target: 60000, unit: "$" },
        { name: "Utilization", value: 82, target: 85, unit: "%" },
        { name: "Avg Engagement", value: 18500, target: 20000, unit: "$" },
        { name: "Client NPS", value: 78, target: 75, unit: "" },
        { name: "Pipeline", value: 135000, target: 150000, unit: "$" },
        { name: "Win Rate", value: 42, target: 45, unit: "%" },
      ],
      agents: [
        {
          role: "CEO",
          status: "active",
          pendingTasks: 1,
          lastAction: "New service line proposal review",
        },
        {
          role: "CFO",
          status: "active",
          pendingTasks: 1,
          lastAction: "Invoice batch sent — $23K outstanding",
        },
        {
          role: "COO",
          status: "active",
          pendingTasks: 2,
          lastAction: "Resource allocation optimized",
        },
        {
          role: "CMO",
          status: "active",
          pendingTasks: 1,
          lastAction: "Case study published: FinTech Co",
        },
        { role: "CTO", status: "idle", pendingTasks: 0, lastAction: "Internal tools maintenance" },
        {
          role: "HR",
          status: "active",
          pendingTasks: 1,
          lastAction: "Expert sourcing for AI engagement",
        },
        { role: "Legal", status: "idle", pendingTasks: 0, lastAction: "MSA templates refreshed" },
        {
          role: "Strategy",
          status: "active",
          pendingTasks: 2,
          lastAction: "Market opportunity: AI governance",
        },
        {
          role: "Knowledge",
          status: "active",
          pendingTasks: 1,
          lastAction: "Framework library expanded",
        },
      ],
      goals: [
        { name: "Close $60K Q1 Revenue", progress: 0.79, priority: 0.95, deadline: "2026-03-31" },
        {
          name: "Launch AI Governance Service",
          progress: 0.55,
          priority: 0.85,
          deadline: "2026-04-01",
        },
        {
          name: "Build Expert Network to 20",
          progress: 0.7,
          priority: 0.72,
          deadline: "2026-05-01",
        },
        {
          name: "Publish Thought Leadership",
          progress: 0.6,
          priority: 0.65,
          deadline: "2026-03-15",
        },
      ],
      recentActivity: [
        {
          time: "30m ago",
          agent: "Strategy",
          action: "AI governance market sizing complete — $2.4B TAM",
        },
        { time: "3h ago", agent: "CFO", action: "Invoice batch: 3 invoices totaling $23,400 sent" },
        {
          time: "8h ago",
          agent: "CEO",
          action: "Proposal submitted to NexGen Financial — $35K engagement",
        },
        {
          time: "1d ago",
          agent: "CMO",
          action: "Case study: 'How FinTech Co Saved $200K with AI Strategy'",
        },
        { time: "2d ago", agent: "HR", action: "Onboarded 2 new SMEs for AI governance practice" },
      ],
    },
  ],

  decisions: [
    {
      id: "dec-001",
      businessId: "urbanmarket",
      businessName: "UrbanMarket",
      title: "Switch Primary 3PL Provider",
      urgency: 0.92,
      agent: "COO",
      raisedAt: "2026-02-16T10:30:00Z",
      summary:
        "Current 3PL breached SLA 3 times in 2 weeks. 12 orders delayed >48hrs. Customer complaints up 40%.",
      options: [
        {
          label: "Switch to ShipFast Pro",
          impact: "Better SLA, +$0.85/order cost, 2-week transition",
          recommended: true,
        },
        {
          label: "Renegotiate Current Contract",
          impact: "Penalty clause + dedicated account manager, no transition cost",
        },
        {
          label: "Add Backup 3PL",
          impact: "Redundancy, +15% logistics cost, split fulfillment complexity",
        },
      ],
      recommendation:
        "Switch to ShipFast Pro — their 99.2% SLA and same-day processing justifies the cost increase given current customer churn risk.",
      category: "operations",
    },
    {
      id: "dec-002",
      businessId: "techflow",
      businessName: "TechFlow",
      title: "Enterprise Tier Pricing Model",
      urgency: 0.85,
      agent: "CEO",
      raisedAt: "2026-02-15T14:00:00Z",
      summary:
        "3 enterprise prospects waiting on pricing. Need to decide between seat-based, usage-based, or hybrid model.",
      options: [
        {
          label: "Seat-based ($89/seat/mo)",
          impact: "Predictable revenue, simple to understand, may limit adoption",
        },
        {
          label: "Usage-based (pay-per-API-call)",
          impact: "Aligns with value, harder to predict revenue, complex billing",
        },
        {
          label: "Hybrid ($49/seat + usage)",
          impact: "Base + growth revenue, moderate complexity",
          recommended: true,
        },
      ],
      recommendation:
        "Hybrid model — captures base recurring revenue while rewarding heavy usage. Similar to Slack/Twilio model.",
      category: "strategy",
    },
    {
      id: "dec-003",
      businessId: "techflow",
      businessName: "TechFlow",
      title: "Approve CAC Investigation Budget",
      urgency: 0.78,
      agent: "CFO",
      raisedAt: "2026-02-16T08:00:00Z",
      summary:
        "Customer acquisition cost trending up 15% MoM. Requesting $5K budget for attribution audit and channel optimization.",
      options: [
        {
          label: "Approve $5K",
          impact: "Full audit + A/B testing across channels",
          recommended: true,
        },
        { label: "Approve $2.5K", impact: "Partial audit — paid channels only" },
        { label: "Defer 30 days", impact: "Monitor organically, risk continued cost increase" },
      ],
      recommendation:
        "Approve full $5K — 15% MoM CAC increase compounds fast. Early intervention saves 10-20x the audit cost.",
      category: "finance",
    },
    {
      id: "dec-004",
      businessId: "strategypeak",
      businessName: "StrategyPeak",
      title: "Accept NexGen Financial Engagement",
      urgency: 0.75,
      agent: "CEO",
      raisedAt: "2026-02-16T11:00:00Z",
      summary:
        "NexGen Financial responded positively to $35K AI strategy proposal. 8-week engagement, need 2 SMEs. Current utilization at 82%.",
      options: [
        {
          label: "Accept — Staff Internally",
          impact: "High margin (65%), stretches current team to 92% utilization",
          recommended: true,
        },
        {
          label: "Accept — Subcontract 1 SME",
          impact: "Moderate margin (48%), manageable utilization (87%)",
        },
        {
          label: "Counter at $42K",
          impact: "Better margin, risk losing deal — NexGen comparing 2 other firms",
        },
      ],
      recommendation:
        "Accept and staff internally. 92% utilization is high but manageable for 8 weeks. $35K at 65% margin = $22.75K gross profit.",
      category: "strategy",
    },
    {
      id: "dec-005",
      businessId: "urbanmarket",
      businessName: "UrbanMarket",
      title: "Return Policy Revision",
      urgency: 0.65,
      agent: "Legal",
      raisedAt: "2026-02-14T16:00:00Z",
      summary:
        "Current 60-day return window contributing to 8.2% return rate. Industry standard is 30 days. Proposed revision to 30 days with exceptions.",
      options: [
        {
          label: "30-day window (standard)",
          impact: "Est. 35% reduction in returns, potential negative reviews",
          recommended: true,
        },
        {
          label: "30-day + VIP exceptions",
          impact: "Est. 30% reduction, loyal customers keep flexibility",
        },
        { label: "Keep 60-day", impact: "No change, returns continue trending up" },
      ],
      recommendation:
        "30-day with VIP exceptions — protects loyal customer relationships while reducing abuse. Estimated $12K/year savings.",
      category: "legal",
    },
    {
      id: "dec-006",
      businessId: "techflow",
      businessName: "TechFlow",
      title: "SOC 2 Audit Vendor Selection",
      urgency: 0.58,
      agent: "CTO",
      raisedAt: "2026-02-15T09:00:00Z",
      summary:
        "Need to select SOC 2 Type II audit vendor. 3 finalists evaluated. Enterprise customers requiring compliance proof.",
      options: [
        {
          label: "Vanta ($18K/yr)",
          impact: "Automated, fast (8 weeks), integrates with our stack",
          recommended: true,
        },
        {
          label: "Drata ($22K/yr)",
          impact: "More comprehensive, 10 weeks, better enterprise reporting",
        },
        { label: "Big 4 Traditional ($45K)", impact: "Most credible with Fortune 500, 16 weeks" },
      ],
      recommendation:
        "Vanta — best speed-to-compliance ratio. Enterprise tier launch blocked on SOC 2; every week saved = faster revenue.",
      category: "compliance",
    },
    {
      id: "dec-007",
      businessId: "strategypeak",
      businessName: "StrategyPeak",
      title: "AI Governance Service Line Investment",
      urgency: 0.52,
      agent: "Strategy",
      raisedAt: "2026-02-16T13:00:00Z",
      summary:
        "Market analysis shows $2.4B TAM for AI governance consulting. Recommend $8K investment in frameworks, templates, and marketing.",
      options: [
        {
          label: "Full investment ($8K)",
          impact: "First-mover advantage, complete service offering in 6 weeks",
          recommended: true,
        },
        {
          label: "Lean launch ($3K)",
          impact: "Basic offering in 3 weeks, iterate based on demand",
        },
        { label: "Wait & watch", impact: "No cost, risk losing first-mover to competitors" },
      ],
      recommendation:
        "Full investment — $2.4B TAM with few specialist consultancies. $8K is <1 engagement worth of investment.",
      category: "strategy",
    },
  ],

  workforce: [
    {
      name: "Sarah Chen",
      specialty: "Full-Stack Dev",
      trust: 0.92,
      activePackages: 2,
      completedPackages: 8,
      business: "TechFlow",
    },
    {
      name: "Marcus Rivera",
      specialty: "UI/UX Design",
      trust: 0.88,
      activePackages: 1,
      completedPackages: 5,
      business: "TechFlow",
    },
    {
      name: "Aisha Patel",
      specialty: "Content Marketing",
      trust: 0.85,
      activePackages: 2,
      completedPackages: 6,
      business: "UrbanMarket",
    },
    {
      name: "James Okafor",
      specialty: "AI/ML Engineering",
      trust: 0.79,
      activePackages: 1,
      completedPackages: 3,
      business: "StrategyPeak",
    },
    {
      name: "Elena Volkov",
      specialty: "Data Analytics",
      trust: 0.95,
      activePackages: 1,
      completedPackages: 12,
      business: "TechFlow",
    },
  ],

  // ── Kanban Board ──
  kanban: {
    columns: ["Backlog", "In Progress", "Review", "Done"],
    tasks: [
      {
        id: "t-01",
        title: "Enterprise Tier Pricing Model",
        business: "TechFlow",
        agent: "CEO",
        column: "Review",
        priority: "high",
        goalId: "g-tf-02",
        dueDate: "2026-02-20",
      },
      {
        id: "t-02",
        title: "SOC 2 Vendor Selection",
        business: "TechFlow",
        agent: "CTO",
        column: "In Progress",
        priority: "high",
        goalId: "g-tf-04",
        dueDate: "2026-02-25",
      },
      {
        id: "t-03",
        title: "API v2 Documentation",
        business: "TechFlow",
        agent: "CTO",
        column: "In Progress",
        priority: "medium",
        goalId: "g-tf-05",
        dueDate: "2026-02-28",
      },
      {
        id: "t-04",
        title: "CAC Attribution Audit",
        business: "TechFlow",
        agent: "CFO",
        column: "Backlog",
        priority: "high",
        goalId: "g-tf-01",
        dueDate: "2026-03-05",
      },
      {
        id: "t-05",
        title: "Q2 Content Calendar",
        business: "TechFlow",
        agent: "CMO",
        column: "Done",
        priority: "medium",
        goalId: "g-tf-01",
        dueDate: "2026-02-15",
      },
      {
        id: "t-06",
        title: "Switch 3PL Provider",
        business: "UrbanMarket",
        agent: "COO",
        column: "Review",
        priority: "critical",
        goalId: "g-um-05",
        dueDate: "2026-02-22",
      },
      {
        id: "t-07",
        title: "Return Policy Revision",
        business: "UrbanMarket",
        agent: "Legal",
        column: "Review",
        priority: "medium",
        goalId: "g-um-02",
        dueDate: "2026-02-28",
      },
      {
        id: "t-08",
        title: "Instagram Spring Campaign",
        business: "UrbanMarket",
        agent: "CMO",
        column: "In Progress",
        priority: "medium",
        goalId: "g-um-01",
        dueDate: "2026-03-01",
      },
      {
        id: "t-09",
        title: "Southeast Market Analysis",
        business: "UrbanMarket",
        agent: "Strategy",
        column: "In Progress",
        priority: "low",
        goalId: "g-um-03",
        dueDate: "2026-03-15",
      },
      {
        id: "t-10",
        title: "Supplier Renegotiation (Top 5 SKUs)",
        business: "UrbanMarket",
        agent: "COO",
        column: "Done",
        priority: "medium",
        goalId: "g-um-04",
        dueDate: "2026-02-10",
      },
      {
        id: "t-11",
        title: "NexGen Financial Proposal",
        business: "StrategyPeak",
        agent: "CEO",
        column: "Done",
        priority: "high",
        goalId: "g-sp-01",
        dueDate: "2026-02-15",
      },
      {
        id: "t-12",
        title: "AI Governance Framework v1",
        business: "StrategyPeak",
        agent: "Strategy",
        column: "In Progress",
        priority: "high",
        goalId: "g-sp-02",
        dueDate: "2026-03-10",
      },
      {
        id: "t-13",
        title: "Expert Network Outreach",
        business: "StrategyPeak",
        agent: "HR",
        column: "In Progress",
        priority: "medium",
        goalId: "g-sp-03",
        dueDate: "2026-03-01",
      },
      {
        id: "t-14",
        title: "Case Study: FinTech Co",
        business: "StrategyPeak",
        agent: "CMO",
        column: "Done",
        priority: "medium",
        goalId: "g-sp-04",
        dueDate: "2026-02-14",
      },
      {
        id: "t-15",
        title: "Invoice Batch Processing",
        business: "StrategyPeak",
        agent: "CFO",
        column: "Done",
        priority: "low",
        goalId: "g-sp-01",
        dueDate: "2026-02-16",
      },
      {
        id: "t-16",
        title: "Onboarding Flow Optimization",
        business: "TechFlow",
        agent: "COO",
        column: "Done",
        priority: "medium",
        goalId: "g-tf-01",
        dueDate: "2026-02-14",
      },
      {
        id: "t-17",
        title: "Churn Analysis Dashboard",
        business: "TechFlow",
        agent: "CTO",
        column: "Backlog",
        priority: "medium",
        goalId: "g-tf-03",
        dueDate: "2026-03-10",
      },
      {
        id: "t-18",
        title: "Fulfillment Automation RFP",
        business: "UrbanMarket",
        agent: "CTO",
        column: "Backlog",
        priority: "low",
        goalId: "g-um-05",
        dueDate: "2026-04-01",
      },
    ],
  },

  // ── Gantt Chart ──
  gantt: {
    timelineStart: "2026-02-01",
    timelineEnd: "2026-06-30",
    items: [
      // TechFlow
      {
        id: "g-tf-01",
        name: "Reach $25K MRR",
        business: "TechFlow",
        start: "2026-01-15",
        end: "2026-03-31",
        progress: 0.85,
        type: "strategic",
        level: "strategic",
        deps: [],
        color: "#00ff41",
      },
      {
        id: "g-tf-02",
        name: "Launch Enterprise Tier",
        business: "TechFlow",
        start: "2026-02-01",
        end: "2026-04-15",
        progress: 0.45,
        type: "strategic",
        level: "strategic",
        deps: ["g-tf-04"],
        color: "#00ff41",
      },
      {
        id: "g-tf-03",
        name: "Reduce Churn to <3%",
        business: "TechFlow",
        start: "2026-02-01",
        end: "2026-03-15",
        progress: 0.6,
        type: "operational",
        level: "tactical",
        deps: [],
        color: "#4488ff",
      },
      {
        id: "g-tf-04",
        name: "SOC 2 Compliance",
        business: "TechFlow",
        start: "2026-02-10",
        end: "2026-06-01",
        progress: 0.3,
        type: "compliance",
        level: "operational",
        deps: [],
        color: "#ff6b35",
      },
      {
        id: "g-tf-05",
        name: "API v2 Launch",
        business: "TechFlow",
        start: "2026-01-20",
        end: "2026-03-01",
        progress: 0.7,
        type: "product",
        level: "tactical",
        deps: [],
        color: "#4488ff",
      },
      {
        id: "g-tf-06",
        name: "Hire 2 Senior Devs",
        business: "TechFlow",
        start: "2026-02-15",
        end: "2026-04-01",
        progress: 0.25,
        type: "operational",
        level: "operational",
        deps: [],
        color: "#bb88ff",
      },
      // UrbanMarket
      {
        id: "g-um-01",
        name: "Hit $200K Revenue",
        business: "UrbanMarket",
        start: "2026-01-01",
        end: "2026-06-30",
        progress: 0.78,
        type: "strategic",
        level: "strategic",
        deps: [],
        color: "#00ff41",
      },
      {
        id: "g-um-02",
        name: "Reduce Returns to <5%",
        business: "UrbanMarket",
        start: "2026-02-01",
        end: "2026-04-01",
        progress: 0.4,
        type: "operational",
        level: "tactical",
        deps: [],
        color: "#4488ff",
      },
      {
        id: "g-um-03",
        name: "Launch Southeast Market",
        business: "UrbanMarket",
        start: "2026-03-01",
        end: "2026-05-15",
        progress: 0.2,
        type: "strategic",
        level: "strategic",
        deps: ["g-um-01"],
        color: "#00ff41",
      },
      {
        id: "g-um-04",
        name: "Improve AOV to $75",
        business: "UrbanMarket",
        start: "2026-02-01",
        end: "2026-03-31",
        progress: 0.55,
        type: "operational",
        level: "tactical",
        deps: [],
        color: "#4488ff",
      },
      {
        id: "g-um-05",
        name: "Automate Fulfillment",
        business: "UrbanMarket",
        start: "2026-02-15",
        end: "2026-04-30",
        progress: 0.35,
        type: "operational",
        level: "operational",
        deps: [],
        color: "#bb88ff",
      },
      // StrategyPeak
      {
        id: "g-sp-01",
        name: "Close $60K Q1 Revenue",
        business: "StrategyPeak",
        start: "2026-01-01",
        end: "2026-03-31",
        progress: 0.79,
        type: "strategic",
        level: "strategic",
        deps: [],
        color: "#00ff41",
      },
      {
        id: "g-sp-02",
        name: "Launch AI Governance Service",
        business: "StrategyPeak",
        start: "2026-02-10",
        end: "2026-04-01",
        progress: 0.55,
        type: "strategic",
        level: "strategic",
        deps: [],
        color: "#00ff41",
      },
      {
        id: "g-sp-03",
        name: "Build Expert Network to 20",
        business: "StrategyPeak",
        start: "2026-02-01",
        end: "2026-05-01",
        progress: 0.7,
        type: "operational",
        level: "operational",
        deps: [],
        color: "#bb88ff",
      },
      {
        id: "g-sp-04",
        name: "Publish Thought Leadership",
        business: "StrategyPeak",
        start: "2026-02-01",
        end: "2026-03-15",
        progress: 0.6,
        type: "marketing",
        level: "tactical",
        deps: [],
        color: "#4488ff",
      },
    ],
  },

  // ── Business Model View ──
  businessModel: {
    goalTypes: ["strategic", "operational", "product", "compliance", "marketing"],
    operationalLevels: ["strategic", "tactical", "operational"],
    goals: [
      // TechFlow
      {
        id: "bg-tf-01",
        business: "TechFlow",
        name: "Market Leadership in SMB SaaS",
        type: "strategic",
        level: "strategic",
        priority: 0.95,
        description: "Establish TechFlow as the go-to platform for SMB workflow automation",
        desires: [
          "Maximize MRR growth",
          "Expand to enterprise segment",
          "Achieve product-market fit",
        ],
        workflows: [
          {
            id: "w-tf-01",
            name: "Customer Acquisition Pipeline",
            type: "bpmn",
            steps: ["Lead Generation → Qualification → Demo → Trial → Conversion → Onboarding"],
            agents: ["CMO", "COO"],
            status: "active",
            level: "tactical",
          },
          {
            id: "w-tf-02",
            name: "Enterprise Sales Process",
            type: "bpmn",
            steps: [
              "Prospect Identification → Outreach → Discovery Call → Proposal → Negotiation → Close → Implementation",
            ],
            agents: ["CEO", "COO"],
            status: "designing",
            level: "strategic",
          },
        ],
      },
      {
        id: "bg-tf-02",
        business: "TechFlow",
        name: "Product Excellence",
        type: "product",
        level: "tactical",
        priority: 0.88,
        description: "Ship high-quality features that drive retention and expansion",
        desires: ["Reduce churn", "Increase feature adoption", "Maintain 99.95% uptime"],
        workflows: [
          {
            id: "w-tf-03",
            name: "Feature Development Lifecycle",
            type: "bpmn",
            steps: ["Ideation → Spec → Design → Build → Test → Deploy → Monitor → Iterate"],
            agents: ["CTO", "COO"],
            status: "active",
            level: "tactical",
          },
          {
            id: "w-tf-04",
            name: "Incident Response",
            type: "bpmn",
            steps: [
              "Detection → Triage → Investigation → Mitigation → Resolution → Post-Mortem → Prevention",
            ],
            agents: ["CTO"],
            status: "active",
            level: "operational",
          },
          {
            id: "w-tf-05",
            name: "Release Management",
            type: "bpmn",
            steps: ["Plan → Develop → Stage → QA → Canary → Full Deploy → Validate"],
            agents: ["CTO"],
            status: "active",
            level: "operational",
          },
        ],
      },
      {
        id: "bg-tf-03",
        business: "TechFlow",
        name: "Compliance & Trust",
        type: "compliance",
        level: "operational",
        priority: 0.78,
        description: "Achieve SOC 2 and maintain regulatory compliance to unlock enterprise sales",
        desires: ["SOC 2 Type II certification", "GDPR compliance", "Enterprise-grade security"],
        workflows: [
          {
            id: "w-tf-06",
            name: "SOC 2 Audit Process",
            type: "bpmn",
            steps: [
              "Vendor Selection → Gap Assessment → Remediation → Evidence Collection → Audit → Certification",
            ],
            agents: ["CTO", "Legal"],
            status: "active",
            level: "operational",
          },
          {
            id: "w-tf-07",
            name: "Security Review Cycle",
            type: "bpmn",
            steps: [
              "Vulnerability Scan → Risk Assessment → Patch Planning → Implementation → Verification",
            ],
            agents: ["CTO"],
            status: "active",
            level: "operational",
          },
        ],
      },
      // UrbanMarket
      {
        id: "bg-um-01",
        business: "UrbanMarket",
        name: "Revenue Growth to $200K",
        type: "strategic",
        level: "strategic",
        priority: 0.92,
        description: "Scale revenue through channel expansion and AOV optimization",
        desires: ["Expand to Southeast", "Increase AOV", "Reduce CAC"],
        workflows: [
          {
            id: "w-um-01",
            name: "Order-to-Delivery Pipeline",
            type: "bpmn",
            steps: ["Order Placed → Payment → Pick → Pack → Ship → Deliver → Follow-up"],
            agents: ["COO", "CTO"],
            status: "active",
            level: "operational",
          },
          {
            id: "w-um-02",
            name: "Marketing Campaign Lifecycle",
            type: "bpmn",
            steps: ["Strategy → Creative → Launch → Monitor → Optimize → Report → Learn"],
            agents: ["CMO"],
            status: "active",
            level: "tactical",
          },
          {
            id: "w-um-03",
            name: "Market Expansion Playbook",
            type: "bpmn",
            steps: ["Research → Validate → Localize → Launch → Scale → Optimize"],
            agents: ["CEO", "Strategy"],
            status: "designing",
            level: "strategic",
          },
        ],
      },
      {
        id: "bg-um-02",
        business: "UrbanMarket",
        name: "Operational Excellence",
        type: "operational",
        level: "tactical",
        priority: 0.82,
        description: "Optimize fulfillment, reduce returns, and streamline supply chain",
        desires: ["Return rate <5%", "3PL SLA 99%+", "Inventory turnover 8x"],
        workflows: [
          {
            id: "w-um-04",
            name: "Return Processing",
            type: "bpmn",
            steps: [
              "RMA Request → Approval → Receive → Inspect → Refund/Exchange → Restock → Analytics",
            ],
            agents: ["COO", "CFO"],
            status: "active",
            level: "operational",
          },
          {
            id: "w-um-05",
            name: "Supplier Management",
            type: "bpmn",
            steps: ["Evaluate → Negotiate → Contract → Order → Receive → QC → Pay → Review"],
            agents: ["COO", "CFO"],
            status: "active",
            level: "operational",
          },
          {
            id: "w-um-06",
            name: "Inventory Replenishment",
            type: "bpmn",
            steps: [
              "Monitor Levels → Forecast Demand → Generate PO → Approve → Send → Track → Receive → Update",
            ],
            agents: ["COO"],
            status: "active",
            level: "operational",
          },
        ],
      },
      // StrategyPeak
      {
        id: "bg-sp-01",
        business: "StrategyPeak",
        name: "Revenue & Pipeline Growth",
        type: "strategic",
        level: "strategic",
        priority: 0.95,
        description: "Close Q1 revenue target and build $150K+ pipeline",
        desires: ["$60K Q1 revenue", "$150K pipeline", "45% win rate"],
        workflows: [
          {
            id: "w-sp-01",
            name: "Engagement Lifecycle",
            type: "bpmn",
            steps: [
              "Lead → Qualify → Propose → Negotiate → Win → Staff → Deliver → Close → Upsell",
            ],
            agents: ["CEO", "COO"],
            status: "active",
            level: "strategic",
          },
          {
            id: "w-sp-02",
            name: "Proposal Development",
            type: "bpmn",
            steps: [
              "Brief → Research → Scope → Price → Draft → Review → Approve → Submit → Follow-up",
            ],
            agents: ["CEO", "Strategy"],
            status: "active",
            level: "tactical",
          },
        ],
      },
      {
        id: "bg-sp-02",
        business: "StrategyPeak",
        name: "AI Governance Practice",
        type: "strategic",
        level: "strategic",
        priority: 0.88,
        description: "Launch new AI governance consulting service line targeting $2.4B TAM",
        desires: ["First-mover advantage", "Framework IP creation", "3 engagements in Q2"],
        workflows: [
          {
            id: "w-sp-03",
            name: "Service Line Development",
            type: "bpmn",
            steps: [
              "Market Research → Framework Design → Template Creation → Pilot Client → Iterate → Scale",
            ],
            agents: ["Strategy", "Knowledge"],
            status: "active",
            level: "strategic",
          },
          {
            id: "w-sp-04",
            name: "Thought Leadership Pipeline",
            type: "bpmn",
            steps: ["Topic Selection → Research → Draft → Review → Publish → Promote → Measure"],
            agents: ["CMO", "Strategy"],
            status: "active",
            level: "tactical",
          },
        ],
      },
      {
        id: "bg-sp-03",
        business: "StrategyPeak",
        name: "Expert Network Scaling",
        type: "operational",
        level: "operational",
        priority: 0.72,
        description: "Build contractor network to 20 vetted experts across domains",
        desires: ["20 vetted experts", "90% availability rate", "Avg trust score >0.85"],
        workflows: [
          {
            id: "w-sp-05",
            name: "Expert Onboarding",
            type: "bpmn",
            steps: [
              "Source → Screen → Interview → Reference Check → Trial Project → Rate → Onboard",
            ],
            agents: ["HR", "COO"],
            status: "active",
            level: "operational",
          },
        ],
      },
      {
        id: "bg-um-03",
        business: "UrbanMarket",
        name: "Brand & Customer Experience",
        type: "marketing",
        level: "tactical",
        priority: 0.68,
        description: "Build brand loyalty and improve NPS through customer experience",
        desires: ["Loyalty program launch", "NPS >50", "Social media engagement 5%+"],
        workflows: [
          {
            id: "w-um-07",
            name: "Customer Feedback Loop",
            type: "bpmn",
            steps: ["Collect → Analyze → Categorize → Prioritize → Action → Communicate → Measure"],
            agents: ["CMO", "COO"],
            status: "designing",
            level: "tactical",
          },
        ],
      },
    ],
  },
};
