import { i as OpenClawConfig } from "../../types.openclaw-BuKAF4PW.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-BVJ2Rte8.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-DUJz-9i6.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-C01XwMRy.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-TY_PD3kg.js";
import { t as ChannelMessageActionName } from "../../types.public-CzfdpDjZ.js";
import { n as PluginRuntime } from "../../types-6l5HWcJc.js";
import { d as readRemoteMediaBuffer } from "../../fetch-C_xZbkaM.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-BlH28Cyt.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DT4x3IJB.js";
import { r as buildChannelConfigSchema } from "../../config-schema-B_2f5acI.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-TqGT2xIt.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-DdSTLDmU.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-CS2dAVNb.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-DlGgJwJW.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-CVRENTJ_.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-BdSkb6oA.js";
import { n as resolveWebhookPath } from "../../webhook-path-cfL4BYKI.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-D8qDDt6d.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-DDdH27iV.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-BbH7WFCh.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BGvZlyA7.js";
import { r as createChannelPairingController } from "../../channel-pairing-DYU6jRwZ.js";
import { t as chunkTextForOutbound } from "../../text-chunking-DWkW5QQN.js";
import { m as missingTargetError } from "../../channel-feedback-BUrDJ-fd.js";
import { t as extractToolSend } from "../../tool-send-B628mpt1.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-io7VNlyi.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-CFAivOu6.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };