import { i as OpenClawConfig } from "../../types.openclaw-CQzDxdpQ.js";
import { ft as GoogleChatAccountConfig, mt as GoogleChatConfig } from "../../types.channels-BX77gn-L.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-DQVa3xpB.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-jXSHRHDW.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-6_aqXYT2.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DrB_kWzl.js";
import { t as ChannelMessageActionName } from "../../types.public-C5MFEvPW.js";
import { n as PluginRuntime } from "../../types-CXGnubLv.js";
import { d as readRemoteMediaBuffer } from "../../fetch-C-jSUan0.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-BIgfK4F8.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BUCmnyv5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-D14tWtON.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BzbwrEoM.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-CU6NXSx8.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-VYDXV5_b.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-U0Jok8Qk.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-CoqXEype.js";
import { n as resolveWebhookPath } from "../../webhook-path-BIqlProu.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CeBGjAic.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-BsyYnCvF.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-CzGji8qY.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-CZMYEMFE.js";
import { r as createChannelPairingController } from "../../channel-pairing-CDDwGgW9.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CL4-YftM.js";
import { m as missingTargetError } from "../../channel-feedback-CYjkLiO2.js";
import { t as extractToolSend } from "../../tool-send-B9qFMmxY.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-DvgETItZ.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-CqVXOYN_.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };