// Google provider config compatibility migration for legacy provider blocks.
//
// Legacy google provider configs (generated by older onboard/setup) may omit
// the `api` field and individual model `cost.cacheWrite`. This module backfills
// those values so the model catalog loads correctly without silent drop.
import type { OpenClawConfig } from "openclaw/plugin-sdk/config-contracts";

const GOOGLE_PROVIDER_IDS = new Set([
  "google",
  "google-antigravity",
  "google-gemini-cli",
  "google-vertex",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeOptionalString(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  return trimmed ? trimmed : undefined;
}

function resolveGoogleProviderApi(providerKey: string, _provider: Record<string, unknown>): string {
  return providerKey === "google-vertex" ? "google-vertex" : "google-generative-ai";
}

export function normalizeCompatibilityConfig({ cfg }: { cfg: OpenClawConfig }): {
  config: OpenClawConfig;
  changes: string[];
} {
  const rawProviders = cfg.models?.providers;
  if (!isRecord(rawProviders)) {
    return { config: cfg, changes: [] };
  }

  const changes: string[] = [];
  let providersChanged = false;
  const nextProviders: Record<string, unknown> = { ...rawProviders };

  for (const [providerKey, rawProvider] of Object.entries(rawProviders)) {
    const normalizedKey = providerKey.toLowerCase();
    if (!GOOGLE_PROVIDER_IDS.has(normalizedKey)) {
      continue;
    }
    if (!isRecord(rawProvider)) {
      continue;
    }

    let providerChanged = false;
    const nextProvider: Record<string, unknown> = { ...rawProvider };

    // Backfill missing api field so model catalog routing resolves correctly.
    if (!normalizeOptionalString(nextProvider.api)) {
      const api = resolveGoogleProviderApi(normalizedKey, nextProvider);
      nextProvider.api = api;
      providerChanged = true;
      changes.push(`Set models.providers.${providerKey}.api to "${api}".`);
    }

    // Backfill missing cost.cacheWrite on model entries.  Legacy blocks
    // only carried {input, output, cacheRead}; the static catalog uses
    // {input: 0, output: 0, cacheRead: 0, cacheWrite: 0} for all Google
    // models, so 0 is the correct historical default.
    const rawModels = rawProvider.models;
    if (Array.isArray(rawModels)) {
      let modelsChanged = false;
      const nextModels = rawModels.map((model, index) => {
        if (!isRecord(model)) return model;
        const cost = model.cost;
        if (!isRecord(cost)) return model;
        if ("cacheWrite" in cost) return model;

        modelsChanged = true;
        changes.push(`Set models.providers.${providerKey}.models[${index}].cost.cacheWrite to 0.`);
        return { ...model, cost: { ...cost, cacheWrite: 0 } };
      });

      if (modelsChanged) {
        nextProvider.models = nextModels;
        providerChanged = true;
      }
    }

    if (providerChanged) {
      nextProviders[providerKey] = nextProvider;
      providersChanged = true;
    }
  }

  if (!providersChanged) {
    return { config: cfg, changes: [] };
  }

  return {
    config: {
      ...cfg,
      models: {
        ...cfg.models,
        providers: nextProviders as NonNullable<OpenClawConfig["models"]>["providers"],
      },
    },
    changes,
  };
}
