import { p as isBlockedHostnameOrIp } from "../../ssrf-D3pufDBY.js";
import { o as SessionEntry } from "../../types-BoPp7-Sf.js";
import { g as OpenClawPluginApi } from "../../types-BOTb5nyG.js";
import { _ as sleep } from "../../utils-D1CyDeib.js";
import { r as GatewayRequestHandlerOptions } from "../../types-DZSMYXQj.js";
import { t as definePluginEntry } from "../../plugin-entry-CtrgLk_6.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-CxM_5XQX.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-B8Gi0B9c.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-DwXjtsu5.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };