# ci.example.yaml (pseudo)
# Replace with GitHub Actions/GitLab/etc.

stages:
  - build
  - test
  - e2e

build:
  script:
    - docker build -t dispatch-api:ci -f ops/Dockerfile.dispatch-api.example .

migrate_and_test:
  script:
    - docker compose -f ops/docker-compose.yaml up -d postgres
    - ./db/run_migrations.sh
    - ./dispatch-api/run_unit_tests.sh

e2e:
  script:
    - docker compose -f ops/docker-compose.yaml up -d
    - ./dispatch/e2e/run.sh
