export {
  JsonFileReadError,
  createAsyncLock,
  readJson,
  readJson as readJsonFileStrict,
  readJsonIfExists,
  readJsonIfExists as readDurableJsonFile,
  readJsonSync,
  tryReadJson,
  tryReadJson as readJsonFile,
  tryReadJsonSync as readJsonFileSync,
  writeJson,
  writeJson as writeJsonAtomic,
  writeText,
  writeText as writeTextAtomic,
} from "@openclaw/fs-safe/json";
