import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-9_btbLFO.js";
import { t as getChatChannelMeta } from "../../chat-meta-42nqDCp5.js";
import { r as buildChannelConfigSchema } from "../../config-schema-gd9RYI9s.js";
import { n as AcpRuntimeError } from "../../errors-zyHRqIKC.js";
import { _ as readStringParam, g as readStringOrNumberParam, h as readStringArrayParam, l as jsonResult, m as readReactionParams, p as readNumberParam } from "../../common-DZFnGYgt.js";
import { r as resolvePollMaxSelections } from "../../polls-BXQX1ijK.js";
import { t as clearAccountEntryFields } from "../../config-helpers-VqWhr_tS.js";
import { n as formatPairingApproveHint } from "../../helpers-BJ8ZIvo-.js";
import { r as makeProxyFetch } from "../../proxy-fetch-v9WlvIjL.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-4_KBakSP.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-gXAt4SsD.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-BrUwGj7G.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-CBVJeodZ.js";
import "../../channel-core-Bs76qCQe.js";
import { t as resolveTelegramToken } from "../../token-Bv1wiouR.js";
import "../../acp-runtime-Cq-PGkyp.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-BWpHs4Jo.js";
import "../../channel-plugin-common-DxtLXldp.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-DFnAP_vm.js";
import "../../channel-status-C--eIG63.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-C4yPoZ3d.js";
import "../../channel-actions-BGsl31yM.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-DrrtUmg3.js";
import { n as setTelegramRuntime } from "../../runtime-GlT2XfSI.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-CuLdY3he.js";
import "../../config-api-BIZTtgiS.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-DLyP4lua.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-CK5lnFHj.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-D3HN6oo6.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-CLYXBxae.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
