// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["yandex"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "yandex",
    artifactBasename: "api.js",
  });
}
export const applyYandexConfig: FacadeModule["applyYandexConfig"] = ((...args) =>
  loadFacadeModule()["applyYandexConfig"](...args)) as FacadeModule["applyYandexConfig"];
export const applyYandexProviderConfig: FacadeModule["applyYandexProviderConfig"] = ((...args) =>
  loadFacadeModule()["applyYandexProviderConfig"](
    ...args,
  )) as FacadeModule["applyYandexProviderConfig"];
export const buildYandexModelDefinition: FacadeModule["buildYandexModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildYandexModelDefinition"](
    ...args,
  )) as FacadeModule["buildYandexModelDefinition"];
export const buildYandexProvider: FacadeModule["buildYandexProvider"] = ((...args) =>
  loadFacadeModule()["buildYandexProvider"](...args)) as FacadeModule["buildYandexProvider"];
export const YANDEX_BASE_URL: FacadeModule["YANDEX_BASE_URL"] =
  loadFacadeModule()["YANDEX_BASE_URL"];
export const YANDEX_DEFAULT_MODEL_REF: FacadeModule["YANDEX_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["YANDEX_DEFAULT_MODEL_REF"];
export const YANDEX_MODEL_CATALOG: FacadeModule["YANDEX_MODEL_CATALOG"] =
  createLazyFacadeArrayValue(
    () => loadFacadeModule()["YANDEX_MODEL_CATALOG"] as unknown as readonly unknown[],
  ) as FacadeModule["YANDEX_MODEL_CATALOG"];
