{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
