/**
 * Built-in strategy template definitions.
 * These serve as starting points for users to create L0 strategies.
 */

import type { StrategyTemplate } from "../types.js";

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  {
    id: "sma-crossover",
    name: "SMA Crossover",
    description:
      "Classic dual moving average crossover strategy. Buys when fast SMA crosses above slow SMA, sells on the reverse.",
    category: "trend",
    parameters: [
      {
        name: "fastPeriod",
        type: "number",
        default: 10,
        min: 2,
        max: 200,
        description: "Fast SMA period",
      },
      {
        name: "slowPeriod",
        type: "number",
        default: 30,
        min: 5,
        max: 500,
        description: "Slow SMA period",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 20,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "rsi-mean-reversion",
    name: "RSI Mean Reversion",
    description:
      "Buy when RSI is oversold, sell when overbought. Works best in range-bound markets.",
    category: "mean-reversion",
    parameters: [
      {
        name: "rsiPeriod",
        type: "number",
        default: 14,
        min: 2,
        max: 100,
        description: "RSI calculation period",
      },
      {
        name: "oversold",
        type: "number",
        default: 30,
        min: 5,
        max: 50,
        description: "Oversold threshold",
      },
      {
        name: "overbought",
        type: "number",
        default: 70,
        min: 50,
        max: 95,
        description: "Overbought threshold",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 20,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "bollinger-bands",
    name: "Bollinger Bands",
    description: "Mean reversion using Bollinger Bands. Buys at lower band, sells at upper band.",
    category: "mean-reversion",
    parameters: [
      {
        name: "period",
        type: "number",
        default: 20,
        min: 5,
        max: 200,
        description: "Bollinger Band period",
      },
      {
        name: "stdDev",
        type: "number",
        default: 2,
        min: 1,
        max: 4,
        description: "Standard deviation multiplier",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 20,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "macd-divergence",
    name: "MACD Divergence",
    description:
      "Trades based on MACD line and signal line crossovers with histogram confirmation.",
    category: "momentum",
    parameters: [
      {
        name: "fastPeriod",
        type: "number",
        default: 12,
        min: 2,
        max: 100,
        description: "MACD fast EMA period",
      },
      {
        name: "slowPeriod",
        type: "number",
        default: 26,
        min: 5,
        max: 200,
        description: "MACD slow EMA period",
      },
      {
        name: "signalPeriod",
        type: "number",
        default: 9,
        min: 2,
        max: 50,
        description: "Signal line period",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 20,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "trend-following-momentum",
    name: "Trend Following Momentum",
    description:
      "Follows strong trends using ADX filter and EMA alignment. Only trades when trend is confirmed.",
    category: "trend",
    parameters: [
      {
        name: "emaPeriod",
        type: "number",
        default: 50,
        min: 10,
        max: 200,
        description: "Trend EMA period",
      },
      {
        name: "adxPeriod",
        type: "number",
        default: 14,
        min: 5,
        max: 50,
        description: "ADX period for trend strength",
      },
      {
        name: "adxThreshold",
        type: "number",
        default: 25,
        min: 15,
        max: 50,
        description: "Minimum ADX for trend confirmation",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 15,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "volatility-mean-reversion",
    name: "Volatility Mean Reversion",
    description: "Trades volatility expansion/contraction cycles using ATR and Keltner Channels.",
    category: "volatility",
    parameters: [
      {
        name: "atrPeriod",
        type: "number",
        default: 14,
        min: 5,
        max: 100,
        description: "ATR period",
      },
      {
        name: "atrMultiplier",
        type: "number",
        default: 2,
        min: 1,
        max: 5,
        description: "ATR multiplier for bands",
      },
      {
        name: "lookbackPeriod",
        type: "number",
        default: 20,
        min: 5,
        max: 100,
        description: "Volatility lookback",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 15,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "regime-adaptive",
    name: "Regime Adaptive",
    description:
      "Switches between trend-following and mean-reversion based on detected market regime.",
    category: "multi-factor",
    parameters: [
      {
        name: "regimeWindow",
        type: "number",
        default: 60,
        min: 20,
        max: 200,
        description: "Regime detection window",
      },
      {
        name: "trendEmaPeriod",
        type: "number",
        default: 20,
        min: 5,
        max: 100,
        description: "Trend EMA for trending regime",
      },
      {
        name: "reversionRsi",
        type: "number",
        default: 14,
        min: 5,
        max: 50,
        description: "RSI period for mean-reversion regime",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 15,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "multi-timeframe-confluence",
    name: "Multi-Timeframe Confluence",
    description:
      "Requires trend alignment across multiple timeframes before entry. Reduces false signals.",
    category: "multi-factor",
    parameters: [
      { name: "fastTf", type: "string", default: "1h", description: "Fast timeframe" },
      { name: "slowTf", type: "string", default: "1d", description: "Slow timeframe" },
      {
        name: "emaPeriod",
        type: "number",
        default: 20,
        min: 5,
        max: 100,
        description: "EMA period on each timeframe",
      },
      {
        name: "positionSizePct",
        type: "number",
        default: 15,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "risk-parity-triple-screen",
    name: "Risk Parity Triple Screen",
    description:
      "Elder's Triple Screen system with risk-parity position sizing. Uses weekly trend, daily momentum, intraday entry.",
    category: "multi-factor",
    parameters: [
      {
        name: "weeklyEmaPeriod",
        type: "number",
        default: 13,
        min: 5,
        max: 52,
        description: "Weekly trend EMA period",
      },
      {
        name: "dailyOscPeriod",
        type: "number",
        default: 5,
        min: 2,
        max: 20,
        description: "Daily oscillator period",
      },
      {
        name: "riskPct",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        description: "Risk per trade as % of equity",
      },
      {
        name: "atrStopMultiplier",
        type: "number",
        default: 2,
        min: 1,
        max: 5,
        description: "ATR multiplier for stop-loss",
      },
    ],
    supportedMarkets: ["crypto", "equity"],
  },
  {
    id: "custom",
    name: "Custom Strategy",
    description:
      "Empty template for building a strategy from scratch. Define your own entry/exit logic.",
    category: "multi-factor",
    parameters: [
      {
        name: "positionSizePct",
        type: "number",
        default: 10,
        min: 1,
        max: 100,
        description: "Position size as % of equity",
      },
    ],
    supportedMarkets: ["crypto", "equity", "commodity"],
  },
];
