import { i as OpenClawConfig } from "../../types.openclaw-BYfkTL_f.js";
import { S as MarkdownTableMode, _ as GroupPolicy } from "../../types.base-0oN-mnFt.js";
import { o as GroupToolPolicyConfig } from "../../types.tools-DLW0nzGW.js";
import { et as MSTeamsChannelConfig, it as MSTeamsTeamConfig, nt as MSTeamsReplyStyle, tt as MSTeamsConfig } from "../../types.channels-6kkMAKLf.js";
import { o as SsrFPolicy } from "../../ssrf-HuuPklwv.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Ds9BBXA3.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-C_h6wIm7.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-CNfePAuU.js";
import { n as RuntimeEnv } from "../../runtime-BGFXd35m.js";
import { n as ChannelOutboundAdapter } from "../../outbound.types-DuRB2RNl.js";
import { m as ChannelGroupContext, t as BaseProbeResult, u as ChannelDirectoryEntry } from "../../types.core-DMG-czl3.js";
import { O as buildMediaPayload, r as ReplyPayload } from "../../reply-payload-DpKGqclz.js";
import { n as ChannelPlugin, t as ChannelMessageActionName } from "../../types.public-C1Mqglnc.js";
import { n as PluginRuntime } from "../../types-PzLD5nJ3.js";
import { l as extractOriginalFilename } from "../../store-a9HWwy4M.js";
import { a as resolveToolsBySender } from "../../group-policy-CxeU_GX7.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DfNGR-8N.js";
import { c as resolveAllowlistMatchSimple, t as AllowlistMatch } from "../../allowlist-match-BZA8Pr5o.js";
import { s as normalizeStringEntries } from "../../string-normalization-x_uTWirA.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-C1kYqyXr.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-Bur1Py-O.js";
import { a as normalizeChannelSlug, i as buildChannelKeyCandidates, l as resolveNestedAllowlistDecision, s as resolveChannelEntryMatchWithFallback } from "../../channel-config-eqnLe3b3.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-CT-Dq5L6.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-CE8kF-5-.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-krgJT8On.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-Bb7YUMqW.js";
import { o as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-DLhsAKHN.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BJQxjUSA.js";
import { a as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-BeiSNxGo.js";
import { f as mergeAllowlist, m as summarizeMapping } from "../../allow-from-BDXyfWKn.js";
import { i as logTypingFailure } from "../../logging-BJYi2w-F.js";
import { u as withFileLock } from "../../file-lock-DdQUZeRU.js";
import { r as createChannelPairingController } from "../../channel-pairing-Lu6dsx7G.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CwtMbR6o.js";
import { t as setMSTeamsRuntime } from "../../runtime-api-BM9nNjTc.js";
export { AllowlistMatch, BaseProbeResult, ChannelDirectoryEntry, ChannelGroupContext, ChannelMessageActionName, ChannelOutboundAdapter, ChannelPlugin, DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, GroupPolicy, GroupToolPolicyConfig, MSTeamsChannelConfig, MSTeamsConfig, MSTeamsReplyStyle, MSTeamsTeamConfig, MarkdownTableMode, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, ReplyPayload, RuntimeEnv, SsrFPolicy, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };