export const browserCoreExamples = [
  "mullusi browser status",
  "mullusi browser start",
  "mullusi browser stop",
  "mullusi browser tabs",
  "mullusi browser open https://example.com",
  "mullusi browser focus abcd1234",
  "mullusi browser close abcd1234",
  "mullusi browser screenshot",
  "mullusi browser screenshot --full-page",
  "mullusi browser screenshot --ref 12",
  "mullusi browser snapshot",
  "mullusi browser snapshot --format aria --limit 200",
  "mullusi browser snapshot --efficient",
  "mullusi browser snapshot --labels",
];

export const browserActionExamples = [
  "mullusi browser navigate https://example.com",
  "mullusi browser resize 1280 720",
  "mullusi browser click 12 --double",
  'mullusi browser type 23 "hello" --submit',
  "mullusi browser press Enter",
  "mullusi browser hover 44",
  "mullusi browser drag 10 11",
  "mullusi browser select 9 OptionA OptionB",
  "mullusi browser upload /tmp/mullusi/uploads/file.pdf",
  'mullusi browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mullusi browser dialog --accept",
  'mullusi browser wait --text "Done"',
  "mullusi browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mullusi browser console --level error",
  "mullusi browser pdf",
];
