import { i as OpenClawConfig } from "../../types.openclaw-BMMD0Ykw.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DUJfIIgy.js";
import { s as AuthProfileStore } from "../../types-Ce68c77g.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-DaGHwSe6.js";
import { Wn as VideoGenerationProviderPlugin } from "../../types-CWJThuOe2.js";
import { n as createSubsystemLogger } from "../../subsystem-B5jYXQwj.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BcAEfWeg.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-BAaVOXU2.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CFt3Ciy4.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-CUrSWRWL.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-_N51KxDF.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-BWaJ8bNH.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };