import { i as resolveOpenProviderRuntimeGroupPolicy } from "../../runtime-group-policy-apkf7dQf.js";
import { a as mergeDiscordAccountConfig, f as resolveDiscordMaxLinesPerMessage, i as listEnabledDiscordAccounts, l as resolveDiscordAccountConfig, o as resolveDefaultDiscordAccountId, r as listDiscordAccountIds, s as resolveDiscordAccount, t as createDiscordActionGate } from "../../accounts-D7adEcBe.js";
import { t as inspectDiscordAccount } from "../../account-inspect-BqFYT3DT.js";
import { n as resolveDiscordChannelId, t as parseDiscordTarget } from "../../target-parsing-Boyot3d6.js";
import { n as fetchDiscord, r as requestDiscord, t as DiscordApiError } from "../../api-BNKL6f2E.js";
import { i as normalizeDiscordOutboundTarget, n as looksLikeDiscordTargetId, r as normalizeDiscordMessagingTarget } from "../../normalize-CWBFc2Qo.js";
import { n as resolveDiscordTarget, r as parseDiscordSendTarget } from "../../target-resolver-BTukvFs_.js";
import { a as buildDiscordComponentMessageFlags, c as resolveDiscordComponentAttachmentName, d as buildDiscordComponentCustomId, f as buildDiscordModalCustomId, g as parseDiscordModalCustomIdForInteraction, h as parseDiscordModalCustomId, i as buildDiscordComponentMessage, l as DISCORD_COMPONENT_CUSTOM_ID_KEY, m as parseDiscordComponentCustomIdForInteraction, n as DiscordFormModal, o as DISCORD_COMPONENT_ATTACHMENT_PREFIX, p as parseDiscordComponentCustomId, r as createDiscordFormModal, s as readDiscordComponentSpec, t as formatDiscordComponentEventText, u as DISCORD_MODAL_CUSTOM_ID_KEY } from "../../components-BPEU5Car.js";
import { t as buildDiscordInteractiveComponents } from "../../shared-interactive-BGoUDVx1.js";
import "../../targets-DFvrWrdA.js";
import { a as shouldSuppressLocalDiscordExecApprovalPrompt, i as isDiscordExecApprovalClientEnabled, n as getDiscordExecApprovalApprovers, r as isDiscordExecApprovalApprover } from "../../approval-shared-BUpXuojr.js";
import { i as resolveDiscordGroupToolPolicy, n as collectDiscordStatusIssues, r as resolveDiscordGroupRequireMention, t as discordPlugin } from "../../channel-B_l19a_y.js";
import { t as normalizeExplicitDiscordSessionKey } from "../../session-key-normalization-BV8an_F_.js";
import { t as discordSetupPlugin } from "../../channel.setup-Cv7LoIsa.js";
import { n as handleDiscordSubagentEnded, r as handleDiscordSubagentSpawning, t as handleDiscordSubagentDeliveryTarget } from "../../subagent-hooks-Cmel0KVk.js";
import { t as tryHandleDiscordMessageActionGuildAdmin } from "../../handle-action.guild-admin-CpjMXDQC.js";
import { n as listDiscordDirectoryPeersFromConfig, t as listDiscordDirectoryGroupsFromConfig } from "../../directory-config-CtRoW16z.js";
import { t as fetchPluralKitMessageInfo } from "../../pluralkit-BPLNBrvY.js";
import { a as resolveDiscordPrivilegedIntentsFromFlags, i as probeDiscord, n as fetchDiscordApplicationSummary, r as parseApplicationIdFromToken, t as fetchDiscordApplicationId } from "../../probe-ChnmDJTg.js";
import { t as collectDiscordSecurityAuditFindings } from "../../security-audit-kGNSSYTE.js";
import { a as mergeAbortSignals, i as DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, n as DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, r as DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, t as DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS } from "../../timeouts-C3hvukWp.js";
//#region extensions/discord/api.ts
const handleDiscordMessageAction = async (...args) => (await import("../../channel-actions.runtime-D0C5T77w.js")).handleDiscordMessageAction(...args);
//#endregion
export { DISCORD_ATTACHMENT_IDLE_TIMEOUT_MS, DISCORD_ATTACHMENT_TOTAL_TIMEOUT_MS, DISCORD_COMPONENT_ATTACHMENT_PREFIX, DISCORD_COMPONENT_CUSTOM_ID_KEY, DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS, DISCORD_DEFAULT_LISTENER_TIMEOUT_MS, DISCORD_MODAL_CUSTOM_ID_KEY, DiscordApiError, DiscordFormModal, buildDiscordComponentCustomId, buildDiscordComponentMessage, buildDiscordComponentMessageFlags, buildDiscordInteractiveComponents, buildDiscordModalCustomId, collectDiscordSecurityAuditFindings, collectDiscordStatusIssues, createDiscordActionGate, createDiscordFormModal, discordPlugin, discordSetupPlugin, fetchDiscord, fetchDiscordApplicationId, fetchDiscordApplicationSummary, fetchPluralKitMessageInfo, formatDiscordComponentEventText, getDiscordExecApprovalApprovers, handleDiscordMessageAction, handleDiscordSubagentDeliveryTarget, handleDiscordSubagentEnded, handleDiscordSubagentSpawning, inspectDiscordAccount, isDiscordExecApprovalApprover, isDiscordExecApprovalClientEnabled, listDiscordAccountIds, listDiscordDirectoryGroupsFromConfig, listDiscordDirectoryPeersFromConfig, listEnabledDiscordAccounts, looksLikeDiscordTargetId, mergeAbortSignals, mergeDiscordAccountConfig, normalizeDiscordMessagingTarget, normalizeDiscordOutboundTarget, normalizeExplicitDiscordSessionKey, parseApplicationIdFromToken, parseDiscordComponentCustomId, parseDiscordComponentCustomIdForInteraction as parseDiscordComponentCustomIdForCarbon, parseDiscordComponentCustomIdForInteraction, parseDiscordModalCustomId, parseDiscordModalCustomIdForInteraction as parseDiscordModalCustomIdForCarbon, parseDiscordModalCustomIdForInteraction, parseDiscordSendTarget, parseDiscordTarget, probeDiscord, readDiscordComponentSpec, requestDiscord, resolveDefaultDiscordAccountId, resolveDiscordAccount, resolveDiscordAccountConfig, resolveDiscordChannelId, resolveDiscordComponentAttachmentName, resolveDiscordGroupRequireMention, resolveDiscordGroupToolPolicy, resolveDiscordMaxLinesPerMessage, resolveDiscordPrivilegedIntentsFromFlags, resolveOpenProviderRuntimeGroupPolicy as resolveDiscordRuntimeGroupPolicy, resolveDiscordTarget, shouldSuppressLocalDiscordExecApprovalPrompt, tryHandleDiscordMessageActionGuildAdmin };
