import { i as OpenClawConfig } from "../../types.openclaw-BlE9q7jU.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-DPJ5My8u.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-K3KGpeVn.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-CHNX91pr.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-BoZgMdCh.js";
import { t as ChannelMessageActionName } from "../../types.public-Bp4rl8_W.js";
import { n as PluginRuntime } from "../../types-6GKVZ6OQ.js";
import { o as fetchRemoteMedia } from "../../fetch-GIaa1zLy.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-BcSZwXKC.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-DNQK_vYV.js";
import { r as buildChannelConfigSchema } from "../../config-schema-z_IyuJQR.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BruMQXri.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-BlQMW_d7.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-Cd8RuskB.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-Ya8W-NBn.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-B_Muqem1.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-CfYlXv7z.js";
import { n as resolveWebhookPath } from "../../webhook-path-Bs7GF6a1.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-Daiomu0c.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-BTk2AE7e.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-Dam_NyPH.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-bPcJbot3.js";
import { r as createChannelPairingController } from "../../channel-pairing-Br2SBmy5.js";
import { t as chunkTextForOutbound } from "../../text-chunking-Xn1GuzXu.js";
import { d as missingTargetError } from "../../channel-feedback-3LwyQx4L.js";
import { t as extractToolSend } from "../../tool-send-DJqmynCp.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-DSu_pNQM.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-C-iP9AV-.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchRemoteMedia, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };