import { p as isBlockedHostnameOrIp } from "../../ssrf-D7o7kbM-.js";
import { o as SessionEntry } from "../../types-CeXGWBP7.js";
import { C as OpenClawPluginApi } from "../../types-Cdl1yOYR.js";
import { _ as sleep } from "../../utils-Crlp6Geq.js";
import { r as GatewayRequestHandlerOptions } from "../../types-C70cVWuL.js";
import { t as definePluginEntry } from "../../plugin-entry-Ca1qCmfi.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BrZJ1X5M.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-C0IZ8R7N.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-BMacgZNy.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };