import { i as OpenClawConfig } from "../../types.openclaw-DPnlcagS.js";
import { ft as GoogleChatAccountConfig, mt as GoogleChatConfig } from "../../types.channels-DvgbEUo9.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-BLkNF-zo.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-CHNX91pr.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-CYkHgag6.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-remGx4m5.js";
import { t as ChannelMessageActionName } from "../../types.public-BlA4mimK.js";
import { n as PluginRuntime } from "../../types-CvAaVTok.js";
import { d as readRemoteMediaBuffer } from "../../fetch-DEguNGL_.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-C_gAmsRj.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-D5Xi2EwO.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BZ1GGqdH.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-DlNZ6eLr.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-CNTJMskH.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-CgfdTume.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-DGEqtp0p.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-vDiCF5CM.js";
import { n as resolveWebhookPath } from "../../webhook-path-BF_Ni5yZ.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CT5xAlrM.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-Br6neYyv.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-BKfYxNpj.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-CHsuUwe8.js";
import { r as createChannelPairingController } from "../../channel-pairing-DHrwWyRA.js";
import { t as chunkTextForOutbound } from "../../text-chunking-DRPNmnpl.js";
import { m as missingTargetError } from "../../channel-feedback-DT-CMSP-.js";
import { t as extractToolSend } from "../../tool-send-Dc6gv4rz.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-W2GkcRM5.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-rhvI65og.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };