import { i as OpenClawConfig } from "../../types.openclaw-C5VNg6h3.js";
import { t as FallbackAttempt } from "../../model-fallback.types-DiKlaksI.js";
import { s as AuthProfileStore } from "../../types-T6Kv1yTQ2.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-C_p6LFqB.js";
import { Wn as VideoGenerationProviderPlugin } from "../../types-Dggwf5Fv.js";
import { n as createSubsystemLogger } from "../../subsystem-CodqpXnP.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-DHHhLue8.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-Bo6XL9xN.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CAfYJ6I0.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-DMXAZirw.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-CFiEYV4U.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-i-Mkdnl4.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };