// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               unknown
// source: envd/v1/filesystem.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envd.v1";

/** FileInfo describes a file or directory entry. */
export interface FileInfo {
  name: string;
  size: number;
  mode: number;
  isDir: boolean;
  modTimeUnix: number;
}

export interface StatRequest {
  path: string;
}

export interface StatResponse {
  path: string;
  size: number;
  mode: number;
  isDir: boolean;
  modTimeUnix: number;
}

export interface ReadFileRequest {
  path: string;
}

export interface ReadFileResponse {
  data: Buffer;
  eof: boolean;
}

export interface WriteFileRequest {
  /** Path to write to (must be set in the first chunk). */
  path: string;
  /** File permission mode (optional, default 0644, only used from first chunk). */
  mode: number;
  /** File data chunk. */
  data: Buffer;
}

export interface WriteFileResponse {
  bytesWritten: number;
}

export interface ListDirRequest {
  path: string;
}

export interface ListDirResponse {
  entries: FileInfo[];
}

export interface MakeDirRequest {
  path: string;
  /** Permission mode (default 0755). */
  mode: number;
}

export interface MakeDirResponse {}

export interface RemoveRequest {
  path: string;
  /** If true, removes directory contents recursively. */
  recursive: boolean;
}

export interface RemoveResponse {}

function createBaseFileInfo(): FileInfo {
  return { name: "", size: 0, mode: 0, isDir: false, modTimeUnix: 0 };
}

export const FileInfo: MessageFns<FileInfo> = {
  encode(message: FileInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.size !== 0) {
      writer.uint32(16).int64(message.size);
    }
    if (message.mode !== 0) {
      writer.uint32(24).uint32(message.mode);
    }
    if (message.isDir !== false) {
      writer.uint32(32).bool(message.isDir);
    }
    if (message.modTimeUnix !== 0) {
      writer.uint32(40).int64(message.modTimeUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isDir = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.modTimeUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileInfo {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
      isDir: isSet(object.isDir)
        ? globalThis.Boolean(object.isDir)
        : isSet(object.is_dir)
          ? globalThis.Boolean(object.is_dir)
          : false,
      modTimeUnix: isSet(object.modTimeUnix)
        ? globalThis.Number(object.modTimeUnix)
        : isSet(object.mod_time_unix)
          ? globalThis.Number(object.mod_time_unix)
          : 0,
    };
  },

  toJSON(message: FileInfo): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    if (message.isDir !== false) {
      obj.isDir = message.isDir;
    }
    if (message.modTimeUnix !== 0) {
      obj.modTimeUnix = Math.round(message.modTimeUnix);
    }
    return obj;
  },

  create(base?: DeepPartial<FileInfo>): FileInfo {
    return FileInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FileInfo>): FileInfo {
    const message = createBaseFileInfo();
    message.name = object.name ?? "";
    message.size = object.size ?? 0;
    message.mode = object.mode ?? 0;
    message.isDir = object.isDir ?? false;
    message.modTimeUnix = object.modTimeUnix ?? 0;
    return message;
  },
};

function createBaseStatRequest(): StatRequest {
  return { path: "" };
}

export const StatRequest: MessageFns<StatRequest> = {
  encode(message: StatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatRequest {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: StatRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create(base?: DeepPartial<StatRequest>): StatRequest {
    return StatRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatRequest>): StatRequest {
    const message = createBaseStatRequest();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseStatResponse(): StatResponse {
  return { path: "", size: 0, mode: 0, isDir: false, modTimeUnix: 0 };
}

export const StatResponse: MessageFns<StatResponse> = {
  encode(message: StatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.size !== 0) {
      writer.uint32(16).int64(message.size);
    }
    if (message.mode !== 0) {
      writer.uint32(24).uint32(message.mode);
    }
    if (message.isDir !== false) {
      writer.uint32(32).bool(message.isDir);
    }
    if (message.modTimeUnix !== 0) {
      writer.uint32(40).int64(message.modTimeUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isDir = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.modTimeUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatResponse {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
      isDir: isSet(object.isDir)
        ? globalThis.Boolean(object.isDir)
        : isSet(object.is_dir)
          ? globalThis.Boolean(object.is_dir)
          : false,
      modTimeUnix: isSet(object.modTimeUnix)
        ? globalThis.Number(object.modTimeUnix)
        : isSet(object.mod_time_unix)
          ? globalThis.Number(object.mod_time_unix)
          : 0,
    };
  },

  toJSON(message: StatResponse): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    if (message.isDir !== false) {
      obj.isDir = message.isDir;
    }
    if (message.modTimeUnix !== 0) {
      obj.modTimeUnix = Math.round(message.modTimeUnix);
    }
    return obj;
  },

  create(base?: DeepPartial<StatResponse>): StatResponse {
    return StatResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatResponse>): StatResponse {
    const message = createBaseStatResponse();
    message.path = object.path ?? "";
    message.size = object.size ?? 0;
    message.mode = object.mode ?? 0;
    message.isDir = object.isDir ?? false;
    message.modTimeUnix = object.modTimeUnix ?? 0;
    return message;
  },
};

function createBaseReadFileRequest(): ReadFileRequest {
  return { path: "" };
}

export const ReadFileRequest: MessageFns<ReadFileRequest> = {
  encode(message: ReadFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadFileRequest {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: ReadFileRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create(base?: DeepPartial<ReadFileRequest>): ReadFileRequest {
    return ReadFileRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadFileRequest>): ReadFileRequest {
    const message = createBaseReadFileRequest();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseReadFileResponse(): ReadFileResponse {
  return { data: Buffer.alloc(0), eof: false };
}

export const ReadFileResponse: MessageFns<ReadFileResponse> = {
  encode(message: ReadFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.eof !== false) {
      writer.uint32(16).bool(message.eof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.eof = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadFileResponse {
    return {
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
      eof: isSet(object.eof) ? globalThis.Boolean(object.eof) : false,
    };
  },

  toJSON(message: ReadFileResponse): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.eof !== false) {
      obj.eof = message.eof;
    }
    return obj;
  },

  create(base?: DeepPartial<ReadFileResponse>): ReadFileResponse {
    return ReadFileResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadFileResponse>): ReadFileResponse {
    const message = createBaseReadFileResponse();
    message.data = object.data ?? Buffer.alloc(0);
    message.eof = object.eof ?? false;
    return message;
  },
};

function createBaseWriteFileRequest(): WriteFileRequest {
  return { path: "", mode: 0, data: Buffer.alloc(0) };
}

export const WriteFileRequest: MessageFns<WriteFileRequest> = {
  encode(message: WriteFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.mode !== 0) {
      writer.uint32(16).uint32(message.mode);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WriteFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWriteFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WriteFileRequest {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: WriteFileRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create(base?: DeepPartial<WriteFileRequest>): WriteFileRequest {
    return WriteFileRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WriteFileRequest>): WriteFileRequest {
    const message = createBaseWriteFileRequest();
    message.path = object.path ?? "";
    message.mode = object.mode ?? 0;
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseWriteFileResponse(): WriteFileResponse {
  return { bytesWritten: 0 };
}

export const WriteFileResponse: MessageFns<WriteFileResponse> = {
  encode(message: WriteFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bytesWritten !== 0) {
      writer.uint32(8).int64(message.bytesWritten);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WriteFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWriteFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bytesWritten = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WriteFileResponse {
    return {
      bytesWritten: isSet(object.bytesWritten)
        ? globalThis.Number(object.bytesWritten)
        : isSet(object.bytes_written)
          ? globalThis.Number(object.bytes_written)
          : 0,
    };
  },

  toJSON(message: WriteFileResponse): unknown {
    const obj: any = {};
    if (message.bytesWritten !== 0) {
      obj.bytesWritten = Math.round(message.bytesWritten);
    }
    return obj;
  },

  create(base?: DeepPartial<WriteFileResponse>): WriteFileResponse {
    return WriteFileResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WriteFileResponse>): WriteFileResponse {
    const message = createBaseWriteFileResponse();
    message.bytesWritten = object.bytesWritten ?? 0;
    return message;
  },
};

function createBaseListDirRequest(): ListDirRequest {
  return { path: "" };
}

export const ListDirRequest: MessageFns<ListDirRequest> = {
  encode(message: ListDirRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDirRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDirRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDirRequest {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: ListDirRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create(base?: DeepPartial<ListDirRequest>): ListDirRequest {
    return ListDirRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListDirRequest>): ListDirRequest {
    const message = createBaseListDirRequest();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseListDirResponse(): ListDirResponse {
  return { entries: [] };
}

export const ListDirResponse: MessageFns<ListDirResponse> = {
  encode(message: ListDirResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      FileInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDirResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDirResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(FileInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListDirResponse {
    return {
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => FileInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListDirResponse): unknown {
    const obj: any = {};
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => FileInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListDirResponse>): ListDirResponse {
    return ListDirResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListDirResponse>): ListDirResponse {
    const message = createBaseListDirResponse();
    message.entries = object.entries?.map((e) => FileInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMakeDirRequest(): MakeDirRequest {
  return { path: "", mode: 0 };
}

export const MakeDirRequest: MessageFns<MakeDirRequest> = {
  encode(message: MakeDirRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.mode !== 0) {
      writer.uint32(16).uint32(message.mode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MakeDirRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMakeDirRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mode = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MakeDirRequest {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      mode: isSet(object.mode) ? globalThis.Number(object.mode) : 0,
    };
  },

  toJSON(message: MakeDirRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.mode !== 0) {
      obj.mode = Math.round(message.mode);
    }
    return obj;
  },

  create(base?: DeepPartial<MakeDirRequest>): MakeDirRequest {
    return MakeDirRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MakeDirRequest>): MakeDirRequest {
    const message = createBaseMakeDirRequest();
    message.path = object.path ?? "";
    message.mode = object.mode ?? 0;
    return message;
  },
};

function createBaseMakeDirResponse(): MakeDirResponse {
  return {};
}

export const MakeDirResponse: MessageFns<MakeDirResponse> = {
  encode(_: MakeDirResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MakeDirResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMakeDirResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MakeDirResponse {
    return {};
  },

  toJSON(_: MakeDirResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MakeDirResponse>): MakeDirResponse {
    return MakeDirResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MakeDirResponse>): MakeDirResponse {
    const message = createBaseMakeDirResponse();
    return message;
  },
};

function createBaseRemoveRequest(): RemoveRequest {
  return { path: "", recursive: false };
}

export const RemoveRequest: MessageFns<RemoveRequest> = {
  encode(message: RemoveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.recursive !== false) {
      writer.uint32(16).bool(message.recursive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.recursive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveRequest {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      recursive: isSet(object.recursive) ? globalThis.Boolean(object.recursive) : false,
    };
  },

  toJSON(message: RemoveRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.recursive !== false) {
      obj.recursive = message.recursive;
    }
    return obj;
  },

  create(base?: DeepPartial<RemoveRequest>): RemoveRequest {
    return RemoveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RemoveRequest>): RemoveRequest {
    const message = createBaseRemoveRequest();
    message.path = object.path ?? "";
    message.recursive = object.recursive ?? false;
    return message;
  },
};

function createBaseRemoveResponse(): RemoveResponse {
  return {};
}

export const RemoveResponse: MessageFns<RemoveResponse> = {
  encode(_: RemoveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RemoveResponse {
    return {};
  },

  toJSON(_: RemoveResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<RemoveResponse>): RemoveResponse {
    return RemoveResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<RemoveResponse>): RemoveResponse {
    const message = createBaseRemoveResponse();
    return message;
  },
};

/** FileService provides filesystem operations inside the MicroVM. */
export type FileServiceDefinition = typeof FileServiceDefinition;
export const FileServiceDefinition = {
  name: "FileService",
  fullName: "envd.v1.FileService",
  methods: {
    /** Stat returns metadata for a file or directory. */
    stat: {
      name: "Stat",
      requestType: StatRequest as typeof StatRequest,
      requestStream: false,
      responseType: StatResponse as typeof StatResponse,
      responseStream: false,
      options: {},
    },
    /** ReadFile reads a file and streams its content in chunks. */
    readFile: {
      name: "ReadFile",
      requestType: ReadFileRequest as typeof ReadFileRequest,
      requestStream: false,
      responseType: ReadFileResponse as typeof ReadFileResponse,
      responseStream: true,
      options: {},
    },
    /** WriteFile accepts a stream of chunks and writes them to a file. */
    writeFile: {
      name: "WriteFile",
      requestType: WriteFileRequest as typeof WriteFileRequest,
      requestStream: true,
      responseType: WriteFileResponse as typeof WriteFileResponse,
      responseStream: false,
      options: {},
    },
    /** ListDir returns directory entries with metadata. */
    listDir: {
      name: "ListDir",
      requestType: ListDirRequest as typeof ListDirRequest,
      requestStream: false,
      responseType: ListDirResponse as typeof ListDirResponse,
      responseStream: false,
      options: {},
    },
    /** MakeDir creates directories recursively. */
    makeDir: {
      name: "MakeDir",
      requestType: MakeDirRequest as typeof MakeDirRequest,
      requestStream: false,
      responseType: MakeDirResponse as typeof MakeDirResponse,
      responseStream: false,
      options: {},
    },
    /** Remove deletes files or directories. */
    remove: {
      name: "Remove",
      requestType: RemoveRequest as typeof RemoveRequest,
      requestStream: false,
      responseType: RemoveResponse as typeof RemoveResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
