// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               unknown
// source: envd/v1/health.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envd.v1";

export enum ServingStatus {
  SERVING_STATUS_UNSPECIFIED = 0,
  SERVING_STATUS_SERVING = 1,
  SERVING_STATUS_NOT_SERVING = 2,
  UNRECOGNIZED = -1,
}

export function servingStatusFromJSON(object: any): ServingStatus {
  switch (object) {
    case 0:
    case "SERVING_STATUS_UNSPECIFIED":
      return ServingStatus.SERVING_STATUS_UNSPECIFIED;
    case 1:
    case "SERVING_STATUS_SERVING":
      return ServingStatus.SERVING_STATUS_SERVING;
    case 2:
    case "SERVING_STATUS_NOT_SERVING":
      return ServingStatus.SERVING_STATUS_NOT_SERVING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServingStatus.UNRECOGNIZED;
  }
}

export function servingStatusToJSON(object: ServingStatus): string {
  switch (object) {
    case ServingStatus.SERVING_STATUS_UNSPECIFIED:
      return "SERVING_STATUS_UNSPECIFIED";
    case ServingStatus.SERVING_STATUS_SERVING:
      return "SERVING_STATUS_SERVING";
    case ServingStatus.SERVING_STATUS_NOT_SERVING:
      return "SERVING_STATUS_NOT_SERVING";
    case ServingStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CheckRequest {}

export interface CheckResponse {
  status: ServingStatus;
}

function createBaseCheckRequest(): CheckRequest {
  return {};
}

export const CheckRequest: MessageFns<CheckRequest> = {
  encode(_: CheckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CheckRequest {
    return {};
  },

  toJSON(_: CheckRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<CheckRequest>): CheckRequest {
    return CheckRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<CheckRequest>): CheckRequest {
    const message = createBaseCheckRequest();
    return message;
  },
};

function createBaseCheckResponse(): CheckResponse {
  return { status: 0 };
}

export const CheckResponse: MessageFns<CheckResponse> = {
  encode(message: CheckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckResponse {
    return { status: isSet(object.status) ? servingStatusFromJSON(object.status) : 0 };
  },

  toJSON(message: CheckResponse): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = servingStatusToJSON(message.status);
    }
    return obj;
  },

  create(base?: DeepPartial<CheckResponse>): CheckResponse {
    return CheckResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CheckResponse>): CheckResponse {
    const message = createBaseCheckResponse();
    message.status = object.status ?? 0;
    return message;
  },
};

/** HealthService provides a readiness check for envd. */
export type HealthServiceDefinition = typeof HealthServiceDefinition;
export const HealthServiceDefinition = {
  name: "HealthService",
  fullName: "envd.v1.HealthService",
  methods: {
    /** Check returns the current health status of the envd agent. */
    check: {
      name: "Check",
      requestType: CheckRequest as typeof CheckRequest,
      requestStream: false,
      responseType: CheckResponse as typeof CheckResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
