// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               unknown
// source: envd/v1/process.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envd.v1";

export interface StartRequest {
  /** Shell command to execute via sh -lc. */
  command: string;
  /** Working directory (default: /workspace). */
  workdir: string;
  /** Environment variables to set. */
  env: { [key: string]: string };
  /** Execution timeout in seconds (0 = no timeout). */
  timeoutSec: number;
}

export interface StartRequest_EnvEntry {
  key: string;
  value: string;
}

export interface StartResponse {
  stdout?: Buffer | undefined;
  stderr?: Buffer | undefined;
  /** True when the process has exited and all output has been sent. */
  eof: boolean;
  /** Process exit code, set only when eof=true. */
  exitCode: number;
  /** Server-assigned process identifier, set in the first response message. */
  processId: string;
  /** True if the process was killed due to timeout, set only when eof=true. */
  timedOut: boolean;
}

export interface SendInputRequest {
  /** Target process identifier. */
  processId: string;
  /** Data to write to the process stdin. */
  data: Buffer;
}

export interface SendInputResponse {}

export interface SendSignalRequest {
  /** Target process identifier. */
  processId: string;
  /** Signal number to send (e.g. 15 for SIGTERM, 9 for SIGKILL). */
  signal: number;
}

export interface SendSignalResponse {}

export interface ListRequest {}

export interface ListResponse {
  processes: ProcessInfo[];
}

export interface ProcessInfo {
  processId: string;
  command: string;
  running: boolean;
}

function createBaseStartRequest(): StartRequest {
  return { command: "", workdir: "", env: {}, timeoutSec: 0 };
}

export const StartRequest: MessageFns<StartRequest> = {
  encode(message: StartRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.command !== "") {
      writer.uint32(10).string(message.command);
    }
    if (message.workdir !== "") {
      writer.uint32(18).string(message.workdir);
    }
    globalThis.Object.entries(message.env).forEach(([key, value]: [string, string]) => {
      StartRequest_EnvEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.timeoutSec !== 0) {
      writer.uint32(32).uint32(message.timeoutSec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.command = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workdir = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = StartRequest_EnvEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.env[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timeoutSec = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartRequest {
    return {
      command: isSet(object.command) ? globalThis.String(object.command) : "",
      workdir: isSet(object.workdir) ? globalThis.String(object.workdir) : "",
      env: isObject(object.env)
        ? (globalThis.Object.entries(object.env) as [string, any][]).reduce(
            (acc: { [key: string]: string }, [key, value]: [string, any]) => {
              acc[key] = globalThis.String(value);
              return acc;
            },
            {},
          )
        : {},
      timeoutSec: isSet(object.timeoutSec)
        ? globalThis.Number(object.timeoutSec)
        : isSet(object.timeout_sec)
          ? globalThis.Number(object.timeout_sec)
          : 0,
    };
  },

  toJSON(message: StartRequest): unknown {
    const obj: any = {};
    if (message.command !== "") {
      obj.command = message.command;
    }
    if (message.workdir !== "") {
      obj.workdir = message.workdir;
    }
    if (message.env) {
      const entries = globalThis.Object.entries(message.env) as [string, string][];
      if (entries.length > 0) {
        obj.env = {};
        entries.forEach(([k, v]) => {
          obj.env[k] = v;
        });
      }
    }
    if (message.timeoutSec !== 0) {
      obj.timeoutSec = Math.round(message.timeoutSec);
    }
    return obj;
  },

  create(base?: DeepPartial<StartRequest>): StartRequest {
    return StartRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartRequest>): StartRequest {
    const message = createBaseStartRequest();
    message.command = object.command ?? "";
    message.workdir = object.workdir ?? "";
    message.env = (globalThis.Object.entries(object.env ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.timeoutSec = object.timeoutSec ?? 0;
    return message;
  },
};

function createBaseStartRequest_EnvEntry(): StartRequest_EnvEntry {
  return { key: "", value: "" };
}

export const StartRequest_EnvEntry: MessageFns<StartRequest_EnvEntry> = {
  encode(message: StartRequest_EnvEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartRequest_EnvEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartRequest_EnvEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartRequest_EnvEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: StartRequest_EnvEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<StartRequest_EnvEntry>): StartRequest_EnvEntry {
    return StartRequest_EnvEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartRequest_EnvEntry>): StartRequest_EnvEntry {
    const message = createBaseStartRequest_EnvEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseStartResponse(): StartResponse {
  return {
    stdout: undefined,
    stderr: undefined,
    eof: false,
    exitCode: 0,
    processId: "",
    timedOut: false,
  };
}

export const StartResponse: MessageFns<StartResponse> = {
  encode(message: StartResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stdout !== undefined) {
      writer.uint32(10).bytes(message.stdout);
    }
    if (message.stderr !== undefined) {
      writer.uint32(18).bytes(message.stderr);
    }
    if (message.eof !== false) {
      writer.uint32(24).bool(message.eof);
    }
    if (message.exitCode !== 0) {
      writer.uint32(32).int32(message.exitCode);
    }
    if (message.processId !== "") {
      writer.uint32(42).string(message.processId);
    }
    if (message.timedOut !== false) {
      writer.uint32(48).bool(message.timedOut);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stdout = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stderr = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.eof = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.exitCode = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.processId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timedOut = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartResponse {
    return {
      stdout: isSet(object.stdout) ? Buffer.from(bytesFromBase64(object.stdout)) : undefined,
      stderr: isSet(object.stderr) ? Buffer.from(bytesFromBase64(object.stderr)) : undefined,
      eof: isSet(object.eof) ? globalThis.Boolean(object.eof) : false,
      exitCode: isSet(object.exitCode)
        ? globalThis.Number(object.exitCode)
        : isSet(object.exit_code)
          ? globalThis.Number(object.exit_code)
          : 0,
      processId: isSet(object.processId)
        ? globalThis.String(object.processId)
        : isSet(object.process_id)
          ? globalThis.String(object.process_id)
          : "",
      timedOut: isSet(object.timedOut)
        ? globalThis.Boolean(object.timedOut)
        : isSet(object.timed_out)
          ? globalThis.Boolean(object.timed_out)
          : false,
    };
  },

  toJSON(message: StartResponse): unknown {
    const obj: any = {};
    if (message.stdout !== undefined) {
      obj.stdout = base64FromBytes(message.stdout);
    }
    if (message.stderr !== undefined) {
      obj.stderr = base64FromBytes(message.stderr);
    }
    if (message.eof !== false) {
      obj.eof = message.eof;
    }
    if (message.exitCode !== 0) {
      obj.exitCode = Math.round(message.exitCode);
    }
    if (message.processId !== "") {
      obj.processId = message.processId;
    }
    if (message.timedOut !== false) {
      obj.timedOut = message.timedOut;
    }
    return obj;
  },

  create(base?: DeepPartial<StartResponse>): StartResponse {
    return StartResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StartResponse>): StartResponse {
    const message = createBaseStartResponse();
    message.stdout = object.stdout ?? undefined;
    message.stderr = object.stderr ?? undefined;
    message.eof = object.eof ?? false;
    message.exitCode = object.exitCode ?? 0;
    message.processId = object.processId ?? "";
    message.timedOut = object.timedOut ?? false;
    return message;
  },
};

function createBaseSendInputRequest(): SendInputRequest {
  return { processId: "", data: Buffer.alloc(0) };
}

export const SendInputRequest: MessageFns<SendInputRequest> = {
  encode(message: SendInputRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processId !== "") {
      writer.uint32(10).string(message.processId);
    }
    if (message.data.length !== 0) {
      writer.uint32(18).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendInputRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendInputRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendInputRequest {
    return {
      processId: isSet(object.processId)
        ? globalThis.String(object.processId)
        : isSet(object.process_id)
          ? globalThis.String(object.process_id)
          : "",
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: SendInputRequest): unknown {
    const obj: any = {};
    if (message.processId !== "") {
      obj.processId = message.processId;
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create(base?: DeepPartial<SendInputRequest>): SendInputRequest {
    return SendInputRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendInputRequest>): SendInputRequest {
    const message = createBaseSendInputRequest();
    message.processId = object.processId ?? "";
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseSendInputResponse(): SendInputResponse {
  return {};
}

export const SendInputResponse: MessageFns<SendInputResponse> = {
  encode(_: SendInputResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendInputResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendInputResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SendInputResponse {
    return {};
  },

  toJSON(_: SendInputResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SendInputResponse>): SendInputResponse {
    return SendInputResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SendInputResponse>): SendInputResponse {
    const message = createBaseSendInputResponse();
    return message;
  },
};

function createBaseSendSignalRequest(): SendSignalRequest {
  return { processId: "", signal: 0 };
}

export const SendSignalRequest: MessageFns<SendSignalRequest> = {
  encode(message: SendSignalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processId !== "") {
      writer.uint32(10).string(message.processId);
    }
    if (message.signal !== 0) {
      writer.uint32(16).int32(message.signal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendSignalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendSignalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.signal = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendSignalRequest {
    return {
      processId: isSet(object.processId)
        ? globalThis.String(object.processId)
        : isSet(object.process_id)
          ? globalThis.String(object.process_id)
          : "",
      signal: isSet(object.signal) ? globalThis.Number(object.signal) : 0,
    };
  },

  toJSON(message: SendSignalRequest): unknown {
    const obj: any = {};
    if (message.processId !== "") {
      obj.processId = message.processId;
    }
    if (message.signal !== 0) {
      obj.signal = Math.round(message.signal);
    }
    return obj;
  },

  create(base?: DeepPartial<SendSignalRequest>): SendSignalRequest {
    return SendSignalRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendSignalRequest>): SendSignalRequest {
    const message = createBaseSendSignalRequest();
    message.processId = object.processId ?? "";
    message.signal = object.signal ?? 0;
    return message;
  },
};

function createBaseSendSignalResponse(): SendSignalResponse {
  return {};
}

export const SendSignalResponse: MessageFns<SendSignalResponse> = {
  encode(_: SendSignalResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendSignalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendSignalResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SendSignalResponse {
    return {};
  },

  toJSON(_: SendSignalResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<SendSignalResponse>): SendSignalResponse {
    return SendSignalResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SendSignalResponse>): SendSignalResponse {
    const message = createBaseSendSignalResponse();
    return message;
  },
};

function createBaseListRequest(): ListRequest {
  return {};
}

export const ListRequest: MessageFns<ListRequest> = {
  encode(_: ListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListRequest {
    return {};
  },

  toJSON(_: ListRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<ListRequest>): ListRequest {
    return ListRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListRequest>): ListRequest {
    const message = createBaseListRequest();
    return message;
  },
};

function createBaseListResponse(): ListResponse {
  return { processes: [] };
}

export const ListResponse: MessageFns<ListResponse> = {
  encode(message: ListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.processes) {
      ProcessInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processes.push(ProcessInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListResponse {
    return {
      processes: globalThis.Array.isArray(object?.processes)
        ? object.processes.map((e: any) => ProcessInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListResponse): unknown {
    const obj: any = {};
    if (message.processes?.length) {
      obj.processes = message.processes.map((e) => ProcessInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListResponse>): ListResponse {
    return ListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListResponse>): ListResponse {
    const message = createBaseListResponse();
    message.processes = object.processes?.map((e) => ProcessInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseProcessInfo(): ProcessInfo {
  return { processId: "", command: "", running: false };
}

export const ProcessInfo: MessageFns<ProcessInfo> = {
  encode(message: ProcessInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processId !== "") {
      writer.uint32(10).string(message.processId);
    }
    if (message.command !== "") {
      writer.uint32(18).string(message.command);
    }
    if (message.running !== false) {
      writer.uint32(24).bool(message.running);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.processId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.command = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.running = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessInfo {
    return {
      processId: isSet(object.processId)
        ? globalThis.String(object.processId)
        : isSet(object.process_id)
          ? globalThis.String(object.process_id)
          : "",
      command: isSet(object.command) ? globalThis.String(object.command) : "",
      running: isSet(object.running) ? globalThis.Boolean(object.running) : false,
    };
  },

  toJSON(message: ProcessInfo): unknown {
    const obj: any = {};
    if (message.processId !== "") {
      obj.processId = message.processId;
    }
    if (message.command !== "") {
      obj.command = message.command;
    }
    if (message.running !== false) {
      obj.running = message.running;
    }
    return obj;
  },

  create(base?: DeepPartial<ProcessInfo>): ProcessInfo {
    return ProcessInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProcessInfo>): ProcessInfo {
    const message = createBaseProcessInfo();
    message.processId = object.processId ?? "";
    message.command = object.command ?? "";
    message.running = object.running ?? false;
    return message;
  },
};

/** ProcessService manages command execution inside the MicroVM. */
export type ProcessServiceDefinition = typeof ProcessServiceDefinition;
export const ProcessServiceDefinition = {
  name: "ProcessService",
  fullName: "envd.v1.ProcessService",
  methods: {
    /** Start executes a command and streams stdout/stderr back. */
    start: {
      name: "Start",
      requestType: StartRequest as typeof StartRequest,
      requestStream: false,
      responseType: StartResponse as typeof StartResponse,
      responseStream: true,
      options: {},
    },
    /** SendInput writes data to a running process's stdin. */
    sendInput: {
      name: "SendInput",
      requestType: SendInputRequest as typeof SendInputRequest,
      requestStream: false,
      responseType: SendInputResponse as typeof SendInputResponse,
      responseStream: false,
      options: {},
    },
    /** SendSignal sends a signal to a running process group. */
    sendSignal: {
      name: "SendSignal",
      requestType: SendSignalRequest as typeof SendSignalRequest,
      requestStream: false,
      responseType: SendSignalResponse as typeof SendSignalResponse,
      responseStream: false,
      options: {},
    },
    /** List returns all currently tracked processes. */
    list: {
      name: "List",
      requestType: ListRequest as typeof ListRequest,
      requestStream: false,
      responseType: ListResponse as typeof ListResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
