/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface DeliveryAttemptEvidence {
  attempted_at: number | null;
  created_at: number;
  dedupe_key: string;
  delivery_attempt_id: string;
  delivery_claim_expires_at: number | null;
  delivery_claimed_by: string | null;
  error_message: string | null;
  evidence_json: string | null;
  failed_at: number | null;
  handoff_accepted_at: number | null;
  metadata_json: string | null;
  replay_pass_id: string | null;
  route_kind: string | null;
  route_ref: string | null;
  scheduled_at: number;
  source_owner: string;
  source_ref: string;
  status: string;
  target_kind: string | null;
  target_ref: string | null;
  unknown_at: number | null;
  updated_at: number;
  wake_id: string;
}

export interface DurableEventEvidence {
  agent_invocation_id: string | null;
  causation_event_id: string | null;
  checkpoint_ref: string | null;
  correlation_id: string | null;
  event_id: string;
  event_seq: number;
  event_time: number;
  event_type: string;
  idempotency_key: string | null;
  payload_hash: string | null;
  payload_json: string | null;
  recorded_at: number;
  runtime_run_id: string;
  step_id: string | null;
  tool_invocation_id: string | null;
}

export interface DurableExecutionRecords {
  checkpoint_ref: string | null;
  completed_at: number | null;
  created_at: number;
  heartbeat_at: number | null;
  idempotency_key: string | null;
  input_ref: string | null;
  message_id: string | null;
  metadata_json: string | null;
  operation_kind: string;
  operation_version: Generated<string>;
  parent_runtime_run_id: string | null;
  parent_step_id: string | null;
  recovery_state: Generated<string>;
  report_route_id: string | null;
  request_hash: string | null;
  runtime_run_id: string;
  source_owner: string | null;
  source_ref: string | null;
  status: string;
  turn_id: string | null;
  updated_at: number;
  work_unit_id: string | null;
}

export interface DurableExecutionSteps {
  attempt: Generated<number>;
  checkpoint_ref: string | null;
  claim_expires_at: number | null;
  claimed_by: string | null;
  completed_at: number | null;
  created_at: number;
  error_ref: string | null;
  heartbeat_at: number | null;
  idempotency_key: string | null;
  input_ref: string | null;
  max_attempts: number | null;
  metadata_json: string | null;
  output_ref: string | null;
  parent_step_id: string | null;
  recovery_state: string;
  runtime_run_id: string;
  started_at: number | null;
  status: string;
  step_id: string;
  step_type: string;
  updated_at: number;
}

export interface DurablePayloadRefs {
  created_at: number;
  hash: string | null;
  media_type: string | null;
  metadata_json: string | null;
  ref_id: string;
  ref_kind: string;
  runtime_run_id: string;
  step_id: string | null;
  storage_kind: string;
  storage_uri: string | null;
}

export interface DurableRunCorrelations {
  child_runtime_run_id: string;
  created_at: number;
  link_type: string;
  metadata_json: string | null;
  parent_runtime_run_id: string;
  parent_step_id: string;
  status: string;
  updated_at: number;
}

export interface DurableSignalEvidence {
  consumed_at: number | null;
  correlation_id: string | null;
  idempotency_key: string | null;
  metadata_json: string | null;
  payload_ref: string | null;
  received_at: number;
  runtime_run_id: string;
  signal_id: string;
  signal_type: string;
  step_id: string | null;
}

export interface DurableTimerObligations {
  cancelled_at: number | null;
  created_at: number;
  due_at: number;
  fired_at: number | null;
  metadata_json: string | null;
  runtime_run_id: string;
  status: string;
  step_id: string | null;
  timer_id: string;
  timer_type: string;
}

export interface UncertaintyFacts {
  created_at: number;
  dedupe_key: string | null;
  event_id: string | null;
  fact_id: string;
  facts_json: string | null;
  facts_ref: string | null;
  kind: string;
  metadata_json: string | null;
  ref_id: string | null;
  resolution_kind: string | null;
  resolution_ref: string | null;
  resolved_at: number | null;
  source_owner: string;
  source_ref: string;
  source_run_id: string | null;
  status: string;
  step_id: string | null;
  updated_at: number;
}

export interface WakeObligations {
  acked_at: number | null;
  attempt_count: Generated<number>;
  created_at: number;
  dedupe_key: string;
  facts_ref: string | null;
  failed_reason: string | null;
  last_attempt_at: number | null;
  metadata_json: string | null;
  owner_kind: string | null;
  owner_ref: string | null;
  parent_run_id: string | null;
  parent_session_key: string | null;
  reason: string;
  report_route_ref: string | null;
  source_owner: string;
  source_ref: string;
  source_run_id: string | null;
  status: string;
  target_agent: string | null;
  target_channel: string | null;
  target_kind: string | null;
  target_ref: string | null;
  target_resolution_reason: string | null;
  target_resolution_status: string | null;
  target_session: string | null;
  updated_at: number;
  wake_id: string;
}

export interface DB {
  delivery_attempt_evidence: DeliveryAttemptEvidence;
  durable_event_evidence: DurableEventEvidence;
  durable_execution_records: DurableExecutionRecords;
  durable_execution_steps: DurableExecutionSteps;
  durable_payload_refs: DurablePayloadRefs;
  durable_run_correlations: DurableRunCorrelations;
  durable_signal_evidence: DurableSignalEvidence;
  durable_timer_obligations: DurableTimerObligations;
  uncertainty_facts: UncertaintyFacts;
  wake_obligations: WakeObligations;
}
