import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-05Z3mmpO.js";
import { s as normalizeStringEntries } from "../../string-normalization-BeeXgDIU.js";
import { a as withFileLock } from "../../file-lock-CQT0mhTn.js";
import { a as resolveChannelEntryMatchWithFallback, n as buildChannelKeyCandidates, r as normalizeChannelSlug, s as resolveNestedAllowlistDecision } from "../../channel-config-CRL3C52q.js";
import { a as resolveAllowlistMatchSimple } from "../../allowlist-match-BS5FqXk-.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-CeZSHsWQ.js";
import { n as fetchWithSsrFGuard } from "../../fetch-guard-CmN33efq.js";
import { S as buildMediaPayload } from "../../reply-payload-C2gvzrRj.js";
import { o as extractOriginalFilename } from "../../store-yK49THmd.js";
import { i as resolveToolsBySender } from "../../group-policy-CHIp1weU.js";
import { t as createChannelReplyPipeline } from "../../channel-reply-pipeline-TlW8N3_3.js";
import { r as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-gZjBaPFF.js";
import { f as summarizeMapping, u as mergeAllowlist } from "../../allow-from-eZ6uedD3.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-CaaZXWTO.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-BqQgBxTG.js";
import { a as resolveSenderScopedGroupPolicy, i as evaluateSenderGroupAccessForPolicy } from "../../group-access-C0bxOoE2.js";
import { n as readStoreAllowFromForDmPolicy, o as resolveDmGroupAccessWithLists, s as resolveEffectiveAllowFromLists } from "../../dm-policy-shared-C7MlRVkr.js";
import { r as logTypingFailure } from "../../logging-DosEY-m1.js";
import { t as resolveChannelMediaMaxBytes } from "../../media-limits-LwaYNoUx.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DDuxp0PB.js";
import { n as createChannelPairingController } from "../../channel-pairing-CWWMPhAh.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-CaAM_77P.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-DCt8LcT9.js";
import { r as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-BCOdLV9x.js";
import { t as loadOutboundMediaFromUrl } from "../../outbound-media-Dl3SXxKB.js";
import { t as chunkTextForOutbound } from "../../text-chunking-BceJUYd2.js";
import { r as setMSTeamsRuntime } from "./runtime-api-CCWMmRED.js";
export { DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, PAIRING_APPROVED_MESSAGE, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelPairingController, createChannelReplyPipeline, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, evaluateSenderGroupAccessForPolicy, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, readStoreAllowFromForDmPolicy, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveDmGroupAccessWithLists, resolveEffectiveAllowFromLists, resolveNestedAllowlistDecision, resolveSenderScopedGroupPolicy, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };
