import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-B32J-iNN.js";
import { s as normalizeStringEntries } from "../../string-normalization-DiPHgdft.js";
import { o as withFileLock } from "../../file-lock-D5OTq3qW.js";
import { a as resolveChannelEntryMatchWithFallback, n as buildChannelKeyCandidates, r as normalizeChannelSlug, s as resolveNestedAllowlistDecision } from "../../channel-config-BI04LRnO.js";
import { a as resolveAllowlistMatchSimple } from "../../allowlist-match-D8Bi9YxS.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-DppuT-pZ.js";
import { S as buildMediaPayload } from "../../reply-payload-Bslhx7AA.js";
import { i as resolveToolsBySender } from "../../group-policy-DS0FBqgc.js";
import { o as extractOriginalFilename } from "../../store-De_Ewk5o.js";
import { n as fetchWithSsrFGuard } from "../../fetch-guard-DMbKx-s6.js";
import { t as createChannelReplyPipeline } from "../../reply-pipeline-BAF74ck_.js";
import { r as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-CDt0hRZR.js";
import { f as summarizeMapping, u as mergeAllowlist } from "../../allow-from-CvE3rvhy.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-CmZDlIwd.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-jjAiM0PK.js";
import { a as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-CBRFuqY7.js";
import { t as loadOutboundMediaFromUrl } from "../../outbound-media-vAhpTcTX.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-M85B-vhs.js";
import { a as resolveChannelMediaMaxBytes } from "../../media-runtime-DTV5lL4v.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CVvpFHIe.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-C9w9gv4K.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-CkwlpDZd.js";
import { r as logTypingFailure } from "../../logging-Dr3f0mtP.js";
import { n as createChannelPairingController } from "../../channel-pairing-C53hVVH8.js";
import { r as setMSTeamsRuntime } from "../../runtime-api-qRxCpAe5.js";
export { DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, PAIRING_APPROVED_MESSAGE, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };
