import { i as OpenClawConfig } from "../../types.openclaw-BdSNxnBz.js";
import { t as FallbackAttempt } from "../../model-fallback.types-D-yOuaC4.js";
import { s as AuthProfileStore } from "../../types-6eKuwe7u.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-D1yztQ8y.js";
import { Un as VideoGenerationProviderPlugin } from "../../types-ItMBrbf4.js";
import { n as createSubsystemLogger } from "../../subsystem-CVkBUUYw.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-DQCUfNup.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-6Ty263Tj.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-DYum6be2.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-C-XfClZC.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-1JIz6aMZ.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-BWiG4jOG.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };