import { i as OpenClawConfig } from "../../types.openclaw-C9E_zZnO.js";
import { dt as GoogleChatConfig, lt as GoogleChatAccountConfig } from "../../types.channels-CZZMDOR0.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-BTwhyOZ1.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-COvVZOrq.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-gexONR-2.js";
import { t as ChannelMessageActionName } from "../../types.public-D_xOTs5v.js";
import { n as PluginRuntime } from "../../types-C2b0JJwH.js";
import { o as fetchRemoteMedia } from "../../fetch-DEKmH2GE.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-Dc9uVKJp.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-hxH9SU7b.js";
import { r as buildChannelConfigSchema } from "../../config-schema-O6SnT1Ui.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-CxM_5XQX.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-DEhWRvDO.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-0bq23hIC.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-CFR3xeVt.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-BR5GerSC.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-GOjn0JDu.js";
import { n as resolveWebhookPath } from "../../webhook-path-D4SsmZB_.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-BaPtUGas.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-Bxt7lLvD.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-C9LoOxmz.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BJTuJHYf.js";
import { r as createChannelPairingController } from "../../channel-pairing-lZSBgnCR.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CwtMbR6o.js";
import { d as missingTargetError } from "../../channel-feedback-DejI588Q.js";
import { t as extractToolSend } from "../../tool-send-DUtJR00m.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-WdfHCkHG.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-Dp_gE2OH.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchRemoteMedia, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };