import { i as OpenClawConfig } from "../../types.openclaw-C58U02FA.js";
import { t as FallbackAttempt } from "../../model-fallback.types-vzLpXIuM.js";
import { s as AuthProfileStore } from "../../types-BUF85Z6a.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-BLNWWh2p.js";
import { Jn as VideoGenerationProviderPlugin } from "../../types-UTp4ves_.js";
import { n as createSubsystemLogger } from "../../subsystem-BDulbhZL.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-BP9-Poca.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-BwdKq3YJ.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-LmyboZJS.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-B7104Xv4.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-BXGJVnBu.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-Co9M57rK.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };