import { p as isBlockedHostnameOrIp } from "../../ssrf-qTfRSneg.js";
import { o as SessionEntry } from "../../types-BFjEZxU5.js";
import { v as OpenClawPluginApi } from "../../types-CyE3PKKi.js";
import { _ as sleep } from "../../utils-qPx1BPM5.js";
import { r as GatewayRequestHandlerOptions } from "../../types-DRDg5I41.js";
import { t as definePluginEntry } from "../../plugin-entry-yNzaet8Q.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BazbOKNB.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-C8qiQJHI.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-Cylr6qUw.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };